### ISSUE TITLE
Remove migration is reverting GUID properties/columns to wrong type (String)

### ISSUE THREAD

**Issue by XzaR90** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1002]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
```
public class TestModel {

public int Id { set; get; }
public Guid? TestId { set; get; }

//To be added in next migration
public string Name { set; get; }
}
```

In Package manager console type:
add-migration TestModelAddedName
remove-migration
add-migration TestModelAddedName
> Unable to cast object of type 'System.Guid' to type 'System.String'

### The issue
Describe what is not working as expected.
ApplicationDbContextModelSnapshot.cs have been reverted but the guid is now a string.
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalShadowEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Update.Internal.UpdateAdapter.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Workaround
If using GIT you can just revert changes on ApplicationDbContextModelSnapshot.cs or manualy edit it.

### Further technical details

MySQL version: `(new Version(10, 1, 31), ServerType.MariaDb`
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.0
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
Migration Assembly in a different project.

**Comment by lauxjpn** [comment]
Thank you for reporting this issue!

### Issue

I could successfully reproduce the problem. When adding the first `TestModelAddedName` migration, the following *correct* snapshot is being generated:

```c#
// <auto-generated />
using System;
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IssueConsoleTemplate.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("TestId") // <-- Guid? is the correct type
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TestModelSet");
                });
#pragma warning restore 612, 618
        }
    }
}
```
After removing the migration again, the snapshot is suddenly wrong, and also different from the still correct `.Designer.cs` file of the previous migration (that has no `string Name` property yet):

```c#
// <auto-generated />
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IssueConsoleTemplate.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TestId") // <-- string is the wrong type
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TestModelSet");
                });
#pragma warning restore 612, 618
        }
    }
}
```

This will also happen with a non-nullable `Guid`.

### Workaround

Either just copy the class content of the `.Designer.cs` file of the previous migration, or just replace the `string` type with the `Guid?` type.

### Fix

We will fix this shortly, which will be part of the nightly builds. The fix will be part of the `3.2.0` release.

**Comment by fjsosa** [comment]
I'm having the same issue without removing the migration, the issue appears with I try to add a new migration with Version 3.2.3

**Comment by lauxjpn** [comment]
> I'm having the same issue without removing the migration, the issue appears with I try to add a new migration with Version 3.2.3

@fjsosa That should be a different issue then. Please open a new issue for your case and provide us with some steps to reproduce the issue over there.
