### ISSUE TITLE
Navigation properties not working for explicit and lazy loading from v3.0.0+

### ISSUE THREAD

**Issue by MemoTrap** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1032]
_As this appears to be so basic, I must be doing something wrong._

A very simple scenario, from the EF Core tutorial, applied to MariaDB.

### Steps to reproduce
Model.cs
```
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFGetStarted {
  public class BloggingContext : DbContext {
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring (DbContextOptionsBuilder options)
      => options
        //.UseLazyLoadingProxies ()
        .UseMySql ("server=localhost;database=efcorebasics;uid=test;pwd=test");

  }

  public class Blog {
    public int BlogId { get; set; }
    public string Url { get; set; }

    public virtual List<Post> Posts { get; } = new List<Post> ();
  }

  public class Post {
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public int BlogId { get; set; }
    public virtual Blog Blog { get; set; }
  }
}
```

Program.cs
```
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EFGetStarted {
  class Program {
    static void Main () {
      using (var db = new BloggingContext ()) {

        var blogs = db.Blogs;
        //var blogs = db.Blogs.Include (b => b.Posts);
        Console.WriteLine ($"#Blogs={db.Blogs.Count()}");
        foreach (var blog in blogs) {

          db.Entry (blog)
            .Collection (b => b.Posts)
            .Load ();

          Console.WriteLine ($"{blog.Url}: #Posts={blog.Posts.Count()}");
          foreach (var post in blog.Posts)
            Console.WriteLine ($"  {post.Title}, {post.Content}");
        }
      }

      Console.WriteLine ("Press Return to terminate");
      Console.ReadLine ();

    }
  }
}
```

Database
```
DROP DATABASE IF EXISTS `efcorebasics`;
CREATE DATABASE IF NOT EXISTS `efcorebasics`;
USE `efcorebasics`;

DROP TABLE IF EXISTS `blogs`;
CREATE TABLE IF NOT EXISTS `blogs` (
  `BlogId` int(11) NOT NULL AUTO_INCREMENT,
  `Url` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`BlogId`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `blogs` (`BlogId`, `Url`) VALUES
	(2, 'https://devblogs.microsoft.com/dotnet');


DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS `posts` (
  `PostId` int(11) NOT NULL AUTO_INCREMENT,
  `Title` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `Content` longtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `BlogId` int(11) NOT NULL,
  PRIMARY KEY (`PostId`),
  KEY `IX_Posts_BlogId` (`BlogId`),
  CONSTRAINT `FK_Posts_Blogs_BlogId` FOREIGN KEY (`BlogId`) REFERENCES `blogs` (`BlogId`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

INSERT INTO `posts` (`PostId`, `Title`, `Content`, `BlogId`) VALUES
	(3, '2nd Post', 'I am an expert now!', 2),
	(4, 'Hello World', 'I wrote an app using EF Core!', 2);
```

### The issue
Application crashes when trying to load "Posts" for Blog", line 15.

Works for eager loading, but throws exception for explicit and lazy loading.

Also works for EFCore version 2.2.6 / Pomelo.EntityFrameworkCore.MySql 2.2.6 in all three loading modes.

Exception:
```
Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.
```
```
   at MySql.Data.MySqlClient.MySqlCommand.set_CommandText(String value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Load()
   at Microsoft.EntityFrameworkCore.ChangeTracking.CollectionEntry.Load()
   at EFGetStarted.Program.Main() in F:\svn-source\common\snippets\EntityFramework\EFCoreGetStarted\EFGetStartedMariaDBSimple\Program.cs:line 15
```

### Further technical details

MySQL version: MariaDB 10.4.12

Operating system: Win 7

Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.EntityFrameworkCore.Core.Relational version 3.1.2
Microsoft.EntityFrameworkCore.Core version 3.1.2
Microsoft.EntityFrameworkCore.Proxies version 3.1.2
MySqlConnector version 0.61.0

Microsoft.NetCore.App version: 3.1

**Comment by lauxjpn** [comment]
This particular example might actually trigger a bug. I will investigate this further.

To make you code work with the current version, don't iterate directly over the `DbSet<>`, because it keeps the `DataReader` open. The following code snippet will work:

```c#
// The following line will currently not work when used in a foreach:
// var blogs = db.Blogs;

// The following line will work:
var blogs = db.Blogs.ToList();
```

**Comment by MemoTrap** [comment]
> To make you code work with the current version, don't iterate directly over the DbSet<>, because it keeps the DataReader open.

Thank you!

**Comment by lauxjpn** [comment]
The are no changes of the current EF Core behavior planed for the future. As for Pomelo, we could think about making the exception (especially the message) more explicit, so users are aware of the nature of this limitation and how to handle it.
