### ISSUE TITLE
Problem with search in array string/number

### ISSUE THREAD

**Issue by Matix8981** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1039]
### The issue
Hi,
I try find rows where in field distributions exist id of distribution.
Field distributions is equal to ["0", "1"] and [0, 1], for testing i use string. 
```
IQueryable<test> testQuery = from s in database.test select s;
testQuery = testQuery.Where(row => row.Distributions.Object.Contains("0"));


public class test
{
    [Column("id")]
    public int Id { get; set; }
    [Column("distributions")]
    public JsonObject<List<string>> Distributions {get; set;}
}
```

```
System.InvalidOperationException: The LINQ expression 'DbSet<test>
    .OrderBy(v => v.Price)
    .Where(v => v.Distributions.Object
        .Contains("0"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at hostlist.Controllers.testController.<>c__DisplayClass6_0.<Sort>b__0() in F:\Hostlist\api\Controllers\testController.cs:line 134
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at hostlist.Controllers.testController.Sort(testParams args, Int32 page) in F:\Hostlist\api\Controllers\testController.cs:line 70
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### Further technical details

MySQL version: MariaDB 10.4
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: Newest
Microsoft.AspNetCore.App version: Newest

**Comment by lauxjpn** [comment]
The current JSON support is very limited. There is no query support for JSON values yet. You can only set and retrieve the hole field/object.
Of course, you can fallback on `FromSqlRaw` and `FromSqlInterpolated`.

We are a bit behind schedule improving the JSON support, but it is one of two major features, that are being implemented next.

**Comment by Matix8981** [comment]
Any idea for query builder without FromSqlRaw? I need check if in list exist distribution ID.
example in someone row distributions is equal to 1,2,3,4 (or [1,2,3,4] or ["1","2","3","4"]) and i want filter rows where exist distribution with ID 1

**Comment by mguinness** [comment]
One possibility is to store the distributions 1,2,3,4 in a varchar field and use the following to filter. 

```C#
var dist = 1;
var temp = "," + dist.ToString() + ",";
var data = database.test.Where(s => ("," + s.Distributions + ",").Contains(temp));
```

**Comment by lauxjpn** [comment]
The solution @mguinness presented is definitely the simplest to implement. So if it is good enough in your case, you should go with it.

That being said, if you need a more sophisticated approach, buckle up!
I compiled a fully working sample console project below, based on our previous example from the https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/693#issuecomment-572045842 issue, where we showed how to use a custom JSON column type mapping.

The new sample here extends the previous concept and uses a variety of different methods to query a JSON columns (might be interesting for @Schaussi and @yokkohsan as well).

It show how to query JSON columns mapped to `System.String`, `JsonObject<T>`, any custom POCO object (without `JsonObject<T>`) and any custom POCO object collection.

It does this using a simple `LIKE` clause, creating a custom SQL query with `FromSqlInterpolated` and `JSON_CONTAINS()` and calling `EF.Functions.JsonContains` (a custom function translation).

```c#
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal;
using Pomelo.EntityFrameworkCore.MySql.Query.Internal;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;

namespace IssueConsoleTemplate
{
    #region Json Function Query Support
    
    public static class MySqlJsonDbFunctionsExtensions
    {
        public static bool JsonContains(
            this DbFunctions _,
            object expression,
            object value,
            string path)
            => throw new InvalidOperationException();

        public static string JsonQuote(
            this DbFunctions _,
            string value)
            => @$"""{value.Replace(@"""", @"\""")}""";
    }

    public class JsonExtendedMethodCallTranslatorProvider : MySqlMethodCallTranslatorProvider
    {
        public JsonExtendedMethodCallTranslatorProvider(
            [NotNull] RelationalMethodCallTranslatorProviderDependencies dependencies)
            : base(dependencies)
        {
            var sqlExpressionFactory = dependencies.SqlExpressionFactory;

            AddTranslators(
                new IMethodCallTranslator[]
                {
                    new MySqlJsonDbFunctionsExtensionsMethodTranslator(sqlExpressionFactory),
                });
        }
    }

    public class MySqlJsonDbFunctionsExtensionsMethodTranslator : IMethodCallTranslator
    {
        private readonly MethodInfo _jsonContains = typeof(MySqlJsonDbFunctionsExtensions).GetRuntimeMethod(
            nameof(MySqlJsonDbFunctionsExtensions.JsonContains),
            new[] {typeof(DbFunctions), typeof(object), typeof(object), typeof(string)});

        private readonly ISqlExpressionFactory _sqlExpressionFactory;

        public MySqlJsonDbFunctionsExtensionsMethodTranslator(
            ISqlExpressionFactory sqlExpressionFactory)
            => _sqlExpressionFactory = sqlExpressionFactory;

        public virtual SqlExpression Translate(SqlExpression instance, MethodInfo method, IReadOnlyList<SqlExpression> arguments)
        {
            if (method == _jsonContains)
            {
                return _sqlExpressionFactory.Function(
                    "JSON_CONTAINS",
                    new[] {arguments[1], arguments[2], arguments[3]},
                    typeof(bool)
                );
            }

            return null;
        }
    }

    #endregion

    #region JSON Column Type Support

    public class JsonStringTypeMappingSourcePlugin : IRelationalTypeMappingSourcePlugin
    {
        private readonly MySqlStringTypeMapping _json;

        public JsonStringTypeMappingSourcePlugin(IMySqlOptions options)
            => _json = new MySqlStringTypeMapping("json", DbType.String, options);

        /// <summary>
        /// Return a String type mapping, if `JSON` has been specified explicitly as the column type.
        /// </summary>
        public RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
            => string.Equals(mappingInfo.StoreTypeName, "json", StringComparison.OrdinalIgnoreCase)
                ? _json
                : null;
    }

    #endregion
    
    #region Database Entities

    public class IceCream
    {
        public int Id { get; set; }
        public string Name { get; set; }

        //
        // JSON properties:
        //

        public JsonObject<IceCreamProperties> Properties { get; set; }
        public IceCreamSupplierInformation SupplierInformation { get; set; }
        public List<string> FoodAdditives { get; set; }
        public string Tags { get; set; }
    }

    #endregion

    #region JSON Objects

    public class IceCreamProperties
    {
        public int PopularityRank { get; set; }
        public bool InStock { get; set; }
    }

    public class IceCreamSupplierInformation
    {
        public string Name { get; set; }
        public double StandardHygiene { get; set; }
    }

    #endregion

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Register the custom type mapping plugin and our custom method call translator
            // provider.
            // Since this is a console program, we need to create our own ServiceCollection
            // for this.
            // In an ASP.NET Core application, the AddSingleton call can just be added to
            // the general service configuration method.
            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkMySql()
                .AddSingleton<IRelationalTypeMappingSourcePlugin, JsonStringTypeMappingSourcePlugin>()
                .AddSingleton<IMethodCallTranslatorProvider, JsonExtendedMethodCallTranslatorProvider>()
                .AddScoped<ILoggerFactory>(
                    s => LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .BuildServiceProvider();

            optionsBuilder
                .UseInternalServiceProvider(serviceProvider) // <-- use our ServiceProvider
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=Issue1039",
                    b => b.ServerVersion("8.0.20-mysql"))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    // Force JSON as the column type and define custom value conversions.
                    entity.Property(e => e.Properties)
                        .HasConversion(
                            v => v.Json,
                            v => new JsonObject<IceCreamProperties>(v))
                        .HasColumnType("json");
                    
                    entity.Property(e => e.SupplierInformation)
                        .HasConversion(
                            v => JsonConvert.SerializeObject(v),
                            v => JsonConvert.DeserializeObject<IceCreamSupplierInformation>(v))
                        .HasColumnType("json");
                    
                    entity.Property(e => e.FoodAdditives)
                        .HasConversion(
                            v => JsonConvert.SerializeObject(v),
                            v => JsonConvert.DeserializeObject<List<string>>(v))
                        .HasColumnType("json");
                    
                    entity.Property(e => e.Tags)
                        .HasColumnType("json");

                    entity.HasData(
                        new IceCream
                        {
                            Id = 1,
                            Name = "Vanilla",
                            Properties = new JsonObject<IceCreamProperties>(
                                new IceCreamProperties
                                {
                                    PopularityRank = 1,
                                    InStock = true,
                                }),
                            SupplierInformation = new IceCreamSupplierInformation
                            {
                                Name = "Fasssst Dilivery",
                                StandardHygiene = 0.45,
                            },
                            FoodAdditives = new List<string> {"E102"},
                            Tags = @"[""fluffy"", ""white"", ""yellow""]",
                        },
                        new IceCream
                        {
                            Id = 2,
                            Name = "Chocolate",
                            Properties = new JsonObject<IceCreamProperties>(
                                new IceCreamProperties
                                {
                                    PopularityRank = 2,
                                    InStock = true,
                                }),
                            SupplierInformation = new IceCreamSupplierInformation
                            {
                                Name = "Sweet Dilivery",
                                StandardHygiene = 0.65,
                            },
                            FoodAdditives = new List<string> {"E124","E155"},
                            Tags = @"[""creamy"", ""brown""]",
                        },
                        new IceCream
                        {
                            Id = 3,
                            Name = "Strawberry",
                            Properties = new JsonObject<IceCreamProperties>(
                                new IceCreamProperties
                                {
                                    PopularityRank = 3,
                                    InStock = false,
                                }),
                            SupplierInformation = new IceCreamSupplierInformation
                            {
                                Name = "Fresh Dilivery",
                                StandardHygiene = 0.85,
                            },
                            FoodAdditives = new List<string> {"E124"},
                            Tags = @"[""sweet"", ""red""]",
                        },
                        new IceCream
                        {
                            Id = 4,
                            Name = "Matcha",
                            Properties = new JsonObject<IceCreamProperties>(
                                new IceCreamProperties
                                {
                                    PopularityRank = 42,
                                    InStock = false,
                                }),
                            SupplierInformation = new IceCreamSupplierInformation
                            {
                                Name = "Fine Dine",
                                StandardHygiene = 0.98,
                            },
                            FoodAdditives = new List<string> {"E102", "E142"},
                            Tags = @"[""bitter"", ""green""]",
                        }
                    );
                });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            // Query all ice creams.
            // Needs:
            //   - JsonStringTypeMappingSourcePlugin
            var iceCreams = context.IceCreams
                .OrderBy(i => i.Id)
                .ToList();

            Debug.Assert(iceCreams.Count == 4);
            Debug.Assert(iceCreams[3].SupplierInformation.Name == "Fine Dine");

            // Query ice creams by handling the JSON column as plain text and using a simple LIKE clause. 
            // Needs:
            //   - JsonStringTypeMappingSourcePlugin
            var yellowTaggedIceCreams = context.IceCreams
                .Where(i => i.Tags.Contains("yellow"))
                .ToList();

            Debug.Assert(yellowTaggedIceCreams.Count == 1);

            // Query ice creams by using a sql query and using the MySQL JSON_CONTAINS() function.
            // Needs:
            //   - JsonStringTypeMappingSourcePlugin
            var yellowFoodColoringENumber = "E102";
            var iceCreamsWithYellowFoodColoring = context.IceCreams
                .FromSqlInterpolated($"select * from `IceCreams` where json_contains(`FoodAdditives`, json_quote({yellowFoodColoringENumber}), '$') <> 0")
                .ToList();

            Debug.Assert(iceCreamsWithYellowFoodColoring.Count == 2);

            // Query ice creams by using EF functions.
            // Needs:
            //   - JsonStringTypeMappingSourcePlugin,
            //   - MySqlJsonDbFunctionsExtensions
            //   - JsonExtendedMethodCallTranslatorProvider
            //   - MySqlJsonDbFunctionsExtensionsMethodTranslator
            var redFoodColoringENumber = "E124";
            var iceCreamsWithRedFoodColoring = context.IceCreams
                .Where(i => EF.Functions.JsonContains(i.FoodAdditives, EF.Functions.JsonQuote(redFoodColoringENumber), "$"))
                .ToList();

            Debug.Assert(iceCreamsWithRedFoodColoring.Count == 2);
        }
    }
}
```
