### ISSUE TITLE
Could not load file or assembly 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'.

### ISSUE THREAD

**Issue by Nguyenyellow74** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1048]
### The issue
I already installed dotnet-ef, Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Design, Pomelo.EntityFrameworkCore.MySql, Pomelo.JsonObject. but when i run the command "dotnet ef migrations add InitialCreate" i get the error "Could not load file or assembly 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'. The system cannot find the file specified." 
I have tried uninstall all packages and reinstall them but it didn't work. The error occur before installing Pomelo.JsonObject.
But I can do "dotnet run" without getting error. 

The exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'. The system cannot find the file specified.
```

The project.csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />
    <PackageReference Include="Pomelo.JsonObject" Version="2.2.1" />
  </ItemGroup>
</Project>
```

The DbContext:
```
using Microsoft.EntityFrameworkCore;

namespace MoneyManagementWebApp.Models
{
    public class MoneyManagementContext : DbContext
    {
        public DbSet<User> Users { get; set;}
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Reason> Reasons { get; set; }
        public DbSet<Receiving> Receivings { get; set; }
        public DbSet<Spending> Spendings { get; set; }

        public MoneyManagementContext (DbContextOptions<MoneyManagementContext> options) : base(options) {
            
        }
    }
}
```

Startup.cs: (I only modified the ConfigureServices function)
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using MoneyManagementWebApp.Models;

namespace MoneyManagementWebApp
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddDbContext<MoneyManagementContext>(options => 
            options.UseMySql("server=localhost;database=money_management;user=user;password=password"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
```

### Further technical details

MySQL version: 5.7.29
Operating system: Ubuntu 64bit 18.04 LTS

**Comment by lauxjpn** [comment]
I looked over you code and it looks good to me. I also tested this locally and it works fine.
Please provide us with the full original project (zip/7zip file or GitHub repo), so we can reproduce the issue on our end.

**Comment by Nguyenyellow74** [comment]
@lauxjpn 
This is my project's repo: https://github.com/Nguyenyellow74/MoneyManagementApp

**Comment by lauxjpn** [comment]
Adding a migration to your project works without issues on my end.
Please run the following command from the directory containing the `MoneyManagementWebApp.csproj` file and post the output:

```
dotnet ef migrations add Initial --verbose
```

**Comment by Nguyenyellow74** [comment]
@lauxjpn Here is the output:
```
Using project '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/MoneyManagementWebApp.csproj'.
Using startup project '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/MoneyManagementWebApp.csproj'.
Writing '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/obj/MoneyManagementWebApp.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpeZ5GBX.tmp /verbosity:quiet /nologo /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/MoneyManagementWebApp.csproj
Writing '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/obj/MoneyManagementWebApp.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpBnTJdb.tmp /verbosity:quiet /nologo /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/MoneyManagementWebApp.csproj
Build started...
dotnet build /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/MoneyManagementWebApp.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.91
Build succeeded.
dotnet exec --depsfile /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1/MoneyManagementWebApp.deps.json --additionalprobingpath /home/nguyen/.nuget/packages --runtimeconfig /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1/MoneyManagementWebApp.runtimeconfig.json /home/nguyen/.dotnet/tools/.store/dotnet-ef/3.1.2/dotnet-ef/3.1.2/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations add InitialCreate --assembly /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1/MoneyManagementWebApp.dll --startup-assembly /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1/MoneyManagementWebApp.dll --project-dir /home/nguyen/Study/NLCNTT/MoneyManagementWebApp/ --language C# --working-dir /home/nguyen/Study/NLCNTT/MoneyManagementWebApp --verbose --root-namespace MoneyManagementWebApp
Using assembly 'MoneyManagementWebApp'.
Using startup assembly 'MoneyManagementWebApp'.
Using application base '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1'.
Using working directory '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp'.
Using root namespace 'MoneyManagementWebApp'.
Using project directory '/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'MoneyManagementContext'.
Finding DbContext classes in the project...
Using context 'MoneyManagementContext'.
System.IO.FileNotFoundException: Could not load file or assembly 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'. The system cannot find the file specified.

File name: 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.FindRawMapping(RelationalTypeMappingInfo mappingInfo)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.FindMapping(RelationalTypeMappingInfo& mappingInfo)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<FindMappingWithConversion>b__7_0(ValueTuple`3 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(MemberInfo member)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.PropertyDiscoveryConvention.IsCandidatePrimitiveProperty(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.PropertyDiscoveryConvention.Process(IConventionEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.PropertyDiscoveryConvention.ProcessEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnEntityTypeAdded(OnEntityTypeAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAddedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)


Could not load file or assembly 'Pomelo.JsonObject, Version=2.2.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'. The system cannot find the file specified.

```

**Comment by lauxjpn** [comment]
Please check that the `Pomelo.JsonObject.dll` file exists in the `/home/nguyen/Study/NLCNTT/MoneyManagementWebApp/bin/Debug/netcoreapp3.1` directory.

You can also try to clone your repo to another directory and try again from this fresh path.

**Comment by Nguyenyellow74** [comment]
@lauxjpn Thanks! i think that is the problem, i can't find Pomelo.JsonObject.dll. Where can i get that file? Or how can i generate it?

**Comment by lauxjpn** [comment]
As long as you don't want to handle JSON in your MySQL database (and even then), it is not necessary to reference `Pomelo.JsonObject` at all.

So you can just remove the following line from your `.csproj` file:

```xml
<PackageReference Include="Pomelo.JsonObject" Version="2.2.1" />
```

If you *do* want to use `JsonObject<T>` (which is what the `Pomelo.JsonObject` package is all about) then you can find the package on [NuGet](https://www.nuget.org/packages/Pomelo.JsonObject).
