### ISSUE TITLE
Unable to cast object of type 'System.Guid' to type 'System.String' when updating data using Add-Migration

### ISSUE THREAD

**Issue by mc0re** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1079]
### Steps to reproduce

This is a snippet of my project.

```
public class UserEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    public string Name { get; set; }
}
```

In the `DbContext` I have
```
modelBuilder.Entity<UserEntity>().HasData(Seeder.PredefinedUser);
```

Where a predefined user is just some randomly defined entity.
I ran `Add-Migration V1`, everything went fine.

Now I am updating something in the predefined user (say, `Name`). And run `Add-Migration` again. This produces an error.

### The issue

`Add-Migration` produces an exception.
```
System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalShadowEntityEntry..ctor(IStateManager stateManager, IEntityType entityType, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.NewInternalEntityEntry(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryFactory.Create(IStateManager stateManager, IEntityType entityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Update.Internal.UpdateAdapter.CreateEntry(IDictionary`2 values, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to cast object of type 'System.Guid' to type 'System.String'.
```

### Further technical details

MySQL version: Azure
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.3
Microsoft.AspNetCore.App version: 3.1

**Comment by mc0re** [comment]
I realized that I used `Remove-Migration`, and then I found the already existing issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1002 . So it's a duplicate.
