### ISSUE TITLE
SQL Syntax Error when using MariaDB 10.4.12

### ISSUE THREAD

**Issue by Laikar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1083]
I tried to use the [BlazorBoilerplate](https://github.com/enkodellc/blazorboilerplate) to start creating a website, it uses The entityFramework for its database access, but does not support MariaDB by default.
### Steps to reproduce
Download the Blazor boilerplate template, and add a option for using MariaDB with the following code:
```
builder.UseMySql(ConnectionString, mySqlOptions =>
            {
                mySqlOptions.ServerVersion(new Version(10,4,12), ServerType.MariaDb);
            });
```

### The issue
When the whole project loads, instead of the expected webpage, [this ](https://i.imgur.com/vqmhtrO.png)shows up.

[The whole page as text](https://pastebin.com/khEKmA0S)

Exception message: 
```
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'uniqueidentifier(36) NOT NULL,
`Name` nvarchar(256) NULL,
`NormalizedN' at line 2
```
Stack trace:
```
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'uniqueidentifier(36) NOT NULL,
    `Name` nvarchar(256) NULL,
    `NormalizedN' at line 2
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'uniqueidentifier(36) NOT NULL,
    `Name` nvarchar(256) NULL,
    `NormalizedN' at line 2
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 777
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 220
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BlazorBoilerplate.Storage.DatabaseInitializer.MigrateAsync() in F:\DrawMoe\src\BlazorBoilerplate.Storage\DatabaseInitializer.cs:line 63
   at BlazorBoilerplate.Storage.DatabaseInitializer.SeedAsync() in F:\DrawMoe\src\BlazorBoilerplate.Storage\DatabaseInitializer.cs:line 49
```

### Further technical details

MySQL version: Mariadb 10.4.12
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

**Comment by lauxjpn** [comment]
I haven't tested this yet with BlazorBoilerplate, but `uniqueidentifier` is not a MySQL data type.

Since the exception shows also `nvarchar` usage, which is basically deprecated and should not be used in MySQL anymore (and is generated by Pomelo by default), it seems that explicit SQL Server database store types where defined for the model you are using (e.g. by using `HasColumnType("uniqueidentifier")`).

If you want to reuse the model definition for MySQL, you might want to keep it as clean as possible of database specific types.

**Comment by Laikar** [comment]
Allright, will report to teh BlazorBoilerplate devs, many thanks

**Comment by lauxjpn** [comment]
> Allright, will report to teh BlazorBoilerplate devs, many thanks

@Laikar That is probably unnecessary. It should be enough for you to just recreate the migrations.

Take a look at their [Postgres Support](https://github.com/enkodellc/blazorboilerplate#postgres-support) section on their front page. The steps for MySQL should be similar.

**Comment by Laikar** [comment]
Will do, again, many thanks.
