### ISSUE TITLE
EF Code first generates broken migrations when dropping foreign key

### ISSUE THREAD

**Issue by ptsneves** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1093]
### Steps to reproduce
Delete an existing foreign key from the Enitty
```
dotnet ef migrations add FKDrop
dotnet ef database update
```

### The issue
dotnet ef database update throws exception

```dotnet ef database update
Build started...
Build succeeded.
MySql.Data.MySqlClient.MySqlException (0x80004005): Can't DROP 'FK_DroneBatteryLevels_Devices_Serial'; check that column/key exists
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Can't DROP 'FK_DroneBatteryLevels_Devices_Serial'; check that column/key exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 226
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 74
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Can't DROP 'FK_DroneBatteryLevels_Devices_Serial'; check that column/key exists
```nical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version: mysql  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL)
Microsoft.AspNetCore.App version: 3.1
EntityFramework 3.1.4

**Comment by mguinness** [comment]
You'll need to provide more info than just the stack trace...  Start with the table schema and [Generate SQL scripts](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#generate-sql-scripts).  What change did you make to the model to cause the FK to be dropped?

**Comment by ptsneves** [comment]
@mguinness  thanks for the attention.

schema
https://pastebin.com/0qFtdSd4

migration
https://pastebin.com/Ph5z8nEU

I thought i would put in pastebin as it is a big dump. Let me know if you need more info.

**Comment by mguinness** [comment]
Are you sure all the prior migrations completed successfully?  Was the migration below generated or custom?

```SQL

SET foreign_key_checks = 0

ALTER TABLE `Devices` MODIFY COLUMN `Id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE Devices MODIFY COLUMN Id int auto_increment

SET foreign_key_checks = 1

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20191207181551_MySQLIncrementingID', '3.1.4');
```

**Comment by mguinness** [comment]
Also you have the following in your migration, but it wasn't previously defined...

```ALTER TABLE `Devices` DROP KEY `AK_Devices_SerialNumber`;```

**Comment by ptsneves** [comment]
@mguinness Thanks a lot for the help!

>Are you sure all the prior migrations completed successfully? Was the migration below generated or custom?

As far as i know they were successful. I know this must sound a cringe worthy question, but besides the success of ```dotnet ef database update``` is there anything else i should check?


This is based on a migration i manually generated, due to the fact that the tables were not auto increment in pomelo, when i migrated from mssql to mysql. The migration is like

```
migrationBuilder.Sql("SET foreign_key_checks = 0");                                               
            var pomeloMigrationNoteCore2Bug = "ALTER TABLE {0} MODIFY COLUMN {1} int auto_increment";         
                                                                                                              
            migrationBuilder.AlterColumn<int>(                                                                
                name: "Id",                                                                                   
                table: "Devices",                                                                             
                nullable: false,                                                                              
                oldClrType: typeof(int))                                                                      
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);    
            migrationBuilder.Sql(String.Format(pomeloMigrationNoteCore2Bug, "Devices", "Id"));                
            migrationBuilder.Sql("SET foreign_key_checks = 1");
```
Did i mess up?

> Also you have the following in your migration, but it wasn't previously defined...
Can you clarify what and you mean by wasn't previously defined and where?

**Comment by ptsneves** [comment]
Summary on my issue.

There is an AlternateKey drop which seems to not exist anywhere else besides the generated migration.
Applying this faulty migration will leave the database in an irreversible state in terms of EF migrations.

Editing out the AlternateKey drop from the migration file, makes the migration succeed and behave correctly.

**Comment by mguinness** [comment]
> Also if this looks like a huge mess and you feel I am wasting your time, do you have a suggestion on how can I get out of it? This is not in production, so if i lose the migrations it would not be a huge loss.

There's a lot to unravel especially without having the DbContext and model definitions to look at.  If you wish to squash all the previous migrations, just delete the Migrations folder and then add an initial migration to create a new database (and manually copy any existing data over from the old database).

**Comment by ptsneves** [comment]
I was able to get to a stable state, with the manual removal of the AK. Thanks and sorry for the hassle. If there is a donation box, i would chime in.
