### ISSUE TITLE
MySQL does not support the EF Core concept of schemas

### ISSUE THREAD

**Issue by MarioStreubel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1100]
I migrated from 
Pomelo.EntityFrameworkCore.MySql 2.2.0 =>3.1.1
Microsoft.EntityFrameworkCore 2.2.6 => 3.1.1

### Steps to reproduce
First lines of my Initial migration - existing since 2.2.0 and worked before
```
            migrationBuilder.EnsureSchema(
                name: "Live");

            migrationBuilder.EnsureSchema(
                name: "Push");

            migrationBuilder.EnsureSchema(
                name: "Retro");

            migrationBuilder.EnsureSchema(
                name: "System");

            migrationBuilder.CreateTable(
                name: "Online_Intraday",
                schema: "Live",
                columns: table => new
                {
                    IntradayId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    IntradayType = table.Column<string>(nullable: false),
                    Hour = table.Column<int>(nullable: false),
                    Value = table.Column<int>(nullable: true),
                    Average = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Intraday", x => x.IntradayId);
                });

            migrationBuilder.CreateTable(
                name: "Online_Topic",
                schema: "Live",
                columns: table => new
                {
                    TopicId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Title = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Order = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Topic", x => x.TopicId);
                });

            migrationBuilder.CreateTable(
                name: "Online_Visit",
                schema: "Live",
                columns: table => new
                {
                    VisitId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Type = table.Column<string>(nullable: false),
                    Value = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Visit", x => x.VisitId);
                });

            migrationBuilder.CreateTable(
                name: "Online_VisitsRealtime",
                schema: "Live",
                columns: table => new
                {
                    VisitsRealtimeId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Value = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_VisitsRealtime", x => x.VisitsRealtimeId);
                });

            migrationBuilder.CreateTable(
                name: "DeviceCount",
                schema: "Push",
                columns: table => new
                {
                    PushDeviceCountId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Value = table.Column<long>(nullable: false, defaultValue: 0L)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceCount", x => x.PushDeviceCountId);
                });

            migrationBuilder.CreateTable(
                name: "Push",
                schema: "Push",
                columns: table => new
                {
                    PushId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Reaction = table.Column<float>(nullable: false),
                    Title = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Time = table.Column<DateTime>(nullable: false),
                    PushpalReferenceId = table.Column<long>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Push", x => x.PushId);
                });

            migrationBuilder.CreateTable(
                name: "Online_Intraday",
                schema: "Retro",
                columns: table => new
                {
                    IntradayId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    IntradayType = table.Column<string>(nullable: false),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Hour = table.Column<int>(nullable: false),
                    Value = table.Column<int>(nullable: false),
                    Average = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Intraday", x => x.IntradayId);
                });

            migrationBuilder.CreateTable(
                name: "Online_PageImpressionPerVisit",
                schema: "Retro",
                columns: table => new
                {
                    PageImpressionPerVisitId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Type = table.Column<string>(nullable: false),
                    Value = table.Column<float>(nullable: false),
                    Trend = table.Column<float>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_PageImpressionPerVisit", x => x.PageImpressionPerVisitId);
                });

            migrationBuilder.CreateTable(
                name: "Online_Topic",
                schema: "Retro",
                columns: table => new
                {
                    TopicId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Title = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Order = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Topic", x => x.TopicId);
                });

            migrationBuilder.CreateTable(
                name: "Online_Visit",
                schema: "Retro",
                columns: table => new
                {
                    VisitId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Name = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Value = table.Column<int>(nullable: false),
                    Trend = table.Column<float>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Online_Visit", x => x.VisitId);
                });

            migrationBuilder.CreateTable(
                name: "Tv_Broadcast",
                schema: "Retro",
                columns: table => new
                {
                    BroadcastId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Name = table.Column<string>(unicode: false, maxLength: 250, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tv_Broadcast", x => x.BroadcastId);
                });

            migrationBuilder.CreateTable(
                name: "Tv_Station",
                schema: "Retro",
                columns: table => new
                {
                    StationId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Name = table.Column<string>(unicode: false, maxLength: 250, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tv_Station", x => x.StationId);
                });

            migrationBuilder.CreateTable(
                name: "Tv_Topic",
                schema: "Retro",
                columns: table => new
                {
                    TopicId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Title = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Order = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tv_Topic", x => x.TopicId);
                });

            migrationBuilder.CreateTable(
                name: "Configuration",
                schema: "System",
                columns: table => new
                {
                    ConfigurationId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Option = table.Column<string>(nullable: false),
                    Key = table.Column<string>(unicode: false, maxLength: 500, nullable: true),
                    Value = table.Column<string>(unicode: false, maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Configuration", x => x.ConfigurationId);
                });

            migrationBuilder.CreateTable(
                name: "FileImport",
                schema: "System",
                columns: table => new
                {
                    EntryId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    Name = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Start = table.Column<DateTime>(nullable: false),
                    End = table.Column<DateTime>(nullable: false),
                    Duration = table.Column<double>(nullable: false),
                    FileName = table.Column<string>(unicode: false, maxLength: 500, nullable: true),
                    Successful = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FileImport", x => x.EntryId);
                });

            migrationBuilder.CreateTable(
                name: "Runner",
                schema: "System",
                columns: table => new
                {
                    RunnerId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    InstanceId = table.Column<Guid>(nullable: false),
                    Name = table.Column<string>(unicode: false, maxLength: 250, nullable: true),
                    Start = table.Column<DateTime>(nullable: false),
                    End = table.Column<DateTime>(nullable: false),
                    Duration = table.Column<double>(nullable: false),
                    Successful = table.Column<bool>(nullable: false, defaultValue: false),
                    Retry = table.Column<int>(nullable: false, defaultValue: 0),
                    JobExitStatus = table.Column<string>(unicode: false, maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Runner", x => x.RunnerId);
                });

            migrationBuilder.CreateTable(
                name: "Tv_Daily",
                schema: "Retro",
                columns: table => new
                {
                    DailyId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    DayOfWeek = table.Column<string>(nullable: false),
                    Viewer = table.Column<double>(nullable: false),
                    MarketShare = table.Column<double>(nullable: false),
                    StationId = table.Column<int>(nullable: true),
                    BroadcastId = table.Column<int>(nullable: true),
                    Date = table.Column<DateTime>(type: "DATE", nullable: false),
                    Duration = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tv_Daily", x => x.DailyId);
                    table.ForeignKey(
                        name: "FK_Tv_Daily_Tv_Broadcast_BroadcastId",
                        column: x => x.BroadcastId,
                        principalSchema: "Retro",
                        principalTable: "Tv_Broadcast",
                        principalColumn: "BroadcastId",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Tv_Daily_Tv_Station_StationId",
                        column: x => x.StationId,
                        principalSchema: "Retro",
                        principalTable: "Tv_Station",
                        principalColumn: "StationId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Tv_Trend",
                schema: "Retro",
                columns: table => new
                {
                    TrendId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    CreatedAt = table.Column<DateTime>(nullable: false),
                    CreatedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    ModifiedAt = table.Column<DateTime>(nullable: true),
                    ModifiedBy = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    DayOfWeek = table.Column<string>(nullable: false),
                    Viewer = table.Column<double>(nullable: false),
                    MarketShare = table.Column<double>(nullable: false),
                    StationId = table.Column<int>(nullable: true),
                    BroadcastId = table.Column<int>(nullable: true),
                    From = table.Column<DateTime>(type: "DATE", nullable: false),
                    Until = table.Column<DateTime>(type: "DATE", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tv_Trend", x => x.TrendId);
                    table.ForeignKey(
                        name: "FK_Tv_Trend_Tv_Broadcast_BroadcastId",
                        column: x => x.BroadcastId,
                        principalSchema: "Retro",
                        principalTable: "Tv_Broadcast",
                        principalColumn: "BroadcastId",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Tv_Trend_Tv_Station_StationId",
                        column: x => x.StationId,
                        principalSchema: "Retro",
                        principalTable: "Tv_Station",
                        principalColumn: "StationId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Tv_Daily_BroadcastId",
                schema: "Retro",
                table: "Tv_Daily",
                column: "BroadcastId");

            migrationBuilder.CreateIndex(
                name: "IX_Tv_Daily_StationId",
                schema: "Retro",
                table: "Tv_Daily",
                column: "StationId");

            migrationBuilder.CreateIndex(
                name: "IX_Tv_Trend_BroadcastId",
                schema: "Retro",
                table: "Tv_Trend",
                column: "BroadcastId");

            migrationBuilder.CreateIndex(
                name: "IX_Tv_Trend_StationId",
                schema: "Retro",
                table: "Tv_Trend",
                column: "StationId");

            migrationBuilder.CreateIndex(
                name: "IX_Combined",
                schema: "System",
                table: "Runner",
                columns: new[] { "RunnerId", "CreatedAt", "InstanceId", "Name" });

...

            if (dbContext.Database.GetPendingMigrations().Any())
            {
                dbContext.Database.Migrate();
            }
```

### The issue
I use schemata since the beginning of the project and it worked fine before, after migrating to 3.1.1 I got this error.

```
Exception message: A schema "System" has been set for an object of type "CreateTableOperation" with the name of "Migrations". MySQL does not support the EF Core concept of schemas. Any schema property of any "MigrationOperation" must be null.
Stack trace:
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.CheckSchema(MigrationOperation operation)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetCreateScript()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Umi.Mockup.DatabaseHelper.Create(Boolean seedConfig, MySqlDbContextSeedOptions seedOptions, Boolean ensureCreate, Boolean ensureDelete, Boolean ensureDeleteOnDispose, IEnvironment environment) in ...
```

### Further technical details

MySQL version: 8.0
Operating system: Windows for building, Linux Docker container for Running
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

**Comment by mguinness** [comment]
Schemas are not supported, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/923 & https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/982 for discussion.

**Comment by lauxjpn** [comment]
Also take a look at #972, that provides possibilities to translate a schema and a table name to just a table name.

I also left in some (unofficial) ways to override the behavior to throw on schema use. But going with #972, if you want to use EF Core schemas, or with multiple `DbContext`s, if you need to work with different databases, is the recommended way to go in your case.

**Comment by rahatur** [comment]
Having the same error in 3.2.2

**Comment by lauxjpn** [comment]
> Having the same error in 3.2.2

@rahatur That is because using different databases inside one DbContext is currently not supported. So this is expected behavior.

Take a look at the previous two comments. They reference your options.

**Comment by TheRealLenon** [comment]
@lauxjpn are you aware of any roadmap for this feature?

I'm trying to make a kind of "generic" DbContext, which will support MySQL & MSSQL, which is using the `modelBuilder.HasDefaultSchema(DatabaseSchema);` on the builder.

**Comment by lauxjpn** [comment]
> @lauxjpn are you aware of any roadmap for this feature?

@TheRealLenon Since MySQL (not Pomelo) does not support schemas, there isn't really much for us to do here.

---

> I'm trying to make a kind of "generic" DbContext, which will support MySQL & MSSQL, which is using the `modelBuilder.HasDefaultSchema(DatabaseSchema);` on the builder.

Is there a particular reason, why SQL Server is going to need to use schemas? Because the simplest solution is just to not use this SQL Server feature at all.

If your question is primarily about how to support multiple providers with different features when using migrations, then take a look at [Migrations with Multiple Providers](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers).

One way to implement this then would be to have a base `DbContext` that pretty much contains everything and then just derive a provider specific class from that for each provider that you support.
You can then use different mode definitions (e.g. in your `OnModelCreating()` overload) for your individual providers. So you could use a model that explicitly uses schemas for SQL Server and one for MySQL that does not.

Instead of using multiple `DbContext` classes, it is also possible to use just one and branch your code using statements like `Database.IsSqlServer()` or `Database.IsMySql()` (or even using `Database.ProviderName`) in your model definition.

Finally, there is a Pomelo specific `DbContext` option `SchemaBehavior()`, that you can change to either just ignore all schema mentions or to merge them together with the table name:

```c#
// Just ignore all schemas:
optionsBuilder
    .UseMySql(
        connectionString,
        serverVersion,
        o => o.SchemaBehavior(MySqlSchemaBehavior.Ignore))

// Translate schemas into a table name prefix like `schema_table`:
optionsBuilder
    .UseMySql(
        connectionString,
        serverVersion,
        o => o.SchemaBehavior(MySqlSchemaBehavior.Translate, (schema, table) => $"{schema}_{table}"))
```
