### ISSUE TITLE
Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'STATISTICS.INDEX_TYPE'

### ISSUE THREAD

**Issue by MKI-Miro** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1162]
### Steps to reproduce
 dotnet ef dbcontext scaffold "server=mysql80.websupport.sk ...

### The issue

```
Exception message:
MySql.Data.MySqlClient.MySqlException (0x80004005): Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'STATISTICS.INDEX_TYPE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Stack trace:
`Build succeeded.
MySql.Data.MySqlClient.MySqlException (0x80004005): Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'STATISTICS.INDEX_TYPE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'STATISTICS.INDEX_TYPE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 210
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetIndexes(DbConnection connection, IReadOnlyList`1 tables, Func`3 tableFilter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'STATISTICS.INDEX_TYPE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by``

### Further technical details

MySQL version: 
Server version: 8.0.18-9 - Percona Server (GPL), Release '9', Revision '53e606f'
Protocol version: 10

Operating system: 
Pomelo.EntityFrameworkCore.MySql version: 3.2.0
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

**Comment by lauxjpn** [comment]
As a quick workaround, remove `ONLY_FULL_GROUP_BY` from [sql-mode](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html).
Bugfix will be out soon.
