### ISSUE TITLE
Packet received out-of-order

### ISSUE THREAD

**Issue by Toemsel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1176]
### Steps to reproduce
Simple select on a table.

### The issue
This exception is extremely flaggy. 1/500  times.

```
MySql.Data.MySqlClient.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.DoReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 470
   at MySqlConnector.Protocol.Serialization.StandardPayloadHandler.ReadPayloadAsync(ArraySegmentHolder`1 cache, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/StandardPayloadHandler.cs:line 42
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 782
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 794
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 507
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 72
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 729
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 396
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at DBCT.Persistence.Repository.EntityFramework.EntityFrameworkRepository`1.FirstOrDefaultAsync(Expression`1 predicate) in C:\Users\Thomas\Source\Repos\Toemsel\DBCT\DBCT.Persistence\Repository\EntityFramework\EntityFrameworkRepository.cs:line 32
   at DBCT.Persistence.UserContext.DoLogin(String emailAddress, String rawPassword, String lastKnownIpAddress) in C:\Users\Thomas\Source\Repos\Toemsel\DBCT\DBCT.Persistence\UserContext.cs:line 153
   at DBCT.WebApp.Pages.Auth.Login.LoginUserRequest() in C:\Users\Thomas\Source\Repos\Toemsel\DBCT\DBCT.WebApp\Pages\Auth\Login.razor:line 146
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Further technical details

MySQL version: 10.3.22-MariaDB-1ubuntu1
Operating system: Ubuntu Ubuntu 20.04.1 LTS
Pomelo.EntityFrameworkCore.MySql version: 3.2.1
Microsoft.AspNetCore.App version: 3.1
.NET Core version: 3.1.201

**Comment by mguinness** [comment]
As you didn't provide any code to repro the error, can you confirm you're awaiting async operation?  

Are you using Galera Cluster?  If so, you should take a look at issue https://github.com/mysql-net/MySqlConnector/issues/267.

Otherwise since the underlying exception is in [MySqlConnector](https://github.com/mysql-net/MySqlConnector) repo you should open an issue there.

**Comment by Sandaman2015** [comment]
i got same error with "Packet received out-of-order. Expected 1; got 2.",
here is my using :
Dotnet 5.0 + EntityFrameWork Core 2.0 + Polemo.EntityFrameWork.Mysql 5.0.1, this is a web api project.
Mysql Veresion: 8.0+
Opreation System: windwos 10
My project is open in github, hopefully you can look where is my code warn,  my project designed by repository unit  and all method was used asynchronous task. i awalys consider about it could be something wrong with my asnchronous task method on BaseRepository.c# 
open project url on github:  https://github.com/Sandaman2015/ZswBlog.Core
