### ISSUE TITLE
Exception when trying to generate reverse migration script

### ISSUE THREAD

**Issue by cdie** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1202]
### Steps to reproduce
Trying to generate a revert migration script : dotnet ef migrations script TheAppliedMigration TheMigrationBeforeIt -o revert.sql

### The issue
Exception on running command

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=3.2.3.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)
   at Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext`5..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`8..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`3..ctor(DbContextOptions options)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`1..ctor(DbContextOptions options)
   at HTS_SharedDataModel.EFCore.Data.HTSSharedDbContext..ctor(DbContextOptions`1 options) in D:\repos\HTS_SharedDataModel\src\HTS_SharedDataModel.EFCore\Data\HTSSharedDbContext.cs:line 25
   at HTS_SharedDataModel_MigrationHelper.DbContextFactory.CreateDbContext(String[] args) in D:\repos\HTS_SharedDataModel\src\HTS_SharedDataModel_MigrationHelper\Program.cs:line 12
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Further technical details

MySQL version: 
Operating system: Win 10 x64
Pomelo.EntityFrameworkCore.MySql version: 3.2.3
Microsoft.AspNetCore.App version: 5.0.0 rc2

Other details about my project setup:

**Comment by lauxjpn** [comment]
Please check what version of EF Core you are using. It is likely that you are using `5.0.0-rc.2` or some other 5.0-based version. Pomelo 3.2.3 is compatible only with EF Core 3.1.x (see [Compatibility: Dependencies](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#dependencies)).

To use EF Core 5 with Pomelo, use the latest _prerelease_ from out [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) (also see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-707776730).

**Comment by cdie** [comment]
Thank you for this answer, indeed I was using 5.0.0 rc2. 
with latest Pomelo alpha, it works as expected ! 
Many thanks !
