### ISSUE TITLE
"Sequence contains no matching element" Error while scaffolding dbcontext

### ISSUE THREAD

**Issue by mhdshevilkp2441** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#125]
### Steps to reproduce
Created a database in MySql with MSSql migration using migration wizard. Installed required packages for using Pomelo MySql Provider.
At the time of scaffolding dbcontext with NPM, it shows the error message "Sequence contains no matching element"

### The issue
Scaffold-DbContext shows error

```
Exception message: System.InvalidOperationException: Sequence contains no matching element
Stack trace: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetIndexes()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no matching element
```

### Further technical details

MySQL version: Server 5.6 (Workbench 6.2 CE)
Operating system: Windows 7 SP1 32 bit
Pomelo.EntityFrameworkCore.MySql version: 1.1.0-*

Other details about my project setup:
![image](https://cloud.githubusercontent.com/assets/23699619/20561720/f47d7cf4-b1a5-11e6-8020-1b7c4e107dcd.png)
![image](https://cloud.githubusercontent.com/assets/23699619/20561763/2bcaba82-b1a6-11e6-9624-614c317eb348.png)

**Comment by Kagamine** [comment]
Could you provide me your db creation sql?

**Comment by Kagamine** [comment]
Hey, this is not MySQL script.

**Comment by mhdshevilkp2441** [comment]
This is which I saved while doing migration from MsSql to MySql using MySql Migration Wizard

**Comment by Kagamine** [comment]
I want your MySql script not MSSQL

**Comment by Kagamine** [comment]
Could you post the files in which your migration folder?

**Comment by Kagamine** [comment]
MySQL is different from SQL Server. For example, MySQL doesn't support AKs. 

I'm not sure the migration script which generated by MSSQL can be merged into MySQL.
