### ISSUE TITLE
Cannot create enum column with code-first approach

### ISSUE THREAD

**Issue by PaulBol** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1271]
### The issue and reproduction steps
I would like to create a table like
```
CREATE TABLE `products` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Size` enum('small','medium','large') NOT NULL,
  PRIMARY KEY (`ID`)
)
```

using code first.

I tried

```
public class Product
{
    [Key(), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    [Column(TypeName = "varchar(255)"), Required()]
    public string Name { get; set; } 

    [DataType("enum('small','medium','large')")]
    public string Size { get; private set; } = "medium";
}
```

That produces column
```
`Size` longtext
```

Is there a chance to create the enum column with specific values?

### Further technical details

MySQL version: 8.0.22
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.2
Microsoft.AspNetCore.App version: --

**Comment by lauxjpn** [comment]
@PaulBol The MySQL `enum` type is currently not officially supported. We have an open issue about it though (see #36) and we will implement it in 5.0.x (but probably not in the initial release).

What database/table creation mechanism are you using? `Database.EnsureCreated()` or migrations?

**Comment by PaulBol** [comment]
Thanks for the feedback! I saw issue #36 but didn't connect the dots.

I'm using `Database.EnsureCreated()`. Will try to get the conversion to work via conventions until 5.0.x is ready and close this issue as duplicate.

**Comment by lauxjpn** [comment]
@PaulBol Let us know, if you need any help with that.
Also, if you are just using `Database.EnsureCreated()`, you can also just define the column as `varchar(n)`, and just run an `ALTER TABLE` statement after the `Database.EnsureCreated()` as a quick workaround.

**Comment by PaulBol** [comment]
Thanks for your support. This is the workaround that I ended up with

```cs
foreach (var enumProp in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetProperties()))
{
    var dataTypeAttribute = enumProp.PropertyInfo.GetCustomAttribute(typeof(DataTypeAttribute)) as DataTypeAttribute;
    if (dataTypeAttribute?.CustomDataType != null && dataTypeAttribute.CustomDataType.StartsWith("enum('", StringComparison.OrdinalIgnoreCase))
    {
        enumProp.SetColumnType(dataTypeAttribute.CustomDataType);
    }
}
```

**Comment by lauxjpn** [comment]
@PaulBol Thanks for sharing your solution with us.

In case you need true `enum` support, you can also just provide your own `IRelationalTypeMappingSourcePlugin` implementation.
Here is a fully working sample console project, that demonstrates this approach:

<details>
<summary>Sample program for custom enum support</summary>

```c#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;

namespace IssueConsoleTemplate
{
    // 
    // Database Entities:
    // 

    public class Product
    {
        public int ID { get; set; }

        [Required]
        [MaxLength(255)]
        public string Name { get; set; } 

        [Column(TypeName = "enum('small','medium','large')")]
        public string Size { get; set; } = "medium";
    }
    
    //
    // Custom type mapping plugin:
    //
    
    public class EnumTypeMappingSourcePlugin : IRelationalTypeMappingSourcePlugin
    {
        private readonly IMySqlOptions _options;

        public EnumTypeMappingSourcePlugin(IMySqlOptions options)
            => _options = options;

        /// <summary>
        /// Return a string type mapping with an `enum` store type, if an `enum()` type has been specified explicitly as the column type.
        /// </summary>
        public RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
            => string.Equals(mappingInfo.StoreTypeNameBase, "enum", StringComparison.OrdinalIgnoreCase)
                ? new MySqlStringTypeMapping(mappingInfo.StoreTypeName, _options)
                : null;
    }

    // 
    // DbContext:
    // 

    public class Context : DbContext
    {
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Register the custom type mapping plugin.
            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkMySql()
                .AddSingleton<IRelationalTypeMappingSourcePlugin, EnumTypeMappingSourcePlugin>()
                .AddScoped(
                    _ => LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .BuildServiceProvider();

            optionsBuilder
                .UseInternalServiceProvider(serviceProvider) // <-- use our custom ServiceProvider
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=Issue1271",
                    b => b.ServerVersion("8.0.21-mysql")
                          .CharSetBehavior(CharSetBehavior.NeverAppend))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }

            using (var context = new Context())
            {
                context.Products.Add(
                    new Product
                    {
                        ID = 1,
                        Name = "First Product",
                        Size = "small",
                    });

                context.SaveChanges();
            }

            using (var context = new Context())
            {
                var products = context.Products.ToList();

                Trace.Assert(products.Count == 1);
                Trace.Assert(products[0].ID == 1);
                Trace.Assert(products[0].Size == "small");
            }
            
            using (var context = new Context())
            {
                context.Products.Add(
                    new Product
                    {
                        ID = 2,
                        Name = "Second Product",
                        Size = "incorrect", // <-- incorrect enum value
                    });

                var exceptionThrown = false;
                
                try
                {
                    context.SaveChanges();
                }
                catch (Exception e)
                {
                    exceptionThrown = true;
                }
                
                Trace.Assert(exceptionThrown);
            }
        }
    }
}
```
</details>

<details>
<summary>Output of sample program</summary>

```console
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.21 MySql
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (76ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP DATABASE `Issue1271`;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1271`;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (45ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Products` (
          `ID` int NOT NULL AUTO_INCREMENT,
          `Name` varchar(255) NOT NULL,
          `Size` enum('small','medium','large') NULL,
          CONSTRAINT `PK_Products` PRIMARY KEY (`ID`)
      );
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.21 MySql
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11ms) [Parameters=[@p0='1', @p1='First Product' (Nullable = false) (Size = 255), @p2='small' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Products` (`ID`, `Name`, `Size`)
      VALUES (@p0, @p1, @p2);
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.21 MySql
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `p`.`ID`, `p`.`Name`, `p`.`Size`
      FROM `Products` AS `p`
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled DetailedErrorsEnabled ServerVersion 8.0.21 MySql
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (178ms) [Parameters=[@p0='1', @p1='First Product' (Nullable = false) (Size = 255), @p2='incorrect' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Products` (`ID`, `Name`, `Size`)
      VALUES (@p0, @p1, @p2);
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'IssueConsoleTemplate.Context'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
       ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'Size' at row 1
       ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'Size' at row 1
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
         at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 125
         at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 390
         at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
         at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 210
         at System.Data.Common.DbCommand.ExecuteReader()
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
         at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'Size' at row 1
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'Size' at row 1
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 390
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 210
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```
</details>

**Comment by PaulBol** [comment]
Cool! Looks way more professional than my workaround :-)
