### ISSUE TITLE
EF Core 5.0 Owned bug

### ISSUE THREAD

**Issue by huiyuanai709** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1290]
### Steps to reproduce
EF Core 5.0 OwnOne relation, It shouldn't have foreignKey relationship

### The issue
database script is correct
when call SaveChanges, It throw ForeignKey exception
```
Exception message:
The value of 'NotifyStrategy.NotifyViewId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Infrastructure.Repositories.NotifyViewRepository.Create(NotifyView notifyView, CancellationToken cancellationToken) in
```

### Further technical details

MySQL version: 5.7
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: alpha-2
Microsoft.AspNetCore.App version: 5.0

Other details about my project setup:

**Comment by lauxjpn** [comment]
@huiyuanai709 Please post the involved model classes, the model definitions (Fluent API) and the query, so we can reproduce the issue. Even better would be a small sample app.

**Comment by huiyuanai709** [comment]
My problem, Now it't correct now

**Comment by mguinness** [comment]
@huiyuanai709 Glad that you have it working now, can you share your fix in case others encounter this issue?
