### ISSUE TITLE
DbContextOptionsBuilder UseMySQL option 'name' not supported

### ISSUE THREAD

**Issue by lasamuadib** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1292]
### Steps to reproduce
I always use connection string names in my Scaffold-DbContext and thus the DB context that's created.  Now when I do that the scaffold works, but when running the code it blows up in the OnConfiguring statement.

`optionsBuilder.UseMySql("name=CCP", Microsoft.EntityFrameworkCore.ServerVersion.FromString("8.0.21-mysql"));`

System.ArgumentException: 'Option 'name' not supported.'

### The issue
This has always worked fine previously in numerous projects and broke when upgrading to EF Core 5.0 and vs 5.0.0-alpha.2 of this library.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: System.ArgumentException: 'Option 'name' not supported.'
Stack trace:
System.ArgumentException
  HResult=0x80070057
  Message=Option 'name' not supported.
  Source=MySqlConnector
  StackTrace:
   at MySqlConnector.MySqlConnectionStringOption.GetOptionForKey(String key) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 478
   at MySqlConnector.MySqlConnectionStringBuilder.set_Item(String key, Object value) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 379
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at MySqlConnector.MySqlConnectionStringBuilder..ctor(String connectionString) in /_/src/MySqlConnector/MySqlConnectionStringBuilder.cs:line 20
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsBuilderExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, ServerVersion serverVersion, Action`1 mySqlOptionsAction)
   at CNData.Models.Database.CCP.CCPContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in C:\Source\Workspaces\Coca-Cola\CokeNotifications\CNData\Models\Database\CCP\CCPContext.cs:line 90
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CNData.CCPData.ReadNotificationsTemplates() in C:\Source\Workspaces\Coca-Cola\CokeNotifications\CNData\CCPData.cs:line 74
   at CNTest.MainWindow.btnFixTemplates_Click(Object sender, RoutedEventArgs e) in C:\Source\Workspaces\Coca-Cola\CokeNotifications\CNTest\MainWindow.xaml.cs:line 105
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at CNTest.App.Main()
```

  This exception was originally thrown at this call stack:
```
    [External Code]
    CNData.Models.Database.CCP.CCPContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder) in CCPContext.cs
    [External Code]
    CNData.CCPData.ReadNotificationsTemplates() in CCPData.cs
    CNTest.MainWindow.btnFixTemplates_Click(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs
    [External Code]
```

### Further technical details

MySQL version: 8.0.21
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: 3.1

**Comment by mguinness** [comment]
As the exception message indicated, that option isn't supported looking at the [Connection String Options](https://mysqlconnector.net/connection-options/) from the underlying [MySqlConnector](https://github.com/mysql-net/MySqlConnector/) library.  I suspect you were previously using the Oracle Connector/NET ADO.NET driver?

**Comment by lauxjpn** [comment]
Probably the simplest way to accomplish what you want in EF Core is to use the [ConfigurationExtensions.GetConnectionString(IConfiguration, String)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationextensions.getconnectionstring?view=dotnet-plat-ext-5.0) extension method:

```c#
optionsBuilder.UseMySql(
    configuration.GetConnectionString("CCP"),
    Microsoft.EntityFrameworkCore.ServerVersion.FromString("8.0.21-mysql"));
```

**Comment by k1iguchi** [comment]
Therefore, MySql Code Generator.cs should generate such code, but it generate the first code.

**Comment by lauxjpn** [comment]
@k1iguchi PR #1611 adds support for `name=` connection strings.

We will generate the same code as before when scaffolding, but `UseMySql()` has been altered so it is able to handle a connection string that starts with `name=` (which is how the general EF Core support for it works).

Thanks for making us look at it again!
