### ISSUE TITLE
Cannot run scaffold when table with foreign key in other schema

### ISSUE THREAD

**Issue by MJWherry** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1313]
### Steps to reproduce
Create Schema1, Schema1
Create Table1 in Schema1 and Table2 in Schema2
Create foreign key in Schema1.Table1 referencing column in Schema2.Table2
run scaffold command for either schema1 or schema two (database=schema1 in conn str)

### The issue
Generation fails, removed foreign key and works

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: System.InvalidOperationException: Sequence contains no matching element
Stack trace:
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints(DbConnection connection, IReadOnlyList`1 tables)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnot
ations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useD
ataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

```

### Further technical details

MySQL version: 8.0.22-mysql
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha2
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
None, if i remove the keys i can scaffold and generate then add the foriegn keys, but ill lose the navigation aspect which is pretty useful, so there is a work around but adds more work on dev end

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/972 for some background regarding schemas.  The scaffolding code will need to be modified to ignore a FK in another database.

**Comment by lauxjpn** [comment]
@MJWherry There is no official other way then to scaffold the database without the foreign key.

Afterwards, you cannot officially reference the other database as well. (I have posted workarounds with sample code for this kind of issue here though.)

---

If this issue here applies to many tables though, and you definitely need to keep those databases physically separated from each other (otherwise, you could manage them in the same database with permissions, if this is about permissions), then it is possible to supply your own `MySqlDatabaseModelFactory` derived class with some custom overrides to EF Core.

If this should be the way you want to go, let me know and I paste you some code or link about the general process to get you started (there already exist some sample code in a comment from me here somewhere, about a scenario where someone wanted to filter the scaffolded objects in a specific way; the code uses the same approach as I am suggesting for this advanced scenario here). This would probably result in a bit of a hack in your case, but since scaffolding is usually only done once...

**Comment by MJWherry** [comment]
Ahh I see. It was more or less 1 db was used for assets and another used for user profile stuff, and a user would have a favorite table with multiple columns referencing the asset db. I can work around by just using Ids and lookups on the code end while adding the foreign keys after scaffolding. Thank you for the info!
