### ISSUE TITLE
Concurrency Update

### ISSUE THREAD

**Issue by ruirodrigues1971** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1316]
### Steps to reproduce
The situation
![image](https://user-images.githubusercontent.com/7416923/106318348-bd2e1700-6267-11eb-925f-ed890fb7f9e3.png)
The SQL Code if want to test (I think  you don't need the code, because I don't think is important, but ...)

```SQL
DROP TABLE IF EXISTS `user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user` (
  `idUser` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `surname` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `email` varchar(320) NOT NULL,
  `NIF` char(9) NOT NULL DEFAULT '' COMMENT 'sendo constituído por 9 dígitos. No caso de uma pessoa singular o primeiro dígito é sempre o 1 ou o 2.',
  `idUserState` int NOT NULL DEFAULT '1',
  `QRCode` varchar(400) DEFAULT NULL COMMENT 'QR Code encripted',
  `QRCodeActive` tinyint(1) NOT NULL DEFAULT '0',
  `QRCodeExpirationDate` datetime DEFAULT NULL,
  `RFID` varchar(400) DEFAULT NULL COMMENT 'you must garantee that is unique, but not using unique in database, because maybe is not necessary to have values\\\\nhttps://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html\\\\\\\\\\\\\\\\nuse of sha1 hex',
  `RFIDactive` tinyint(1) NOT NULL DEFAULT '0',
  `RFIDExpirationDate` datetime DEFAULT NULL,
  `keyboard` varchar(400) DEFAULT NULL,
  `keyboardactive` tinyint(1) NOT NULL DEFAULT '0',
  `keyboardExpirationDate` datetime DEFAULT NULL,
  `landlinephone` varchar(45) NOT NULL DEFAULT '',
  `mobilephone` varchar(45) NOT NULL DEFAULT '',
  `address` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `pswdbinarySHA256` binary(32) DEFAULT NULL COMMENT 'https://www.thatsoftwaredude.com/content/6218/how-to-encrypt-passwords-using-sha256-in-net',
  `startdateactive` datetime DEFAULT NULL,
  `enddateactive` datetime DEFAULT NULL,
  `details` varchar(400) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `joker` varchar(200) DEFAULT NULL COMMENT 'Have to be diferent of null if use authentication methods diferent from a license plate',
  `refresherToken` varchar(36) DEFAULT NULL COMMENT 'Used in refresh token process - uuid',
  `refresherToken_valid_until` datetime DEFAULT NULL,
  `photoPath` varchar(260) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '260 is the limit in windows(normally)',
  `lastLogin` datetime DEFAULT NULL COMMENT 'utc time',
  PRIMARY KEY (`idUser`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `QRCode_UNIQUE` (`QRCode`),
  UNIQUE KEY `RFIDcodebinarysha1_UNIQUE` (`RFID`),
  UNIQUE KEY `keyboard_UNIQUE` (`keyboard`),
  KEY `fk_user_state_idx` (`idUserState`),
  CONSTRAINT `fk_user_state` FOREIGN KEY (`idUserState`) REFERENCES `accesstate` (`idaccesstate`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `action`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `action` (
  `idaction` int NOT NULL,
  `name` varchar(45) NOT NULL COMMENT 'name to identify',
  `description` json NOT NULL COMMENT 'Explain what is the action',
  PRIMARY KEY (`idaction`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `usermessages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `usermessages` (
  `number` int unsigned NOT NULL AUTO_INCREMENT,
  `iduser` int NOT NULL,
  `date` datetime NOT NULL,
  `message` varchar(500) NOT NULL,
  PRIMARY KEY (`number`),
  KEY `fk_usermessages_idUser_idx` (`iduser`),
  CONSTRAINT `fk_usermessages_idUser` FOREIGN KEY (`iduser`) REFERENCES `user` (`idUser`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=84 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Messages to the user from the system';
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS `loguseractions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `loguseractions` (
  `idloguseractions` int NOT NULL,
  `iduser` int NOT NULL,
  `idaction` int NOT NULL,
  `Date` datetime NOT NULL,
  `Description` json NOT NULL COMMENT 'this is to be used by the system',
  `DescriptionManual` varchar(100) NOT NULL DEFAULT '' COMMENT 'This can be used when the action is manual',
  PRIMARY KEY (`idloguseractions`),
  KEY `fk_loguseractions_user_idx` (`iduser`),
  KEY `fk_loguseractions_action_idx` (`idaction`),
  CONSTRAINT `fk_loguseractions_action` FOREIGN KEY (`idaction`) REFERENCES `action` (`idaction`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_loguseractions_user` FOREIGN KEY (`iduser`) REFERENCES `user` (`idUser`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
```

### The issue

before the error that produce the problem I run the following method ... It was ok
```C#
using var dbContext = new MyDBContext();
dbContext.Add<User>(user);
user.Usermessages.Add(UserMessagesManager.MessageCreatedUser(user));
user.Loguseractions.Add(LogUserActionsManager.LogCreatedUser(user));
return dbContext.SaveChanges()
```
next in next method after I have done this 

```C#
using var dbContext = new MyDBContext();
user.Loguseractions.Add(LogUserActionsManager.LogChangeEmail(user, email));
user.Usermessages.Add(UserMessagesManager.MessageChangeEmail(user, email));
user.Email = email;
var entry = dbContext.Update(user);
dbContext.SaveChanges();
```

Exception
```
Exception message: Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Stack Trace:
    at AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
    at AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
    at AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
    at ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
    at BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
    at RelationalDatabase.SaveChanges(IList`1 entries)
    at StateManager.SaveChanges(IList`1 entriesToSave)
    at StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
    at MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
    at StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at DbContext.SaveChanges()
    at UserManager.ChangeEmail(User user, String email) line 231
    at RegistUserTest.UpdateEmailTest() line 51
```

**Work changing the order **
```C#
using var dbContext = new MyDBContext();
User userclone = new User()
{
    IdUser = user.IdUser,
    Email=user.Email
};
user.Email = email;
var entry = dbContext.Update(user);
user.Loguseractions.Add(LogUserActionsManager.LogChangeEmail(userclone, email));
user.Usermessages.Add(UserMessagesManager.MessageChangeEmail(userclone, email));
dbContext.SaveChanges();
```

**Maybe this is the normal of entity framework, but was strange for me**

### Further technical details

MySQL version: 8.0.22
Operating system: windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: .NET 5.0 (run application), the model/context in .NET standard 2.1

**Comment by lauxjpn** [comment]
@ruirodrigues1971 For normal operations in EF Core, first query the entity you want to change, then change the entity, then call `DbContext.SaveChanges()`:

```c#
var userId = 1;
using var dbContext = new MyDBContext();

// Query:
var user = dbContext.Users.FirstOrDefault(u => u.IdUser == userId);

// Change:
user.Email = email;
user.Loguseractions.Add(LogUserActionsManager.LogChangeEmail(userclone, email));
user.Usermessages.Add(UserMessagesManager.MessageChangeEmail(userclone, email));

// Call SaveChanges:
dbContext.SaveChanges();
```

Is there a particular reason, why you are working with disconnected entities?

**Comment by ruirodrigues1971** [comment]
@lauxjpn thanks.
You are right the user was gather in previous method (and dbcontext was dispose in that method)
but was very strange because when I have done

```csharp
using var dbContext = new MyDBContext();
user.Loguseractions.Add(LogUserActionsManager.LogChangeEmail(user, email));
//user.Usermessages.Add(UserMessagesManager.MessageChangeEmail(user, email));
user.Email = email;
var entry = dbContext.Update(user);
dbContext.SaveChanges();

```
I had no problem... Only when I add usermessages (comment in the above code) the exception appears.  

I have to learn more about EF core hehehe

but don't need to query this user again  just need to attach again to that particular context
```csharp
using var dbContext = new MyDBContext();
...
user.Email = email;
var entry = dbContext.Update(user); //<------- Attach an entity to context with a EntityState
user.Loguseractions.Add(LogUserActionsManager.LogChangeEmail(userclone, email));
user.Usermessages.Add(UserMessagesManager.MessageChangeEmail(userclone, email));
dbContext.SaveChanges();
```
of course you are right in normal situations is more wise to gather again the user (because of concurrency in database...). But this 2 methods will run one after de other and second one will be always run run after the success of first. The first method is used as helper function in my Test project.

This is only tests that I'm doing, but I see your point...I was trying to avoid one more connection to database.

**Thank you very much for your return...helped to understand better de EF core**
