### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by codehunter13** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1319]
### Steps to reproduce
The following code gives me a ObjectDisposedException. This does not happen with the microsoft mysql provider:
```C#
public async Task Execute(IJobExecutionContext context)
{
    try
    {
        var currentDay = DateTime.Today;

        var userExchanges = await _cryptoHunterDbContext.UserExchanges.ToListAsync();
        userExchanges.ForEach(async userExchange =>
        {
            var userExchangeService = _exchangeFactory.Create(
                userExchange.UserId,
                userExchange.Id);

            var btc = await userExchangeService
                .GetWalletStream()
                .FirstAsync()
                .Select(x => x.BtcValue);

            var existing = await _cryptoHunterDbContext.DailyStatistics
                .FirstOrDefaultAsync(x =>
                    x.UserId == userExchange.UserId &&
                    x.UserExchangeId == userExchange.Id &&
                    x.Day == currentDay);
            if (existing == null)
            {
                //throw new Exception("Daily statistic not found");
                _logger.LogError("Daily statistic not found");
            }
            else
            {
                existing.UpdateBtc(btc);
                await _cryptoHunterDbContext.SaveChangesAsync();
            }
        });
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, ex.Message);
    }
}
```

### The issue
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'CryptoHunterDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at GSL.CryptoHunter.Web.Services.QuartsJobs.QuartzTotalBtcDailyStatisticsJob.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext() in /src/Services/QuartsJobs/QuartzTotalBtcDailyStatisticsJob.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I use Pomelo version 3.2.4

Thx in advance,
Glenn

**Comment by lauxjpn** [comment]
@codehunter13 This is very likely to be an issue in your own implementation and unrelated to Pomelo.

To track this issue down, override the `Dispose()` method in your `DbContext` derived implementation and break into the debugger when the object gets disposed. This way, you should be able to track down, where (and why) your context gets disposed:

```c#
public class CryptoHunterDbContext : DbContext
{
    public override void Dispose()
    {
        Debugger.Break();
        base.Dispose();
    }
}
```

**Comment by codehunter13** [comment]
it gets disposed inside the call await _cryptoHunterDbContext.SaveChangesAsync();
so i dont see what my code is doing wrong.
if i change that line to the non async version, ive no problems

**Comment by lauxjpn** [comment]
@codehunter13 Please post the full stack trace of the `Dispose()` call, so we can take a look at it.

Usually, those kind of issue can happen e.g. in ASP.NET Core applications, if the request was handled and has returned, but some operation on another thread or a not awaited async operation is still running.

**Comment by codehunter13** [comment]
Stacktrace:
`at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at GSL.CryptoHunter.Web.Services.QuartsJobs.QuartzAddDailyStatisticsJob.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext() in C:\Users\Glenn.symons\source\repos\CryptoHunter\GSL.CryptoHunter\GSL.CryptoHunter.Web\Services\QuartsJobs\QuartzAddDailyStatisticsJob.cs:line 72
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

it is indeed an asp net core application that launches an other thread (quartz job).
I changed the code so that it creates a new scope for getting a new dbcontext. In that case, if the request returned, it should not dispose the dbcontext? But is still does. 
And it stays strange that the microsoft mysql provider does not have this problem

`
public async Task Execute(IJobExecutionContext context)
        {
            try
            {
                using (var scope = _serviceProvider.CreateScope())
                {
                    var dbContext = scope.ServiceProvider.GetRequiredService<CryptoHunterDbContext>();
                    var currentDay = DateTime.Today;

                    var userExchanges = await dbContext.UserExchanges.ToListAsync();
                    userExchanges.ForEach(async userExchange =>
                    {
                        var userExchangeService = _exchangeFactory.Create(
                            userExchange.UserId,
                            userExchange.Id);

                        var existing = dbContext.DailyStatistics
                            .FirstOrDefault(x =>
                                x.UserId == userExchange.UserId &&
                                x.UserExchangeId == userExchange.Id &&
                                x.Day == currentDay);
                        if (existing == null)
                        {
                            var newDailyStatistic = new DailyStatistics(currentDay, userExchange.UserId, userExchange.Id);
                            dbContext.DailyStatistics.Add(newDailyStatistic);
                            await dbContext.SaveChangesAsync(); //=> dbcontxt gets disposed here 
                        }
                    });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
        }
`

**Comment by lauxjpn** [comment]
> @codehunter13 Please post the full stack trace of the **Dispose()** call, so we can take a look at it.

I meant the stack trace of the **Dispose()** call (not the **CheckDisposed()** call):

> To track this issue down, override the `Dispose()` method in your `DbContext` derived implementation and break into the debugger when the object gets disposed. This way, you should be able to track down, where (and why) your context gets disposed:
> 
> ```cs
> public class CryptoHunterDbContext : DbContext
> {
>     public override void Dispose()
>     {
>         Debugger.Break();
>         base.Dispose();
>     }
> }
> ```

So we want to track down, where and why your object gets disposed (not where and why it is being checked whether it already has been disposed or not).

**Comment by codehunter13** [comment]
That was the solution. Thx for the explanation!
