### ISSUE TITLE
ToQueryString() throws an exception on guid equality check

### ISSUE THREAD

**Issue by mtnoztrk** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1325]
### Steps to reproduce
Test project with below code reproduces the issue.

Models.cs
``` c#
    public class Cart
    {
        [Key]
        public Guid Id { get; set; }
        public ICollection<CartProduct> CartProducts { get; set; }
    }

    public class Product
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

    public class CartProduct
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ProductId { get; set; }
        public Guid CartId { get; set; }
        public int Quantity { get; set; }

        public Product Product { get; set; }
        public Cart Cart { get; set; }
    }
```
TestContext.cs
``` c#
    public class TestContext : DbContext
    {
        public TestContext()
        {
        }

        public TestContext(DbContextOptions<TestContext> options) : base(options)
        {
        }

        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<CartProduct> CartProducts { get; set; }
    }
```
Test.cs
``` c#
   public class UnitTest1
    {
        [Fact]
        public async Task ToQueryStringTest()
        {
            var conn = "Server=localhost;User Id=root;Password=123;TreatTinyAsBoolean=true;SslMode=none;Database=to_query_string";
            var options = new DbContextOptionsBuilder<TestContext>().UseMySql(conn, ServerVersion.AutoDetect(conn), options =>
            {
                options.EnableRetryOnFailure(3);
            }).Options;
            var dbCtx = new TestContext(options);
            dbCtx.Database.EnsureCreated();
            var cartId = new Guid("04f4b016-08f7-4c03-a109-4d3aa7a77702");

            var qs = dbCtx.CartProducts.Where(c => c.CartId == cartId).ToQueryString();
            // below code does not throw exception
            // var qs = dbCtx.CartProducts.Where(c => c.CartId.ToString() == cartId.ToString()).ToQueryString();
        }
    }
```

### The issue
ToQueryString method throws an exception on Guid equality check. Also error message is very misleading, I tried to add MaxLenght attribute to every "char" related column in but it does not work. Instead of using == operator, I tried Equals() and CompareTo() methods these do not work either.

```
Exception message: Missing length for data type "char".
Stack trace:    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.ValidateMapping(CoreTypeMapping mapping, IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(String storeTypeName)
   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlQueryStringFactory.Create(DbCommand command)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.ToQueryString()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(IQueryable source)
   at AsSplit.UnitTest1.<Test2>d__1.MoveNext() in C:\Users\Metin\source\repos\assplit\AsSplit\UnitTest1.cs:line 36
```

### Further technical details

MySQL version: 5.7.28
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: -

Other details about my project setup:

**Comment by lauxjpn** [comment]
@mtnoztrk Thanks for reporting. Will be in our nightly builds once we merged #1327.
