### ISSUE TITLE
SaveChangesAsync not working with EFCore 6

### ISSUE THREAD

**Issue by Executor-Cheng** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1336]
### Steps to reproduce
Calling `DbContext.SaveChangesAsync([CancellationToken])` method

### The issue
```
Exception message: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.RelationalTransaction..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Data.Common.DbTransaction, System.Guid, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Transaction>, Boolean)'.
Stack trace:
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalTransaction..ctor(IRelationalConnection connection, DbTransaction transaction, Guid transactionId, IDiagnosticsLogger`1 logger, Boolean transactionOwned)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalTransactionFactory.Create(IRelationalConnection connection, DbTransaction transaction, Guid transactionId, IDiagnosticsLogger`1 logger, Boolean transactionOwned)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.CreateRelationalTransaction(DbTransaction transaction, Guid transactionId, Boolean transactionOwned)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Further technical details

MariaDB version: 10.5.5
Operating system: Windows Server 2016 Datacenter
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.EntityFrameworkCore version: 6.0.0-preview.1.21102.2
Microsoft.AspNetCore.App version: 6.0.0-preview.1

**Comment by mguinness** [comment]
It is unlikely that [5.0.0-alpha.2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2) is compatible w/ EF Core 6, suggest you use [EF Core 5](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.3) instead.

**Comment by Executor-Cheng** [comment]
Ok, is there any plan for EF Core 6?

**Comment by mguinness** [comment]
After EF Core 5 stable is released then work will shift to EF Core 6, but there is no timeframe available yet.
