### ISSUE TITLE
No support for MySQL EF Core Multithreaded

### ISSUE THREAD

**Issue by WebMasterSam** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1340]
### Steps to reproduce
Create a simple Parallel loop that will insert multiple items in the same database.

```
var actions = new List<Action>();

actions.Add(() => { new DbContext.Set<TEntity>().Add(entity); });
actions.Add(() => { new DbContext.Set<TEntity>().Add(entity); });
actions.Add(() => { new DbContext.Set<TEntity>().Add(entity); });
actions.Add(() => { new DbContext.Set<TEntity>().Add(entity); });

Parallel.ForEach(actions, new ParallelOptions { MaxDegreeOfParallelism = 2 },
action =>
{
     action();
});
```

### The issue
MySQL does not accept multiple active connections to the same database within the same transaction. Entity Framework opens a new connection internally each time we want to Add an entity.

So, it's impossible to open a global connection manually that we would pass to all our subsequent DBContexts.

I know that DBContexts are not Thread-safe in EF Core, this is why I would create a new DBContext for each thread.
```
Exception message: Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported.

Stack trace:   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CloseTheMonth.Backend.Data.Repositories.AccountUserRightRepository.ListAccounts(Guid userId) in C:\Work\GitHub\CloseTheMonth\Backend\CloseTheMonth.Data\Repositories\AccountUserRightRepository.cs:line 44
   at CloseTheMonth.Backend.Services.AccountUserRightService.ListAccounts(Guid userId) in C:\Work\GitHub\CloseTheMonth\Backend\CloseTheMonth.Services\AccountUserRightService.cs:line 53
   at CloseTheMonth.Backend.Controllers.AppController.Init(String authorization, AppInitRequest request) in C:\Work\GitHub\CloseTheMonth\Backend\CloseTheMonth.Backend\Controllers\AppController.cs:line 101
```
### Reflections...
If I could open a connection globally, like this, and pass it to my DBContexts, that would do the trick.

```
var actions = new List<Action>();

using (var conn = new MySqlConnection())
{
   actions.Add(() => { new DbContext(conn).Set<TEntity>().Add(entity); });
   actions.Add(() => { new DbContext(conn).Set<TEntity>().Add(entity); });
   actions.Add(() => { new DbContext(conn).Set<TEntity>().Add(entity); });
   actions.Add(() => { new DbContext(conn).Set<TEntity>().Add(entity); });

   Parallel.ForEach(actions, new ParallelOptions { MaxDegreeOfParallelism = 2 },
   action =>
   {
        action();
   });
}
```

Any other solution can be appreciated also. The only thing is that I can make this very simple Parallel loop work...

### Further technical details

MySQL version: 8.0.22
Operating system: Windows 10 / Linux
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
Microsoft.AspNetCore.App version: 2.1.0

**Comment by mguinness** [comment]
Does this answer for [Using EF in conjunction with Task Parallel Library](https://stackoverflow.com/a/44768901/310601) help?

**Comment by WebMasterSam** [comment]
I just learned something new, which is we can't perform concurrent actions within the same connection, we NEED to open multiple connections to perform multiple actions at the same time. Outside a transaction, there's no problem, but within a transaction, MySQL prohibits opening multiple connections. It's simply not supported.

One solution I've been pointed to is to use something else like Bulk inserts (doing it without EF Core) when my large insert routines need performance enhancement.

More informations on my StackOverflow question
https://stackoverflow.com/questions/66426527/is-there-a-way-to-pass-an-already-opened-mysql-connection-to-ef-core-dbcontext
