### ISSUE TITLE
Invalid SQL generated when changing the primary key in migration with .AddPrimaryKey(...)

### ISSUE THREAD

**Issue by Mertsch** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1348]
### Steps to reproduce
See code in https://github.com/Mertsch/PomeloPrimaryKeyBug
1. Have a primary key
2. Add migration
3. Change primary key
4. Add migration
5. Execute migrations (get exception on the 2nd)

### The issue
The migration step
```
migrationBuilder.AddPrimaryKey(
                name: "PK_tasks_workers",
                table: "tasks_workers",
                columns: new[] { "TrekkTemplateId", "WorkerId" });
```
generates the SQL statement
```
ALTER TABLE `tasks_workers` ADD CONSTRAINT `TemplateContainsTemplateWorkers`
 FOREIGN KEY (`TrekkTemplateId`) -- Correct, this is the actual column name
 REFERENCES `tasks` (`TrekkTemplateId`) -- Incorrect!, this is the column name from FOREIGN KEY, not the real one.
 ON DELETE CASCADE;
```
## Exception
```
Failed executing DbCommand (25ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `tasks_workers` ADD CONSTRAINT `TemplateContainsTemplateWorkers` FOREIGN KEY (`TrekkTemplateId`) REFERENCES `tasks` (`TrekkTemplateId`) ON DELETE CASCADE;
MySqlConnector.MySqlException (0x80004005): Can't create table `repobugdb`.`tasks_workers` (errno: 150 "Foreign key constraint is incorrectly formed")
 ---> MySqlConnector.MySqlException (0x80004005): Can't create table `repobugdb`.`tasks_workers` (errno: 150 "Foreign key constraint is incorrectly formed")
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 131
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 436
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 100
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version:  10.4.17-MariaDB - mariadb.org binary distribution 
Operating system: Win 10 x64
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: 5.0.4

**Comment by lauxjpn** [comment]
The following code works for me without issues:

<details>
<summary>Program.cs</summary>
```c#
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<IceCream_IceCreamParlor> IceCreamIceCreamParlors{ get; set; } = new HashSet<IceCream_IceCreamParlor>();
    }

    public class IceCreamParlor
    {
        public int IceCreamParlorId { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<IceCream_IceCreamParlor> IceCreamIceCreamParlors{ get; set; } = new HashSet<IceCream_IceCreamParlor>();
    }
    
    public class IceCream_IceCreamParlor
    {
        /public int AccidentalId { get; set; } // <-- Remove for the second migration
        public int IceCreamId { get; set; }
        public int IceCreamParlorId { get; set; }
        
        public IceCream IceCream { get; set; }
        public IceCreamParlor IceCreamParlor { get; set; }
    }

    public class Context : DbContext
    {
        public virtual DbSet<IceCream> IceCreams { get; set; }
        public virtual DbSet<IceCreamParlor> IceCreamParlors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                const string connectionString = "server=127.0.0.1;port=3308;user=root;password=;database=Issue1348_01";
                var serverVersion = ServerVersion.AutoDetect(connectionString);
                
                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion,
                        options => options
                            .CharSetBehavior(CharSetBehavior.NeverAppend)) 
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream_IceCreamParlor>(
                entity =>
                {
                    entity.HasKey(e => e.AccidentalId); // <-- Remove for second migration
                    // entity.HasKey(e => new {e.IceCreamId, e.IceCreamParlorId}); // <-- Add for second migration
                    entity.HasIndex(e => e.IceCreamId);
                    entity.HasIndex(e => e.IceCreamParlorId);
                });
        }
    }

    internal static class Program
    {
        private static void Main(string[] args)
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```
</details>

I run the following CLI command:

```
dotnet ef migrations add Initial
```

It generates the following migration `Up()` method:

<details>
<summary>Initial migration UP() method</summary>
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
    // ...

    migrationBuilder.CreateTable(
        name: "IceCream_IceCreamParlor",
        columns: table => new
        {
            AccidentalId = table.Column<int>(type: "int", nullable: false) // <-- the ID the should be removed with the next migration
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
            IceCreamId = table.Column<int>(type: "int", nullable: false),
            IceCreamParlorId = table.Column<int>(type: "int", nullable: false)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_IceCream_IceCreamParlor", x => x.AccidentalId); // <-- the PK the should be changed with the next migration
            table.ForeignKey(
                name: "FK_IceCream_IceCreamParlor_IceCreamParlors_IceCreamParlorId",
                column: x => x.IceCreamParlorId,
                principalTable: "IceCreamParlors",
                principalColumn: "IceCreamParlorId",
                onDelete: ReferentialAction.Cascade);
            table.ForeignKey(
                name: "FK_IceCream_IceCreamParlor_IceCreams_IceCreamId",
                column: x => x.IceCreamId,
                principalTable: "IceCreams",
                principalColumn: "IceCreamId",
                onDelete: ReferentialAction.Cascade);
        });

    migrationBuilder.CreateIndex(
        name: "IX_IceCream_IceCreamParlor_IceCreamId",
        table: "IceCream_IceCreamParlor",
        column: "IceCreamId");

    migrationBuilder.CreateIndex(
        name: "IX_IceCream_IceCreamParlor_IceCreamParlorId",
        table: "IceCream_IceCreamParlor",
        column: "IceCreamParlorId");
}
```
</details>

I add and remove the marked comments in the code and run the following CLI command:

```
dotnet ef migrations add ChangePrimaryKey
```

It generates the following migration `Up()` method:

<details>
<summary>ChangePrimaryKey migration Up() method</summary>
```c#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropPrimaryKey(
        name: "PK_IceCream_IceCreamParlor",
        table: "IceCream_IceCreamParlor");

    migrationBuilder.DropColumn(
        name: "AccidentalId",
        table: "IceCream_IceCreamParlor");

    migrationBuilder.AddPrimaryKey(
        name: "PK_IceCream_IceCreamParlor",
        table: "IceCream_IceCreamParlor",
        columns: new[] { "IceCreamId", "IceCreamParlorId" });
}
```
</details>

I run the following CLI command:

```
dotnet ef migrations script
```

It generates the following SQL script:

<details>
<summary>Final SQL script</summary>
```sql
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);

START TRANSACTION;

CREATE TABLE `IceCreamParlors` (
    `IceCreamParlorId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext NULL,
    CONSTRAINT `PK_IceCreamParlors` PRIMARY KEY (`IceCreamParlorId`)
);

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
);

CREATE TABLE `IceCream_IceCreamParlor` (
    `AccidentalId` int NOT NULL AUTO_INCREMENT,
    `IceCreamId` int NOT NULL,
    `IceCreamParlorId` int NOT NULL,
    CONSTRAINT `PK_IceCream_IceCreamParlor` PRIMARY KEY (`AccidentalId`),
    CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreamParlors_IceCreamParlorId` FOREIGN KEY (`IceCreamParlorId`) REFERENCES `IceCreamParlors` (`IceCreamParlorId`) ON DELETE CASCADE,
    CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreams_IceCreamId` FOREIGN KEY (`IceCreamId`) REFERENCES `IceCreams` (`IceCreamId`) ON DELETE CASCADE
);

CREATE INDEX `IX_IceCream_IceCreamParlor_IceCreamId` ON `IceCream_IceCreamParlor` (`IceCreamId`);

CREATE INDEX `IX_IceCream_IceCreamParlor_IceCreamParlorId` ON `IceCream_IceCreamParlor` (`IceCreamParlorId`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210402011307_Initial', '5.0.4');

COMMIT;

START TRANSACTION;

DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `Extra` = 'auto_increment'
                        AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID INT(11);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                        AND `COLUMN_TYPE` LIKE '%int%'
                        AND `COLUMN_KEY` = 'PRI';
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

ALTER TABLE `IceCream_IceCreamParlor` DROP FOREIGN KEY `FK_IceCream_IceCreamParlor_IceCreamParlors_IceCreamParlorId`;

ALTER TABLE `IceCream_IceCreamParlor` DROP FOREIGN KEY `FK_IceCream_IceCreamParlor_IceCreams_IceCreamId`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'IceCream_IceCreamParlor');
ALTER TABLE `IceCream_IceCreamParlor` DROP PRIMARY KEY;

ALTER TABLE `IceCream_IceCreamParlor` ADD CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreamParlors_IceCreamParlorId` FOREIGN KEY (`IceCreamParlorId`) REFERENCES `IceCreamParlors` (`IceCreamParlorId`) ON DELETE CASCADE;

ALTER TABLE `IceCream_IceCreamParlor` ADD CONSTRAINT `FK_IceCream_IceCreamParlor_IceCreams_IceCreamId` FOREIGN KEY (`IceCreamId`) REFERENCES `IceCreams` (`IceCreamId`) ON DELETE CASCADE;

ALTER TABLE `IceCream_IceCreamParlor` DROP COLUMN `AccidentalId`;

ALTER TABLE `IceCream_IceCreamParlor` ADD CONSTRAINT `PK_IceCream_IceCreamParlor` PRIMARY KEY (`IceCreamId`, `IceCreamParlorId`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210402011347_ChangePrimaryKey', '5.0.4');

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;

COMMIT;
```
</details>

This SQL script runs without errors in any MySQL/MariaDB version I tried, including `10.2.33-MariaDB`.

**Comment by Mertsch** [comment]
@lauxjpn I have tried `5.0.0-alpha.3.ci.20210405222846` and the error in the sample repo has been replaced by a different error

```
Applying migration '20210315180016_InititalMigration'.
Applying migration '20210315180105_ChangeDbTrekkTemplateUserKey'.
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `tasks_workers` DROP INDEX `IX_tasks_workers_TrekkTemplateId`;
MySqlConnector.MySqlException (0x80004005): Cannot drop index 'IX_tasks_workers_TrekkTemplateId': needed in a foreign key constraint
 ---> MySqlConnector.MySqlException (0x80004005): Cannot drop index 'IX_tasks_workers_TrekkTemplateId': needed in a foreign key constraint
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 131
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 436
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 100
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot drop index 'IX_tasks_workers_TrekkTemplateId': needed in a foreign key constraint
```

**Comment by lauxjpn** [comment]
The issue now is the following call in your second migrations `Up()` method:

```c#
migrationBuilder.DropIndex(
    name: "IX_tasks_workers_TrekkTemplateId",
    table: "tasks_workers");
```

This call shouldn't be there, but appears to be generated by the EF Core differ for some inexplicable reason.

So as a quick workaround, remove the line from the `Up()` method, and your code should run fine.

I am currently tracking down, whether this has to do with your redundant `UsingEntity()` call.

**Comment by bricelam** [comment]
Can you submit a new issue on [dotnet/efcore](https://github.com/dotnet/efcore) so we can investigate further?

**Comment by bricelam** [comment]
This provider may need to be responsible for rebuilding the foreign keys (similar to https://github.com/dotnet/efcore/issues/12586), but I want to make sure I fully understand the issue first.

**Comment by lauxjpn** [comment]
> This provider may need to be responsible for rebuilding the foreign keys (similar to dotnet/efcore#12586), but I want to make sure I fully understand the issue first.

@bricelam I'll open an issue on the EF Core repo. The issue is, that the index gets dropped in the first place. It is the wrong index (it has nothing to do with the PK that is being dropped).

**Comment by lauxjpn** [comment]
The migration operation order is [not going to change in EF Core](https://github.com/dotnet/efcore/issues/24638#issuecomment-925884294), so we will implement a Pomelo specific fix for this.

**Comment by andreiTuduce** [comment]
Are there any news to this issue?
