### ISSUE TITLE
error Unknown column 'ResidentId' in 'field list'

### ISSUE THREAD

**Issue by EccentricDyslexic** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1376]
### Steps to reproduce

From controller
```C#
var newForm = new Form()                        
{
    Id = viewModel.Incident.Id,                    
    SubmittedDate = submittedDateTimeZoned.ToDateTimeUtc(),
    SubmitterId = User.FindFirstValue(ClaimTypes.NameIdentifier),
    IsDraft = draft,
    FormType = FormType.Incident,
    FollowUp = false,
    FollowedUpById = null,
    FollowedUpDateTime = null
};
dbContext.Add(newForm);
dbContext.SaveChanges(); 
```

From context
```C#
builder.Entity<Form>()
    .ToTable("formdata");
builder.Entity<Form>()
    .HasOne(i => i.SubmitterPerson)
    .WithMany()
    .HasForeignKey(i => i.SubmitterId);
builder.Entity<Form>()
    .HasOne(i => i.FollowedUpBy)
    .WithMany()
    .HasForeignKey(i => i.FollowedUpById);
```

From class
```C#
public class Form
{
    public string Id { get; set; }
    public DateTime SubmittedDate { get; set; }
    public string SubmitterId { get; set; }
    public Person SubmitterPerson { get; set; }
    public bool? IsDraft { get; set; }
    public FormType FormType { get; set; }
    public bool? FollowUp { get; set; }
    public string FollowedUpById { get; set; }
    public Person FollowedUpBy { get; set; }
    public DateTime? FollowedUpDateTime { get; set; }
    public IList<FormPeople> AssociatedPeople { get; set; }
}

public enum FormType : byte
{
    Incident = 1,
    PrimaryHealthCare = 2,
    FullSupervision = 3,
    ObservationSupervision = 4,
    TelephoneSupervison = 5,
    One2OneSupervision = 6
}
```
### The issue
The error is that an odd reference to ResidentId is being targeted and I've no idea where it has come from!

```
MySqlConnector.MySqlException (0x80004005): Unknown column 'ResidentId' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

A form maps to an incident entry form so is a 1-to-1 relationship.

### Further technical details

MySQL version: 8.0.19
Operating system: W10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0.a2
Microsoft.AspNetCore.App version: 5.0

**Comment by mguinness** [comment]
Have you overridden `SaveChanges()` in your `DBContext`?

**Comment by EccentricDyslexic** [comment]
Hi, I’m not sure what you mean by that to be honest. I’m learning from the deep end after my BIL helped me build a web app. He’s got me set up but I’ve struggled without decent ef debugging so upgraded to ef5 with pomelo. 
I don’t believe I have overridden save changes?

Sent from my iPad Pro

On 6 Apr 2021, at 23:57, mguinness ***@***.***> wrote:

﻿
Have you overridden SaveChanges() in your DBContext?

**Comment by mguinness** [comment]
You would have a declaration like `public override int SaveChanges()` in your `DbContext`.  Are you able to debug the code in Visual Studio?  What is the SQL being generated?

**Comment by lauxjpn** [comment]
In addition to what @mguinness said, execute a search in your IDE/editor over all files of the project/solution for `ResidentId`. It should point you to either a property of one of your entities, or to your model definition (e.g. in `YoueDbContext.OnModelCreating()`), or both.

**Comment by EccentricDyslexic** [comment]
> ResidentId

Hi, im happy to let someone teamview in to have a look if viable, but would rather not share it because it has some sensitive information within.

There are a few incidences of ResidentId in the controler, but non i can see that should have any effect on this particular entity. 

Here is the sql generated `Form {Id: 9e0893fe-46bc-4213-853e-fd75172bfa1f} Added FK {FollowedUpById: <null>} FK {ResidentId: <null>} FK {SubmitterId: 5E5D44AF-2B72-4F7D-AC95-F99530E2752D}
Incident {Id: 9e0893fe-46bc-4213-853e-fd75172bfa1f} Added FK {Id: 9e0893fe-46bc-4213-853e-fd75172bfa1f}`

**Comment by EccentricDyslexic** [comment]
> You would have a declaration like `public override int SaveChanges()` in your `DbContext`. Are you able to debug the code in Visual Studio? What is the SQL being generated?

I search for override and yes - 

```  protected override void OnModelCreating(ModelBuilder builder)```

**Comment by EccentricDyslexic** [comment]
This is my context 

```using CareHomeForms.Services.Data.Models;
using CareHomeForms.Services.Data.Models.DocumentModels;
using CareHomeForms.Services.Data.Models.FormModels;
using Microsoft.EntityFrameworkCore;

namespace CareHomeForms.Services.Data
{
    public class CareHomesDbContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Employee> Employees { get; set; }

        public DbSet<Resident> Residents { get; set; }
        public DbSet<Home> Homes { get; set; }
        public DbSet<ContactDetails> ContactDetails { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentReviews> DocumentReviews { get; set; }
        public DbSet<PersonDocument> PersonDocuments { get; set; }
        public DbSet<LoginUser> LogInUser { get; set; }
        public DbSet<LoginRole> LogInRoles { get; set; }
        public DbSet<Form> Forms { get; set; }
        public DbSet<FormPeople> PersonForms { get; set; }
        public DbSet<Incident> Incidents { get; set; }

        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<PrimaryHealthCare> PHCForms { get; set; }


        public CareHomesDbContext(DbContextOptions<CareHomesDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Person>()
                .ToTable("people");

            builder.Entity<Employee>()
                .ToTable("employees"); // Employee objects map to this table

            builder.Entity<Employee>()
                .HasOne(e => e.Person) // It has a relationship to a Person using this property
                .WithOne(p=>p.Employee) // And the person maps back to this with a single employee but no property is defined to model that direction
                .HasForeignKey<Employee>(e=>e.Id); // This is the field to use on the employee for the foreign key

            builder.Entity<Employee>()
                .HasOne(e => e.Resident)
                .WithOne(r => r.KeyWorker)
                .HasForeignKey<Employee>(e=>e.Id);

            builder.Entity<Employee>()
             .HasOne(h => h.Home)
             .WithMany(h => h.Employees)
             .HasForeignKey(h => h.Id);

            builder.Entity<Home>()
                .ToTable("homes");

            builder.Entity<Home>()
                .HasOne(i => i.Address)
                .WithOne();

            builder.Entity<Home>()
                 .HasMany(h => h.Residents)
                 .WithOne(r => r.Home);

            builder.Entity<Home>()
               .HasMany(h => h.ContactDetails)
               .WithOne(cd => cd.Home)
               .HasForeignKey(cd => cd.OwnerId);

            builder.Entity<ContactDetails>()//the entity 'ContactDetails' maps to 
                .ToTable("contactdetails");//the table named 'contactdetails' in the database.

            builder.Entity<ContactDetails>()
                .HasOne(cd => cd.Person)
                .WithMany(p => p.ContactDetails);

            builder.Entity<ContactDetails>()
                .HasOne(cd => cd.Home)
                .WithMany(h => h.ContactDetails);

            builder.Entity<ContactDetails>()
              .HasOne(i => i.Person)
              .WithMany(i => i.ContactDetails)
              .HasForeignKey(i => i.OwnerId);
         
            builder.Entity<Address>()
                .ToTable("addresses");

            builder.Entity<Address>()
                .HasOne(a => a.Person)
                .WithOne(p => p.Address)
                .HasForeignKey<Address>(a => a.AddressFor);

            builder.Entity<Resident>()
                .ToTable("residents");
            
            builder.Entity<Resident>()
                .HasOne(r => r.Home)
                .WithMany(h => h.Residents);

            builder.Entity<Resident>()
                .HasOne(r => r.Person)
                .WithOne(i => i.Resident)
                .HasForeignKey<Resident>(i => i.Id);
            
            builder.Entity<LoginRole>()
                .ToTable("loginroles")
                .HasKey(i => i.LoginId);

            builder.Entity<LoginRole>()
                .HasOne(i => i.LoginUser)
                .WithMany(i => i.LogInRoles)
                .HasForeignKey(i => i.LoginId);

            builder.Entity<LoginUser>()
                .ToTable("logins");

            builder.Entity<LoginUser>()
                .HasOne(i => i.Person)
                .WithOne()
                .HasForeignKey<LoginUser>(i => i.Id);

            builder.Entity<Document>()
                .ToTable("documents");

            builder.Entity<Document>()
                .HasOne(i => i.AuthorPerson)
                .WithMany()
                .HasForeignKey(i => i.Author);

            builder.Entity<Document>()
                .HasMany(i => i.Reviews)
                .WithOne()
                .HasForeignKey(i => new { i.OriginalDocumentId, i.VersionNumber })
                .HasPrincipalKey(i => new { i.OriginalId, i.Version });
                    
            builder.Entity<Document>()
                .HasOne(i => i.LastReviewedBy)
                .WithMany()
                .HasForeignKey(i => i.ReviewedById);



             builder.Entity<Form>()
                .ToTable("formdata");

            builder.Entity<Form>()
                .HasOne(i => i.SubmitterPerson)
                .WithMany()
                .HasForeignKey(i => i.SubmitterId);

            builder.Entity<Form>()
                .HasOne(i => i.FollowedUpBy)
                .WithMany();

          

            builder.Entity<PersonDocument>()
                .HasOne(i => i.Person)
                .WithMany()
                .HasForeignKey(i => i.PersonId);

            builder.Entity<DocumentReviews>()
                .ToTable("documentreviews");

            builder.Entity<DocumentReviews>()
                .HasOne(i => i.Reviewer)
                .WithMany()
                .HasForeignKey(i=>i.ReviewedById);
                     
            builder.Entity<Attachment>()
                .ToTable("attachments");

            builder.Entity<FormPeople>()
                .ToTable("peopleforms")
                .HasKey(i => new { i.PersonId, i.FormId });

            builder.Entity<FormPeople>()
                .HasOne(i => i.Form) // Don't need the HasPrincipal since it follows the convension and is called FormId
                .WithMany(i => i.AssociatedPeople);

            builder.Entity<FormPeople>()
                .HasOne(i => i.Person)
                .WithMany(i => i.Forms);

            builder.Entity<PersonDocument>()
               .ToTable("peopledocuments");

            builder.Entity<PersonDocument>()
                .HasKey(i => new { i.PersonId, i.DocumentId });

            builder.Entity<PersonDocument>()
                .HasOne(i => i.Document)
                .WithOne(i => i.AssociatedPerson);

            builder.Entity<Incident>()
                .ToTable("incident");

            builder.Entity<Incident>()
                .Property(i => i.Informed111)
                .HasColumnName("_111Informed");

            builder.Entity<Incident>()
                .Property(i => i.Informed999)
                .HasColumnName("_999Informed");

            builder.Entity<Incident>()
                .HasOne(i => i.Form)
                .WithOne()
                .HasForeignKey<Incident> (i => i.Id);//for one to one relationships we need to configure FK like this for some reason
            
            builder.Entity<Incident>()
            .Property(f => f.IncidentNumber)
            .ValueGeneratedOnAdd();

            builder.Entity<PrimaryHealthCare>()
                .ToTable("primaryhealthcareform");

            builder.Entity<PrimaryHealthCare>()
                .HasOne(i => i.FormData)
                .WithOne()
                .HasForeignKey<PrimaryHealthCare>(i => i.Id); ;
        }
    }
}
```

**Comment by EccentricDyslexic** [comment]
This is my startup

```     services.AddDbContext<CareHomesDbContext>((svc, options) =>
            {
            options.UseLoggerFactory(svc.GetService<ILoggerFactory>());
            var dbOptions = svc.GetService<IOptions<DatabaseOptions>>();
                options
                    .UseMySql(
                    dbOptions.Value.ConnectionString,
                    new MySqlServerVersion(new Version(8, 0, 19)), // <-- use new Version() parameter instead
                    mySqlOptions => mySqlOptions
                    .CharSetBehavior(CharSetBehavior.NeverAppend))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
            });```

**Comment by lauxjpn** [comment]
@EccentricDyslexic Please post the class of the `Resident` entity.

It is possible, that it does not have a primary key setup. If that would be the case, then since it is being referenced by other entities, it might end up being assigned a shadow property that is being named `ResidentId`, to ensure that a primary key is available.

If you then use an existing database, this shadow property would have never been created (and therefore not exist) and would lead to a syntax error due to the missing column in the table.

**Comment by EccentricDyslexic** [comment]
```public class Resident
	{
		public string Id { get; set; }

		public Person Person { get; set; }
		public Home Home { get; set; }
		public Employee KeyWorker { get; set; }
		public ICollection<Form> Forms { get; set; }
	}```

**Comment by lauxjpn** [comment]
@EccentricDyslexic How does the `Form` class (`formdata` table) look like?

**Comment by EccentricDyslexic** [comment]
![image](https://user-images.githubusercontent.com/6297733/113876546-20807c00-97b8-11eb-97b7-c1e31354f2d1.png)

**Comment by EccentricDyslexic** [comment]
> That is likely to solve your issue.

Yes, it diid, thanks for that. but in order to not have this issue again, what shoud i do?

**Comment by lauxjpn** [comment]
> Yes, it diid, thanks for that. but in order to not have this issue again, what shoud i do?

Technically, it is enough to have a foreign key property for every relationship (so one FK for a pair of navigation properties, implicit or explicit).

However, if you are new to EF Core, I would suggest to always fully define your model with the Fluent API (e.g. in the `OnModelCreating()` method). That does include the `.HasForeignKey()` call for navigation properties (which you have done for some, but not all your navigation properties). This would not directly prevented the issue, but it does help with awareness about navigation properties.

If you define a navigation property in model class, create the corresponding model definition for it.
