### ISSUE TITLE
Transaction Exception occurs outside of transaction

### ISSUE THREAD

**Issue by andrekat** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1381]
### Steps to reproduce
I am trying to delete all records in a transaction to insert new ones. During the process an exception occurs, which is fine - according to this it should undo the transaction and continue in my flow. Now the problem: After this error, I try to update an entry in the context, but this fails with the same error message, although it is a completely different table and transaction? 

### The issue
After the transaction fails, I am doing an "RollbackAsync()" which in my oppinion should rollback the failed transaction?

The code which throws an exception and rolls back:

```
            await using var transaction = await _context.Database.BeginTransactionAsync();
            try
            {
                var oldOrderDtos = await _context.Orders.Where(x => x.UserId == user.Id).Select(x => new OrderDto() { Id = x.Id }).AsNoTracking()
                    .ToListAsync();
                var newOrderDtos = _mapper.Map<IEnumerable<OrderDto>>(orders).ToList();

                _context.Orders.RemoveRange(oldOrderDtos);
                await _context.SaveChangesAsync();

                newOrderDtos.ForAll(x => x.UserId = user.Id);
                _context.Orders.AddRange(newOrderDtos);
                await _context.SaveChangesAsync();

                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError($"[{user.Email}] Error while syncing orders.", ex);
                return "ORDERS-" + ex.Message + "-" + user.Id;
            }
```

The code which updates an entry regardless if the previous transaction was successful and throws the same exception as the transaction above:

            var unfinishedHistory = await GetUnfinishedAsync(userId);
            unfinishedHistory.Success = success;
            unfinishedHistory.SyncEnd = DateTimeOffset.Now;
            unfinishedHistory.ErrorMessage = error;

            await _context.SaveChangesAsync();

```
Exception message: An exception occurred in the database while saving changes for context type 'Repository.ReportContext'.
Stack trace: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry '3794344738976' for key 'Orders.PRIMARY'
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry '3794344738976' for key 'Orders.PRIMARY'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 131
   at MySqlConnector.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 93
   at MySqlConnector.MySqlDataReader.NextResultAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 52
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Further technical details

MySQL version: 8.0.12
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: ASP.NET Core 5

Other details about my project setup:

The whole process is running in an Hangfire Background Job.

**Comment by andrekat** [comment]
After further research it looks like that the changes of the transaction are still being tracked in the main context? 

GetEntriesToSave(cascadeChanges: true) in StateManager.cs - ln: 1199 

Returns 100 changes which are tracked from the previously mentioned transaction. Do I miss something here? The only difference I've found from Microsoft Docs (https://docs.microsoft.com/en-us/ef/core/saving/transactions) is that they are initializing a fresh context - since I am injecting the context with DI I am not able to do this? 

Thanks in advance!

**Comment by lauxjpn** [comment]
@andrekat Take a look at the following code, that demonstrates how the `DbContext` and your databse state can get out of sync with each other:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDate { get; set; }
        public bool Checked { get; set; }
    }
    
    public class Context : DbContext
    {
        public virtual DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                const string connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1381";
                var serverVersion = ServerVersion.AutoDetect(connectionString);
                
                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion) 
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasData(
                        new IceCream {IceCreamId = 1, Name = "Vanilla", ExpirationDate = new DateTime(2020, 12, 31)},
                        new IceCream {IceCreamId = 2, Name = "Chocolate", ExpirationDate = new DateTime(2020, 12, 31)});
                });
        }
    }

    internal static class Program
    {
        private static async Task Main()
        {
            await using var context = new Context();

            await context.Database.EnsureDeletedAsync();
            await context.Database.EnsureCreatedAsync();

            var today = new DateTime(2021, 4, 12);

            await using (var transaction = await context.Database.BeginTransactionAsync())
            {
                try
                {
                    var expiredIceCreams = await context.IceCreams
                        .Where(i => EF.Functions.DateDiffDay(today, i.ExpirationDate) < 0)
                        .ToListAsync();
                    context.RemoveRange(expiredIceCreams);
                    await context.SaveChangesAsync();

                    var newIceCreams = expiredIceCreams.Select(
                        i => new IceCream
                        {
                            IceCreamId = i.IceCreamId,
                            Name = i.Name,
                            ExpirationDate = today.AddYears(1)
                        });
                    await context.AddRangeAsync(newIceCreams);

#pragma warning disable CS0162
                    // This exception is being thrown after we have removed the entities from the DbContext, and after
                    // we have added new entities to the DbContext.
                    throw new InvalidOperationException("Some exception is being thrown.");

                    await context.SaveChangesAsync();

                    await transaction.CommitAsync();
#pragma warning restore CS0162
                }
                catch
                {
                    // Rolling back the transaction will ensure a clean databse state, without any removed and then
                    // added entities. However, this does not change the tracked entities of the DbContext in any way.
                    // So the DbContext is still in the same state it was before the exception was thrown.
                    //
                    // The call is not really needed here, because the using block is rolling back the transaction for
                    // us implicitly:
                    //
                    // await transaction.RollbackAsync();
                }
            }

            // The DbContext is still tracking 2 entities (the 2 we previously added with the new expiration date of one
            // year in the future) with a state of `Added`.
            // However, while the previous (expired) entities had been removed from the DbContext, they were never
            // removed from the database.
            // Therefore, this will result in an error from MySQL, because EF Core will generate an INSERT command for
            // an already/still existing row (with the same ID) in the database. 
            var trackedIceCreams = context.IceCreams.Local;
            foreach (var iceCream in trackedIceCreams)
            {
                iceCream.Checked = true;
            }
            await context.SaveChangesAsync(); // <-- Throws
            
            // Verify operations.
            // This code does not get called anymore due to the previous exception.
            await using var checkContext = new Context();
            var allIceCreams = await checkContext.IceCreams
                .OrderBy(i => i.IceCreamId)
                .ToListAsync();
            
            Trace.Assert(allIceCreams.Count == 2);
            Trace.Assert(allIceCreams[0].ExpirationDate == today.AddYears(1));
            Trace.Assert(allIceCreams[0].Checked == true);
            Trace.Assert(allIceCreams[1].ExpirationDate == today.AddYears(1));
            Trace.Assert(allIceCreams[1].Checked == true);
        }
    }
}
```

</details>

So it is important so to understand, that while rolling back a transaction ensures a clean database state, it does not have any effect on the `DbContext` whatsoever, which will still be in the state it was before the rollback.

**Comment by andrekat** [comment]
Thank you for providing this example! So to ensure a clean database state you'd recommend to detach all recently added / removed entries from the database context?

**Comment by lauxjpn** [comment]
> Thank you for providing this example! So to ensure a clean database state you'd recommend to detach all recently added / removed entries from the database context?

(I'll assume you mean "clean _context_ state".)

In general, that really depends on the scenario. What you want to do is either undo the changes on the context, that are being rolled back by the transaction, or just dispose the context altogether and create a new one.

Concretely, detaching entities is one way to do it in this scenario here.
Another one would be to change the entities state to `Modified`. This works in my sample code, because the `IceCreamId` was reused.
