### ISSUE TITLE
Method 'Create' in type 'MySqlSqlTranslatingExpressionVisitorFactory' does not have an implementation

### ISSUE THREAD

**Issue by zqlovejyc** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1383]
```
Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=3.2.4.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)
   at Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_Dependencies()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Storage.IDatabaseFacadeDependenciesAccessor.get_Dependencies()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetFacadeDependencies(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.SetCommandTimeout(DatabaseFacade databaseFacade, Nullable`1 timeout)
   at EFCoreRepository.Repositories.MySqlRepository..ctor(DbContext context) in /_/EFCoreRepository/Repositories/MySqlRepository.cs:line 48
   at EFCoreRepository.Extensions.IServiceCollectionExtensions.<>c__DisplayClass0_0.<AddEFCoreRepository>b__0(String key) in /_/EFCoreRepository/Extensions/IServiceCollectionExtensions.cs:line 102
   at EFCoreConsole.Program.Main(String[] args) in D:\Github\EFCoreRepository\EFCoreConsole\Program.cs:line 108
```

**Comment by mguinness** [comment]
Closing as duplicate, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1138#issuecomment-670049509.  Please refer to the [Dependencies](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#dependencies) matrix.

**Comment by lauxjpn** [comment]
@zqlovejyc If you are using EF Core 5, use the latest _prerelease_ from out [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) feed.

**Comment by zqlovejyc** [comment]
> @zqlovejyc If you are using EF Core 5, use the latest _prerelease_ from out [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) feed.

thanks
