### ISSUE TITLE
Problems encountered in adding spatial type data with ABP framework

### ISSUE THREAD

**Issue by RalphLuo** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1412]
### Steps to reproduce
Problems encountered in adding spatial type data with ABP framework.
`public class Article : Entity<long>
{
public Geometry Address
{ get; set; }
}`

### The issue
Insertion with spatial type data failed.
Insert without spatial type data can be performed successfully.
Update or query can be performed successfully.

The exception message of insertion failure is as follows:
```
Exception message:
An unhandled exception has occurred while executing the request.

Stack trace:
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'coordinateValue' with type 'NetTopologySuite.Geometries.CoordinateZ'. Path 'coordinates[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Volo.Abp.Json.Newtonsoft.AbpNewtonsoftJsonSerializerProvider.Serialize(Object obj, Boolean camelCase, Boolean indented)
   at Volo.Abp.Json.AbpHybridJsonSerializer.Serialize(Object obj, Boolean camelCase, Boolean indented)
   at Volo.Abp.EntityFrameworkCore.EntityHistory.EntityHistoryHelper.GetPropertyChanges(EntityEntry entityEntry)
   at Volo.Abp.EntityFrameworkCore.EntityHistory.EntityHistoryHelper.CreateEntityChangeOrNull(EntityEntry entityEntry)
   at Volo.Abp.EntityFrameworkCore.EntityHistory.EntityHistoryHelper.CreateChangeList(ICollection`1 entityEntries)
   at Volo.Abp.EntityFrameworkCore.AbpDbContext`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.SaveChangesAsync(CancellationToken cancellationToken)
   at Volo.Abp.Uow.UnitOfWork.CompleteAsync(CancellationToken cancellationToken)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
```

### Further technical details

[Yczy.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/6390191/Yczy.zip)

MySQL version: 5.7.32
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version:5.0.0-beta.1
Microsoft.AspNetCore.App version:5.0.0.0

Other details about my project setup:
Attached is my code solution.

**Comment by lauxjpn** [comment]
> Self referencing loop detected for property 'coordinateValue' with type 'NetTopologySuite.Geometries.CoordinateZ'. Path 'coordinates[0]'.

That is not unexpected. The NTS classes are relatively complex and contain many references, of which a couple could be duplicates or circular references etc.

If you would be able to specify the serialization options to use, you could just configure it to allow handle circular references gracefully.

However, you cannot currently set the serialization options. This has been requested as a feature before, so we should implement this in the near future.

I'll post you some workarounds.

**Comment by lauxjpn** [comment]
You should reference `NetTopologySuite.IO.GeoJSON`, which provides general converters to serialize your geometry data to much cleaner JSON as without it, but more importantly, is also able to create the NTS geometry objects when deserializing, which would be tricky otherwise (because they don't contain a public  default constructor, so they don't deserialize out-of-the-box).

You setup a couple of `JsonSerializerSettings` options and add all the GeoJSON converters to it as well.
Since our EF Core JSON converter does not currently take a `JsonSerializerSettings` parameter, you just have to add your own (pretty simple though) and assign it to the JSON property of your entity via `HasConversion()` Fluent API.

Here is a fully working console sample project, that demonstrates this approach:

<details>
<summary>Project.csproj</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-beta.2" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft" Version="5.0.0-beta.2" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
        <PackageReference Include="NetTopologySuite" Version="2.2.0" />
        <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="2.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    </ItemGroup>

</Project>
```

</details>

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.Logging;
using NetTopologySuite.Geometries;
using NetTopologySuite.IO;
using Newtonsoft.Json;

namespace IssueConsoleTemplate
{
    //
    // EF Core entities:
    //
    
    public class IceCreamShop
    {
        public int IceCreamShopId { get; set; }
        public string Name { get; set; }
        public IceCreamShopDetails Details { get; set; }
    }

    //
    // JSON entities:
    //
    
    public class IceCreamShopDetails
    {
        public decimal Rating { get; set; }
        public Geometry Address { get; set; } // or Point etc.
    }
    
    //
    // Custom JSON ValueCoverter:
    //
    
    public class MySqlJsonNewtonsoftPocoValueConverterWithSettings<T> : ValueConverter<T, string>
    {
        public MySqlJsonNewtonsoftPocoValueConverterWithSettings(JsonSerializerSettings settings)
            : base(
                v => ConvertToProviderCore(v, settings),
                v => ConvertFromProviderCore(v, settings))
        {
        }

        private static string ConvertToProviderCore(T v, JsonSerializerSettings jsonSerializerSettings)
            => JsonConvert.SerializeObject(v, jsonSerializerSettings);
    
        private static T ConvertFromProviderCore(string v, JsonSerializerSettings jsonSerializerSettings)
            => JsonConvert.DeserializeObject<T>(v, jsonSerializerSettings);
    }

    //
    // DbContext:
    //
    
    public class Context : DbContext
    {
        public DbSet<IceCreamShop> IceCreamShops { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySql(
                        "server=127.0.0.1;port=3308;user=root;password=;database=Issue1412_01",
                        new MySqlServerVersion(new Version(5, 7, 32)),
                        options => options.UseNewtonsoftJson())
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var jsonSerializerSettings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                NullValueHandling = NullValueHandling.Ignore,
            };

            foreach (var converter in GeoJsonSerializer.Create(new GeometryFactory(new PrecisionModel(), 4326)).Converters)
            {
                jsonSerializerSettings.Converters.Add(converter);
            }

            modelBuilder.Entity<IceCreamShop>(
                entity =>
                {
                    entity.Property(e => e.Details)
                        .HasColumnType("json")
                        .HasConversion(
                            new MySqlJsonNewtonsoftPocoValueConverterWithSettings<IceCreamShopDetails>(
                                jsonSerializerSettings));
                });
        }
    }

    internal static class Program
    {
        private static void Main(string[] args)
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Add(
                    new IceCreamShop
                    {
                        Name = "Cold & Sweet",
                        Details = new IceCreamShopDetails
                        {
                            Rating = 4.5m,
                            Address = new Point(52.5162746, 13.3777041),
                        },
                    });

                context.SaveChanges();
            }

            using (var context = new Context())
            {
                var iceCreamShops = context.IceCreamShops.ToList();

                Trace.Assert(iceCreamShops.Count == 1);
                Trace.Assert(iceCreamShops[0].Details.Rating == 4.5m);
                Trace.Assert(iceCreamShops[0].Details.Address.Coordinate.X == 52.5162746);
                Trace.Assert(iceCreamShops[0].Details.Address.Coordinate.Y == 13.3777041);
            }
        }
    }
}
```

</details>

**Comment by RalphLuo** [comment]
Thank you for your professional and accurate answers, I will give you a five-star praise, and sincerely wish you a happy life!
