### ISSUE TITLE
When Skip(0) and no records, Take method generate invalid SQL syntax

### ISSUE THREAD

**Issue by chris-ryu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1423]
### Steps to reproduce
When Skip(0) with no records return Taks method generate invalid SQL syntax.
But if it returns any record the error is gone.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-20
) AS `t`
INNER JOIN `Subject` AS `s` ON `t`.`SubjectId` = `s`.`Id`
INNER JOI' at line 7
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-20
) AS `t`
INNER JOIN `Subject` AS `s` ON `t`.`SubjectId` = `s`.`Id`
INNER JOI' at line 7
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 810
Stack trace:
```

### Further technical details

MySQL version: 8.0.23
Operating system: 
Pomelo.EntityFrameworkCore.MySql version: 3.2.5
Microsoft.AspNetCore.App version: 3.1.14

Other details about my project setup:

**Comment by mguinness** [comment]
Can you provide the full SQL that is being run against MySQL, in particular the `LIMIT` and  `OFFSET` keywords?  Are you using an `OrderBy` in your LINQ?

**Comment by chris-ryu** [comment]
> Can you provide the full SQL that is being run against MySQL, in particular the `LIMIT` and `OFFSET` keywords? Are you using an `OrderBy` in your LINQ?

yes I'm using OrderByDescending

var result = await db.Lesson
                .Include(_ => _.RecordBooks)
                .Include(_ => _.Trainer)
                .Include(_ => _.Subject)
                .ThenInclude(_ => _.Semester)
                .ThenInclude(_ => _.Category)
                .Where(_ => _.TraineeId == myId)
                .OrderByDescending(_ => _.Start)
                .Skip (pageIndex * limit).Take (limit)
                .Select (_ => new {
                    ...
                })
                .ToListAsync();

**Comment by mguinness** [comment]
What is the SQL being generated?  There appears to be a -20 in the SQL, is it possible that either `pageIndex` or `limit` is negative?

**Comment by chris-ryu** [comment]
> What is the SQL being generated? There appears to be a -20 in the SQL, is it possible that either `pageIndex` or `limit` is negative?

No, pageIndex is exactly 0

Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (9ms) [Parameters=[@__myId_0='521' (Nullable = true)], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*)
FROM `Lesson` AS `l`
WHERE `l`.`TraineeId` = @__myId_0
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (31ms) [Parameters=[@__brandType_0='0'], CommandType='Text', CommandTimeout='30']
SELECT `c`.`Id`, `c`.`Index`, `c`.`Title`
FROM `Category` AS `c`
WHERE `c`.`BrandType` = @__brandType_0
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (47ms) [Parameters=[@__myId_0='521' (Nullable = true), @__p_2='20', @__p_1='0'], CommandType='Text', CommandTimeout='30']
SELECT `t`.`Id`, `t`.`Start`, `t`.`End`, `c`.`Chapter`, `c`.`Index`, `s0`.`SemesterType`, `s`.`CharIndex`, `s`.`Title`, `t`.`Created`, `a`.`DisplayName`
FROM (
    SELECT `l`.`Id`, `l`.`Created`, `l`.`End`, `l`.`Start`, `l`.`SubjectId`, `l`.`TraineeId`, `l`.`TrainerId`
    FROM `Lesson` AS `l`
    WHERE `l`.`TraineeId` = @__myId_0
    ORDER BY `l`.`Start` DESC
    LIMIT @__p_2 OFFSET @__p_1
) AS `t`
INNER JOIN `Subject` AS `s` ON `t`.`SubjectId` = `s`.`Id`
INNER JOIN `Semester` AS `s0` ON `s`.`SemesterId` = `s0`.`Id`
INNER JOIN `Category` AS `c` ON `s0`.`CategoryId` = `c`.`Id`
INNER JOIN `AspNetUsers` AS `a` ON `t`.`TrainerId` = `a`.`Id`
ORDER BY `t`.`Start` DESC
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (71ms) [Parameters=[@__branchId_0='94' (Nullable = true)], CommandType='Text', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`DisplayName` AS `Name`
FROM `AspNetUsers` AS `a`
WHERE (`a`.`UserType` = 16) AND (`a`.`BranchId` = @__branchId_0)
ORDER BY `a`.`DisplayName`
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (33,432ms) [Parameters=[@__myId_0='521'], CommandType='Text', CommandTimeout='30']
SELECT `t`.`Id`, `t`.`AccessFailedCount`, `t`.`AssessorTrainingEnd`, `t`.`AssessorTrainingStart`, `t`.`Birthday`, `t`.`BranchId`, `t`.`BrandId`, `t`.`CertificateIssue`, `t`.`Code`, `t`.`ConcurrencyStamp`, `t`.`DealerId`, `t`.`DisplayName`, `t`.`Email`, `t`.`EmailConfirmed`, `t`.`EnterYear`, `t`.`FamilyName_ENG`, `t`.`Gender`, `t`.`GivenName_ENG`, `t`.`HighSchool`, `t`.`HomeTown`, `t`.`HomeTown_ENG`, `t`.`LockoutEnabled`, `t`.`LockoutEnd`, `t`.`NormalizedEmail`, `t`.`NormalizedUserName`, `t`.`PasswordHash`, `t`.`PhoneNumber`, `t`.`PhoneNumberConfirmed`, `t`.`PracticalTest`, `t`.`Professionality`, `t`.`RetrainingEnd`, `t`.`RetrainingStart`, `t`.`SecurityStamp`, `t`.`TTT1End`, `t`.`TTT1Start`, `t`.`TTT2End`, `t`.`TTT2Start`, `t`.`Title`, `t`.`TraineeStatus`, `t`.`Trainee_1Test`, `t`.`Trainee_2Test`, `t`.`TrainerStatus`, `t`.`TwoFactorEnabled`, `t`.`University`, `t`.`UserName`, `t`.`UserType`, `t`.`WrittenTest`, `t0`.`UserId`, `t0`.`RoleId`, `t0`.`Id`, `t0`.`ConcurrencyStamp`, `t0`.`Name`, `t0`.`NormalizedName`, `t0`.`RoleType`
FROM (
    SELECT `a`.`Id`, `a`.`AccessFailedCount`, `a`.`AssessorTrainingEnd`, `a`.`AssessorTrainingStart`, `a`.`Birthday`, `a`.`BranchId`, `a`.`BrandId`, `a`.`CertificateIssue`, `a`.`Code`, `a`.`ConcurrencyStamp`, `a`.`DealerId`, `a`.`DisplayName`, `a`.`Email`, `a`.`EmailConfirmed`, `a`.`EnterYear`, `a`.`FamilyName_ENG`, `a`.`Gender`, `a`.`GivenName_ENG`, `a`.`HighSchool`, `a`.`HomeTown`, `a`.`HomeTown_ENG`, `a`.`LockoutEnabled`, `a`.`LockoutEnd`, `a`.`NormalizedEmail`, `a`.`NormalizedUserName`, `a`.`PasswordHash`, `a`.`PhoneNumber`, `a`.`PhoneNumberConfirmed`, `a`.`PracticalTest`, `a`.`Professionality`, `a`.`RetrainingEnd`, `a`.`RetrainingStart`, `a`.`SecurityStamp`, `a`.`TTT1End`, `a`.`TTT1Start`, `a`.`TTT2End`, `a`.`TTT2Start`, `a`.`Title`, `a`.`TraineeStatus`, `a`.`Trainee_1Test`, `a`.`Trainee_2Test`, `a`.`TrainerStatus`, `a`.`TwoFactorEnabled`, `a`.`University`, `a`.`UserName`, `a`.`UserType`, `a`.`WrittenTest`
    FROM `AspNetUsers` AS `a`
    WHERE `a`.`Id` = @__myId_0
    LIMIT 2
) AS `t`
LEFT JOIN (
    SELECT `a0`.`UserId`, `a0`.`RoleId`, `a1`.`Id`, `a1`.`ConcurrencyStamp`, `a1`.`Name`, `a1`.`NormalizedName`, `a1`.`RoleType`
    FROM `AspNetUserRoles` AS `a0`
    INNER JOIN `AspNetRoles` AS `a1` ON `a0`.`RoleId` = `a1`.`Id`
) AS `t0` ON `t`.`Id` = `t0`.`UserId`
ORDER BY `t`.`Id`, `t0`.`UserId`, `t0`.`RoleId`, `t0`.`Id`

Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'webapi.Models.AusbildungDbContext'.
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.AppleCrypto.SslRead(SafeSslHandle sslHandle, Byte* writeFrom, Int32 count, Int32& bytesWritten)
   at System.Net.Security.SslStreamPal.DecryptMessage(SafeDeleteContext securityContext, Byte[] buffer, Int32& offset, Int32& count)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer_) in /_/src/MySqlConnector/Protocol/Serialization/StreamByteHandler.cs:line 72
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer_) in /_/src/MySqlConnector/Protocol/Serialization/StreamByteHandler.cs:line 82
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 36
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes_, BufferedByteReader bufferedByteReader_, IByteHandler byteHandler_, Func`1 getNextSequenceNumber_, ProtocolErrorBehavior protocolErrorBehavior_, IOBehavior ioBehavior_) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 413
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask_, BufferedByteReader bufferedByteReader_, IByteHandler byteHandler_, Func`1 getNextSequenceNumber_, ArraySegmentHolder`1 previousPayloads_, ProtocolErrorBehavior protocolErrorBehavior_, IOBehavior ioBehavior_) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 480
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 798
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 257
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.AppleCrypto.SslRead(SafeSslHandle sslHandle, Byte* writeFrom, Int32 count, Int32& bytesWritten)
   at System.Net.Security.SslStreamPal.DecryptMessage(SafeDeleteContext securityContext, Byte[] buffer, Int32& offset, Int32& count)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer_) in /_/src/MySqlConnector/Protocol/Serialization/StreamByteHandler.cs:line 72
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer_) in /_/src/MySqlConnector/Protocol/Serialization/StreamByteHandler.cs:line 82
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 36
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes_, BufferedByteReader bufferedByteReader_, IByteHandler byteHandler_, Func`1 getNextSequenceNumber_, ProtocolErrorBehavior protocolErrorBehavior_, IOBehavior ioBehavior_) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 413
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask_, BufferedByteReader bufferedByteReader_, IByteHandler byteHandler_, Func`1 getNextSequenceNumber_, ArraySegmentHolder`1 previousPayloads_, ProtocolErrorBehavior protocolErrorBehavior_, IOBehavior ioBehavior_) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 480
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 798
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 257
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

**Comment by mguinness** [comment]
I had to tidy up your post to make some sense of it.  However the SQL looks good to me, but the `MySqlException` is different to what was in your original post?

**Comment by lauxjpn** [comment]
@chris-ryu Do you still need help with this issue? If so, please provide the requested information (you posted SQL for a different exception in your previous comment).

Otherwise, we are going to close this issue.
