### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by eduardoxvii** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1436]
### Steps to reproduce
With only about ten users accessing the system and this failure intermittently begins to appear.

### The issue
This error was not showing up in the development environment. It only appeared when deploy to production and the load of use by users. It is an intermittent error.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Cannot access a disposed object
and
Failed executing DbCommand

Stack trace:
```
```
[41m[30mfail[39m[22m[49m: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (0ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SELECT `a`.`Id`, `a`.`AccessFailedCount`, `a`.`ConcurrencyStamp`, `a`.`Email`, `a`.`EmailConfirmed`, `a`.`LockoutEnabled`, `a`.`LockoutEnd`, `a`.`NormalizedEmail`, `a`.`NormalizedUserName`, `a`.`PasswordHash`, `a`.`PhoneNumber`, `a`.`PhoneNumberConfirmed`, `a`.`SecurityStamp`, `a`.`TwoFactorEnabled`, `a`.`UltimaAtualizacao`, `a`.`UserName`
      FROM `AspNetUsers` AS `a`
      WHERE `a`.`NormalizedUserName` = @__normalizedUserName_0
      LIMIT 1
[41m[30mfail[39m[22m[49m: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'ContextoDB.ApplicationDbContext'.
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'MySqlConnection'.
         at MySqlConnector.MySqlConnection.VerifyNotDisposed() in /_/src/MySqlConnector/MySqlConnection.cs:line 928
         at MySqlConnector.MySqlConnection.get_Session() in /_/src/MySqlConnector/MySqlConnection.cs:line 690
         at MySqlConnector.Core.ICancellableCommandExtensions.ResetCommandTimeout(ICancellableCommand command) in /_/src/MySqlConnector/Core/ICancellableCommand.cs:line 82
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
         at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'MySqlConnection'.
         at MySqlConnector.MySqlConnection.VerifyNotDisposed() in /_/src/MySqlConnector/MySqlConnection.cs:line 928
         at MySqlConnector.MySqlConnection.get_Session() in /_/src/MySqlConnector/MySqlConnection.cs:line 690
         at MySqlConnector.Core.ICancellableCommandExtensions.ResetCommandTimeout(ICancellableCommand command) in /_/src/MySqlConnector/Core/ICancellableCommand.cs:line 82
         at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 315
         at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```
### Further technical details

MySQL version: 8.0.17
Operating system: Centos 7
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
Microsoft.AspNetCore.App version: net5.0
Size Table AspNetUsers: 24.000 users

Other details about my project setup:
I was using version 5.0.0-beta.2 and many strange errors appeared after deploying. But after the update to version 5.0.0 all disappeared, leaving this one.

**Comment by lauxjpn** [comment]
As the message says, somewhere in your code, you are accessing an already disposed connection object. This i very unlikely to be a Pomelo/MySqlConnector issue.

Assuming you are not creating the connection object used by Pomelo/EF Core yourself, but are just handing over a connection string to the `UseMySql()` method (as most people do) and register your `DbContext` with `AddDbContext()` or `AddDbContextPool()`, then a connection object will be created and managed by the `DbContext` internally, and the lifetime of the connection object will be tied to the lifetime of the `DbContext` object (I simplify a bit). Since the latter one is registered as _scoped_ by default, it means that it will be disposed automatically by DI, when the web request has been handled.

There are two common scenarios (and a couple of more uncommon ones), that lead to a non-deterministic `ObjectDisposedException`:
* You missed an `await` call for some `async` method by accident, that you use in your code. When this async method now takes longer to complete as the web request it was started on, and it accesses the `DbContext` after the web request has already completed, you will get the exception.
* You deliberately moved some (e.g. more computation-heavy) work to either a code path, that is purely run `async` (but without `await`), or that is executed on another thread. In the first case, the previous scenario applies again. The second case is similar: Once the web request goes out-of-scope, the thread might still run and then access your already disposed `DbContext` or connection object.

If you explicitly use the connection object of the `DbContext`, e.g. by calling `context.Database.GetDbConnection()`, then there exist other common pitfalls.

If you need some tips on how to trace down the code in your code base, that is responsible for this issue, we can provide you some.

**Comment by lauxjpn** [comment]
> Because it's a relatively small piece of code. I easily walked the path and the "awaits" and "async" are all in place...

It can be in any method in the stack frame before/outside the `FindByLogin()` call, or inside the `UserManager.FindByNameAsync()` call. It does not have to be in the `FindByLogin()` method itself.

> Are you referring here to enabling ".EnableSensitiveDataLogging ()"?

No, I really just mean that the stack trace contains all methods called, so somewhere along this path is likely an `async` call without an `await`.

**Comment by eduardoxvii** [comment]
First of all, I'd like to thank **God** for bringing me here, @lauxjpn  for your commitment and qualification and the code **CS4014** that made what would be an exhaustive search a simple button click. 

Yes, the error was the lack of await!

During development the problem did not appear, it was necessary access by many users for the problem to appear. 
The error messages also failed to pinpoint the location of the problem.

Thanks!

**Comment by lauxjpn** [comment]
I'm glad you found it!

(In my experience, it is always good practice to add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` to project files, so that your code does not compile as long as a warning is still present. You can still manually override a warning (e.g. with `#pragma warning`) when applicable, but it would be a conscious act then at least.)
