### ISSUE TITLE
Are there any compatibility issues with MySQL version 5.6.50?

### ISSUE THREAD

**Issue by httpmurilo** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1441]
### Steps to reproduce
MySQL Database Version `5.6.50` required

Set on `startup.cs`
```
var connectionString = "my infos of connection strings";
var serverVersion = ServerVersion.AutoDetect(connectionString);
            services.AddDbContext<ApplicationContext>(
                dbContextOptions  => dbContextOptions.UseMySql(connectionString,serverVersion)
                    .EnableSensitiveDataLogging() 
                    .EnableDetailedErrors()      

```

Execute on project : 
```
dotnet run
```

### The issue
I can test a base where I'm testing the Pomelo.EntityFrameworkCore.MySql implementation. I'm using a database from a hosting I already have.

However I come across the following message : 
```
C:\Users\murilo.melo\Scrapping.Api>dotnet run
Compilando...
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 417
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 376
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 107
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 137
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 863
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 414
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 380
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Scrapping.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Users\murilo.melo\OneDrive - Softplan\Área de Trabalho\estudo_java_web\Scrapping.Api\Scrapping.Api\Startup.cs:line 48
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Scrapping.Api.Program.Main(String[] args) in C:\Users\murilo.melo\OneDrive - Softplan\Área de Trabalho\estudo_java_web\Scrapping.Api\Scrapping.Api\Program.cs:line 16
```
My question is, is there support for MySQL version 5.6.50?

### Further technical details

MySQL version: 5.6.50
Operating system:  Windows 10 Pro.
Pomelo.EntityFrameworkCore.MySql version: 6.0.0-preview.4 
Microsoft.AspNetCore.App version: 5.0.104
Project : WebApi and Classlib.

Other details about my project setup:
The data access layer is in the class library. And the API performs retrieves the information in that layer.

When I get the same information and try to access using dbeaver, I succeed.

Sorry about my English, I'm still studying.

**Comment by lauxjpn** [comment]
> My question is, is there support for MySQL version 5.6.50?

@httpmurilo Yes, it is supported for most functionality. A couple of features will only run in newer versions, but all basic stuff will work with MySQL 5.6.

If you are having connection problems, it is likely to be a server, configuration or firewall issue.

> I'm using a database from a hosting I already have.

Where is your database hosted? AWS?
From where are you trying to connect to your database? From your developer machine?

> When I get the same information and try to access using dbeaver, I succeed.

From which machine are you able to connect to your database sucessfully?

**Comment by httpmurilo** [comment]
@lauxjpn,Thanks for your attention, my friend. Please close this item, I was mistaken. The problem is that the database hosting for some reason to work, I needed to create and recreate the databases several times to work, I was able to use the tool.
