### ISSUE TITLE
DateTime values not handled correctly in select

### ISSUE THREAD

**Issue by theFra985** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1443]
### Steps to reproduce
Execute a query with a select like this (I'm copying a similar query to the one generating the issue but I think it requires only the TargetDate to reproduce)
```cs
.Select(entry => new {
    entry.Value1,
    Ref1Id = entry.Ref1.Value2,
    Ref2Id = entry.Ref2.Value3,
    TargetDate = entry.Ref1.Unit == TimeUnit.Day
        ? entry.EntryDate.AddDays(entry.Ref1.Amount.Value)
        : entry.Ref1.Unit == TimeUnit.Month
            ? entry.EntryDate.AddMonths((int) entry.Ref1.Amount.Value)
            : entry.Ref1.Unit == TimeUnit.Year
                ? entry.EntryDate.AddYears((int) entry.Ref1.Amount.Value)
                : DateTime.MinValue
})
```

### The issue
EF fails to handle `DateTime.MinValue` correctly reading it as a string. Without debugging external sources you receive only a `NullReferenceException` on the `Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.Dispose()` call (querySplitting is enabled) but debugging I got an `InvalidOperationException` that then generates the `NullReferenceException`.
It seems very strange to me that EF doesn't handle this type of exception correctly but that's not the issue.

The issue seems to reproduce with DateTime's static properties like `MinValue`, `MaxValue` or the constructor but not with externally captured values or `DateTime.Now`.

This is the complete exception
```
System.InvalidOperationException: An error occurred while reading a database value. The expected type was 'System.Nullable`1[System.DateTime]' but the actual value was of type 'System.String'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
   at MySqlConnector.Core.Row.GetDateTime(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 358
   at MySqlConnector.MySqlDataReader.GetDateTime(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 261
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadDateTime(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadDateTime(DbDataReader reader, Int32 ordinal, ReaderColumn column)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(IReadOnlyList`1 columns)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at AspNetCore.Views_ControllerName_ViewName.ExecuteAsync() in Full\Path\To\ViewName.cshtml:line 25
```

### Further technical details

MySQL version: `8.0.25`
Operating system: `Windows 10`
Pomelo.EntityFrameworkCore.MySql version: `5.0.0`
Microsoft.AspNetCore.App version: That package is not directly referenced but the AspNetCore stack version is `5.0.6`

Other details about my project setup:
```
.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)
.LimitKeyedOrIndexedStringColumnLength()
.EnableIndexOptimizedBooleanColumns()
```

**Comment by lauxjpn** [comment]
This is likely to be a duplicate of #1419 (also containing the workaround by @laurent-jeancler-realist).
You can try the `6.0.0-preview.4` release, which contains the fix.

**Comment by theFra985** [comment]
I can confirm the new version solves the issue.
Sorry for not noticing the other one before posting.
Thanks for the support!
