### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by LCastilloSymbiotic** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1459]
Hello, I had this table:

```SQL
CREATE TABLE currencies(
    id INT PRIMARY KEY AUTO_INCREMENT,
    terminal_id INT REFERENCES terminals(terminal_id),
    name VARCHAR(32) DEFAULT '',
);
```

and then update it to this:

```SQL
CREATE TABLE currencies(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) DEFAULT '',
);
```

in the same way update the class to which it is mapped from:
```C#
[Table("currencies")]
public class Currency {
    [Key]
    [Column("id")]
    public int Id { get; set; }
    [Column("terminal_id")]
    public int TerminalId { get; set; }
    [Column("name")]
    public string Name { get; set; }
}
```

to this class:

```C#
[Table("currencies")]
public class Currency {
    [Key]
    [Column("id")]
    public int Id { get; set; }
    [Column("name")]
    public string Name { get; set; }
}
```

and it generates the following error:

```
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'c.TerminalId' in 'field list'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'c.TerminalId' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 217
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Further technical details

MySQL version:  5.7
Operating system:  Google cloud?
Pomelo.EntityFrameworkCore.MySql version: 3.1.0
Microsoft.AspNetCore.App version: 3.0

**Comment by lauxjpn** [comment]
@LCastilloSymbiotic Please post the C# LINQ query you are executing, the SQL generated for the query (logged by EF Core) and the code that calls `UseMySql()` (replace sensitive information before posting).

Also, have you used tried the latest EF Core 3.1 compatible Pomelo version (3.2.5)?

**Comment by LCastilloSymbiotic** [comment]
Hello, I do not have sql code generated, since the Database was created by DDL, the code that I abjoined above is the one that creates the table. Regarding the versions, I did try to use the last one without having satisfactory results. Below is the context creation code:


```

 public class PaymentContext : DbContext
    {
        public PaymentContext(DbContextOptions<PaymentContext> options)
            : base(options) {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

        public DbSet<Currency> Currencies { get; set; }
     }
}
```

**Comment by lauxjpn** [comment]
While it is always a good idea to post the `DbContext` code as well, we need the code containing the `UseMySql()` call:

> [...] and the code that calls `UseMySql()` (replace sensitive information before posting).

---

We also need the code that results in the exception being thrown (your LINQ query):

> Please post the C# LINQ query you are executing [...]

According to your stack trace, it ends with `.ToList()`.

---

Finally, we need the SQL that EF Core generates when it translates your LINQ query (the SQL it sends to the database). This SQL does not contain any DDL statements. It contains the SELECT query that is the reason MySQL returns the error, which results in the exception.

To log the SQL statements, take a look at [Simple Logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging).

**Comment by lauxjpn** [comment]
@LCastilloSymbiotic If you still need help with this issue, please provide the required data. Otherwise, please close this issue. Thanks!
