### ISSUE TITLE
Can't run dotnet ef migrations add without connectionsettings

### ISSUE THREAD

**Issue by jespersh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1464]
### Steps to reproduce
Running the command without a server:
`dotnet ef migrations add InitialCreate`

### The issue
I'm trying to create migrations without connecting to a database like it is possible for Sqlite/sqlserver/others (https://github.com/dotnet/efcore/issues/8427) and it could look like this worked at one point with #272, but broken today.

This should be enough info for `migrations add`:
```C#
public class BloggingContextFactory : IDesignTimeDbContextFactory<BloggingContext>
{
    public BloggingContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<BloggingContext>();
        optionsBuilder.UseMySql(new MySqlServerVersion(new System.Version(8, 0, 21)));

        return new BloggingContext(optionsBuilder.Options);
    }
}
```

```
Exception message: System.InvalidOperationException: A relational store has been configured without specifying either the DbConnection or connection string to use.
Stack trace:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: A relational store has been configured without specifying either the DbConnection or connection string to use.
   at Pomelo.EntityFrameworkCore.MySql.Internal.MySqlOptions.GetConnectionSettings(MySqlOptionsExtension relationalOptions)
   at Pomelo.EntityFrameworkCore.MySql.Internal.MySqlOptions.Initialize(IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.SingletonOptionsInitializer.EnsureInitialized(IServiceProvider serviceProvider, IDbContextOptions options)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>g__BuildServiceProvider|3()
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at EFGetStarted.BloggingContext..ctor(DbContextOptions`1 options) in /Users/jesper/Projects/test-migrations/BloggingContext.cs:line 9
   at EFGetStarted.BloggingContextFactory.CreateDbContext(String[] args) in /Users/jesper/Projects/test-migrations/BloggingContextFactory.cs:line 13
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

Repo: https://github.com/jespersh/test-migrations
MySQL version: serverless/8.0.21
Operating system: Mac/Windows
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
Microsoft.AspNetCore.App version: 5.0.7

Other details about my project setup: This is a minimal example mixed together with https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/ and https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation adjusted for this library.

**Comment by lauxjpn** [comment]
@jespersh Thanks for reporting this issue!

We fixed it for `5.0.2` and `6.0.0-preview.6`.
Use the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) until then.
