### ISSUE TITLE
 The underlying reader doesn't have as many fields as expected

### ISSUE THREAD

**Issue by ClementeGao** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1468]
Pomelo.EntityFrameworkCore.MySql version:3.1.6
dotnet version : 5.0

error info 

```
The underlying reader doesn't have as many fields as expected
```

please help me thanks 

### the exception info :
```
System.InvalidOperationException: The underlying reader doesn't have as many fields as expected.
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeFields()
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at purchasereceiving.api
```

### the linq query:
```c#
FormattableString sql = @$"select
          t1.RecordID,  
          CONVERT(t1.numericalorder USING utf8mb4) AS NumericalOrder,  
          CONVERT(t1.ProductID USING utf8mb4) AS ProductID,
          t1.Detectionproject,
CAST( t1.Detectionstandard AS CHAR(50))  AS Detectionstandard,
           CONVERT(t1.maxnum USING utf8mb4) AS Maxnum,
          CONVERT(t1.minmax USING utf8mb4) AS Minmax,
            CONVERT(t1.contractmaxnum USING utf8mb4) AS Contractmaxnum,
           CONVERT(t1.contractminnum USING utf8mb4) AS Contractminnum,
        t1.Contractclause,
          t1.Remark,
          t2.ProductName
          from dbn_pmcontracttwodetail t1 left join biz_productdetail t2 on t1.productid =t2.ProductID WHERE t1.numericalorder={key}";


                return await _context.contracttwodetail.FromSqlInterpolated(sql)
                    .ToListAsync();
```

### the model:
```c#
public class PurchaseContractTwoDetailEntity
    {
        [Key]
        public int RecordID { get; set; }
        public string ProductID { get; set; }
        public string Detectionproject { get; set; }
        public string Detectionstandard { get; set; }
        public string Maxnum { get; set; }
        public string Minmax { get; set; }
        public string Contractmaxnum { get; set; }
        public string Contractminnum { get; set; }
        public string Numericalorder { get; set; }
        public string ProductName { get; set; }
        public string Remark { get; set; }
        public string Contractclause { get; set; }

        [ForeignKey("NumericalOrder")]
        public PurchaseContractEntity Contract { set; get; }

    }
```

### the usemysql is:

```c#
services.AddDbContextPool<TDbContext>(builder =>
            {
                //链接数据库
                builder.UseMySql(connectionString,  b =>
                {
                    b.CommandTimeout(60);
                    b.EnableRetryOnFailure(5, TimeSpan.FromSeconds(10), null);
                });
                //日志
                if (enableDbLog)
                {
                    builder.UseLoggerFactory(LoggerFactory.Create(configure =>
                    {
                        configure
                        .AddFilter((category, level) => category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information)
                        .AddConsole();
                    }));
                    builder.EnableSensitiveDataLogging();
                }
            });
            return services;
```

**Comment by lauxjpn** [comment]
We need a lot more information than that to help you.

Start by providing us with the following:
* Post the _full_ exception (including the stack trace)
* Post the LINQ query you are trying to execute
* Post the SQL (logged by EF Core) that gets generated for your LINQ query
* Post the model (classes and Fluent API) that gets used in your LINQ query
* Post your `UseMySql()` call (remove sensitive information first)

If you don't post this information, we will not be able to help you.

**Comment by ClementeGao** [comment]
@lauxjpn I have provided you with the information

**Comment by lauxjpn** [comment]
I see, you are using hand crafted SQL statements that you execute, instead of their LINQ equivalent.

I don't have any issues when executing the following test project:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Pomelo.EntityFrameworkCore.MySql.Storage;

namespace IssueConsoleTemplate
{
    [Table("dbn_pmcontracttwodetail")]
    public class PurchaseContractTwoDetailEntity
    {
        [Key]
        public int RecordID { get; set; }

        public string ProductID { get; set; }
        public string Detectionproject { get; set; }
        public string Detectionstandard { get; set; }
        public string Maxnum { get; set; }
        public string Minmax { get; set; }
        public string Contractmaxnum { get; set; }
        public string Contractminnum { get; set; }
        public string Numericalorder { get; set; }
        public string ProductName { get; set; }
        public string Remark { get; set; }
        public string Contractclause { get; set; }

        [ForeignKey("Numericalorder")] // Changed from NumericalOrder to match property Name casing
        public PurchaseContractEntity Contract { set; get; }
    }

    public class PurchaseContractEntity
    {
        [Key]
        public string PurchaseContractEntityID { get; set; }
    }

    [Table("biz_productdetail")]
    public class ProductDetail
    {
        [Key]
        public string ProductID { get; set; }
        public string ProductName { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<PurchaseContractTwoDetailEntity> PurchaseContractTwoDetailEntities { get; set; }
        public DbSet<PurchaseContractEntity> PurchaseContractEntities { get; set; }
        public DbSet<ProductDetail> ProductDetails { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1468";
                var serverVersion = ServerVersion.AutoDetect(connectionString);

                optionsBuilder.UseMySql(
                        connectionString, optionsBuilder => optionsBuilder
                            .ServerVersion(serverVersion)
                            .CharSetBehavior(CharSetBehavior.NeverAppend))
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            b => b
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PurchaseContractTwoDetailEntity>()
                .HasData(
                    new PurchaseContractTwoDetailEntity
                    {
                        RecordID = 1,
                        ProductID = "2",
                        Numericalorder = "3"
                    });

            modelBuilder.Entity<PurchaseContractEntity>()
                .HasData(
                    new PurchaseContractEntity
                    {
                        PurchaseContractEntityID = "3"
                    });
            
            modelBuilder.Entity<ProductDetail>()
                .HasData(
                    new ProductDetail
                    {
                        ProductID = "2",
                    });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var key = "3";
            FormattableString sql = @$"select
    t1.RecordID,
    CONVERT(t1.numericalorder USING utf8mb4) AS NumericalOrder,
    CONVERT(t1.ProductID USING utf8mb4) AS ProductID,
    t1.Detectionproject,
    CAST( t1.Detectionstandard AS CHAR(50)) AS Detectionstandard,
    CONVERT(t1.maxnum USING utf8mb4) AS Maxnum,
    CONVERT(t1.minmax USING utf8mb4) AS Minmax,
    CONVERT(t1.contractmaxnum USING utf8mb4) AS Contractmaxnum,
    CONVERT(t1.contractminnum USING utf8mb4) AS Contractminnum,
    t1.Contractclause,
    t1.Remark,
    t2.ProductName
from dbn_pmcontracttwodetail t1
left join biz_productdetail t2 on t1.productid = t2.ProductID
WHERE t1.numericalorder={key}";

            var result = context.PurchaseContractTwoDetailEntities.FromSqlInterpolated(sql)
                .ToList();
            
            Trace.Assert(result.Count == 1);
            Trace.Assert(result[0].RecordID == 1);
            Trace.Assert(result[0].Contract == null);
        }
    }
}
```
</details>

It generates the following SQL:

<details>
<summary>Generated SQL</summary>

```sql
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.15 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.25 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (63ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP DATABASE `Issue1468`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1468`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `biz_productdetail` (
          `ProductID` varchar(255) NOT NULL,
          `ProductName` longtext NULL,
          CONSTRAINT `PK_biz_productdetail` PRIMARY KEY (`ProductID`)
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (23ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `PurchaseContractEntities` (
          `PurchaseContractEntityID` varchar(255) NOT NULL,
          CONSTRAINT `PK_PurchaseContractEntities` PRIMARY KEY (`PurchaseContractEntityID`)
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (33ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `dbn_pmcontracttwodetail` (
          `RecordID` int NOT NULL AUTO_INCREMENT,
          `ProductID` longtext NULL,
          `Detectionproject` longtext NULL,
          `Detectionstandard` longtext NULL,
          `Maxnum` longtext NULL,
          `Minmax` longtext NULL,
          `Contractmaxnum` longtext NULL,
          `Contractminnum` longtext NULL,
          `Numericalorder` varchar(255) NULL,
          `ProductName` longtext NULL,
          `Remark` longtext NULL,
          `Contractclause` longtext NULL,
          CONSTRAINT `PK_dbn_pmcontracttwodetail` PRIMARY KEY (`RecordID`),
          CONSTRAINT `FK_dbn_pmcontracttwodetail_PurchaseContractEntities_Numericalor~` FOREIGN KEY (`Numericalorder`) REFERENCES `PurchaseContractEntities` (`PurchaseContractEntityID`) ON DELETE RESTRICT
      );

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `PurchaseContractEntities` (`PurchaseContractEntityID`)
      VALUES ('3');

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `biz_productdetail` (`ProductID`, `ProductName`)
      VALUES ('2', NULL);

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `dbn_pmcontracttwodetail` (`RecordID`, `Contractclause`, `Contractmaxnum`, `Contractminnum`, `Detectionproject`, `Detectionstandard`, `Maxnum`, `Minmax`, `Numericalorder`, `ProductID`, `ProductName`, `Remark`)
      VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', '2', NULL, NULL);

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (27ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE INDEX `IX_dbn_pmcontracttwodetail_Numericalorder` ON `dbn_pmcontracttwodetail` (`Numericalorder`);

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[p0='3' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      select
          t1.RecordID,
          CONVERT(t1.numericalorder USING utf8mb4) AS NumericalOrder,
          CONVERT(t1.ProductID USING utf8mb4) AS ProductID,
          t1.Detectionproject,
          CAST( t1.Detectionstandard AS CHAR(50)) AS Detectionstandard,
          CONVERT(t1.maxnum USING utf8mb4) AS Maxnum,
          CONVERT(t1.minmax USING utf8mb4) AS Minmax,
          CONVERT(t1.contractmaxnum USING utf8mb4) AS Contractmaxnum,
          CONVERT(t1.contractminnum USING utf8mb4) AS Contractminnum,
          t1.Contractclause,
          t1.Remark,
          t2.ProductName
      from dbn_pmcontracttwodetail t1
      left join biz_productdetail t2 on t1.productid = t2.ProductID
      WHERE t1.numericalorder=@p0
```

</details>

Generally, you should use the same exact spelling (casing) for your column Names (e.g. you currently use `Numericalorder` (lower case `o`) and `NumericalOrder` (upper case `O`).

>  i think maybe the entity has too many fields

That is not the case.

**Comment by ClementeGao** [comment]
@lauxjpn let me try it again

**Comment by ClementeGao** [comment]
@lauxjpn when i use Pomelo.EntityFrameworkCore.MySql version:3.1.6 has problem  but if it is 5.0.0, has no prolem
