### ISSUE TITLE
Scaffolding crash with Sequence contains no matching element

### ISSUE THREAD

**Issue by joacar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#148]
### Steps to reproduce
1. Create a MySql database
2. Run `dotnef ef dbcontext scaffold <server> "Pomelo.EntityFrameworkCore.MySql" -c <my_context> --data-dir Models/` (tried without specifying data-dir and context as well as just targeting a specific table via -t argument) 

### The issue
No scaffolding created
`System.InvalidOperationException: Sequence contains no matching element`

````
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:03.06
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetIndexes()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no matching element
````

### Further technical details

MySQL version: 5.6.10
Operating system: macOS Sierra 10.12.1
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

Other details about my project setup: Fresh Web Api with Visual Studio preview for Mac.

**App.csproj**
````
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
      <Version>1.0.0-msbuild1-final</Version>
    </DotNetCliToolReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
      <Version>1.0.0-msbuild1-final</Version>
    </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <Version>1.0.0-msbuild1-final</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk.Web">
      <Version>1.0.0-alpha-20161104-2-112</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql">
      <Version>1.1.0-rtm-10004</Version>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design">
      <Version>1.1.0-rtm-10004</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <Version>1.1.0</Version>
    </PackageReference>
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
````

**Comment by Kagamine** [comment]
Dupe of #127. Please use 1.1.0 instead of 1.1.0-rtm-10004

We suggest you to search the existed issues before open a new one.

**Comment by joacar** [comment]
Yes sorry should had searched :)

Will switch to 1.1.0 and resolve it!

Thanks for great work
