### ISSUE TITLE
Unknown column 'r.id' in 'where clause' with double nested query

### ISSUE THREAD

**Issue by leoshusar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1481]
Hi! I am getting an exception with this query:

```cs
var result = context.Racks
    .Select(r => new
    {
        RackSize = r.Type.Size,
        ShelvesOrdered = r.Shelves
            .OrderBy(s => s.VerticalPosition)
            .ToList()
    })
    .Select(r => new
    {
        r.RackSize,
        AboveShelfThickness = r.ShelvesOrdered
            .Skip(shelfIndex + 1)
            .Select(s => (int?)s.Type.Thickness)
            .FirstOrDefault(),
    })
    .FirstOrDefault();
```

EF generates this SQL:

```sql
SELECT `r0`.`size` AS `RackSize`, (
    SELECT `s0`.`Thickness`
    FROM (
        SELECT `s`.`id`, `s`.`rack_id`, `s`.`shelf_type_id`, `s`.`vertical_position`
        FROM `shelves` AS `s`
        WHERE `r`.`id` = `s`.`rack_id`
        ORDER BY `s`.`vertical_position`
        LIMIT 18446744073709551610 OFFSET @__p_0
    ) AS `t`
    INNER JOIN `ShelfType` AS `s0` ON `t`.`shelf_type_id` = `s0`.`Id`
    ORDER BY `t`.`vertical_position`
    LIMIT 1) AS `AboveShelfThickness`
FROM `racks` AS `r`
INNER JOIN `rack_types` AS `r0` ON `r`.`rack_type_id` = `r0`.`id`
LIMIT 1
```

and then it complains about the `` WHERE `r`.`id` = `s`.`rack_id` `` part.

I've read that MySQL does not support correlation clauses more than one level deep(?)

Here is my ready-to-run repro:
https://github.com/leoshusar/PomeloMySqlBugRepro
or here, in case I delete that repository some time: [PomeloMySqlBugRepro-master.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/6902247/PomeloMySqlBugRepro-master.zip)

### Exception
```
An exception occurred while iterating over the results of a query for context type 'MySqlBug.Context'.
MySqlConnector.MySqlException (0x80004005): Unknown column 'r.id' in 'where clause'
    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
    at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
    at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
    at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
    at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
    at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
    at System.Data.Common.DbCommand.ExecuteReader() in System.Data.Common.dll:token 0x60015cc+0x0
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60003fb+0x83
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60017b0+0x65
    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in Pomelo.EntityFrameworkCore.MySql.dll:token 0x60001d6+0x0
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60017af+0x36
MySqlConnector.MySqlException (0x80004005): Unknown column 'r.id' in 'where clause'
    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
    at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
    at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
    at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
    at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
    at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
    at System.Data.Common.DbCommand.ExecuteReader() in System.Data.Common.dll:token 0x60015cc+0x0
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60003fb+0x83
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60017b0+0x65
    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in Pomelo.EntityFrameworkCore.MySql.dll:token 0x60001d6+0x0
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in MicrUnhandled exception. osoft.EntityFrameworkCore.Relational.dll:token 0x60017af+0x36
MySqlConnector.MySqlException (0x80004005): Unknown column 'r.id' in 'where clause'
    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
    at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
    at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
    at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
    at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
    at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
    at System.Data.Common.DbCommand.ExecuteReader() in System.Data.Common.dll:token 0x60015cc+0x0
    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60003fb+0x83
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result) in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60017b0+0x65
    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in Pomelo.EntityFrameworkCore.MySql.dll:token 0x60001d6+0x0
    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in Microsoft.EntityFrameworkCore.Relational.dll:token 0x60017af+0x36
    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found) in System.Linq.dll:token 0x60000f6+0x43
    at lambda_method9(Closure , QueryContext )
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in Microsoft.EntityFrameworkCore.dll:token 0x600089d+0x70
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in Microsoft.EntityFrameworkCore.dll:token 0x6000833+0x0
    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source) in System.Linq.Queryable.dll:token 0x600013c+0xe
    at <Program>$.<Main>$(String[] args) in C:\Users\husar\source\repos\MySqlBug\MySqlBug\Program.cs:line 11
```

### Further technical details

MySQL version: 10.5.11-mariadb
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.8 (also tried 6-preview)

EDIT: Same problem with only single `Select`:

```cs
var result = context.Racks
    .Select(r => new
    {
        r.Type.Size,
        AboveShelfThickness = r.Shelves
            .OrderBy(s => s.VerticalPosition)
            .Skip(shelfIndex + 1)
            .Select(s => (int?)s.Type.Thickness)
            .FirstOrDefault(),
    })
    .FirstOrDefault();
```

**Comment by mguinness** [comment]
Have you tried MySQL 8?  It appears that [Support lateral derived tables](https://jira.mariadb.org/browse/MDEV-19078) is not supported in MariaDB yet.  There is a feature flag `OuterReferenceInMultiLevelSubquery` that is only applicable for MySQL.

**Comment by leoshusar** [comment]
MySQL 8 works, thank you!
I guess no changes will be made for MariaDB so this can be closed?

**Comment by mguinness** [comment]
@leoshusar Can you share the SQL generated for MySQL so we can compare?

@lauxjpn Is there a workaround for MariaDB and if not, could we throw an exception?

**Comment by leoshusar** [comment]
Sure!
My server version now is 8.0.26-mysql.

Here is the output SQL of the first command:

```sql
SELECT `r0`.`size` AS `RackSize`, (
    SELECT `s0`.`Thickness`
    FROM (
        SELECT `s`.`id`, `s`.`rack_id`, `s`.`shelf_type_id`, `s`.`vertical_position`
        FROM `shelves` AS `s`
        WHERE `r`.`id` = `s`.`rack_id`
        ORDER BY `s`.`vertical_position`
        LIMIT 18446744073709551610 OFFSET @__p_0
    ) AS `t`
    INNER JOIN `ShelfType` AS `s0` ON `t`.`shelf_type_id` = `s0`.`Id`
    ORDER BY `t`.`vertical_position`
    LIMIT 1) AS `AboveShelfThickness`
FROM `racks` AS `r`
INNER JOIN `rack_types` AS `r0` ON `r`.`rack_type_id` = `r0`.`id`
LIMIT 1
```

and I noticed that when I change code to this:

```cs
var result = context.Racks
    .Select(r => new
    {
        r.Type,
        AboveShelfThickness = context.Shelves
            .Include(s => s.Type)
            .Where(s => s.RackId == r.Id)
            .OrderBy(s => s.VerticalPosition)
            .Skip(shelfIndex + 1)
            .FirstOrDefault(),
    })
    .FirstOrDefault();
```

it generates SQL with LATERAL JOIN:

```sql
SELECT `r0`.`id`, `r0`.`size`, `t0`.`id`, `t0`.`rack_id`, `t0`.`shelf_type_id`, `t0`.`vertical_position`, `t0`.`Id0`, `t0`.`Thickness`, `t0`.`c`
FROM `racks` AS `r`
INNER JOIN `rack_types` AS `r0` ON `r`.`rack_type_id` = `r0`.`id`
LEFT JOIN LATERAL (
    SELECT `t`.`id`, `t`.`rack_id`, `t`.`shelf_type_id`, `t`.`vertical_position`, `s0`.`Id` AS `Id0`, `s0`.`Thickness`, 1 AS `c`
    FROM (
        SELECT `s`.`id`, `s`.`rack_id`, `s`.`shelf_type_id`, `s`.`vertical_position`
        FROM `shelves` AS `s`
        WHERE `s`.`rack_id` = `r`.`id`
        ORDER BY `s`.`vertical_position`
        LIMIT 18446744073709551610 OFFSET @__p_0
    ) AS `t`
    INNER JOIN `ShelfType` AS `s0` ON `t`.`shelf_type_id` = `s0`.`Id`
    ORDER BY `t`.`vertical_position`
    LIMIT 1
) AS `t0` ON TRUE
LIMIT 1
```

**Comment by lauxjpn** [comment]
> Is there a workaround for MariaDB and if not, could we throw an exception?

I think there is no workaround we can implement for the issue with MariaDB.
The way to solve the issue is to write the query in a different way.

We could implement an expression visitor, that explicitly checks for columns of outer queries that are being referenced in inner queries, so we can throw a more concrete exception instead of the `MySqlException`, if you guys think that it's worth it.
