### ISSUE TITLE
Create table script adds `CHARACTER SET utf8mb4` and this causes error

### ISSUE THREAD

**Issue by imalkevich** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1493]
### The issue
I have a project with I started with the previous version of Pomelo. Recently I migrated to version 5.0.1. 

When I'm trying to make a fresh installation of the application, I'm getting incorrect syntax message for the following line:

`Message longtext CHARACTER SET utf8mb4(2048) NOT NULL`

If I manually remove `CHARACTER SET` and execute the command in Workbench, everything works smoothly.

I tried to following the following issue and apply the suggested fix of not specifying character set explicitly - https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1435 - but with no success...

Here is my `Startup.cs` configuration:
```C#
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseMySql(
        Configuration.GetConnectionString("DefaultConnection"),
        new MariaDbServerVersion(new Version(10, 3))
    ),
    ServiceLifetime.Scoped);
```

Here is what I added in `ApplicationDbContext.cs` following the discussions:
```C#
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    // this should have fixed issue and act similar to CharSetBehavior(CharSetBehavior.NeverAppend) #1435
    builder.HasCharSet(null, DelegationModes.ApplyToDatabases);
}
```

But I'm not able to fix the error - here is a stack trace that I'm getting:
```
2021-08-22 15:03:09.8549|20102|ERROR|Microsoft.EntityFrameworkCore.Database.Command|Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `Logs` (
    `Id` varchar(255) NOT NULL,
    `UserName` varchar(512) NULL,
    `UserIp` varchar(512) NULL,
    `Action` varchar(512) NOT NULL,
    `Status` varchar(512) NOT NULL,
    `AffectedUserName` varchar(512) NULL,
    `EntityId` varchar(512) NULL,
    `EntityIcon` varchar(512) NULL,
    `CardName` varchar(512) NULL,
    `RoomName` varchar(512) NULL,
    `AutomationName` varchar(512) NULL,
    `ObjectName` varchar(512) NULL,
    `Location` varchar(512) NULL,
    `Message` longtext CHARACTER SET utf8mb4(2048) NOT NULL,
    `CreatedDate` datetime(6) NOT NULL,
    `IsArchived` tinyint(1) NOT NULL,
    CONSTRAINT `PK_Logs` PRIMARY KEY (`Id`)
); |url: |action: 
2021-08-22 15:03:09.8821||ERROR|Iotics.Api.Program|Stopped program because of exception MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(2048) NOT NULL,
    `CreatedDate` datetime(6) NOT NULL,
    `IsArchived` tin...' at line 15
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 888
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 266
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Iotics.Api.Program.Main(String[] args) in C:\MyProjects\iotics\Iotics.Admin\Iotics.Api\Program.cs:line 35|url: |action: 
Unhandled exception. MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(2048) NOT NULL,
    `CreatedDate` datetime(6) NOT NULL,
    `IsArchived` tin...' at line 15
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 888
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 266
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Iotics.Api.Program.Main(String[] args) in C:\MyProjects\iotics\Iotics.Admin\Iotics.Api\Program.cs:line 35
   at Iotics.Api.Program.<Main>(String[] args)
/run.sh: line 28:   308 Aborted                 (core dumped) dotnet Iotics.Api.dll
```

### Further technical details

MySQL version: Maria DB 10.3
Operating system: Ubuntu 20.04.3
Pomelo.EntityFrameworkCore.MySql version: 5.0.1

**Comment by mguinness** [comment]
I don't think the problem is with charset, but the length of 2048.   Please post your `Log` class and any Fluent API in `OnModelCreating`.

**Comment by imalkevich** [comment]
Here is the code I have related to this table in `OnModelCreating`:
```
builder.Entity<Log>()
                .HasOne(l => l.User)
                .WithMany(u => u.Logs)
                .OnDelete(DeleteBehavior.Cascade);

builder.Entity<Location>()
                .HasMany(l => l.Logs)
                .WithOne(log => log.PhysicalLocation)
                .HasForeignKey(log => log.LocationId)
                .OnDelete(DeleteBehavior.Cascade);
```

And here is the class definition itself:
```
public class Log
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string Id { get; set; }

        [StringLength(512)]
        public string UserName { get; set; }

        public bool? IsAdmin { get; set; }

        public bool? IsSystemEntry { get; set; }

        [StringLength(512)]
        public string UserIp { get; set; }

        [Required]
        [StringLength(512)]
        public string Action { get; set; }

        [Required]
        [StringLength(512)]
        public string Status { get; set; }

        [StringLength(512)]
        public string AffectedUserName { get; set; }

        [StringLength(512)]
        public string EntityId { get; set; }

        [StringLength(512)]
        public string EntityIcon { get; set; }

        [StringLength(512)]
        public string CardName { get; set; }

        [StringLength(512)]
        public string RoomName { get; set; }

        [StringLength(512)]
        public string AutomationName { get; set; }

        [StringLength(4096)]
        public string ObjectName { get; set; }

        [StringLength(512)]
        public string Location { get; set; }

        [Required]
        [StringLength(2048)]
        public string Message { get; set; }

        [Required]
        public DateTime CreatedDate { get; set; }

        [Required]
        public bool IsArchived { get; set; }

        public string UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }

        public string LocationId { get; set; }

        [ForeignKey(nameof(LocationId))]
        public Location PhysicalLocation { get; set; }
    }
```

Though this class has changed a couple of time, thus the SQL for creating this class doesn't match the existing state of this class...

Regarding the comment about `2048` - indeed, seems like the following DDL will also work:
`Message` longtext CHARACTER SET utf8mb4 NOT NULL,` (instead of the original one ``Message` longtext CHARACTER SET utf8mb4(2048) NOT NULL,`).

And now I'm wondering - potentially I can remove `[StringLength(2048)]` attribute from my class, but this might affect only one migration, right? So maybe in the first place SQL should be generated without number of characters? (some warning might be also useful in this case...) Or there is a better idea how to fix this error on my side?

Thanks

**Comment by mguinness** [comment]
> And now I'm wondering - potentially I can remove `[StringLength(2048)]` attribute from my class, but this might affect only one migration, right? So maybe in the first place SQL should be generated without number of characters? (some warning might be also useful in this case...) Or there is a better idea how to fix this error on my side?

You should probably replace with `[Column(TypeName = "text")]` to specify what type you need in the database.

**Comment by lauxjpn** [comment]
> [...] So maybe in the first place SQL should be generated without number of characters? (some warning might be also useful in this case...) [...]

Yeah, when using `longtext`, explicit string lengths should not be output by Pomelo.

**Comment by lauxjpn** [comment]
@imalkevich I am unable to reproduce the issue with the following code and Pomelo `5.0.1`:

<details>
<summary>Program.cs</summary>

```c#
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        
        [Required]
        [StringLength(20_000)]
        public string Name { get; set; }
    }
    
    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                const string connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1493";
                var serverVersion = ServerVersion.AutoDetect(connectionString);

                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion)
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }
    }
}
```

</details>

It generates the following SQL output:

```sql
CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET utf8mb4;
```

Please either change the sample code in a way, that reproduces the issue, or post the relevant parts of the original migration files (`Up()` method and related `x.Design.cs` file parts), so we can investigate this further.

**Comment by imalkevich** [comment]
@lauxjpn Thanks, sure, here is the part of `x.Designer.cs` file
```charp
protected override void BuildTargetModel(ModelBuilder modelBuilder)
{
                modelBuilder.Entity("Iotics.Api.Models.Log", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("AffectedUserName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("AutomationName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("CardName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityIcon")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("EntityId")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(2048);

                    b.Property<string>("ObjectName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("RoomName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("UserIp")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Logs");
                });
}
```

Please let me know if this doesn't help.

Thanks

**Comment by lauxjpn** [comment]
The `HasColumnType("longtext CHARACTER SET utf8mb4")` call is likely to be the issue here. Pomelo `5.0.1` does not add the character set to the column type anymore (which was only a workaround in previous versions) and instead uses the `HasCharSet()` extension method (or the equivalent `MySql:CharSet` annotation).

@imalkevich Are you sure that you are using Pomelo `5.0.1` and/or that you are not setting the character set as part of the column type (e.g. in your `OnModelCreating()` method)?

I'll take a closer look at this tomorrow.
In any case, we should make sure, that we properly handle legacy cases of specifying character sets like in this way.

**Comment by lauxjpn** [comment]
> @imalkevich Are you sure that you are using Pomelo `5.0.1` and/or that you are not setting the character set as part of the column type (e.g. in your `OnModelCreating()` method)?

When I generate a migration for the sample code I posted above, the following files are being generated:

<details>
<summary>20210907181735_Initial.cs</summary>

```c#
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace IssueConsoleTemplate.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "IceCreams",
                columns: table => new
                {
                    IceCreamId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "longtext", maxLength: 20000, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IceCreams", x => x.IceCreamId);
                })
                .Annotation("MySql:CharSet", "utf8mb4");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "IceCreams");
        }
    }
}
```
</details>

<details>
<summary>20210907181735_Initial.Designer.cs</summary>

```c#
// <auto-generated />
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210907181735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("IssueConsoleTemplate.IceCream", b =>
                {
                    b.Property<int>("IceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("longtext");

                    b.HasKey("IceCreamId");

                    b.ToTable("IceCreams");
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

You can see that the files only contain proper column types without the charset. The charset is only mentioned here as explicit annotations in the `Up()` method.

Therefore, please make sure and report back to us, that your are indeed using Pomelo `5.0.1` for generating your migration, and also not explicitly setting `longtext CHARACTER SET utf8mb4` as the column type in your model definition (e.g. your `OnModelCreating()` method).

We will hold any further investigations into this issue, until we've heard back from you.

**Comment by lauxjpn** [comment]
I am able to reproduce the issue, if I create a migration in Pomelo `3.2.6`, that uses a max. length of `2048` for a string property, and then update to Pomelo `5.0.1` and create the migration script.

In that case, I get the following script:

```sql
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET utf8mb4;

START TRANSACTION;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4(2048) NOT NULL, /* <-- incorrect syntax */
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210907184335_Initial', '5.0.5');

COMMIT;
```

**Comment by imalkevich** [comment]
Yes @lauxjpn . This is my case - this project was started with .NET Core 3.1 and previous version of Pomelo, and all the migrations were generated with older version. Couple of months ago I switched this code to .NET 5 and newer version of Pomelo, and up until this point I didn't notice this issue before I had to create a new environment...

**Comment by lauxjpn** [comment]
@imalkevich No worries, thanks for taking the time to make us fix it!

The fix is already done, I'll just need to add some tests to the PR before merging it.
We will backport it to `5.0.2` as well.

**Comment by imalkevich** [comment]
Thanks a lot @lauxjpn ! Looking forward for `5.0.2` to test it out

**Comment by lauxjpn** [comment]
@imalkevich Feel free to use the latest compatible [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) until `5.0.2` is out (which is likely to be tomorrow).

**Comment by imalkevich** [comment]
@lauxjpn sorry for ping back, I should have tried it earlier, but was looking for `5.0.2` release...

Now I have the following issue - here is the SQL generated for one of the tables:
```
CREATE TABLE `Downloads` (
    `Id` varchar(255) NOT NULL,
    `CreationDate` datetime(6) NOT NULL,
    `ExpirationDate` datetime(6) NOT NULL,
    `IsUsed` tinyint(1) NOT NULL,
    `UserId` varchar(255) NOT NULL,
    CONSTRAINT `PK_Downloads` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_Downloads_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
);
```

And I'm having the following error `errno: 150 "Foreign key constraint is incorrectly formed"`.

In order to fix the SQL I need to add `CHARACTER SET utf8mb4` to `Id` and `UserId` columns, so this way it works:
* ``Id` varchar(255) NOT NULL` -> ``Id` varchar(255) CHARACTER SET utf8mb4 NOT NULL,`
* ``UserId` varchar(255) NOT NULL` -> ``UserId` varchar(255) CHARACTER SET utf8mb4 NOT NULL`

And I added the following line to `OnModelCreating` `builder.HasCharSet("utf8mb4")`:
```
protected override void OnModelCreating(ModelBuilder builder)
{
            base.OnModelCreating(builder);

            builder.HasCharSet("utf8mb4");
}
```

But it doesn't seem to help...

Sorry in case I'm missing shomthing...

Thanks

**Comment by imalkevich** [comment]
Edit: found the following question that was answer some time ago - https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1437 - but unfortunately `modelBuilder.HasCharSet("utf8mb4")` has no effect in my case...

**Comment by lauxjpn** [comment]
If you want _all_ your tables and columns using `utf8mb4`, then `builder.HasCharSet("utf8mb4");` should work, but no specifying it at all should be the same (as it is the default anyway).
It should result in all text based columns getting a `CHARACTER SET utf8mb4` clause added to them.

What is the generated SQL for the `AspNetUsers` table?

It might be necessary to post us the actual migration code (or the project if you can). Otherwise, this will be difficult to analyze.

**Comment by imalkevich** [comment]
@lauxjpn thanks for looking... I've added you to the repository with the project https://github.com/imalkevich/iotics/tree/iotics/pomelo, maybe this will be helpful?

There are two places you might be interested in :
![image](https://user-images.githubusercontent.com/7044304/134581338-e0f324d0-cc74-44f4-98ab-0212c21bfca2.png)

I will try to output the SQl generated over the weekend and will send you the details.

Thanks

**Comment by lauxjpn** [comment]
@imalkevich I moved the new issue to #1521.

**Comment by gitown** [comment]
@imalkevich This issue seems to not be fully resolved, if I set the TypeName to NVARCHAR in my entity's colum attribte, the migration will add CHARACTER SET utf8mb4 and that will cause an error!
Here is my entity:

```c#
    public class Country
    {
        [Required, Key, Column("Id")]
        public uint CountryId { get; set; }

        [Required, Column(TypeName = "NVARCHAR"), StringLength(45)]
        public string Code { get; set; }

        public ICollection<Author> Authors { get; set; }
    }
```

The migration will genreate this SQL query:

```sql
     CREATE TABLE `Countries` (
          `Id` int unsigned NOT NULL AUTO_INCREMENT,
          `Code` NVARCHAR(45) CHARACTER SET utf8mb4 NOT NULL, /* When the type is NVARCHAR we can't use 'CHARACTER SET utf8mb4'*/
          CONSTRAINT `PK_Countries` PRIMARY KEY (`Id`)
      ) CHARACTER SET utf8mb4;
```

If we define the column's type explicitly to NVARCHAR, the CHARACTER SET utf8mb4 should not be added.

**Comment by lauxjpn** [comment]
@gitown I opened #1565 for the issue you reported.
