### ISSUE TITLE
I got 'Some services are not able to be constructed ' when start my simplest ServiceWorker project in .net 5

### ISSUE THREAD

**Issue by amirex128** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1499]
hello 👋 
i have some trouble with this package when i start a raw ServiceWorker.
my project is ServiceWorker that recently i created for test connection with mysql
i have a simple context and i use this code for add context to dependency injection 

```C#
var serverVersion = new MariaDbServerVersion(new Version(10, 3, 31));

// Replace 'YourDbContext' with the name of your own DbContext derived class.
services.AddDbContext<ParsitakContext>(
    dbContextOptions => dbContextOptions
        .UseMySql(connectionString, serverVersion)
);
```
and when i injects ParsitakContext.cs in my worker class i got error something like this
## my exception
```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: WorkerService1.Worker': Cannot consume scoped service 'Infrastructure.EntityFramework.Context.ParsitakContext' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WorkerService1.Program.Main(String[] args) in C:\Users\_Amirex_\Desktop\WorkerService1\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: WorkerService1.Worker': Cannot consume scoped service 'Infrastructure.EntityFramework.Context.ParsitakContext' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.

Inner Exception 2:
InvalidOperationException: Cannot consume scoped service 'Infrastructure.EntityFramework.Context.ParsitakContext' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.

```

## Program.cs
```C#
using System;
using Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WorkerService1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    // Replace with your connection string.
                    var connectionString =
                        "server=localhost; port=3306; database=parsitak; user=root; password=12345;";

                    // Replace with your server version and type.
                    // Use 'MariaDbServerVersion' for MariaDB.
                    // Alternatively, use 'ServerVersion.AutoDetect(connectionString)'.
                    // For common usages, see pull request #1233.
                    var serverVersion = new MariaDbServerVersion(new Version(10, 3, 31));

                    // Replace 'YourDbContext' with the name of your own DbContext derived class.
                    services.AddDbContext<ParsitakContext>(
                        dbContextOptions => dbContextOptions
                            .UseMySql(connectionString, serverVersion)
                    );
                    services.AddHostedService<Worker>();
                });
        }
    }
}

```

## Worker.cs

```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Infrastructure.EntityFramework.Context;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace WorkerService1
{
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly ParsitakContext parsitakContext;

        public Worker(ILogger<Worker> logger, ParsitakContext parsitakContext)
        {
            _logger = logger;
            this.parsitakContext = parsitakContext;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
    }
}
```
## ParsitakContext.cs
```C#
using Domain.Entities.Parsitak;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.EntityFramework.Context
{
    public class ParsitakContext : DbContext
    {
        public ParsitakContext(DbContextOptions<ParsitakContext> options) : base(options)
        {
        }

        public DbSet<Reference> References { get; set; }
        public DbSet<Product> Products { get; set; }
    }
}
```

![image](https://user-images.githubusercontent.com/38375484/132345051-69b237ce-1984-4e6d-899d-70a89b390fab.png)

### Further technical details

MySQL version: 10.3.31-MariaDB-log 
Operating system: centos 7
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.AspNetCore.App version: 5

Other details about my project setup:
raw project service worker
MariaDB 
.net 5
i don't have any other code or package in my project and its really empty project with this package for connect to mysql database

**Comment by lauxjpn** [comment]
@amirex128 You are injecting your `ParsitakContext` into your `Worker` class via its constructor.

However, while your `ParsitakContext` is being registered by `AddDbContext<>()` as _scoped_, your `Worker` class is being registered by `AddHostedService<>()` as _singleton_.

And you cannot inject a scoped service into a singleton service (you can only inject singleton services into singleton services).

**Comment by lauxjpn** [comment]
@amirex128 Since we haven't heard back from you, we are going to close this issue.
