### ISSUE TITLE
System.TypeLoadException: Method 'AppendIdentityWhereCondition' does not have an implemention

### ISSUE THREAD

**Issue by uzairali001** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1510]
### Steps to reproduce
When I upgrade my project to use .net 6.0-rc1 I can no longer use Pomelo it throws this error
```
'AppendIdentityWhereCondition' in type 'Pomelo.EntityFrameworkCore.MySql.Update.Internal.MySqlUpdateSqlGenerator' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=6.0.0.0, Culture=neutral,
```
And this is the stack trace
```
System.TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'Pomelo.EntityFrameworkCore.MySql.Update.Internal.MySqlUpdateSqlGenerator' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)
   at Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_0(IDbContextOptions options, ConcurrentDictionary`2 configurations)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at MyCoAuthentication.Core.Entities.MyCoAuthDbContext..ctor(DbContextOptions`1 options) in F:\Blazor\MyCoAuthentication\MyCoAuthentication\Core\Entities\MyCoAuthDbContext.cs:line 17
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
```

### Further technical details

MySQL version: 8.0.22
Operating system: Win11
Pomelo.EntityFrameworkCore.MySql version: 6.0.0-preview.5
Microsoft.AspNetCore.App version: 6.0.100-rc.1.21458.32

**Comment by DavidErben** [comment]
I get the same error! Damn, hoped it will work. :joy:

**Comment by lixinyang123** [comment]
俺也一样

**Comment by died** [comment]
Check [this](https://github.com/dotnet/efcore/issues/26059#issuecomment-920680555)

> Uninstall EFCore RC1 , clean up, install Preview 7, then it worked.

**Comment by uzairali001** [comment]
Alright I understand `pomelo` is not ready for `.net6.0-rc1` yet so that begs the question when will it be supported?

**Comment by mguinness** [comment]
> Alright I understand `pomelo` is not ready for `.net6.0-rc1` yet so that begs the question when will it be supported?

Commits are being made regularly, but it's WIP.  Please watch https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1413 for updates.

**Comment by lauxjpn** [comment]
Technically, Pomelo should be **.net 6.0-rc1** compatible, just not yet **EF Core 6.0-rc1** compatible 😄

**Comment by mtad2002** [comment]
any solution for this error?

**Comment by mguinness** [comment]
Give [RC2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-rc.2) a try and let us know.

**Comment by mtad2002** [comment]
> Give [RC2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-rc.2) a try and let us know.

others said rc2 didn`t work, i tried and it worked for me
