### ISSUE TITLE
The transaction associated with this command is not the connection's active transaction

### ISSUE THREAD

**Issue by l0gicgate** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1512]
### The issue
I seem to be intermittently experiencing this issue when running our test suite in Github CI. I cannot seem to reproduce the issue locally.

Whenever attempting to run `DbContext.Database.GetPendingMigrations().Any()` I will sometimes encounter the following:
```
Error Message:
   System.InvalidOperationException : The transaction associated with this command is not the connection's active transaction; see https://fl.vu/mysql-trans
  Stack Trace:
     at MySqlConnector.MySqlCommand.ExecuteScalarAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 286
   at MySqlConnector.MySqlCommand.ExecuteScalar() in /_/src/MySqlConnector/MySqlCommand.cs:line 104
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
```

### Further technical details

MySQL version: 8.0
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 6.0
Microsoft.AspNetCore.App version: 5.0

Other details about my project setup:

**Comment by lauxjpn** [comment]
@l0gicgate Non-deterministic issues like this one are always a bite more complicated to track down.

Let's try to get to the bottom of this:

* What else is the method that calls `DbContext.Database.GetPendingMigrations().Any()` doing (especially before the call)?
* Is it an `async` method and does it any async calls and if so, are those calls awaited?
* Any [CS4014](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014) warnings when compiling the code?
* Is the same `DbContext` object (or its underlying connection) used in any sort of parallel running operations?
* Are you explicitly using more than one thread?

If you can post some source code it would likely help a lot in finding the underlying issue.

**Comment by l0gicgate** [comment]
> What else is the method that calls DbContext.Database.GetPendingMigrations().Any() doing (especially before the call)?

Before the tests run there's a database cleaner that would run and setup some fixtures. It looks like this was the source of the issue.

I'm closing this as resolved. Thank you for rubberducking.
