### ISSUE TITLE
Scaffolding for TimeOnly datatype not implemented yet?

### ISSUE THREAD

**Issue by aderrose** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1513]
### Steps to reproduce
Try to create a database column with the new EF6 TimeOnly datatype and scaffold to MySQL, example below:

```C#
namespace Test.Models;

public class SunTime
{
    public int ID { get; set; }
    public DateOnly EntryDate { get; set; }
    public DateTime Sunrise { get; set; }
    public DateTime Sunset { get; set; }
    public TimeOnly DayLength { get; set; } // Problem field
}
```

### The issue
While the project will build, scaffolding will fail with the error `The type mapping for 'TimeOnly' has not implemented code literal generation.`

If I remove the TimeOnly field, scaffold the class and manually enter the field into the migration file and database context file (see below) an EF Core database update works and updates MySQL with a new TIME field.  Equally, if I try to reverse engineer a database with a TIME field, this works as expected and is mapped correctly to a TimeOnly datatype in C#.

As a workaround manual creation isn't a massive issue but it if could be investigated at some point, that would be great.

ContexModelSnaphot.cs
```C#
b.Property<TimeOnly>("DayLength").HasColumnType("time");
```

and migration file
```C#
DayLength = table.Column<TimeOnly>(type: "time", nullable: false)
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.NotSupportedException: The type mapping for 'TimeOnly' has not implemented code literal generation.
   at Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping.GenerateCodeLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(AddColumnOperation operation, IndentedStringBuilder builder)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The type mapping for 'TimeOnly' has not implemented code literal generation.
```

### Further technical details

MySQL version: Percona 8.0.25
Operating system: Debian 11 on Windows Subsystem for Linux 2
Pomelo.EntityFrameworkCore.MySql version: 6.0.0-preview.6.ci.20210913042459 (Latest CI Build)
Microsoft.AspNetCore.App version: 6.0.100-preview.7.21379.14

Other details about my project setup:
Visual Studio 2022 Preview 4 running on Windows 11 (Beta Chanel build 22000.194)

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1361

**Comment by aderrose** [comment]
@mguinness I had read #1361 and this issue just says it will be worked on soon.  From doing some testing on the latest CI build it looks like both DateOnly and TimeOnly work except for scaffolding TimeOnly.

I scaffolded and reverse-engineered DateOnly without issue as well as reverse-engineered TimeOnly. I have also successfully written and read back data from MySQL for both DateOnly and TimeOnly.

A new issue was maybe unnecessary and a comment on #1361 to say things are looking okay would have been better.  I guess I was giving a bit of a status update for anybody interested in using the new features in .NET 6.

Anyway, keep up the excellent work everybody.

**Comment by lauxjpn** [comment]
The recent nightly builds contain the implementation for `DateOnly` and `TimeOnly`, so I am assuming you used one of those.

---

@aderrose From your OP, I am not exactly sure yet, what the issue is you are experiencing using a `TimeOnly` type.

We use the term "scaffolding" for reverse engineering a model from an existing database. However, you write:

> Try to create a database column with the new EF6 TimeOnly datatype and scaffold to MySQL, example below:
> 
> ```cs
> namespace Test.Models;
> 
> public class SunTime
> {
>     public int ID { get; set; }
>     public DateOnly EntryDate { get; set; }
>     public DateTime Sunrise { get; set; }
>     public DateTime Sunset { get; set; }
>     public TimeOnly DayLength { get; set; } // Problem field
> }
> ```

If you want us to test scaffolding something, you will need to post us the SQL script for the database we should scaffold.

---

> If I remove the TimeOnly field, scaffold the class and manually enter the field into the migration file and database context file (see below) an EF Core database update works and updates MySQL with a new TIME field. Equally, if I try to reverse engineer a database with a TIME field, this works as expected and is mapped correctly to a TimeOnly datatype in C#.

Is this about migrations or scaffolding? If it is about migrations, can we reproduce the issue by creating an initial migration with the model you posted?

**Comment by aderrose** [comment]
@lauxjpn Thanks for giving me the proper terminology :flushed:

In most cases I use Code-First Migrations to build a database for me and when using the CI build 6.0.0-preview.6.ci.20210913042459 I can create a migration that includes DateOnly type, however, when I try to create a migration for a class that includes TimeOnly I get the error from the OP.

When I'm not sure how to create a Code-First migration for something I'll build what I want in MySQL and scaffold it back to C# and when I tried using DATE and TIME fields (shown below) both work as expected and create DateOnly or TimeOnly C# fields.

So, the OP was asking if the code to create a migration containing a TimeOnly C# field could be checked over as it generates an error at this point.

````
CREATE TABLE `suntimes` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`EntryDate` DATE NOT NULL,
	`Sunrise` DATETIME NOT NULL,
	`Sunset` DATETIME NOT NULL,
	`SolarNoon` DATETIME NOT NULL,
	`DayLength` TIME NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;
````

Thanks again for the explanation and apologises for the confusion.

**Comment by lauxjpn** [comment]
> Thanks for giving me the proper terminology

@aderrose All good. Technically, both is a form of scaffolding (and it's even called "scaffolding" internally, when generating migration code), but since the EF Core CLI commands differentiate between the `scaffold` and the `migrations` commands to keep things clear, we do the same.

---

@ajcvickers @bricelam @roji This issue is an **EF Core bug** and can be reproduced with Sqlite and Npgsql as well:

<details>
<summary>Program.cs to reproduce</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class SunTime
    {
        public int ID { get; set; }
        public DateOnly EntryDate { get; set; }
        public DateTime Sunrise { get; set; }
        public DateTime Sunset { get; set; }
        public TimeOnly DayLength { get; set; } // Problem field
    }

    public class Context : DbContext
    {
        public DbSet<SunTime> SunTimes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //var connectionString = "server=127.0.0.1;port=3308;user=root;password=;database=Issue1513";
            //var serverVersion = ServerVersion.AutoDetect(connectionString);
            
            optionsBuilder
                //.UseMySql(connectionString, serverVersion)
                .UseSqlite(@"Data Source=Issue1513.db")
                //.UseNpgsql(@"server=127.0.0.1;port=5432;user id=postgres;password=postgres;database=Issue1513")
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SunTime>(
                entity =>
                {
                    entity.HasData(
                        new SunTime
                        {
                            ID = 1,
                            EntryDate = new DateOnly(2021, 09, 23),
                            Sunrise = new DateTime(2021, 09, 23, 6, 54, 0),
                            Sunset = new DateTime(2021, 09, 23, 19, 2, 0),
                            DayLength = TimeOnly.FromTimeSpan(
                                new DateTime(2021, 09, 23, 19, 2, 0) -
                                new DateTime(2021, 09, 23, 6, 54, 0))
                        });
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var sunTimes = context.SunTimes.ToList();
            
            Trace.Assert(sunTimes.Count == 1);
            Trace.Assert(sunTimes[0].ID == 1);
        }
    }
}
```

</details>

When you just run the previous code, it works as expected.

However, when trying to add a migration with `dotnet ef migrations add 'Initial'`, the following exception is being thrown:

```
System.NotSupportedException: The type mapping for 'TimeOnly' has not implemented code literal generation.
   at Microsoft.EntityFrameworkCore.Storage.CoreTypeMapping.GenerateCodeLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Array(Type type, IEnumerable values, Boolean vertical)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Literal[T](T[] values, Boolean vertical)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(InsertDataOperation operation, IndentedStringBuilder builder)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationOperationGenerator.Generate(String builderName, IReadOnlyList`1 operations, IndentedStringBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMigration(String migrationNamespace, String migrationName, IReadOnlyList`1 upOperations, IReadOnlyList`1 downOperations)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

This is also the case in EF Core 6.0 RC1.

**Comment by ajcvickers** [comment]
@lauxjpn Thanks; filed https://github.com/dotnet/efcore/issues/26156

**Comment by roji** [comment]
> @aderrose We will implement a workaround for this issue.

Thanks @lauxjpn. I think it's very likely we'll fix this for 6.0, so I wouldn't spend too much time on a workaround.

**Comment by aderrose** [comment]
@lauxjpn & @roji Thanks for the work so far, it looks like the workaround is already ready and an updated CI build has been published which now no longer throws the `NotSupportedException`.

**Comment by lauxjpn** [comment]
@roji Yeah, I implemented the workaround only until RC2. We are a bit behind in our preview releases, so it will take us a couple of days until we are caught up with EF Core upstream.
