### ISSUE TITLE
Take inside Include call throwing an exception

### ISSUE THREAD

**Issue by Et3rnos** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1526]
### Steps to reproduce
This is the code that throws the error.
```cs
var dGuild = await _context.DiscordGuilds.Include(x => x.DiscordUsers.Where(x => x.Verified == true).Take(10)).ThenInclude(x => x.HTBUser).FirstOrDefaultAsync(x => x.GuildId == Context.Guild.Id);
```
However, if I remove the `Take(10)` call, the code succeeds.

### The issue

I also tried printing 
```cs
_context.DiscordGuilds.Include(x => x.DiscordUsers.Where(x => x.Verified == true).Take(10)).ThenInclude(x => x.HTBUser).ToQueryString();
```
and executing the query directly in the mysql database and it succeeded.

Exception message:
```
Unknown column 't.DiscordId' in 'field list'
```

Stack trace:
```
---> MySqlConnector.MySqlException (0x80004005): Unknown column 't.DiscordId' in 'field list'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 888
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
```

### Further technical details

MySQL version: 8.0.26 on Ubuntu
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.AspNetCore.App version: 5.0

Here is my DatabaseContext file:
```cs
public class DatabaseContext : DbContext
    {
        public DbSet<HTBUser> HTBUsers { get; set; }
        public DbSet<DiscordUser> DiscordUsers { get; set; }
        public DbSet<DiscordGuild> DiscordGuilds { get; set; }
        public DbSet<Solve> Solves { get; set; }

        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                var tableName = entityType.GetTableName();
                entityType.SetTableName($"HTBUpdates_{tableName}");
            }
        }
    }
```

I'm adding it to my project using:
```cs
.AddDbContext<DatabaseContext>(options =>
                    options.UseMySql(CONNECTION_STRING, ServerVersion.AutoDetect(CONNECTION_STRING),
                    x => x.MigrationsHistoryTable("HTBUpdates_EFMigrationsHistory")));
```

I'm sorry if this isn't the right place to post this but stackoverflow didn't present any solution to this problem and I think it's a bug in your library. If it isn't then please let me know.

**Comment by mguinness** [comment]
Can you provide your class definitions, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/851 for an example.

> and executing the query directly in the mysql database and it succeeded.

Also please share both before and after SQL for comparison.

**Comment by Et3rnos** [comment]
I appreciate your response. I'll post the requested SQL query tomorrow.
My class definitions are the same as those in this folder:
https://github.com/Et3rnos/HTB_Updates/tree/main/Models/Database

**Comment by Et3rnos** [comment]
As requested, here is the output of 
```cs
_context.DiscordGuilds.Include(x => x.DiscordUsers.Where(x => x.Verified == true).Take(10)).ThenInclude(x => x.HTBUser).ToQueryString()
```
```sql
SELECT `h`.`Id`, `h`.`ChannelId`, `h`.`GuildId`, `t0`.`Id`, `t0`.`DiscordId`, `t0`.`GuildId`, `t0`.`HTBUserId`, `t0`.`Verified`, `t0`.`Id0`, `t0`.`HtbId`, `t0`.`LastUpdated`, `t0`.`Score`, `t0`.`Username`
FROM `HTBUpdates_DiscordGuilds` AS `h`
LEFT JOIN LATERAL (
    SELECT `t`.`Id`, `t`.`DiscordId`, `t`.`GuildId`, `t`.`HTBUserId`, `t`.`Verified`, `h1`.`Id` AS `Id0`, `h1`.`HtbId`, `h1`.`LastUpdated`, `h1`.`Score`, `h1`.`Username`
    FROM (
        SELECT `h0`.`Id`, `h0`.`DiscordId`, `h0`.`GuildId`, `h0`.`HTBUserId`, `h0`.`Verified`
        FROM `HTBUpdates_DiscordUsers` AS `h0`
        WHERE (`h`.`Id` = `h0`.`GuildId`) AND `h0`.`Verified`
        LIMIT 10
    ) AS `t`
    INNER JOIN `HTBUpdates_HTBUsers` AS `h1` ON `t`.`HTBUserId` = `h1`.`Id`
) AS `t0` ON TRUE
ORDER BY `h`.`Id`, `t0`.`Id`, `t0`.`Id0`
```

and
```cs
_context.DiscordGuilds.Include(x => x.DiscordUsers.Where(x => x.Verified == true)).ThenInclude(x => x.HTBUser).ToQueryString()
```
```sql
SELECT `h`.`Id`, `h`.`ChannelId`, `h`.`GuildId`, `t`.`Id`, `t`.`DiscordId`, `t`.`GuildId`, `t`.`HTBUserId`, `t`.`Verified`, `t`.`Id0`, `t`.`HtbId`, `t`.`LastUpdated`, `t`.`Score`, `t`.`Username`
FROM `HTBUpdates_DiscordGuilds` AS `h`
LEFT JOIN (
    SELECT `h0`.`Id`, `h0`.`DiscordId`, `h0`.`GuildId`, `h0`.`HTBUserId`, `h0`.`Verified`, `h1`.`Id` AS `Id0`, `h1`.`HtbId`, `h1`.`LastUpdated`, `h1`.`Score`, `h1`.`Username`
    FROM `HTBUpdates_DiscordUsers` AS `h0`
    INNER JOIN `HTBUpdates_HTBUsers` AS `h1` ON `h0`.`HTBUserId` = `h1`.`Id`
    WHERE `h0`.`Verified`
) AS `t` ON `h`.`Id` = `t`.`GuildId`
ORDER BY `h`.`Id`, `t`.`Id`, `t`.`Id0`
```

Note that when directly inputted in the mysql db, none of the queries fail. But when the ef query with Take is executed, the already mentioned exception is thrown.

**Comment by Et3rnos** [comment]
My `DatabaseContextModelSnapshot.cs` file was autogenerated but if you also need it then please let me know.

**Comment by lauxjpn** [comment]
@Et3rnos I am not able to reproduce this issue using the following code:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace IssueConsoleTemplate
{
    public class DiscordGuild
    {
        [Key]
        public int Id { get; set; }

        public ulong GuildId { get; set; }
        public ulong ChannelId { get; set; }
        public List<DiscordUser> DiscordUsers { get; set; } = new List<DiscordUser>();
    }

    public class DiscordUser
    {
        [Key]
        public int Id { get; set; }

        public ulong DiscordId { get; set; }
        public int GuildId { get; set; }
        public DiscordGuild Guild { get; set; }
        public int HTBUserId { get; set; }
        public HTBUser HTBUser { get; set; }
        public bool Verified { get; set; } = false;
    }

    public class HTBUser
    {
        [Key]
        public int Id { get; set; }

        public int HtbId { get; set; }
        public string Username { get; set; }
        public int Score { get; set; }
        public List<Solve> Solves { get; set; } = new List<Solve>();
        public List<DiscordUser> DiscordUsers { get; set; } = new List<DiscordUser>();
        public DateTime LastUpdated { get; set; }
    }
    
    public class Solve
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public int Id { get; set; }

        public DateTime Date { get; set; }

        [JsonProperty("date_diff")]
        public string DateDiff { get; set; }

        [JsonProperty("object_type")]
        public string ObjectType { get; set; }

        public string Type { get; set; }

        [JsonProperty("first_blood")]
        public bool FirstBlood { get; set; }

        [JsonProperty("id")]
        public int SolveId { get; set; }

        public string Name { get; set; }

        public int Points { get; set; }

        [JsonProperty("machine_avatar")]
        public string MachineAvatar { get; set; }

        [JsonProperty("challenge_category")]
        public string ChallengeCategory { get; set; }

        [System.Text.Json.Serialization.JsonIgnore]
        public int HTBUserId { get; set; }

        [System.Text.Json.Serialization.JsonIgnore]
        public HTBUser HTBUser { get; set; }
    }
    
    public class Context : DbContext
    {
        public DbSet<HTBUser> HTBUsers { get; set; }
        public DbSet<DiscordUser> DiscordUsers { get; set; }
        public DbSet<DiscordGuild> DiscordGuilds { get; set; }
        public DbSet<Solve> Solves { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1526";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion, x => x.MigrationsHistoryTable("HTBUpdates_EFMigrationsHistory"))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                var tableName = entityType.GetTableName();
                entityType.SetTableName($"HTBUpdates_{tableName}");
            }
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var guilds = context.DiscordGuilds
                .Include(x => x.DiscordUsers
                    .Where(x => x.Verified == true)
                    .Take(10))
                .ThenInclude(x => x.HTBUser)
                .ToList();

            Trace.Assert(guilds.Count == 0);
        }
    }
}
```

</details>

The generated SQL query is the exact same (the first one) that you posted.

So your model itself and the query are working as expected without any syntax error.

However, I have not taken a closer look at the migrations at https://github.com/Et3rnos/HTB_Updates/tree/main/Migrations and it is entirely possible, that your migrations do not reflect what is currently at your database.

So I suggest to apply all your migrations to a new database, dump it, then create another database directly from the current model (like I did in the sample code above using `context.Database.EnsureDeleted(); context.Database.EnsureCreated();`, dump it as well and then diff the SQL of the two dumps.

feel free to post the SQL dump of your current actual database here (does not need to contain any data, just the structure statements are fine).

**Comment by Et3rnos** [comment]
Hello @lauxjpn and thank you for your response.
However, the project at my github repository is outdated (namely the Migrations folder) - those were generated for mysql v5.7. I will upload my current Migrations folder and share the link with you soon. I can also dump the database structures if this is not enough.

**Comment by Et3rnos** [comment]
Here you have it
https://drive.google.com/file/d/14QVc9hZn88TFV4vY42boyuW2W7y2_0nn/view?usp=sharing

**Comment by lauxjpn** [comment]
Running the query against a database created from the migrations that you provided works fine.
Have you tried running my sample code against your database on your end (the one that you got the syntax error from)? Does it work or fail?
If it fails, then your database model is different from the one that the migrations represent:

> So I suggest to apply all your migrations to a new database, dump it, then create another database directly from the current model (like I did in the sample code above using `context.Database.EnsureDeleted(); context.Database.EnsureCreated();`, dump it as well and then diff the SQL of the two dumps.
> 
> Feel free to post the SQL dump of your current actual database here (does not need to contain any data, just the structure statements are fine).

**Comment by Et3rnos** [comment]
Hello @lauxjpn! I tried running the code you provided and it succeeded. However, that was not the code I was running. If you notice, I was adding a FirstOrDefaultAsync() call to the end of my query. So I replaced your query with:
```cs
var guilds = context.DiscordGuilds
                .Include(x => x.DiscordUsers
                    .Where(x => x.Verified == true)
                    .Take(10))
                .ThenInclude(x => x.HTBUser)
                .FirstOrDefault(x => x.GuildId == 123);
```
(I added the FirstOrDefault call)

And the previous error occured!

**Comment by Et3rnos** [comment]
Glad to know that @lauxjpn 
So I guess I'll have to upgrade my project to NET 6.0 in order to fix my issue.
Thanks for the help and have a good day :)
