### ISSUE TITLE
Save the error  line:825

### ISSUE THREAD

**Issue by 15192095633** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1546]
### Steps to reproduce
int rowCount = 0;
                if (model == null || (string.IsNullOrWhiteSpace(model.Id)) || (string.IsNullOrWhiteSpace(model.SystemId)) || model.Amount < 0)
                {
                    throw new Exception("参数不正确！");
                }
                FundAccount userFundAccount = db.FundAccount.FirstOrDefault(m => m.DelFalg == 0 && m.Id == model.Id);
                if (userFundAccount == null)
                    throw new ArgumentException($"无效的账户Id。{userFundAccount.Id}");

                FundSubAccount userFundSubAccount = db.FundSubAccount.FirstOrDefault(m => m.DelFalg == 0 && m.FundAccountType == model.FundAccountType && m.FundAccountId == userFundAccount.Id);
                if (userFundSubAccount == null)
                    throw new ArgumentException($"无效的子账户Id。{model.UserId}" + JsonHelper.SerializeObject(model));

                var neworder = new Orders
                {
                    Id = Guid.NewGuid().ToString("N"),
                    OrderNo = OrderHelper.CreateNumber(),
                    UserId = userFundAccount.UserId,
                    Price = model.Amount,
                    PayPrice = model.Amount,
                    DelFalg = 0,
                    CreationTime = DateTime.Now,
                    OrderStatus = (int)OrderStatus.Status1,
                    ProductName = "充值",
                    PayType = (int)PayType.ManualPay,
                    PayStatus = (int)OrderPayStatus.NoPay,
                    BusinessDistricId = model.BusinessDistricId,
                    ItemName = model.ItemName,
                    SystemId = model.SystemId,
                    FundAccountType = model.FundAccountType,
                    FundAccountTypeName = model.FundAccountTypeName,
                };

                neworder.PayStatus = (int)OrderPayStatus.Finish;
                neworder.OrderStatus = (int)OrderStatus.Finish;
                neworder.PayTime = DateTime.Now.Ticks;
                neworder.PaidMoney = model.Amount;
                neworder.AlterTime = DateTime.Now;

                db.Orders.Add(neworder);
                //await db.SaveChangesAsync();
                FundAccount platformFundAccount = await GetPlatformFundAccount(neworder.SystemId);
                platformFundAccount = db.FundAccount.FirstOrDefault(m => m.DelFalg == 0 && m.Id == platformFundAccount.Id);
                if (platformFundAccount == null)
                    throw new ArgumentException($"无效的账户Id。{platformFundAccount.Id}");

                FundSubAccount platformFundSubAccount = db.FundSubAccount.FirstOrDefault(m => m.DelFalg == 0 && m.FundAccountType == model.FundAccountType && m.FundAccountId == platformFundAccount.Id);
                if (platformFundSubAccount == null)
                    throw new ArgumentException($"无效的子账户Id。{platformFundAccount.Id}");

                string platformFundAccountHistoryId = Guid.NewGuid().ToString("N");
                FundAccountHistory platformFundAccountHistory = new FundAccountHistory { Id = platformFundAccountHistoryId, Action = (int)AccountActionEnum.Deposit, AccountId = platformFundAccount.Id, DepositFrozenAmount = model.Amount, DelFalg = 0, CreationTime = DateTime.Now, Remark = "订单金额存入平台资金账号," + neworder.OrderNo, SystemId = neworder.SystemId, FundAccountType = model.FundAccountType, FundAccountTypeName = model.FundAccountTypeName, FundSubAccountId = platformFundSubAccount.Id };
                db.FundAccountHistory.Add(platformFundAccountHistory);
                //await db.SaveChangesAsync();
                platformFundAccount.DepositFrozenAmount = platformFundAccount.DepositFrozenAmount + model.Amount;
                platformFundAccount.AlterTime = DateTime.Now;

                platformFundSubAccount.DepositFrozenAmount = platformFundSubAccount.DepositFrozenAmount + model.Amount;
                platformFundSubAccount.AlterTime = DateTime.Now;

                string userFundAccountHistoryId = Guid.NewGuid().ToString("N");
                FundAccountHistory userFundAccountHistory = new FundAccountHistory { Id = userFundAccountHistoryId, Action = (int)AccountActionEnum.Deposit, AccountId = userFundAccount.Id, DepositFrozenAmount = model.Amount, DelFalg = 0, CreationTime = DateTime.Now, Remark = "订单金额存入平用户资金账号," + neworder.OrderNo, SystemId = neworder.SystemId, FundAccountType = model.FundAccountType, FundAccountTypeName = model.FundAccountTypeName, FundSubAccountId = userFundSubAccount.Id };
                db.FundAccountHistory.Add(userFundAccountHistory);
                //await db.SaveChangesAsync();
                userFundAccount.DepositFrozenAmount = userFundAccount.DepositFrozenAmount + model.Amount;
                userFundAccount.AlterTime = DateTime.Now;

                userFundSubAccount.DepositFrozenAmount = userFundSubAccount.DepositFrozenAmount + model.Amount;
                userFundSubAccount.AlterTime = DateTime.Now;

                await db.SaveChangesAsync();// line:825

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 8.0.23
Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 3.2.7
Microsoft.AspNetCore.App version:3.1

Other details about my project setup:

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1285

**Comment by lauxjpn** [comment]
@15192095633 We will need a bit of context about this issue.

> ```
> INSERT INTO `Orders` (`Id`, `AlterTime`, `AlterUser`, `BusinessDistricId`, `CreationTime`, `Creator`, `DataId`, `DelFalg`, `FundAccountType`, `FundAccountTypeName`, `ItemName`, `OrderNo`, `OrderStatus`, `PaidMoney`, `Parames`, `Pay`, `PayPrice`, `PayStatus`, `PayTime`, `PayType`, `Price`, `ProductName`, `Remark`, `SystemId`, `UserId`)
>       VALUES (@p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71, @p72, @p73, @p74, @p75, @p76, @p77, @p78, @p79, @p80, @p81);
> fail: Microsoft.EntityFrameworkCore.Update[10000]
> An exception occurred in the database while saving changes for context type 'Account.DataContext'.
> System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
>  ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
>  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
>  ---> System.Net.Sockets.SocketException (125): Operation canceled
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
> ```

Could be a deadlock.
Is the exception thrown every time, or just sometimes?

**Comment by michab23** [comment]
Looking like the same issue for us... The exception thrown every time we run this query (INSERT). 

![image](https://user-images.githubusercontent.com/16411202/140904856-6ea18ef4-aa70-45dd-b1ac-eb39e661f8c0.png)

**Comment by lauxjpn** [comment]
@michab23 Thanks for picking this up!

Please provide us with the following information:

>### Further technical details
>
>MySQL version: 
>Operating system: 
>Pomelo.EntityFrameworkCore.MySql version: 
>MySqlConnector version: 
>Microsoft.AspNetCore.App version: 

Then, please post the code of the failing LINQ query/queries, and of the involved entities of that LINQ query and the resulting log output (that you have shown above as a screenshot) as text, so we can reproduce the issue.

**Comment by 15192095633** [comment]
> 



> @15192095633 We will need a bit of context about this issue.
> 
> > ```
> > INSERT INTO `Orders` (`Id`, `AlterTime`, `AlterUser`, `BusinessDistricId`, `CreationTime`, `Creator`, `DataId`, `DelFalg`, `FundAccountType`, `FundAccountTypeName`, `ItemName`, `OrderNo`, `OrderStatus`, `PaidMoney`, `Parames`, `Pay`, `PayPrice`, `PayStatus`, `PayTime`, `PayType`, `Price`, `ProductName`, `Remark`, `SystemId`, `UserId`)
> >       VALUES (@p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71, @p72, @p73, @p74, @p75, @p76, @p77, @p78, @p79, @p80, @p81);
> > fail: Microsoft.EntityFrameworkCore.Update[10000]
> > An exception occurred in the database while saving changes for context type 'Account.DataContext'.
> > System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
> >  ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
> >  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
> >  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
> >  ---> System.Net.Sockets.SocketException (125): Operation canceled
> >    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> >    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
> > ```
> 
> Could be a deadlock. Is the exception thrown every time, or just sometimes?

 just sometimes

> @michab23 Thanks for picking this up!
> 
> Please provide us with the following information:
> 
> > ### Further technical details
> > MySQL version:
> > Operating system:
> > Pomelo.EntityFrameworkCore.MySql version:
> > MySqlConnector version:
> > Microsoft.AspNetCore.App version:
> 
> Then, please post the code of the failing LINQ query/queries, and of the involved entities of that LINQ query and the resulting log output (that you have shown above as a screenshot) as text, so we can reproduce the issue.

 just sometimes

**Comment by lauxjpn** [comment]
@15192095633 Here are a couple of follow-up questions:

* It this happening in your production environment or on your local development machine?
* Are there many concurrent app requests happening?
* How many client connections does the MySQL database server have at the time of the timeout and what is its `max_connections` value?
* Do you have connection pooling enabled (that is the default) and if so, what is its `MaxPoolSize` value (the default is `100`)?
* Is your connection string changing dynamically, or are you using multiple connection strings to the same database server?
* Are you using multiple app servers (or even serverless hosting like AWS Lambda) that connect to the same database server?

**Comment by lauxjpn** [comment]
@15192095633 You haven't responded to my last questions yet. Is this still an issue for you, or can we close this one?

**Comment by lauxjpn** [comment]
@15192095633 Since you haven't provided us with the requested information, we are closing this issue.
