### ISSUE TITLE
EF Core CLI fails to 'database update' if previously configured entity is meant to end up in another schema

### ISSUE THREAD

**Issue by m-wilczynski** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#155]
### Steps to reproduce
When trying to configure entity to go to other schema than initial one like this:

```
modelBuilder.Entity<ApplicationUser>(b =>
{
        b.ToTable("Users", "otherSchema");
}
```

Operation `dotnet ef database update` fails to apply recent migration that included such change.

### The issue

EF Core CLI explodes as seen in provided stack trace.
I'm not a pro of MySQL myself as I come from MSSQL background but it seems that there's a problem with SQL syntax generated by `Generate(EnsureSchemaOperation operation, IModel model, MigrationCommandListBuilder builder)` method in class **`MySqlMigrationsSqlGenerationHelper`** (line: 229).
It seems that `CREATE OR REPLACE FUNCTION` syntax is incorrect, as it yields same error when I try to execute it in MySQL Workbench (marks `OR REPLACE` as error).
Couldn't find such syntax in MySQL documentation for 5.6 and 5.7 too, but I can't be sure.
My current fix is to remove schema part in `.ToTable()` and then it works just fine.

**Stack trace:**
```
MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FUNCTION mysql_ef_ensure_schema() RETURNS VOID
BEGIN
    IF NOT EXISTS(SELECT ' at line 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FUNCTION mysql_ef_ensure_schema() RETURNS VOID
BEGIN
    IF NOT EXISTS(SELECT ' at line 1
```

### Further technical details

MySQL version:  5.7
Operating system: Windows 10 64bit
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

Other details about my project setup:

**Comment by mguinness** [comment]
Can you include related output from `dotnet ef migrations script` so we can better understand the issue?

**Comment by Kagamine** [comment]
We have not support cross DB operations yet.

**Comment by mguinness** [comment]
Looking at class [MySqlMigrationsSqlGenerationHelper](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L234-L242), the SQL could be replaced with:

```SQL
DROP PROCEDURE IF EXISTS mysql_ef_ensure_schema;
CREATE PROCEDURE mysql_ef_ensure_schema()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME` = '{ operation.Name }')
    THEN
        CREATE SCHEMA `{ operation.Name }`;
    END IF;
END;
```

**Comment by m-wilczynski** [comment]
Hey,

Thanks for prompt response.
@Kagamine I don't believe another schema is an another DB.
That might be not true for MySQL, but in Microsoft SQL Server you could have separate schema inside one database and they could be useful for separating access for different types of users and also to organize tables into closely related groups, ie. finance, users, inventory etc.
It felt natural for me when coming from MSSQL. If that's not the case for MySQL, then sorry for bother.

As for @mguinness comment, the change proposed would at least be compatible with MySQL, because previous one seems to be not a valid SQL syntax for MySQL at all.

My example is actually an Identity classes from EntityFramework brought to different schema, so you could just take empty ASP.NET Core MVC project with user accounts and try to change `ToTable` to use different schema than the initial catalog you got in your connection string.

**Comment by mguinness** [comment]
@m-wilczynski This is not the case for MySQL, see schema definition in [MySQL Glossary](http://dev.mysql.com/doc/en/glossary.html#glos_schema):

> In MySQL, physically, a schema is synonymous with a database. You can substitute the keyword SCHEMA instead of DATABASE in MySQL SQL syntax, for example using CREATE SCHEMA instead of CREATE DATABASE.

**Comment by m-wilczynski** [comment]
I see, that would make sense then.
I would recommend to check the SQL script I've mentioned, if it really should fail like that. 
Thanks!

**Comment by Kagamine** [comment]
@mguinness Could you open a PR to fix this
