### ISSUE TITLE
Could not load type ScaffoldingPropertyExtensions from Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by MKI-Miro** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1554]
### Steps to reproduce
`dotnet ef dbcontext scaffold`

### The issue

```
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.ScaffoldingPropertyExtensions' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.FixedCSharpEntityTypeGenerator.<>c.<GenerateProperties>b__13_0(IProperty p)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
```

### Further technical details

MySQL version: MariaDB 10.0.3
Pomelo.EntityFrameworkCore.MySql version:6.0 RC1
Microsoft.AspNetCore.App version: .NET 6

**Comment by mguinness** [comment]
Please try [6.0.0-rc.2](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-rc.2) that was just published to NuGet.

**Comment by MKI-Miro** [comment]
Works thank you , that was really quick :)
