### ISSUE TITLE
'Table '<table_name>' already exists' error when updating database by new Migration layer

### ISSUE THREAD

**Issue by diegodalben** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1568]
Hi!

### Steps to reproduce
Apply the update database command to any DbContext after creating a new Migration layer.

### The issue
The update database command is trying to recreate the tables already created in the first migration run.

My DbContexts has 'DefaultSchema' set and I'm using the 'MySqlSchemaBehavior.Ignore' option as SchemaBehavior, but the script applied by dotnet-ef is considering the 'DefaultSchema' to check if the table exists in the database before to creating it.

Below are the output scripts applied by dotnet-ef:

```sql
SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='Migrations' AND TABLE_NAME='__Configuration_MigrationsHistory';

CREATE TABLE `__Configuration_MigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK__Configuration_MigrationsHistory` PRIMARY KEY (`MigrationId`)
);
```

The correct way is not to apply the 'CREATE TABLE', as the table already exists in the database.
How the 'SELECT' query is filtering on the 'TABLE_SCHEMA' column, it doesn't find the table, so it tries to apply 'CREATE TABLE'.

The dotnet-ef command used to update the database:
```bash
dotnet ef database update --context MyDbContext
```

```
Exception message: Table '__Configuration_MigrationsHistory' already exists
Stack trace: MySql.Data.MySqlClient.MySqlException (0x80004005): Table '__Configuration_MigrationsHistory' already exists
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table '__Configuration_MigrationsHistory' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 218
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 68
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 8.0.23
Operating system: Ubuntu 20.04 LTS
Pomelo.EntityFrameworkCore.MySql version: 3.2.7
EntityFrameworkCore version: 3.1.21
.NET Core version: 3.1.415

Tks!

**Comment by mguinness** [comment]
From a cursory look at the code, it appears that `MySqlSchemaBehavior` should be checked during SQL generation.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/520f4dbc7733ca5f97122fdf0dddfcf77e1b6cef/src/EFCore.MySql/Migrations/Internal/MySqlHistoryRepository.cs#L31-L50

**Comment by lauxjpn** [comment]
@diegodalben As a workaround, don't setup a schema (or procedurally remove it at the end of your `OnModelCreating()` method) until this is fixed.

**Comment by diegodalben** [comment]
Thanks @mguinness and @lauxjpn for the quick feedback and help.
