### ISSUE TITLE
Issue on deleting the foreign key of entity

### ISSUE THREAD

**Issue by nkwwk** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1575]
### Steps to reproduce
```c#
// Using similar tables
public class Group
{
    [Key]
    public long Id { get; set; }
    [Required]
    public string Name { get; set; }
    public string Description { get; set; }
    public Media CoverPicture { get; set; }
}

public class Media
{
    [Key]
    public long Id { get; set; }
    [Required]
    public string Path { get; set; }
}
```
```c#
// Using the above tables to execute the query from DBSet<Group>
var entity = await _context.Groups
    .Include(x => x.CoverPicture)
    .Where(x => x.Id == request.Id)
    .FirstOrDefaultAsync(cancellationToken);
```
```c#
// Finally, edit the entity and save changes
entity.CoverPicture = null;
// Instance is DBContext
await _context.Instance.SaveChangesAsync(cancellationToken);
```

### The issue
Performing the save changes function supposed to generate the query for setting null to the foreign key of `Group.CoverPicture`, but the query finally generated as
```sql
DELETE FROM `Groups`
WHERE `Id` = @p0;
SELECT ROW_COUNT();
```

Stack trace:
```
Microsoft.EntityFrameworkCore.Update: Error: An exception occurred in the database while saving changes for context type 'Lineup.Infrastructure.CoreDataContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`project`.`usergrouprecords`, CONSTRAINT `FK_UserGroupRecords_Groups_GroupId` FOREIGN KEY (`GroupId`) REFERENCES `groups` (`Id`))
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 908
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 126
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 450
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 312
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 305
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`project`.`usergrouprecords`, CONSTRAINT `FK_UserGroupRecords_Groups_GroupId` FOREIGN KEY (`GroupId`) REFERENCES `groups` (`Id`))
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 908
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 126
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 450
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 312
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 305
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

### Further technical details

MySQL version: 5.7.23
Operating system: Windows 10 x64
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: 6.0.0

**Comment by mguinness** [comment]
Please share the table schemas and any fluent API in your DBContext.

**Comment by lauxjpn** [comment]
@nkwwk In addition to what @mguinness requested, make sure that it also contains everything related to the `usergrouprecords` table (CREATE TABLE statement, entity class, Fluent API).

**Comment by nkwwk** [comment]
```c#
public class User : IdentityUser<long>
{
    [Required]
    public string Name { get; set; }
    public Media ProfilePicture { get; set; }
}
public class UserRole : IdentityRole<long>
{
}
public class Group
{
    [Key]
    public long Id { get; set; }
    [Required]
    public string PublicId { get; set; }
    [Required]
    public string Name { get; set; }
    public string Description { get; set; }
    public Media CoverPicture { get; set; }
}
public class GroupConfiguration : IEntityTypeConfiguration<Group>
{
    public void Configure(EntityTypeBuilder<Group> builder)
    {
        builder.HasIndex(x => x.PublicId).IsUnique();
    }
}
public class UserGroupRecord
{
    [Key]
    public long Id { get; set; }
    [Required]
    public User User { get; set; }
    [Required]
    public long UserId { get; set; }
    [Required]
    public Group Group { get; set; }
    [Required]
    public long GroupId { get; set; }
}
public class Media
{
    [Key]
    public long Id { get; set; }
    [Required]
    public string Path { get; set; }
}
// The DbContext
public class CoreDataContext : IdentityDbContext<IdentityUser<long>, UserRole, long>, ICoreDbContext
{
    public static readonly ILoggerFactory MyLoggerFactory = LoggerFactory.Create(builder => { builder.AddDebug(); });
    public DbContext Instance { get => this; }
    public DbSet<Group> Groups { get; set; }
    public DbSet<User> AppUsers { get; set; }
    public DbSet<UserRole> AppUserRoles { get; set; }
    public DbSet<UserGroupRecord> UserGroupRecords { get; set; }
    public CoreDataContext() {}
    public CoreDataContext(DbContextOptions<CoreDataContext> options) : base(options) { }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseMySql("connection string", new MySqlServerVersion(new Version(5, 7, 23)));
        }
        optionsBuilder.UseLoggerFactory(MyLoggerFactory);
        optionsBuilder.EnableSensitiveDataLogging(true);
    }
    protected override void OnModelCreating(ModelBuilder modelbuilder)
    {
        foreach (var relationship in modelbuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
        {
            relationship.DeleteBehavior = DeleteBehavior.ClientCascade;
        }

        modelbuilder.ApplyConfigurationsFromAssembly(typeof(User).Assembly);

        base.OnModelCreating(modelbuilder);
    }
}
```

The entities relationship does not use any fluent API and only relies on the ef migration.

**Comment by nkwwk** [comment]
Finally after removed
```c#
foreach (var relationship in modelbuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
{
    relationship.DeleteBehavior = DeleteBehavior.ClientCascade;
}
```
The SQL has generated as excepted
```sql
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[@p1='2', @p0=NULL (DbType = Int64)], CommandType='Text', CommandTimeout='30']
UPDATE `Groups` SET `CoverPictureId` = @p0
WHERE `Id` = @p1;
SELECT ROW_COUNT();
```

**Comment by lauxjpn** [comment]
@nkwwk Does this solve your issue or do you still need us to look into this?

**Comment by lauxjpn** [comment]
> @nkwwk Does this solve your issue or do you still need us to look into this?

@nkwwk Since we haven't heard back from you, we will assume that the issue has been resolved for you.
