### ISSUE TITLE
Feature Request: Authentication Methods Dialog

### ISSUE THREAD

**Issue by Hoytron** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1590]
### Steps to reproduce
We are using a MariaDB Server (v10.5.9) and configured pam_auth to authenticate against an active directory ldap server. 

### The issue
After configuration of pam authentication, we cannot login anymore using the same connectionstring.
We get the following error: `Authentication method 'dialog' is not supported`

```
Exception message:  Authentication method 'dialog' is not supported
Stack trace:
   at MySqlConnector.Core.ServerSession.<SwitchAuthenticationAsync>d__78.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 692
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__76.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 503
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySqlConnector.MySqlConnection.<CreateSessionAsync>d__118.MoveNext() in /_/src/MySqlConnector/MySqlConnection.cs:line 885
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySqlConnector.MySqlConnection.<OpenAsync>d__28.MoveNext() in /_/src/MySqlConnector/MySqlConnection.cs:line 414
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 380
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at Application.Utils.DatabaseService.get_DbContext() in C:\Users\xxxx\dev\repo\Application\Utils\DatabaseService.cs:line 46
   at Application.ViewModels.ViewModelMain.Refresh() in C:\Users\xxxx\dev\repo\Application\ViewModels\ViewModelMain.cs:line 26
   at Application.ViewModels.ViewModelMain..ctor() in C:\Users\xxxx\dev\repo\Application\ViewModels\ViewModelMain.cs:line 19
   at Application.Views.ViewLogin.<>c__DisplayClass3_0.<btnLogin_Click>b__0() in C:\Users\xxxx\dev\repo\Application\Views\ViewLogin.xaml.cs:line 43
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Further technical details

MariaDB version: 10.5.9 
Operating system Server: Ubuntu 20.4
Operating system App: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.3
Microsoft.AspNetCore.App version: no aspNetCore

### Already implemented? 
Did I miss any configuration option and it is already possible?

The java connector for mariadb had the same feature request and solved it for simple password authentication:
https://jira.mariadb.org/browse/CONJ-164

Thank you!

**Comment by Hoytron** [comment]
I've found a workaround, or maybe this is even the expected solution. 
You have to set the server option `pam_use_cleartext_plugin = ON` in your mysql / mariadb server config. 

This way the mysqlconnector uses a supported authentication plugin.

**Comment by lauxjpn** [comment]
> I've found a workaround, or maybe this is even the expected solution.

@Hoytron Thanks for letting us know! Maybe @bgrainger can comment on this issue, since I have no experience with MySQL/MariaDB in conjunction with Active Directory authentication.

**Comment by bgrainger** [comment]
Based on my reading of https://mariadb.com/kb/en/authentication-plugin-pam/#client-authentication-plugins, it seems like this is the best solution as long as your scenario works with the limitations noted at https://mariadb.com/kb/en/authentication-plugin-pam/#mysql_clear_password.

Otherwise, the `dialog` plugin expects the MySQL library (MySqlConnector, in this case) to show some kind of UI that allows the user to complete the PAM prompts. That functionality doesn't exist in MySqlConnector; even if it did, it would ultimately require the application to provide some kind of callback that displays UI in the consuming application with the appropriate framework (WPF, WinForms, console, etc.) and could only be used in interactive applications.

I'm not currently going to open a MySqlConnector issue requesting `dialog` authentication plugin support, but will recommend the workaround you found.

**Comment by Hoytron** [comment]
Thank you for investigating this issue. 
The workaround works as expected. We secured the connection via SSL, to keep the transmitted password hidden. 

A Callback-like solution could solve this, but this has to be implemented in the official MySqlConnector. 

Maybe this issue and solution helps others out there.
