### ISSUE TITLE
Pomelo/MySQL provider bug when using AWS Serverless for .NET 6 template

### ISSUE THREAD

**Issue by jakehova** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1604]
### Steps to reproduce
1) Install latest version of aws toolkit (for .net 6)
2) install latest aws templates for visual studio
3)  Create new project using AWS Serverless Application (.NET CORE C#) => ASP.NET Core 6 (Container)
4) Add a Project that contains Pomelo/EF Core with a DBContext
5) Run the application.  When the dbcontext performs a db action, it will throw an error regarding serialization.

### The issue
The error I'm getting is exactly like this: https://github.com/dotnet/efcore/issues/25222 .  

What's odd is that if my API project is a .net 6 minimal api project (how it has been while I've been developing), then everything works fine.  However, when I use the aws templated .net 6 serverless app to replace my API project so that I can deploy directly to AWS, I get the error above.  

As indicated in the above, it looks like the MySQL provider is throwing an exception and the Pomelo library is trying to serialize the error.  Is there a way to resolve or troubleshoot this?

### Further technical details

MySQL version: var serverVersion = new MySqlServerVersion(new System.Version(8, 0, 26));
Operating system: Windows 11 & AWS Lambda
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: .net 6

Other details about my project setup:
1) I have a primary API project that is pretty lightweight.  It just sets up dependency injection.
2) Class library that has the domain models and datacontext creation
3) Class library that contains Handling requests that are sent to the API (I use Mediatr to pass the request from the API to the handler). 

I'm using EF Core 6.0.1.  

This is the first project I've used Pomelo and MySQL so I wish I could troubleshoot better for you.  If there's any information i can add that will help resolve this, please let me know.

**Comment by lauxjpn** [comment]
@jakehova Please post the full exception including the call stack that you are getting on Lambda.

**Comment by jakehova** [comment]
> > Until around `2022-01-20T15:00:00Z` you should be able to reach the following URIs (I will take everything down after that) [...]
> 
> @jakehova I have now removed the CloudFormation stack and the corresponding database instance of the working code sample from AWS again, so the URIs are not going to work anymore.

I apologize for getting back to you late.  I had to setup an EC2 and deploy there to get around the issue so I've been working on that.

I'll setup a project and send it to you.

I'm

**Comment by lauxjpn** [comment]
@jakehova Did you test the project that I attached to my post above? It should work since it did for me.

**Comment by jakehova** [comment]
Yes, your project worked.  

I compared Startup files, nuget packages included, and csproj files and your project and my project are similar.  The one library that my project has that yours doesn't is Mediatr and Mediatr.Extensions.Microsoft.DependencyInjection.  That library shouldn't have an impact on this though.  I think there is something interfering with the serialization of objects coming back from RDS.  

The exception that gets caught when I call a get is: Cannot access a disposed object.
Object name: 'MySqlConnection'.

The stack trace reveals this error: 

`JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.MoveNextAction.Target.`

If I invoke the exact same code from a regular .net 6 API project, the query gets executed properly.  

I'm generating my context very similarly to you: 

    `  public static IServiceCollection AddAppContext(this IServiceCollection services, string connectionString)
        {
            services.AddDbContext<MyDbContext>(options =>
            {
                options.UseMySql(connectionString, new MySqlServerVersion(new System.Version(8, 0, 26)));
                options.EnableSensitiveDataLogging();
                options.EnableDetailedErrors();
            });

            return services;
        }`

I'm pulling the code using: 

    `  var requestForms = await _db.RequestForm.AsNoTracking().Where(rf => rf.ManagementRequest.Count() == 0)                                                              
                                                                   .ToListAsync();

            return requestForms;`

Is there a way to debug the pomelo provider to see the actual request go up and coming back to see if the issue is on the way back or on the way up?

**Comment by lauxjpn** [comment]
This is unlikely to be a Pomelo issue.

That being said, the full exception and stack trace should be output to your Lambda related logs (e.g. in the CloudWatch log group for that Lambda function, take a look at the Log stream for that particular run).

It should look something like this:

<details>
<summary>Sample CloudWatch log of sample project</summary>

```
    2022-01-19T14:12:38.861+01:00	START RequestId: f29ade32-ada4-443f-a7f6-eaa1e141f6d8 Version: $LATEST
    2022-01-19T14:12:38.862+01:00	2022-01-19T13:12:38.847Z [Information] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
    2022-01-19T14:12:38.862+01:00	2022-01-19T13:12:38.862Z [Information] Microsoft.Hosting.Lifetime: Hosting environment: Production
    2022-01-19T14:12:38.862+01:00	2022-01-19T13:12:38.862Z [Information] Microsoft.Hosting.Lifetime: Content root path: /var/task
    2022-01-19T14:12:39.427+01:00	2022-01-19T13:12:39.427Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting GET https://yy07k6tzqg.execute-api.eu-central-1.amazonaws.com/Prod/api/Values - 0
    2022-01-19T14:12:39.686+01:00	2022-01-19T13:12:39.686Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint 'Issue1604.Controllers.ValuesController.Get (Issue1604)'
    2022-01-19T14:12:39.746+01:00	2022-01-19T13:12:39.745Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Route matched with {action = "Get", controller = "Values"}. Executing controller action with signature System.Collections.Generic.IEnumerable`1[System.String] Get() on controller Issue1604.Controllers.ValuesController (Issue1604).
    2022-01-19T14:12:54.987+01:00	2022-01-19T13:12:54.987Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action Issue1604.Controllers.ValuesController.Get (Issue1604) in 15238.813ms
    2022-01-19T14:12:54.988+01:00	2022-01-19T13:12:54.987Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint 'Issue1604.Controllers.ValuesController.Get (Issue1604)'
    2022-01-19T14:12:55.185+01:00	2022-01-19T13:12:55.185Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Error] Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction: Unknown error responding to request: MySqlException:
    2022-01-19T14:12:55.185+01:00	MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
    2022-01-19T14:12:55.185+01:00	---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 433
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 937
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 406
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
    2022-01-19T14:12:55.185+01:00	at Issue1604.Controllers.ValuesController.Get() in E:\Sources\PomeloIssues\Issue1604\Issue1604\Controllers\ValuesController.cs:line 18
    2022-01-19T14:12:55.185+01:00	at lambda_method2(Closure , Object , Object[] )
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
    2022-01-19T14:12:55.185+01:00	--- End of stack trace from previous location ---
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    2022-01-19T14:12:55.185+01:00	--- End of stack trace from previous location ---
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    2022-01-19T14:12:55.185+01:00	at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.ProcessRequest(ILambdaContext lambdaContext, Object context, InvokeFeatures features, Boolean rethrowUnhandledError)
    2022-01-19T14:12:55.185+01:00	MySqlException:
    2022-01-19T14:12:55.185+01:00	MySqlConnector.MySqlException (0x80004005): Connect Timeout expired.
    2022-01-19T14:12:55.185+01:00	---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 433
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 937
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 406
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
    2022-01-19T14:12:55.185+01:00	at Issue1604.Controllers.ValuesController.Get() in E:\Sources\PomeloIssues\Issue1604\Issue1604\Controllers\ValuesController.cs:line 18
    2022-01-19T14:12:55.185+01:00	at lambda_method2(Closure , Object , Object[] )
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
    2022-01-19T14:12:55.185+01:00	--- End of stack trace from previous location ---
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
    2022-01-19T14:12:55.185+01:00	--- End of stack trace from previous location ---
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    2022-01-19T14:12:55.185+01:00	at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    2022-01-19T14:12:55.185+01:00	at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.ProcessRequest(ILambdaContext lambdaContext, Object context, InvokeFeatures features, Boolean rethrowUnhandledError)
    2022-01-19T14:12:55.185+01:00	MySqlException:
    2022-01-19T14:12:55.185+01:00	MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 433
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
    2022-01-19T14:12:55.185+01:00	at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
    2022-01-19T14:12:55.225+01:00	2022-01-19T13:12:55.225Z f29ade32-ada4-443f-a7f6-eaa1e141f6d8 [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished GET https://yy07k6tzqg.execute-api.eu-central-1.amazonaws.com/Prod/api/Values - 0 - 500 - - 15781.9733ms
    2022-01-19T14:12:55.347+01:00	END RequestId: f29ade32-ada4-443f-a7f6-eaa1e141f6d8
    2022-01-19T14:12:55.347+01:00	REPORT RequestId: f29ade32-ada4-443f-a7f6-eaa1e141f6d8 Duration: 16391.82 ms Billed Duration: 16993 ms Memory Size: 256 MB Max Memory Used: 100 MB Init Duration: 600.93 ms
```

</details>

In your case, the assumption is that the actual exception is being hidden by something in the pipeline that is trying to serialize the exception to return it to your call as JSON.

So first get the exception that is shown in the log (which is probably just the JSON related one) and post it here. With that information, we can probably figure out how to disable the exception serialization by whatever component is doing it, to get to the underlying actual exception.

This is assuming, that this is all because of some initial/actual exception that is then being serialized by some component, which then fails.
It is of course also just possible, that there is no initial exception and that whatever object graph you are trying to serialize as the response to the request, is just too deep and therefore hits the allowed depth of `32`.

**Comment by lauxjpn** [comment]
@jakehova What is the status of this issue? Did you collect the information we asked for?

**Comment by jakehova** [comment]
I agree that I do not think it is a Pomelo issue. 

Your project did work for me so it must be a configuration on my end that is changing the serializer.  I will look into it more when I have more time.  

You can close the issue and I will re-open or add a response when I get around to looking into it more.
