### ISSUE TITLE
MySqlException: syntax error, unexpected $end

### ISSUE THREAD

**Issue by sanishmistry** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1618]
### Steps to reproduce

Run a MySQL Full text search in boolean mode with a query ending in the character `+`

```C#
var q = "test+";
var results = await db.SearchItems!.Where(i => EF.Functions.Match(i.Title, q, MySqlMatchSearchMode.Boolean)).ToListAsync();
```

### The issue

I get the following error which seems to indicate the the query parameters are not bound properly?

```
MySqlConnector.MySqlException (0x80004005): syntax error, unexpected $end
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 127
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 456
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 330
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 323
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

### Further technical details

MySQL version:  8.0.28
Operating system:   Ubuntu 21.10
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: net6.0

**Comment by mguinness** [comment]
What is the generated SQL?  See [Fulltext search with char * produces a syntax error with InnoDB](https://bugs.mysql.com/bug.php?id=78485).

**Comment by sanishmistry** [comment]
The generated SQL is OK.

I have tried the same query in MySQL Workbench, and I get the same error, so I guess its a bug with MySQL...
