### ISSUE TITLE
Table constraints get dropped on migration fail

### ISSUE THREAD

**Issue by Phomor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1632]
### Steps to reproduce
The following classes.
```
using Microsoft.EntityFrameworkCore;

namespace EFModeling.OwnedEntities;

public class EntityContext : DbContext
{
    public DbSet<Order> Orders { get; set; }
    public DbSet<DetailedOrder> DetailedOrders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseMySql("db connect string", version));
}
```

```using System;

namespace EFModeling.OwnedEntities;

public class DetailedOrder
{
    public Guid Id { get; set; }
    public Order Order { get; set; }
    public Guid OrderId { get; set; }
}
```

```
using System;

namespace EFModeling.OwnedEntities;

public class Order
{
    public Guid Id { get; set; }
    public DetailedOrder DetailedOrder { get; set; }
}
```

Create a migration. Then change something about the Relationship, for example change DetailedOrder class to
```
using System;

namespace EFModeling.OwnedEntities;

public class DetailedOrder
{
    public Guid Id { get; set; }
    public Order Order { get; set; }
    public Guid? OrderId { get; set; }
}
```
Make another migration.
Add some sql code to this last migration that will fail after 
``` 
           migrationBuilder.DropForeignKey(
                name: "FK_DetailedOrders_Orders_OrderId",
                table: "DetailedOrders");
```
Apply both migrations, they obviously fail.
Remove the Sql code that makes the migration fail and apply the migrations again.
It fails again with the error message "Can't DROP 'FK_DetailedOrders_Orders_OrderId'; check that column/key exists".

### The issue
The second migration should not fail after removing the faulty sql code.
The foreign key constraint that gets added with the first migration and dropped at the start of the second migration does not get readded when the second migration fails and rolls back which causes the migration to fail even without any errors.

```
Exception message: Can't DROP 'FK_DetailedOrders_Orders_OrderId'; check that column/key exists
Stack trace:MySqlConnector.MySqlException (0x80004005): Can't DROP 'FK_DetailedOrders_Orders_OrderId'; check that column/key exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 127
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOB
ehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 456
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) i
n /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 282
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 101
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 8.0.28
Operating system: Windows 10 Pro v2004
Pomelo.EntityFrameworkCore.MySql version: both 3.2.7 and 6.0.1
both netcoreapp3.1 and net6.0
Microsoft.EntityFrameworkCore version: both 3.1.24 and 6.0.1

**Comment by Alexr03** [comment]
I am experiencing this issue. Wondering if this has been looked at or any workarounds?

**Comment by tvardero** [comment]
Our team expiriences this issue more often to be a coincidence. I was thinking they were doing something silly with their database. Until this happened to me. 
I have looked closely: FK existed before executing the command, however command still failed saying it "does not exist". And FK actually was deleted.

Looks like command is executed twice, succeedes on first and fails on second attempt.

Pomelo.EntityFrameworkCore.MySql Version 9.0.0-preview.3.efcore.9.0.0
Microsoft.EntityFrameworkCore.Tools 9.0.6
.NET 9
