### ISSUE TITLE
Migrate down fails when rename a column before renaming a table

### ISSUE THREAD

**Issue by foriequal0** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1658]
### Steps to reproduce

Have a model and a DbContext like this
```c#
class SomeModel
{
    public string SomeColumn { get; set; }
}

class MyDbContext : DbContext
{
     public DbSet<SomeModel> SomeTable { get; set; }
}
```
Change them to this
```c#
class SomeModel
{
    public string SomeColumn2 { get; set; }
}

class MyDbContext : DbContext
{
     public DbSet<SomeModel> SomeTable2 { get; set; }
}
```

Write a migration
```c#
namespace NK.LobbyWebAPI.Migrations.Manager
{
    public partial class Rename : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "SomeTable",
                newName: "SomeTable2");

            migrationBuilder.RenameColumn(
                name: "SomeColumn",
                table: "SomeTable2",
                newName: "SomeColumn2");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "SomeColumn2",
                table: "SomeTable2",
                newName: "SomeColumn");

            migrationBuilder.RenameTable(
                name: "SomeTable2",
                newName: "SomeTable");
        }
    }
```

Generate a script that migrates down
```shell
dotnet ef migrations script Rename 0
```

### The issue

It should generate following script
```sql
ALTER TABLE `SomeTable2` CHANGE `SomeColumn2` `SomeColumn` varchar(64) NULL;
ALTER TABLE `SomeTable2` RENAME `SomeTable`;
```

But it throws NullReferenceException instead.
```
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.5 initialized 'ManagerDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql:6.0.1' with options: ServerVersion 5.7.35-mysql
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__83_22(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateDownSql(Migration migration, Migration previousMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

However, following migration script doesn't have a problem.
```c#
// --->8--- snip --->8---
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "SomeTable2",
                newName: "SomeTable");

            migrationBuilder.RenameColumn(
                name: "SomeColumn2",
                table: "SomeTable",
                newName: "SomeColumn");
        }
```

### Further technical details

MySQL version: 5.7.35
Operating system: Ubuntu 22.04 on Windows 10 WSL 1.
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by lauxjpn** [comment]
@foriequal0 I am unable to reproduce this issue with the following code:

<details>
<summary>Program.cs</summary>

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class SomeModel
{
    public int SomeModelId { get; set; }
    
#if SECOND_MIGRATION
    public string SomeColumn2 { get; set; }
#else
    public string SomeColumn { get; set; }
#endif
}
    
public class Context : DbContext
{
#if SECOND_MIGRATION
    public DbSet<SomeModel> SomeTable2 { get; set; }
#else
    public DbSet<SomeModel> SomeTable { get; set; }
#endif

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1658";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(
                    connectionString,
                    serverVersion)
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }
}

internal static class Program
{
    private static void Main()
    {
    }
}
```

</details>

I run the following commands:

```pwsh
dotnet ef migrations add 'Initial'

dotnet build '-p:DefineConstants=DEBUG NET6_0 NET SECOND_MIGRATION'
dotnet ef migrations add 'ChangeTableAndPropertyName' --no-build --verbose
```

This generates the following files:

<details>
<summary>20220603101446_Initial.cs</summary>

```c#
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "SomeTable",
                columns: table => new
                {
                    SomeModelId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    SomeColumn = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SomeTable", x => x.SomeModelId);
                })
                .Annotation("MySql:CharSet", "utf8mb4");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SomeTable");
        }
    }
}
```

</details>

<details>
<summary>20220603101452_ChangeTableAndPropertyName.cs</summary>

```c#
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    public partial class ChangeTableAndPropertyName : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_SomeTable",
                table: "SomeTable");

            migrationBuilder.RenameTable(
                name: "SomeTable",
                newName: "SomeTable2");

            migrationBuilder.RenameColumn(
                name: "SomeColumn",
                table: "SomeTable2",
                newName: "SomeColumn2");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SomeTable2",
                table: "SomeTable2",
                column: "SomeModelId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_SomeTable2",
                table: "SomeTable2");

            migrationBuilder.RenameTable(
                name: "SomeTable2",
                newName: "SomeTable");

            migrationBuilder.RenameColumn(
                name: "SomeColumn2",
                table: "SomeTable",
                newName: "SomeColumn");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SomeTable",
                table: "SomeTable",
                column: "SomeModelId");
        }
    }
}
```

</details>

I run the following command:

```pwsh
dotnet ef migrations script 'ChangeTableAndPropertyName' 0
```

The following script is generated:

<details>
<summary>SQL Script</summary>

```sql
START TRANSACTION;

DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `Extra` = 'auto_increment'
                        AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_KEY` = 'PRI'
                        LIMIT 1;
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
        DECLARE HAS_AUTO_INCREMENT_ID INT(11);
        DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
        DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
        DECLARE SQL_EXP VARCHAR(1000);
        SELECT COUNT(*)
                INTO HAS_AUTO_INCREMENT_ID
                FROM `information_schema`.`COLUMNS`
                WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                        AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                        AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                        AND `COLUMN_TYPE` LIKE '%int%'
                        AND `COLUMN_KEY` = 'PRI';
        IF HAS_AUTO_INCREMENT_ID THEN
                SELECT `COLUMN_TYPE`
                        INTO PRIMARY_KEY_TYPE
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SELECT `COLUMN_NAME`
                        INTO PRIMARY_KEY_COLUMN_NAME
                        FROM `information_schema`.`COLUMNS`
                        WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
                                AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
                                AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
                                AND `COLUMN_TYPE` LIKE '%int%'
                                AND `COLUMN_KEY` = 'PRI';
                SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
                SET @SQL_EXP = SQL_EXP;
                PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
                EXECUTE SQL_EXP_EXECUTE;
                DEALLOCATE PREPARE SQL_EXP_EXECUTE;
        END IF;
END //
DELIMITER ;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'SomeTable2');
ALTER TABLE `SomeTable2` DROP PRIMARY KEY;

ALTER TABLE `SomeTable2` RENAME `SomeTable`;

ALTER TABLE `SomeTable` CHANGE `SomeColumn2` `SomeColumn` longtext NULL;

ALTER TABLE `SomeTable` ADD CONSTRAINT `PK_SomeTable` PRIMARY KEY (`SomeModelId`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'SomeTable', 'SomeModelId');

DELETE FROM `__EFMigrationsHistory`
WHERE `MigrationId` = '20220603101452_ChangeTableAndPropertyName';

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;

COMMIT;

START TRANSACTION;

DROP TABLE `SomeTable`;

DELETE FROM `__EFMigrationsHistory`
WHERE `MigrationId` = '20220603101446_Initial';

COMMIT;
```

</details>

The script looks as expected.

I run the following commands to test everything:

```pwsh
dotnet ef database update
dotnet ef database update 'Initial'
```

Both commands run successfully.
After the first command, there is a table `SomeTable2` with the columns `SomeModelId` and `SomeColumn2`.
After the second command, there is a table `SomeTable` with the columns `SomeModelId` and `SomeColumn`.

_Tested with Pomelo `6.0.1` and EF Core `6.0.1` against MySQL 5.7.35 and MySQL 8.0.25._

**Comment by foriequal0** [comment]
@lauxjpn
The problem will not reproduced with the migration that is generated by `dotnet ef`.
I found this while manually modifying/writing the migration.
Could you swap the order of `RenameTable` and `RenameColumn` in the `Down` script?
```c#
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_SomeTable2",
                table: "SomeTable2");

            migrationBuilder.RenameColumn(
                name: "SomeColumn2",
                table: "SomeTable2",
                newName: "SomeColumn");

            migrationBuilder.RenameTable(
                name: "SomeTable2",
                newName: "SomeTable");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SomeTable",
                table: "SomeTable",
                column: "SomeModelId");
        }
```
I think this is also a valid migration, but you can reproduce the exception.

**Comment by lauxjpn** [comment]
> Migrate down fails when rename a column before renaming a table

@foriequal0 My bad, looks like I did not read the title carefully enough!

For MySQL 5.7, there is no `ALTER TABLE ... RENAME COLUMN` statement yet, so we have to generate a more involved `ALTER TABLE ... CHANGE` statement instead, that has to includes everything about that column (store type, default value, etc.).

Since the necessary information is not part of the operation, we have to get it from the model snapshot. The model snapshot is the _target_ model snapshot. To get the column information from the target snapshot, we will use the table name and column name of the rename operation.

In your case, the table name cannot be found in the target snapshot, because you are performing multiple migration operations within one migration, and you are using the source model table name.

If you would use the target model table name instead, then table and column would be found in the target model and the statement would be created. However, since the statement would contain the target model table name (the table name after the execution of the table's rename operation) and due to your custom order of operations, the table would not have been renamed yet, the statement would fail if you would execute it.

---

There are two solutions to this issue:

* Use a database server version, that supports the `ALTER TABLE ... RENAME COLUMN` statement.
* Use the default migration operation order (first rename the table, then rename the column).

**Comment by lauxjpn** [comment]
It should be mentioned, that it is theoretically possible to solve this issue, by keeping track of all the prior operations and their potential impact on table or column names. It's just a question of whether it is worth the effort.

---

The migration architecture that EF Core went for focusses on the target model after all operations for the current migration have been applied, which therefore can be unreliable between operations (though it is the best we get from EF Core).

If each operation would be provided with a source and a target model, representing the model directly before and after the operation respectively, then this would result in much more deterministic operations in general and would much better support custom arrangements of operations by users.
