### ISSUE TITLE
Access denied for user 'root'@'192.168.0.158' (using password: YES)

### ISSUE THREAD

**Issue by zzyoMin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1660]
### Steps to reproduce
I don't know how to repeat as he is a sporadic problem；
Because I checked other relevant information, but the reply I got is basically that the database does not have remote permissions opened, so I don't know what caused the problem. If I ask the wrong place, please forgive me.

### The issue
During the running of the program, this error will occasionally appear suddenly, I queried the database and opened a remote connection

### Apologize
My English is not good, the English I used is translated by Google, I'm sorry if it affects your reading

```C#
services.AddDbContext<MySqlContext>(opt =>
{
    var version = ServerVersion.Parse($"{AppSettings.EntityFrameworkCore.MySqlVersion}-mysql");
    opt.UseMySql(AppSettings.EntityFrameworkCore.ConnectionString, version, builder =>
    {
        //不注册这个,会导致工作单元事务冲突
        //builder.EnableRetryOnFailure(maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(30), errorNumbersToAdd: null);
        builder.MinBatchSize(4);
        builder.CommandTimeout(60);
        builder.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
    });

    opt.UseLoggerFactory(new EFLoggerFactory());

    opt.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //替换默认查询sql生成器,如果通过mycat中间件实现读写分离需要替换默认SQL工厂。
    //opt.ReplaceService<IQuerySqlGeneratorFactory, MilkyWayMySqlQuerySqlGeneratorFactory>();

    opt.EnableSensitiveDataLogging();
    opt.EnableDetailedErrors();
});
```

```
Exception message:Access denied for user 'root'@'192.168.0.158' (using password: YES)
Stack trace:
 at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, String password, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 694
 at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 550
 at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
 at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
 at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
 at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
 at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
 at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
 at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
 at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
 at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
 at Lycoris.Application.AppServices.Stardusts.StardustAppService.GetStardustBriefListAsync(GetStardustBriefListFilter input) in F:\Code\Galaxy_Stardust\Lycoris.Application\AppServices\Stardusts\StardustAppService.cs:line 61
 at Lycoris.Server.Controllers.StardustController.StardustBriefList(StardustBriefListInput input) in F:\Code\Galaxy_Stardust\Lycoris.Server\Controllers\StardustController.cs:line 34
 at lambda_method592(Closure , Object )
 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Further technical details

MySQL version: 8.0.25
Operating system: CentOs 7.9
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0

**Comment by zzyoMin** [comment]
@lauxjpn 

- How often is the exception thrown? (e.g. every 10 connections, once a day, etc.)
   **Occasional, ranging from one to five times a day, and the development environment occurs more frequently**   

- Where is the database server located? (Is it on your local machine? Is it in your local network? Is it hosted by a cloud provider?)
   **The development environment database is located in the docker container, and it can be accessed from the local area network and accessed with dbForge Studio for MySQL or mysqlbench. The RDS of Alibaba Cloud purchased in the production environment is normal.**

- Is this a single database server, or are there multiple database servers? (e.g. a cluster, a load balancer, etc.)
  **At the beginning of the project, the database is still a stand-alone environment**

- Is the exception only thrown in your production environment, or is it also thrown in your development environment?
  **Exceptions are more frequent in the development environment, and rare in the production environment, but they still occur. More often, it occurs after the program starts, and the access is directly the above error. the law of the problem**

- How do you deal with the issue, after the exception has been thrown? (Do you need to restart the application? Do you need to reconfigure the MySQL server? Do you have to do nothing, because after the exception is thrown once, the application continues to run normally again?)
  **After an exception occurs, it needs to be restarted to recover. Sometimes it needs to restart multiple times, sometimes once, which is also irregular.**

**Comment by zzyoMin** [comment]
@lauxjpn I tested with the source code on github and seems to find the problem, it seems to be my own problem, the connection string at some point will have a missing password field or an extra password field, I am looking for the problem. Sorry, it must be my problem

**Comment by lauxjpn** [comment]
@zzyoMin Thanks for letting us know! I am glad you solved the issue.
