### ISSUE TITLE
DropIndexOperation - Value cannot be null. (Parameter 'name')

### ISSUE THREAD

**Issue by andrei-bucurei** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1663]
### Steps to reproduce
1) Create a migration that drops an index:
```C#
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    public partial class AppointmentScheduleSlotIdNoIndex : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Appointments_ScheduleSlotId"
            );
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Appointments_ScheduleSlotId",
                table: "Appointments",
                column: "ScheduleSlotId",
                unique: true);
        }
    }
}
```
2) Apply changes to the database.
Operation does not succeed because it seems it does not recognise the name of the index.

### The issue
Migration that should drop an index throws an exception:

```
Exception message: Value cannot be null. (Parameter 'name')
Stack trace:
System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.Storage.RelationalSqlGenerationHelper.DelimitIdentifier(String name, String schema)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlSqlGenerationHelper.DelimitIdentifier(String name, String schema)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.Generate(DropIndexOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__83_14(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'name')
```

### Further technical details

MySQL version: 5.5.5-10.5.15-MariaDB-0+deb11u1
Operating system: Mac OS
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.5

**Comment by andrei-bucurei** [comment]
The problem is resolved if I specify the table name for the index.
However, the error message is not very clear.

**Comment by lauxjpn** [comment]
The SQL Server provider explicitly checks the table name, so we can do the same:

https://github.com/dotnet/efcore/blob/96f7bb85e87bb3f80d29f0751c860036fc2edfb4/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L1237-L1240

```c#
protected override void Generate(
        DropIndexOperation operation,
        IModel? model,
        MigrationCommandListBuilder builder,
        bool terminate)
    {
        if (string.IsNullOrEmpty(operation.Table))
        {
            throw new InvalidOperationException(SqlServerStrings.IndexTableRequired);
        }
        
        // [...]
```
