### ISSUE TITLE
 Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by oscar02r** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1672]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
```

**Comment by mguinness** [comment]
You haven't provided the information requested in the new issue template.  Describe what is not working as expected.  Ideally include a complete code listing that we can run to reproduce the issue.

**Comment by mguinness** [comment]
@oscar02r Can you provide further details, or let us know how you resolved your issue?

**Comment by lauxjpn** [comment]
@oscar02r Since we haven't heard back from you, we are closing this issue for now.
