### ISSUE TITLE
The LINQ expression 'OUTER APPLY AS t15' could not be translated. Either rewrite the query in a form that can be translated...

### ISSUE THREAD

**Issue by pantonis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1722]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Im trying to run an EF Core query and I get the following error

If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message:
````
An exception occurred while iterating over the results of a query for context type 'MyProject.DwDbContext'.
System.InvalidOperationException: The LINQ expression 'OUTER APPLY
(
  SELECT c.Visible, c.PositionOrder, c.EnablePivot, Equal(f.Id) AS c, f.Name, f.DisplayName, f.Description, Equal(d0.Id) AS c0, d0.Name AS Name0, d0.Id, f.Format, c.Id AS Id0, f.Id AS Id1, f0.Name AS Name1, f0.Id AS Id2
  FROM Column AS c
  LEFT JOIN Field AS f ON c.FieldId == f.Id
  LEFT JOIN DataType AS d0 ON f.DataTypeId == d0.Id
  LEFT JOIN FilterType AS f0 ON f.Id == f0.FieldId
  WHERE NotEqual((
	  SELECT TOP(1) t16.Id
	  FROM TableDefinition AS t16
	  WHERE t.Id == t16.ReportId)) && (((
	  SELECT TOP(1) t17.Id
	  FROM TableDefinition AS t17
	  WHERE t.Id == t17.ReportId) == c.TableDefinitionId) || (Equal((
	  SELECT TOP(1) t17.Id
	  FROM TableDefinition AS t17
	  WHERE t.Id == t17.ReportId)) && Equal(c.TableDefinitionId)))
) AS t15' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
````
Stack trace:
````
 at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckTranslated(Expression translated, Expression original)
 at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckSupport(Expression expression, Boolean isSupported)
 at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitOuterApply(OuterApplyExpression outerApplyExpression)
 at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression)
 at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
 at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
 at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.<VisitChildren>g__VisitList|124_0[T](List`1 list, Boolean inPlace, Boolean& changed, <>c__DisplayClass124_0& )
 at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor)
 at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
 at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression)
 at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
 at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
 at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlParameterBasedSqlProcessor.Optimize(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
 at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
 at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
 at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
 at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
````
### Further technical details

MariaDB version: 10.10.2
Operating system: Windows 10/ Windows Server 2016
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: net6.0

Other details about my project setup:

**Comment by mguinness** [comment]
This looks like the same issue encountered in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1714.  Unfortunately MariaDB doesn't [Support lateral derived tables](https://jira.mariadb.org/browse/MDEV-19078) currently.

**Comment by pantonis** [comment]
Oh man this is a "stop the migration to MariaDb" issue. lots of issues. thought that MariaDB was working flawlessly along MySql but this is not the case..

**Comment by lauxjpn** [comment]
To see the major feature differences between MySQL and MariaDB, take a look at the following 3 classes:
* [ServerVersionSupport](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Infrastructure/ServerVersionSupport.cs)
* [MySqlServerVersion](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs)
* [MariaDbServerVersion](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs)

In regards to general querying, the major difference between the latest version of MySQL and MariaDB is that MySQL supports `LATERAL` tables (`CROSS APPLY` and `OUTER APPLY` in SQL Server) and MariaDB supports sequences.

`LATERAL` tables are usually only used by rather complex LINQ queries and can normally be avoided by splitting the queries in question (either manually or by using [.AsSplitQuery()](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries#split-queries-1)).

**Comment by pantonis** [comment]
Is this something that can be done in the Pomelo.EntityFrameworkCore.MySql internally. (AsSplitQuery when db is MariaDb)

**Comment by lauxjpn** [comment]
> Is this something that can be done in the Pomelo.EntityFrameworkCore.MySql internally. (AsSplitQuery when db is MariaDb)

We can't do that because of the concerns mentioned in the referenced article and also for performance reasons.

But it should be possible for your code to e.g. catch the `InvalidOperationException`, inject an `AsSplitQuery()` call into the expression tree and send the resulting new expression tree down the query translation pipeline again.
