### ISSUE TITLE
MySqlException: No database selected

### ISSUE THREAD

**Issue by wangharris** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1735]
### Steps to reproduce

WeatherForecastController.cs
```C#
private readonly MyDbContext _dbcontext;

public WeatherForecastController(MyDbContext dbcontext)
{
    _dbcontext = dbcontext;
}

[HttpGet]
public IActionResult GetTestDb()
{
    var entity = _dbcontext.Enterprise.FirstOrDefault();
    return Ok(entity);
}
```

MyDbContext.cs
```C#
public class MyDbContext : DbContext
{
    public DbSet<EnterpriseEntity> Enterprise { get; set; }

    public MyDbContext(DbContextOptions<MyDbContext> options)
    : base(options)
    {
    }
}
```

Program.cs
```C#
builder.Services.AddDbContextPool<MyDbContext>(o => 
{
    string connectionString = @"Server=xxxx;port=xx;uid=xxxx;pwd=xxxx;database=portal;CharSet=gbk;max pool size=50;Convert Zero Datetime=True;";
    var serverVersion = ServerVersion.AutoDetect(connectionString);
    o.UseMySql(connectionString, serverVersion);
});
```

### The issue

Calling /WeatherForecast/GetTestDb.  The first db query is ok.  From the second is bad.

Exception
```
MySqlConnector.MySqlException (0x80004005): No database selected
  at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in ResultSet.cs
  at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in MySqlDataReader.cs
  at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary<string, CachedProcedure> cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlDataReader.cs
  at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList<IMySqlCommand> commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in CommandExecutor.cs
  at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlCommand.cs
  at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in MySqlCommand.cs
  at System.Data.Common.DbCommand.ExecuteReader()
  at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator.InitializeReader(Enumerator enumerator)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator+<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator)
  at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+Enumerator.MoveNext()
  at System.Linq.Enumerable.TryGetSingle<TSource>(IEnumerable<TSource> source, out bool found)
  at lambda_method7(Closure , QueryContext )
  at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute<TResult>(Expression query)
  at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute<TResult>(Expression expression)
  at System.Linq.Queryable.FirstOrDefault<TSource>(IQueryable<TSource> source)
  at TestDbApp.Controllers.WeatherForecastController.GetTestDb() in WeatherForecastController.cs
```

Log
```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.12 initialized 'MyDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql:6.0.2' with options: MaxPoolSize=1024 ServerVersion 10.1.9-mariadb 
warn: Microsoft.EntityFrameworkCore.Query[10103]
      The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (54ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `e`.`Id`, `e`.`Enterprise_Code`
      FROM `Enterprise` AS `e`
      LIMIT 1
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (39ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `e`.`Id`, `e`.`Enterprise_Code`
      FROM `Enterprise` AS `e`
      LIMIT 1
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'TestDbApp.MyDbContext'.
      MySqlConnector.MySqlException (0x80004005): No database selected
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
         at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 127
```

### Further technical details

MySQL version: 10.1.9-mariadb
Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: 6.0.306

**Comment by wangharris** [comment]
Maybe a fault of Tencent Cloud.
