### ISSUE TITLE
It seems json array is not supported

### ISSUE THREAD

**Issue by bthulu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1798]
### Steps to reproduce
```
public class ProducingOrder {
    ...
    [Column(TypeName = "json")]
    public List<int> MergeLens { get; set; } = new();
}
```

```
    builder.Services.AddDbContext<AppDbContext>(option =>
    {
        var connectionString = builder.Configuration.GetConnectionString("App")!;
        option.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString),
            action => action.UseMicrosoftJson());
    });
```

```
await _appDbContext.ProducingOrders.Where(e => e.MergeLens.Contains(33)).FirstOrDefaultAsync();
```

### The issue
```
2023-10-13 10:02:47.2683|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.|System.InvalidOperationException: The LINQ expression 'DbSet<ProducingOrder>()
    .Where(p => p.MergeLens
        .Contains(33))' could not be translated. Additional information: Translation of method 'System.Linq.Enumerable.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at PMDCS.Controllers.CallPaperController.Test(Int32 platform) in C:\Users\ilala\code\PaperMiniloadDispatchingCommandSystem\PMDCS\Controllers\CallPaperController.cs:line 138
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

### Further technical details

MySQL version: 8.0.28
Operating system: win10
Pomelo.EntityFrameworkCore.MySql version:7.0.0
Microsoft.AspNetCore.App version:net7.0

Other details about my project setup:

**Comment by lauxjpn** [comment]
@bthulu Json arrays are supported, but you have to use `EF.Functions.JsonContains()` (different syntax) to check whether they contain a value or not.

For a list of supported Json extension methods, see [MySqlJsonDbFunctionsExtensions](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/main/src/EFCore.MySql/Extensions/MySqlJsonDbFunctionsExtensions.cs).

For a comprehensive JSON example that demonstrates different ways to query JSON entities, and also includes usage of `EF.Functions.JsonContains()`, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-725257107.

**Comment by lauxjpn** [comment]
@bthulu @lol768 @alexeygritsenko Is there anything that needs more clarifying, or can we close this issue?

**Comment by alexeygritsenko** [comment]
> Is there anything that needs more clarifying, or can we close this issue?

yes. only thing that confuses me is that instead of the usual EF syntax, we can use an extension. Of course, if you make it for yourself, you can suffer. But for a public library this looks like a crutch. Ideally, mark the model of JSON object with some attribute so that the provider can understand whether it should use sql or an extension internally

**Comment by lauxjpn** [comment]
> > Is there anything that needs more clarifying, or can we close this issue?
> 
> yes. only thing that confuses me is that instead of the usual EF syntax, we can use an extension. Of course, if you make it for yourself, you can suffer. But for a public library this looks like a crutch. Ideally, mark the model of JSON object with some attribute so that the provider can understand whether it should use sql or an extension internally

@alexeygritsenko For the differences between Pomelo's JSON support and the general EF Core 7 JSON support:

> (From https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1752#issuecomment-1505623488)
>
> Pomelo has extended JSON support for both, the Microsoft stack and the Newtonsoft stack. Because we already implemented JSON support a couple of years ago, it works a bit different than the simple JSON support now supported by EF Core.
> 
> For some (older) sample code, with lots of different ways to use JSON, see [#14 (comment)](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-725257107).
> 
> The basics steps are to reference either the `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft` or `Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft` NuGet package, call `.UseMicrosoftJson()` or `.UseNewtonsoftJson()` and set the column type to `json` in the model (e.g. by using `.HasColumnType("json")`) for all columns that you want to use with JSON.

> (From https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1752#issuecomment-1824149966)
>
> Yes, we currently don't support the `ToJson` syntax that EF Core 7 introduced.
> 
> However, we have been supporting JSON in a much more comprehensive way than `ToJson` years before that feature got finally introduced in EF Core. And we support not just the Microsoft stack, but also the Newtonsoft stack. You should have much more options and control with our implementation, than `ToJson`.
> 
> We will implement `ToJson` sometime in the near future for compatibility reasons though.

---

You can track the progress on `ToJson` support by subscribing to #1752.
