### ISSUE TITLE
Already an open DataReader associated with this Connection

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#18]
When I run the following query:

    var blog = db.Blogs.Include(c => c.Posts).Single(c => c.BlogId == blogId);

I get the following error:

    Connection id "0HKTC3BKS8GPL": An unhandled exception was thrown by the application.
    Pomelo.Data.MySql.MySqlException: There is already an open DataReader associated with this Connection which must be closed first.
    at Pomelo.Data.MySql.MySqlConnection.Throw(Exception ex)
    at Pomelo.Data.MySql.MySqlCommand.Throw(Exception ex)
    at Pomelo.Data.MySql.MySqlCommand.CheckState()
    at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
    at Pomelo.Data.MySql.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
    at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCollectionIterator.<GetRelatedValues>d__4.MoveNext()
    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.Include(QueryContext queryContext, Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager)
    at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()

Removing the .Include(c => c.Posts) portion of the query allows it to work, but doesn't include the posts.

Reading further into this, it seems that the Entity Framework may be expecting to use MultipleActiveResultSets, or MARS.  Is there some configuration I can provide to the MySQL connector to use MARS?

**Comment by matthewjcooper** [comment]
Getting the same issue with .Include queries.

**Comment by caleblloyd** [comment]
I've noticed that it is only affecting me on Has Many includes, when including a relation that is a list of objects.  Has One includes seem to work fine.

**Comment by Kagamine** [comment]
It seems that there is no way to enable MultipleActiveResultSets in MySQL, We should refactory the ADO Layer.

**Comment by Kagamine** [comment]
Hi @caleblloyd, @matthewjcooper, just try this:

If you have already installed the pomelo packages: `Pomelo.Data.MySql` and `Pomelo.EntityFrameworkCore.MySql`, please remove them and restore again(`dotnet restore --no-cache`).  The packages are located in `C:\Users\YOURNAME\.nuget\packages`.

I suppose it is works now by a quick fix. 

If the error still occurs, please reopen this issue.

**Comment by Kagamine** [comment]
@applenele Can you add this into unit tests?

**Comment by tuanbs** [comment]
I've been struggling with this issue. Thinking of moving back to SQL Server :(

**Comment by mguinness** [comment]
@tuanbs Are you using the latest MyGet version?  It appears that the MultipleActiveResultSets workaround is [no longer needed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/418#issuecomment-339184998).

**Comment by tuanbs** [comment]
@mguinness Yes, I still have this issue after trying get the latest MyGet version. Hope it could be fixed soon. Thanks.

**Comment by yukozh** [comment]
@tuanbs Could you please open a new issue and provide us the full repro?

**Comment by tuanbs** [comment]
@yukozh I'll open it soon and reproduce the issue. Actually, I've just tried to run my project with SQL Server and got issue of 
```
System.InvalidCastException: Unable to cast object of type 'System.Data.ProviderBase.DbConnectionClosedConnecting'
 to type 'System.Data.SqlClient.SqlInternalConnectionTds'.
```
So I guess my code's structure is to blame. I'm going to rewrite it and try with both SQL Server and MySql to see if it can be fixed. Thanks.
