### ISSUE TITLE
Adding DisableBackslashEscaping prevents database from being created

### ISSUE THREAD

**Issue by JurrianKole** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1803]
### Steps to reproduce

**To help with the reproduction path, you can use the following instructions.**

Spin up an instance of MariaDB, I am using version `11.3.0`. Use whatever credentials you want, I simply used the default `root` credentials.

Create a .NET 6 (haven't tried .NET 7) console application, I called mine `DisableBackslashEscaping`.

Add your `DbContext`, note the `DisableBackslashEscaping()`.

```csharp
public class MyTestDbContext : DbContext
{
    public DbSet<MyTestEntity> MyTestEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        const string TestConnectionString = "Server=localhost;port=3306;User Id=root;Password=root;Database=mydatabase";

        optionsBuilder
            .UseMySql(
                TestConnectionString,
                ServerVersion.AutoDetect(TestConnectionString),
                o =>
                {
                    o.DisableBackslashEscaping(); // Including this setting results in a database which cannot be created
                    o.EnableRetryOnFailure();
                    o.SchemaBehavior(MySqlSchemaBehavior.Ignore);
                });
    }
}
```

Add this basic entity.

```csharp
public class MyTestEntity
{
    [Key]
    public int Id { get; set; }
    
    public string FooBar { get; set; }
}

```

Create a migration.

`ef migrations add --project DisableBackslashEscaping\DisableBackslashEscaping.csproj --startup-project DisableBackslashEscaping\DisableBackslashEscaping.csproj --context DisableBackslashEscaping.MyTestDbContext --configuration Debug Initial --output-dir Migrations`

In `Program.cs`, ask the database context to migrate.

```csharp
var myDatabaseContext = new MyTestDbContext();

myDatabaseContext.Database.Migrate();
```

### The issue

EF's `Migrate` contract states

> Applies any pending migrations for the context to the database. **Will create the database if it does not already exist.**

The database, however, is not being created when `DisableBackslashEscaping` is present in the `DbContext.OnConfiguring` override.

```
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unknown database 'mydatabase'
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 568
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, Object[] parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlInterpolated(DatabaseFacade databaseFacade, FormattableString sql)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.AddSqlMode(String mode)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Program.<Main>$(String[] args) in C:\foobar\DisableBackslashEscaping\Program.cs:line 9
```

### Further technical details

MariaDB version: 11.3.0
Operating system: Windows 11
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
EF Core Design, Relational and Tools packages: 7.0.12
.NET version: .NET 6

**Comment by lauxjpn** [comment]
@JurrianKole Thank you for reporting this issue! We fixed it in #1862 and will will backport it to `8.0.2`.
