### ISSUE TITLE
InvalidOperationException: Read past end of buffer

### ISSUE THREAD

**Issue by Germs2004** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1812]
### Steps to reproduce
I upgraded to the new 8.0.0-beta.2, and my program crashes when it runs this EF query:

`var thisFails = db.TaskItems.Where(x => !string.IsNullOrWhiteSpace(x.TagString)).Select(x => new TaskItem() { TeamId = x.TeamId, Tag = x.TagString }).Distinct().OrderBy(x => x.Tag).ToList();`

Slightly modified code works without errors:
```
var thisSucceeds1 = db.TaskItems.Select(x => new TaskItem() { TeamId = x.TeamId, Tag = x.TagString }).Distinct().OrderBy(x => x.Tag).ToList();
var thisSucceeds2 = db.TaskItems.Where(x => !string.IsNullOrWhiteSpace(x.TagString)).Select(x => new TaskItem() { TeamId = x.TeamId, Tag = x.TagString }).OrderBy(x => x.Tag).ToList();
var thisSucceeds3 = db.TaskItems.Where(x => !string.IsNullOrWhiteSpace(x.TagString)).Select(x => new TaskItem() { TeamId = x.TeamId, Tag = x.TagString }).Distinct().ToList();
```

Here's a small solution that reproduces the issue:
[BugRepro2.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/13401978/BugRepro2.zip)

### The issue
```
MySqlConnector.MySqlException (0x80004005): Failed to read the result set.
 ---> System.InvalidOperationException: Read past end of buffer.
   at MySqlConnector.Protocol.Serialization.ByteArrayReader.VerifyRead(Int32 length) in /_/src/MySqlConnector/Protocol/Serialization/ByteArrayReader.cs:line 178
   at MySqlConnector.Protocol.Serialization.ByteArrayReader.ReadByte() in /_/src/MySqlConnector/Protocol/Serialization/ByteArrayReader.cs:line 32
   at MySqlConnector.Protocol.Payloads.ColumnCountPayload.Create(ReadOnlySpan`1 span, Boolean supportsOptionalMetadata) in /_/src/MySqlConnector/Protocol/Payloads/ColumnCountPayload.cs:line 24
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 112
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 290
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BugRepro2.Program.Main() in D:\Backup\Programming\BugRepro2\BugRepro2\Program.cs:line 11
```

### Further technical details

MySQL version: 10.11.5-MariaDB-log
Pomelo.EntityFrameworkCore.MySql version: 8.0.0-beta.2 (I had the same problem with 8.0.0-silver.1.ci.20231118200130)
.NET version: 8.0.0

Thank you for your hard work on this.  We all really appreciate it.

**Comment by lauxjpn** [comment]
I am unable to reproduce this issue with the following code that runs without throwing an exception:

<details>
<summary>Program.cs</summary>

```csharp
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

[Table("TaskItems")]
public class TaskItem
{
    [Key]
    public int TaskId { get; set; }

    public int TeamId { get; set; }
    public string TagString { get; set; } = string.Empty;
    public string Tag { get; set; } = string.Empty;
}

public class Context : DbContext
{
    public DbSet<TaskItem> TaskItems { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1812;charset=latin1";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasCharSet("latin1");

        modelBuilder.Entity<TaskItem>(entity =>
        {
            entity.HasData(
                new TaskItem
                {
                    TaskId = 1,
                    TeamId = 42,
                    TagString = "Needs answer",
                    Tag = "needs-answer"
                },
                new TaskItem
                {
                    TaskId = 2,
                    TeamId = 42,
                    TagString = "Needs answer",
                    Tag = "needs-answer"
                });
        });
    }
}

internal static class Program
{
    private static void Main()
    {
        using (var creationContext = new Context())
        {
            creationContext.Database.EnsureDeleted();
            creationContext.Database.EnsureCreated();
            
            using var connection = creationContext.Database.GetDbConnection();
            connection.Open();
            
            using var command = connection.CreateCommand();
            command.CommandText = "SELECT @@version;";
            
            var serverTypeAndVersion = (string)command.ExecuteScalar();
            Trace.Assert(serverTypeAndVersion.StartsWith("10.11.5-mariadb", StringComparison.OrdinalIgnoreCase));
        }

        using (Context context = new())
        {
            var query = context.TaskItems
                .Where(x => !string.IsNullOrWhiteSpace(x.TagString))
                .Select(x => new TaskItem { TeamId = x.TeamId, Tag = x.TagString })
                .Distinct()
                .OrderBy(x => x.Tag)
                .ToList();
            
            Trace.Assert(query.Count == 1);
            Trace.Assert(query.Single().TeamId == 42);
            Trace.Assert(query.Single().Tag == "Needs answer");
        }
    }
}
```

</details>
<details>
<summary>Output (SQL)</summary>

```log
warn: 19.11.2023 12:17:05.336 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 19.11.2023 12:17:05.853 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1812` CHARACTER SET latin1;
info: 19.11.2023 12:17:05.972 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET latin1;
info: 19.11.2023 12:17:05.983 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `TaskItems` (
          `TaskId` int NOT NULL AUTO_INCREMENT,
          `TeamId` int NOT NULL,
          `TagString` longtext CHARACTER SET latin1 NULL,
          `Tag` longtext CHARACTER SET latin1 NULL,
          CONSTRAINT `PK_TaskItems` PRIMARY KEY (`TaskId`)
      ) CHARACTER SET=latin1;
info: 19.11.2023 12:17:05.987 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `TaskItems` (`TaskId`, `Tag`, `TagString`, `TeamId`)
      VALUES (1, 'needs-answer', 'Needs answer', 42),
      (2, 'needs-answer', 'Needs answer', 42);
info: 19.11.2023 12:17:06.307 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `t0`.`TeamId`, `t0`.`Tag`
      FROM (
          SELECT DISTINCT `t`.`TeamId`, `t`.`TagString` AS `Tag`
          FROM `TaskItems` AS `t`
          WHERE `t`.`TagString` IS NOT NULL AND ((TRIM(`t`.`TagString`) <> '') OR `t`.`TagString` IS NULL)
      ) AS `t0`
      ORDER BY `t0`.`Tag`
```

</details>

So either the repro is not correct, or we need better table data.

@Germs2004 Please take my sample code and alter it until it reproduces the issue.

**Comment by Germs2004** [comment]
Your code is much cleaner, thanks.  It runs without errors, but it did delete my database since I didn't proof read it before running.  I restored from backup and reran my original BugRepro2 code, and now, it too works without errors.  Maybe there was a corrupt file in my database folder or something yesterday that restoring from backup fixed, but I can't reproduce the exception now.  I'll close this ticket.  Sorry for the false alarm.
