### ISSUE TITLE
`ROW_COUNT()` returns unexpected value when updating entity using AWS RDS Aurora (MySQL) Proxy endpoint

### ISSUE THREAD

**Issue by ggever** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1822]
### Steps to reproduce
Using the RDS Proxy endpoint instead of normal endpoint of Aurora Mysql in the connection string;
Here is my connection string format:
Server=RDS Proxy endpoint;port=3306;user=XXX;password=YYY;database=zzz;AllowLoadLocalInfile=True;IgnoreCommandTransaction=true

### The issue
I have the same problem with this persion on stackoverflow.
https://stackoverflow.com/questions/76722340/aws-rds-proxy-incompatible-with-entity-framework-core.

I just make a simple update on a Record.

```
Unexpected Error : Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at TEST.Services.Implements.API08DataService.CancelPointTransaction(APFC8063CancelPointTransactionRequest req, CancellationToken ct, DatabaseContext mysqlContext, RedshiftContext redshiftContext, List`1 customerInfoList) in /src/TEST.Services/Implements/API08DataService.cs:line 1958
   at TEST.Services.Implements.API09DataService.<>c__DisplayClass23_1.<<UpdatePrivilegeExpiry>b__7>d.MoveNext() in /src/TEST.Services/Implements/API09DataService.cs:line 2228 Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at TEST.Services.Implements.API08DataService.CancelTransaction(APFC8063CancelTransactionRequest req, CancellationToken ct, DatabaseContext mysqlContext, RedshiftContext redshiftContext, List`1 customerInfoList) in /src/TEST.Services/Implements/API08DataService.cs:line 1958
   at TEST.Services.Implements.API09DataService.<>c__DisplayClass23_1.<<UpdatePrivilegeExpiry>b__7>d.MoveNext() in /src/TEST.Services/Implements/API09DataService.cs:line 2228
```

### Further technical details

MySQL version: Aurora Mysql 3.04.0 ( compatible with MySQL 8.0.28)
Operating system: Docker FROM mcr.microsoft.com/dotnet/sdk:7.0
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
Microsoft.AspNetCore.App version: 

Other details about my project setup:

**Comment by lauxjpn** [comment]
I am able to reproduce the issue with the following code:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class IceCream
{
    public int IceCreamId { get; set; }
    public string Name { get; set; }
}

public class Context : DbContext
{
    public DbSet<IceCream> IceCreams { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            // var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1822";
            var connectionString = "server=proxy-0123456789012-database-1.proxy-abcdefghijkl.eu-central-1.rds.amazonaws.com;port=3306;user=admin;password=;database=Issue1822;SslMode=None";
            var serverVersion = ServerVersion.Parse("8.0.28-mysql");

            optionsBuilder
                .UseMySql(
                    connectionString,
                    serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IceCream>(
            entity =>
            {
                entity.HasData(
                    new IceCream
                    {
                        IceCreamId = 1,
                        Name = "Vanilla",
                    });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using (var context = new Context())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using (var context = new Context())
        {
            var iceCream = context.IceCreams
                .Single();

            iceCream.Name = "Chocolate";

            context.SaveChanges();
        }
        
        using (var context = new Context())
        {
            var iceCreams = context.IceCreams
                .ToList();

            Trace.Assert(iceCreams.Count == 1);
            Trace.Assert(iceCreams[0].Name == "Chocolate");
        }
    }
}
```

</details>

<details>
<summary>Output (SQL)</summary>

```sql
warn: 03/02/2024 14:21:58.500 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 03/02/2024 14:21:58.898 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (48ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP DATABASE `Issue1822`;
info: 03/02/2024 14:21:58.977 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1822`;
info: 03/02/2024 14:21:59.143 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET utf8mb4;
info: 03/02/2024 14:21:59.172 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (29ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `IceCreams` (
          `IceCreamId` int NOT NULL AUTO_INCREMENT,
          `Name` longtext CHARACTER SET utf8mb4 NULL,
          CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
      ) CHARACTER SET=utf8mb4;
info: 03/02/2024 14:21:59.184 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
      VALUES (1, 'Vanilla');
info: 03/02/2024 14:21:59.458 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `i`.`IceCreamId`, `i`.`Name`
      FROM `IceCreams` AS `i`
      LIMIT 2
info: 03/02/2024 14:21:59.593 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (46ms) [Parameters=[@p1='1', @p0='Chocolate' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SET AUTOCOMMIT = 1;
      UPDATE `IceCreams` SET `Name` = @p0
      WHERE `IceCreamId` = @p1;
      SELECT ROW_COUNT();
Unhandled exception. Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at IssueConsoleTemplate.Program.Main() in D:\Sources\PomeloIssues\Issue1822\IssueConsoleTemplate\Program.cs:line 100
Aborted (core dumped)
```

</details>

I then tinkered around with a couple of command variations, without EF Core:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using MySqlConnector;

namespace IssueConsoleTemplate;

internal static class Program
{
    private static readonly string[] CommandTexts =
    [
"""
DROP DATABASE IF EXISTS `Issue1822`;
""",
"""
CREATE DATABASE `Issue1822`;
""",
"""
USE `Issue1822`;
""",
"""
ALTER DATABASE CHARACTER SET utf8mb4;
""",
"""
CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET=utf8mb4;
""",
"""
INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');
""",
    ];
    
    private static void Main()
    {
        // var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1822";
        var connectionString = "server=proxy-0123456789012-database-1.proxy-abcdefghijkl.eu-central-1.rds.amazonaws.com;port=3306;user=admin;password=issue1822asdfqwer;database=Issue1822;SslMode=None";

        using var connection = new MySqlConnection(connectionString);
        connection.Open();
        
        using var command = connection.CreateCommand();
        
        foreach (var commandText in CommandTexts)
        {
            command.CommandText = commandText;
            
            Console.WriteLine(command.CommandText);
            Console.WriteLine();
            
            command.ExecuteNonQuery();
        }

        // select
        command.CommandText = """
SELECT `i`.`IceCreamId`, `i`.`Name`
FROM `IceCreams` AS `i`
LIMIT 2
""";

        Console.WriteLine(command.CommandText);
        Console.WriteLine();

        using (var reader = command.ExecuteReader())
        {
            while (reader.Read()) { }
        }

        //
        // Fails:
        //
        
        command.CommandText = """
SET AUTOCOMMIT = 1;
UPDATE `IceCreams` SET `Name` = 'Chocolate'
WHERE `IceCreamId` = 1;
SELECT ROW_COUNT();
""";

        //
        // Succeeds:
        //
        
//         command.CommandText = """
// SET AUTOCOMMIT = 1;
// UPDATE `IceCreams` SET `Name` = 'Chocolate'
// WHERE `IceCreamId` = 1;
// """;
//
//         command.ExecuteNonQuery();
//
//         Console.WriteLine(command.CommandText);
//         Console.WriteLine();
//
//         command.CommandText = "SELECT ROW_COUNT();";

        Console.WriteLine(command.CommandText);
        Console.WriteLine();

        var rowCount = (long)command.ExecuteScalar();

        Console.WriteLine($"rowCount = {rowCount}");
        Console.WriteLine();
        
        Trace.Assert(rowCount == 1);
    }
}
```

</details>

Sending `SELECT ROW_COUNT();` in the same command as the `UPDATE` statement results in `-1` being returned for `ROW_COUNT()`:

<details>
<summary>Output (SQL)</summary>

```sql
DROP DATABASE IF EXISTS `Issue1822`;

CREATE DATABASE `Issue1822`;

USE `Issue1822`;

ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET=utf8mb4;

INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');

SELECT `i`.`IceCreamId`, `i`.`Name`
FROM `IceCreams` AS `i`
LIMIT 2

SET AUTOCOMMIT = 1;
UPDATE `IceCreams` SET `Name` = 'Chocolate'
WHERE `IceCreamId` = 1;
SELECT ROW_COUNT();

rowCount = -1

Process terminated. Assertion Failed
   at IssueConsoleTemplate.Program.Main() in D:\Sources\PomeloIssues\Issue1822_01\IssueConsoleTemplate\Program.cs:line 105

Aborted (core dumped)
```

</details>

However, when splitting the `UPDATE` from the `SELECT ROW_COUNT();` into different commands, the return value for `ROW_COUNT()` is correct:

<details>
<summary>Output (SQL)</summary>

```sql
DROP DATABASE IF EXISTS `Issue1822`;

CREATE DATABASE `Issue1822`;

USE `Issue1822`;

ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET=utf8mb4;

INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');

SELECT `i`.`IceCreamId`, `i`.`Name`
FROM `IceCreams` AS `i`
LIMIT 2

SET AUTOCOMMIT = 1;
UPDATE `IceCreams` SET `Name` = 'Chocolate'
WHERE `IceCreamId` = 1;

SELECT ROW_COUNT();

rowCount = 1
```

</details>

AFAICS, this seems to be a bug in the AWS RDS Aurora (MySQL) proxy implementation.

Looks to me like they are parsing the SQL queries and stopping after the `UPDATE` statement, assuming that there will not be a return value - or something similar.

/cc @bgrainger

**Comment by lauxjpn** [comment]
@ggever As a workaround, you could split the command with a `DbCommandInterceptor` in a way, that works with the AWS RDS Aurora (MySQL) proxy:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Data.Common;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class IceCream
{
    public int IceCreamId { get; set; }
    public string Name { get; set; }
}

public class RowCountSplittingCommandInterceptor : DbCommandInterceptor
{
    private const string SelectRowCountStatement = "SELECT ROW_COUNT();";

    public override InterceptionResult<DbDataReader> ReaderExecuting(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<DbDataReader> result)
    {
        var commandText = command.CommandText.TrimEnd();
        
        if (commandText.EndsWith(SelectRowCountStatement))
        {
            command.CommandText = commandText[..^SelectRowCountStatement.Length];
            command.ExecuteNonQuery();

            command.Parameters.Clear();
            command.CommandText = SelectRowCountStatement;
        }

        return base.ReaderExecuting(command, eventData, result);
    }

    public override async ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<DbDataReader> result,
        CancellationToken cancellationToken = new CancellationToken())
    {
        var commandText = command.CommandText.TrimEnd();
        
        if (commandText.EndsWith(SelectRowCountStatement))
        {
            command.CommandText = commandText[..^SelectRowCountStatement.Length];
            await command.ExecuteNonQueryAsync(cancellationToken);

            command.Parameters.Clear();
            command.CommandText = SelectRowCountStatement;
        }

        return await base.ReaderExecutingAsync(command, eventData, result, cancellationToken);
    }

    public override InterceptionResult<object> ScalarExecuting(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<object> result)
    {
        var commandText = command.CommandText.TrimEnd();
        
        if (commandText.EndsWith(SelectRowCountStatement))
        {
            command.CommandText = commandText[..^SelectRowCountStatement.Length];
            command.ExecuteNonQuery();

            command.Parameters.Clear();
            command.CommandText = SelectRowCountStatement;
        }
        
        return base.ScalarExecuting(command, eventData, result);
    }

    public override async ValueTask<InterceptionResult<object>> ScalarExecutingAsync(
        DbCommand command,
        CommandEventData eventData,
        InterceptionResult<object> result,
        CancellationToken cancellationToken = new CancellationToken())
    {
        var commandText = command.CommandText.TrimEnd();
        
        if (commandText.EndsWith(SelectRowCountStatement))
        {
            command.CommandText = commandText[..^SelectRowCountStatement.Length];
            await command.ExecuteNonQueryAsync(cancellationToken);

            command.Parameters.Clear();
            command.CommandText = SelectRowCountStatement;
        }
        
        return await base.ScalarExecutingAsync(command, eventData, result, cancellationToken);
    }
}

public class Context : DbContext
{
    public DbSet<IceCream> IceCreams { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            // var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1822_02";
            var connectionString = "server=proxy-0123456789012-database-1.proxy-abcdefghijkl.eu-central-1.rds.amazonaws.com;port=3306;user=admin;password=;database=Issue1822_02;SslMode=None";
            var serverVersion = ServerVersion.Parse("8.0.28-mysql");

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .AddInterceptors(new RowCountSplittingCommandInterceptor()) // <-- add interceptor
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IceCream>(
            entity =>
            {
                entity.HasData(
                    new IceCream
                    {
                        IceCreamId = 1,
                        Name = "Vanilla",
                    });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using (var context = new Context())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();
        }

        using (var context = new Context())
        {
            var iceCream = context.IceCreams
                .Single();

            iceCream.Name = "Chocolate";

            context.SaveChanges();
        }
        
        using (var context = new Context())
        {
            var iceCreams = context.IceCreams
                .ToList();

            Trace.Assert(iceCreams.Count == 1);
            Trace.Assert(iceCreams[0].Name == "Chocolate");
        }
    }
}
```

</details>

<details>
<summary>Output (SQL)</summary>

```sql
warn: 03/02/2024 16:10:38.970 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure)
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 03/02/2024 16:10:39.376 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1822_02`;
info: 03/02/2024 16:10:39.561 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET utf8mb4;
info: 03/02/2024 16:10:39.608 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (47ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `IceCreams` (
          `IceCreamId` int NOT NULL AUTO_INCREMENT,
          `Name` longtext CHARACTER SET utf8mb4 NULL,
          CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
      ) CHARACTER SET=utf8mb4;
info: 03/02/2024 16:10:39.617 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
      VALUES (1, 'Vanilla');
info: 03/02/2024 16:10:39.905 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `i`.`IceCreamId`, `i`.`Name`
      FROM `IceCreams` AS `i`
      LIMIT 2
info: 03/02/2024 16:10:40.042 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (47ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT ROW_COUNT();
info: 03/02/2024 16:10:40.116 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `i`.`IceCreamId`, `i`.`Name`
      FROM `IceCreams` AS `i`
```

</details>

**Comment by bgrainger** [comment]
Yes, from a SQL/MySqlConnector perspective, I wouldn't expect any difference between issuing one `COM_QUERY` packet with

```sql
SET AUTOCOMMIT = 1;
UPDATE `IceCreams` SET `Name` = 'Chocolate'
WHERE `IceCreamId` = 1;
SELECT ROW_COUNT();
```

and two separate packets with 

```sql
SET AUTOCOMMIT = 1;
UPDATE `IceCreams` SET `Name` = 'Chocolate'
WHERE `IceCreamId` = 1;
```

```sql
SELECT ROW_COUNT();
```

This seems like a bug in the RDS Proxy and should be reported to Amazon. (Otherwise, manually splitting up the queries seems like the best workaround.)

**Comment by sergiuciudin** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html

`Using the ROW_COUNT() function in a multi-statement query is not supported.`
