### ISSUE TITLE
Nested Query failed: Load previous row

### ISSUE THREAD

**Issue by Int32Overflow** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1829]
### Steps to reproduce
This one will work:
```csharp
var query = transactionStorage
      .Where(w => w.DateCreated >= startTime && w.DateCreated <= endTime)
      .Select(s => new
       {
           Current = s,
           Previous = transactionStorage.Where(w => w.LogId == s.LogId).OrderByDescending(o => o.DateCreated).First(),
        });
var windowResults = await query.ToListAsync();
```

But if I add `w.DateCreated < s.DateCreated` to the inner query, an exception occures.

```csharp
var query = transactionStorage
      .Where(w => w.DateCreated >= startTime && w.DateCreated <= endTime)
      .Select(s => new
       {
           Current = s,
           Previous = transactionStorage.Where(w => w.LogId == s.LogId && w.DateCreated < s.DateCreated).OrderByDescending(o => o.DateCreated).First(),
        });
var windowResults = await query.ToListAsync();
```

### The issue
The previous row should also be read for a data record. I have built a nested query for this purpose.

**Exception message:** 
```
The LINQ expression 'OUTER APPLY 
(
    SELECT TOP(1) t1.fk_accdoc, t1.ts_created, t1.errorText, t1.FailReason, t1.fk_errorcatalog, t1.fk_FailReason, t1.fk_Knowlage, t1.Info, t1.KnowlageText, t1.fk_log, t1.note, t1.OK, t1.Prio, t1.fk_Station, t1.fk_user_created, t1.fk_workstation
    FROM tbltransaction AS t1
    WHERE (t1.fk_log == t.fk_log) && (t1.ts_created < t.ts_created)
    ORDER BY t1.ts_created DESC
) AS t0' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```
**Stack trace:**
```
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckTranslated(Expression translated, Expression original)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckSupport(Expression expression, Boolean isSupported)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitOuterApply(OuterApplyExpression outerApplyExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitSelect(SelectExpression selectExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlParameterBasedSqlProcessor.Optimize(Expression queryExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__22.MoveNext()
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__67`1.MoveNext()
   at ......
```

### Further technical details

MySQL version: `10.11.2-MariaDB`
Operating system: `Windows 10 Professional x64`
Pomelo.EntityFrameworkCore.MySql version: `7.0.0` AND `8.0.0-beta.2`
Microsoft.AspNetCore.App version: 8

**Comment by lauxjpn** [comment]
MariaDB doesn't have support for `LATERAL` joins yet (which is the equivalent of SQL Server's `OUTER APPLY`). MySQL `8.0.14+` has though.

That means that more complex queries with subqueries might not be supported using MariaDB.

Your initial query works, because it only uses one condition in its `Where()` condition. That allows EF Core to translate the query without using a `LATERAL/OUTER APPLY` statement and instead using a `ROW_NUMBER() OVER(PARTITION BY ...)` statement, which is supported by MariaDB:

```sql
SELECT `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`, `t1`.`TransactionId`, `t1`.`DateCreated`, `t1`.`LogId`
FROM `Transactions` AS `t`
LEFT JOIN (
    SELECT `t0`.`TransactionId`, `t0`.`DateCreated`, `t0`.`LogId`
    FROM (
        SELECT `t2`.`TransactionId`, `t2`.`DateCreated`, `t2`.`LogId`, ROW_NUMBER() OVER(PARTITION BY `t2`.`LogId` ORDER BY `t2`.`DateCreated` DESC) AS `row`
        FROM `Transactions` AS `t2`
    ) AS `t0`
    WHERE `t0`.`row` <= 1
) AS `t1` ON `t`.`LogId` = `t1`.`LogId`
WHERE (`t`.`DateCreated` >= @__startTime_0) AND (`t`.`DateCreated` <= @__endTime_1)
```

The moment you introduce the second condition, the `ROW_NUMBER() OVER(PARTITION BY ...)` statement would not work anymore and EF Core switches to using a `LATERAL/OUTER APPLY` statement (which MariaDB doesn't support yet):

```sql
SELECT `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`, `t0`.`TransactionId`, `t0`.`DateCreated`, `t0`.`LogId`
FROM `tbltransaction` AS `t`
LEFT JOIN LATERAL (
    SELECT `t1`.`TransactionId`, `t1`.`DateCreated`, `t1`.`LogId`
    FROM `tbltransaction` AS `t1`
    WHERE (`t1`.`LogId` = `t`.`LogId`) AND (`t1`.`DateCreated` < `t`.`DateCreated`)
    ORDER BY `t1`.`DateCreated` DESC
    LIMIT 1
) AS `t0` ON TRUE
WHERE (`t`.`DateCreated` >= @__startTime_0) AND (`t`.`DateCreated` <= @__endTime_1)
```

So the current behavior is expected.

---

You can write the query without the need for a `LATERAL` clause, by using joins instead (though it get a bit more complex):

```c#
var windowResults = transactionStorage
    .Where(t => t.DateCreated >= startTime && t.DateCreated <= endTime)
    .GroupJoin(
        transactionStorage
            .Join(
                transactionStorage,
                o => o.LogId,
                i => i.LogId,
                (o, i) => new { Current = o, Ancestor = i })
            .Where(j => j.Current.DateCreated >= startTime && j.Current.DateCreated <= endTime &&
                        j.Ancestor.DateCreated < j.Current.DateCreated),
        o => o,
        j => j.Current,
        (o, jj) => new { Current = o, Ancestors = jj })
    .SelectMany(
        j => j.Ancestors.DefaultIfEmpty(),
        (j, a) => new { j.Current, Ancestor = a.Ancestor })
    .GroupBy(j => j.Current)
    .Select(
        g => new
        {
            Current = g.Key,
            Previous = g
                .Select(j => j.Ancestor)
                .OrderByDescending(a => a.DateCreated)
                .FirstOrDefault()
        })
    .ToList(); 
```

This query will execute successfully using MariaDB and should give you the same result as your initial query:

```sql
SELECT `t3`.`TransactionId`, `t3`.`DateCreated`, `t3`.`LogId`, `t4`.`TransactionId0`, `t4`.`DateCreated0`, `t4`.`LogId0`
FROM (
    SELECT `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`
    FROM `tbltransaction` AS `t`
    LEFT JOIN (
        SELECT `t0`.`TransactionId`, `t0`.`DateCreated`, `t0`.`LogId`, `t2`.`TransactionId` AS `TransactionId0`, `t2`.`DateCreated` AS `DateCreated0`, `t2`.`LogId` AS `LogId0`
        FROM `tbltransaction` AS `t0`
        INNER JOIN `tbltransaction` AS `t2` ON `t0`.`LogId` = `t2`.`LogId`
        WHERE ((`t0`.`DateCreated` >= @__startTime_0) AND (`t0`.`DateCreated` <= @__endTime_1)) AND (`t2`.`DateCreated` < `t0`.`DateCreated`)
    ) AS `t1` ON `t`.`TransactionId` = `t1`.`TransactionId`
    WHERE (`t`.`DateCreated` >= @__startTime_0) AND (`t`.`DateCreated` <= @__endTime_1)
    GROUP BY `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`
) AS `t3`
LEFT JOIN (
    SELECT `t5`.`TransactionId0`, `t5`.`DateCreated0`, `t5`.`LogId0`, `t5`.`TransactionId`, `t5`.`DateCreated`, `t5`.`LogId`
    FROM (
        SELECT `t7`.`TransactionId0`, `t7`.`DateCreated0`, `t7`.`LogId0`, `t6`.`TransactionId`, `t6`.`DateCreated`, `t6`.`LogId`, ROW_NUMBER() OVER(PARTITION BY `t6`.`TransactionId`, `t6`.`DateCreated`, `t6`.`LogId` ORDER BY `t7`.`DateCreated0` DESC) AS `row`
        FROM `tbltransaction` AS `t6`
        LEFT JOIN (
            SELECT `t8`.`TransactionId`, `t9`.`TransactionId` AS `TransactionId0`, `t9`.`DateCreated` AS `DateCreated0`, `t9`.`LogId` AS `LogId0`
            FROM `tbltransaction` AS `t8`
            INNER JOIN `tbltransaction` AS `t9` ON `t8`.`LogId` = `t9`.`LogId`
            WHERE ((`t8`.`DateCreated` >= @__startTime_0) AND (`t8`.`DateCreated` <= @__endTime_1)) AND (`t9`.`DateCreated` < `t8`.`DateCreated`)
        ) AS `t7` ON `t6`.`TransactionId` = `t7`.`TransactionId`
        WHERE (`t6`.`DateCreated` >= @__startTime_0) AND (`t6`.`DateCreated` <= @__endTime_1)
    ) AS `t5`
    WHERE `t5`.`row` <= 1
) AS `t4` ON ((`t3`.`TransactionId` = `t4`.`TransactionId`) AND (`t3`.`DateCreated` = `t4`.`DateCreated`)) AND (`t3`.`LogId` = `t4`.`LogId`)
```

I used the following simple console sample program to test this:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class Transaction
{
    public int TransactionId { get; set; }
    public DateTime DateCreated { get; set; }
    public int LogId { get; set; }
}

public class Context : DbContext
{
    public DbSet<Transaction> Transactions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1829";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(
                    connectionString,
                    serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.ToTable("tbltransaction");
            
            entity.HasData(
                new Transaction
                {
                    TransactionId = 1,
                    DateCreated = new DateTime(2024, 2, 27, 12, 0, 0),
                    LogId = 101,
                },
                new Transaction
                {
                    TransactionId = 2,
                    DateCreated = new DateTime(2024, 2, 27, 15, 5, 0),
                    LogId = 102,
                },
                new Transaction
                {
                    TransactionId = 3,
                    DateCreated = new DateTime(2024, 2, 27, 18, 10, 0),
                    LogId = 101,
                });
        });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();

        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var transactionStorage = context.Transactions;
        var startTime = new DateTime(2024, 2, 27);
        var endTime = new DateTime(2024, 2, 28).AddTicks(-1);

        //
        // Fails using MariaDB:
        //

        Exception exceptionThrown = null;

        try
        {
            var failingWindowResults = transactionStorage
                .Where(w => w.DateCreated >= startTime &&
                            w.DateCreated <= endTime)
                .Select(
                    s => new
                    {
                        Current = s,
                        Previous = transactionStorage
                            .Where(w => w.LogId == s.LogId &&
                                        w.DateCreated < s.DateCreated)
                            .OrderByDescending(o => o.DateCreated)
                            .FirstOrDefault(),
                    })
                .ToList();
        }
        catch (Exception e)
        {
            exceptionThrown = e;
        }
        
        Trace.Assert(exceptionThrown is InvalidOperationException);
        Trace.Assert(exceptionThrown.Message.Contains("OUTER APPLY"));

        //
        // Works with MariaDB using complex joins:
        //

        var windowResults = transactionStorage
            .Where(t => t.DateCreated >= startTime && t.DateCreated <= endTime)
            .GroupJoin(
                transactionStorage
                    .Join(
                        transactionStorage,
                        o => o.LogId,
                        i => i.LogId,
                        (o, i) => new { Current = o, Ancestor = i })
                    .Where(j => j.Current.DateCreated >= startTime && j.Current.DateCreated <= endTime &&
                                j.Ancestor.DateCreated < j.Current.DateCreated),
                o => o,
                j => j.Current,
                (o, jj) => new { Current = o, Ancestors = jj })
            .SelectMany(
                j => j.Ancestors.DefaultIfEmpty(),
                (j, a) => new { j.Current, Ancestor = a.Ancestor })
            .GroupBy(j => j.Current)
            .Select(
                g => new
                {
                    Current = g.Key,
                    Previous = g
                        .Select(j => j.Ancestor)
                        .OrderByDescending(a => a.DateCreated)
                        .FirstOrDefault()
                })
            .ToList(); 

        // Make the result order deterministic for the following asserts.
        windowResults = windowResults
            .OrderBy(w => w.Current.TransactionId)
            .ToList();
        
        Trace.Assert(windowResults.Count == 3);
        
        Trace.Assert(windowResults[0].Current.TransactionId == 1);
        Trace.Assert(windowResults[0].Previous is null);
        
        Trace.Assert(windowResults[1].Current.TransactionId == 2);
        Trace.Assert(windowResults[1].Previous is null);
        
        Trace.Assert(windowResults[2].Current.TransactionId == 3);
        Trace.Assert(windowResults[2].Previous.TransactionId == 1);
    }
}
```

</details>

<details>
<summary>Output (SQL)</summary>

```sql
warn: 29.02.2024 22:28:27.217 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 29.02.2024 22:28:27.567 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (19ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                
      DROP DATABASE `Issue1829`;                                                                                        
info: 29.02.2024 22:28:27.777 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                 
      CREATE DATABASE `Issue1829`;                                                                                      
info: 29.02.2024 22:28:27.902 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                 
      ALTER DATABASE CHARACTER SET utf8mb4;                                                                             
info: 29.02.2024 22:28:27.917 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                
      CREATE TABLE `tbltransaction` (                                                                                   
          `TransactionId` int NOT NULL AUTO_INCREMENT,                                                                  
          `DateCreated` datetime(6) NOT NULL,
          `LogId` int NOT NULL,
          CONSTRAINT `PK_tbltransaction` PRIMARY KEY (`TransactionId`)
      ) CHARACTER SET=utf8mb4;
info: 29.02.2024 22:28:27.919 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `tbltransaction` (`TransactionId`, `DateCreated`, `LogId`)
      VALUES (1, TIMESTAMP '2024-02-27 12:00:00', 101),
      (2, TIMESTAMP '2024-02-27 15:05:00', 102),
      (3, TIMESTAMP '2024-02-27 18:10:00', 101);
fail: 29.02.2024 22:28:28.325 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'IssueConsoleTemplate.Context'.
      System.InvalidOperationException: The LINQ expression 'OUTER APPLY 
      (
          SELECT TOP(1) t1.TransactionId, t1.DateCreated, t1.LogId
          FROM tbltransaction AS t1
          WHERE (t1.LogId == t.LogId) && (t1.DateCreated < t.DateCreated)
          ORDER BY t1.DateCreated DESC
      ) AS t0' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckTranslated(Expression translated, Expression original) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 155
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.CheckSupport(Expression expression, Boolean isSupported) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 145
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitOuterApply(OuterApplyExpression outerApplyExpression) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 60
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 41
         at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitSelect(SelectExpression selectExpression) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 118
         at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlCompatibilityExpressionVisitor.VisitExtension(Expression extensionExpression) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\ExpressionVisitors\Internal\MySqlCompatibilityExpressionVisitor.cs:line 47
         at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlParameterBasedSqlProcessor.Optimize(Expression queryExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Query\Internal\MySqlParameterBasedSqlProcessor.cs:line 59
         at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters) in D:\Sources\EFCore-8.0\src\EFCore.Relational\Query\Internal\RelationalCommandCache.cs:line 71
         at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext) in D:\Sources\EFCore-8.0\src\EFCore.Relational\Extensions\Internal\RelationCommandCacheExtensions.cs:line 27
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator) in D:\Sources\EFCore-8.0\src\EFCore.Relational\Query\Internal\SingleQueryingEnumerable.cs:line 237
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator) in D:\Sources\EFCore-8.0\src\EFCore.Relational\Query\Internal\SingleQueryingEnumerable.cs:line 168
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in D:\Sources\Pomelo.EFCore.MySql-8.0\src\EFCore.MySql\Storage\Internal\MySqlExecutionStrategy.cs:line 48
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in D:\Sources\EFCore-8.0\src\EFCore.Relational\Query\Internal\SingleQueryingEnumerable.cs:line 158
info: 29.02.2024 22:28:28.495 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (29ms) [Parameters=[@__startTime_0='2024-02-27T00:00:00.0000000' (DbType = DateTime), @__endTime_1='2024-02-27T23:59:59.9999999' (DbType = DateTime)], CommandType='Text', CommandTimeout='30']
      SELECT `t3`.`TransactionId`, `t3`.`DateCreated`, `t3`.`LogId`, `t4`.`TransactionId0`, `t4`.`DateCreated0`, `t4`.`LogId0`
      FROM (
          SELECT `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`
          FROM `tbltransaction` AS `t`
          LEFT JOIN (
              SELECT `t0`.`TransactionId`, `t0`.`DateCreated`, `t0`.`LogId`, `t2`.`TransactionId` AS `TransactionId0`, `t2`.`DateCreated` AS `DateCreated0`, `t2`.`LogId` AS `LogId0`
              FROM `tbltransaction` AS `t0`
              INNER JOIN `tbltransaction` AS `t2` ON `t0`.`LogId` = `t2`.`LogId`
              WHERE ((`t0`.`DateCreated` >= @__startTime_0) AND (`t0`.`DateCreated` <= @__endTime_1)) AND (`t2`.`DateCreated` < `t0`.`DateCreated`)
          ) AS `t1` ON `t`.`TransactionId` = `t1`.`TransactionId`
          WHERE (`t`.`DateCreated` >= @__startTime_0) AND (`t`.`DateCreated` <= @__endTime_1)
          GROUP BY `t`.`TransactionId`, `t`.`DateCreated`, `t`.`LogId`
      ) AS `t3`
      LEFT JOIN (
          SELECT `t5`.`TransactionId0`, `t5`.`DateCreated0`, `t5`.`LogId0`, `t5`.`TransactionId`, `t5`.`DateCreated`, `t5`.`LogId`
          FROM (
              SELECT `t7`.`TransactionId0`, `t7`.`DateCreated0`, `t7`.`LogId0`, `t6`.`TransactionId`, `t6`.`DateCreated`, `t6`.`LogId`, ROW_NUMBER() OVER(PARTITION BY `t6`.`TransactionId`, `t6`.`DateCreated`, `t6`.`LogId` ORDER BY `t7`.`DateCreated0` DESC) AS `row`
              FROM `tbltransaction` AS `t6`
              LEFT JOIN (
                  SELECT `t8`.`TransactionId`, `t9`.`TransactionId` AS `TransactionId0`, `t9`.`DateCreated` AS `DateCreated0`, `t9`.`LogId` AS `LogId0`
                  FROM `tbltransaction` AS `t8`
                  INNER JOIN `tbltransaction` AS `t9` ON `t8`.`LogId` = `t9`.`LogId`
                  WHERE ((`t8`.`DateCreated` >= @__startTime_0) AND (`t8`.`DateCreated` <= @__endTime_1)) AND (`t9`.`DateCreated` < `t8`.`DateCreated`)
              ) AS `t7` ON `t6`.`TransactionId` = `t7`.`TransactionId`
              WHERE (`t6`.`DateCreated` >= @__startTime_0) AND (`t6`.`DateCreated` <= @__endTime_1)
          ) AS `t5`
          WHERE `t5`.`row` <= 1
      ) AS `t4` ON ((`t3`.`TransactionId` = `t4`.`TransactionId`) AND (`t3`.`DateCreated` = `t4`.`DateCreated`)) AND (`t3`.`LogId` = `t4`.`LogId`)
```

</details>
