### ISSUE TITLE
Migration : Bad Generated SQL when adding byte[] Property to Model

### ISSUE THREAD

**Issue by timosperisen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#185]
### Issue
Generated SQL code is faulty when a byte[] property is added to an existing class of a project that has had its initial migrations run.

### Steps to reproduce
1. extract attached archive [DbIssue.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/733701/DbIssue.zip)

2. modify database connection string in Models.cs
3. run `dotnet restore`
4. run `dotnet ef migrations add Initial`
5. run `dotnet ef database update`
this should work just fine...
6. add following Property to Models.cs in the Entity class:
```csharp 
    [Required, MinLength(4), MaxLength(16)]
    public byte[]  IPAddressBytes { get; set; }
```
7. run `dotnet ef migrations add 2nd`
8. run `dotnet ef database update`
9. fail

If you remove the property, remove all migrations and add the property first, then run the initial migration it will work properly. 

Adding it later seems to be the issue. The code generator then adds the DEFAULT 0x; instead just DEFAULT 0;

here's the result of `dotnet ef migrations script`:
```sql
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);
CREATE TABLE `Entities` (
    `Id` int AUTO_INCREMENT NOT NULL,
    CONSTRAINT `PK_Entities` PRIMARY KEY (`Id`)
);
INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170126205834_initial', '1.1.0-rtm-22752');
ALTER TABLE `Entities` ADD `IPAddressBytes` varbinary(16) NOT NULL DEFAULT 0x;
INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170126210017_2nd', '1.1.0-rtm-22752');
```

I checked the current source code and this seems to be done in the file
`MySqlMigrationsSqlGenerator.cs` . There's four places where DEFAULT gets appended (search for `.Append(" DEFAULT ")`. It then calls 
```csharp
.Append.(SqlGenerationHelper.GenerateLiteral(...))
```
also I noticed in the file `MySqlSqlGenerator.cs`
In there is a method 
```csharp
protected override void GenerateLiteralValue(StringBuilder builder, byte[] value)
```
that contains the line
```csharp
builder.Append("0x");
```

Could that be the place where it happens? 

### Exception

Exception message:
```text
MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0x' at line 1`
Stack trace:
`MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0x' at line 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable``1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary``2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary``2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable``1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0x' at line 1
```

### Further technical details
 
MySQL version: 10.1.21-MariaDB , 64 bit
Operating system: Windows 10 , 64 bit
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

## Thanks

If you need further information just ask. Thanks!

**Comment by Kagamine** [comment]
Shipped in 1.1.1-prerelease-10016

**Comment by timosperisen** [comment]
Thanks for the quick fix!

It seemed to generate good SQL.

But I noticed something else.

When the property is there in the beginning (new test project using your new prerelease: [PropFromStart.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/735962/PropFromStart.zip) ) and we run
`dotnet ef migrations add init`
and then check the script with 
`dotnet ef migrations script`
the generated SQL looks like this:
```sql
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);
CREATE TABLE `Entities` (
    `Id` int AUTO_INCREMENT NOT NULL,
    `IPAddressBytes` varbinary(16) NOT NULL,
    CONSTRAINT `PK_Entities` PRIMARY KEY (`Id`)
);
INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170127180410_init', '1.1.0-rtm-22752');
```
As you can see there is no default value for that column.

So when we add it later after the first migration it also should not add a default value statement, right?

Thanks for your help in advance!

**Comment by Kagamine** [comment]
@timosperisen You didn't specified the default value of `IPAddressBytes`. See https://docs.microsoft.com/zh-cn/ef/core/modeling/relational/default-values
