### ISSUE TITLE
SetNull produces incorrect SQL

### ISSUE THREAD

**Issue by MeikelLP** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1942]
### Steps to reproduce

https://github.com/MeikelLP/quantum-core-x/pull/125/commits/ddeb283cdf2d896624fcf535a38d31b222321b3c

The repo should be fully functional without any extra setup required to reproduce this issue.

### The issue

I think `.OnDelete(DeleteBehavior.SetNull)` produces incorrect migrations for mysql. Postgresql (and Sqlite?) produce correct migrations. According to https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html it should be `SET DEFAULT` instead of `SET NULL` in sql. Correct me if I'm wrong - I'm a mysql noob

```
[00:53:03.749][ERR]Failed executing DbCommand (16,010ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `GuildMembers` (
    `GuildId` int unsigned NOT NULL,
    `PlayerId` int unsigned NOT NULL,
    `RankPosition` tinyint unsigned NOT NULL,
    `IsLeader` tinyint(1) NOT NULL,
    `SpentExperience` int unsigned NOT NULL,
    CONSTRAINT `PK_GuildMembers` PRIMARY KEY (`GuildId`, `PlayerId`),
    CONSTRAINT `FK_GuildMembers_GuildRanks_GuildId_RankPosition` FOREIGN KEY (`GuildId`, `RankPosition`) REFERENCES `GuildRanks` (`GuildId`, `Position`) ON DELETE CASCADE,
    CONSTRAINT `FK_GuildMembers_Guilds_GuildId` FOREIGN KEY (`GuildId`) REFERENCES `Guilds` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `FK_GuildMembers_Players_PlayerId` FOREIGN KEY (`PlayerId`) REFERENCES `Players` (`Id`) ON DELETE SET NULL
) CHARACTER SET=utf8mb4; 
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Can't create table `metin2`.`GuildMembers` (errno: 150 "Foreign key constraint is incorrectly formed")
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130

```

### Further technical details

MySQL version: mariadb:11.3
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 8.0.2
Microsoft.AspNetCore.App version: 8.0 (but a console app)

Other details about my project setup:

**Comment by MeikelLP** [comment]
Welp apparently this was a skill issue. I put it on the wrong relation...
