### ISSUE TITLE
HELP PLS RAGE MP ERROR

### ISSUE THREAD

**Issue by Criminal93** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1947]
Unable to cast object of type 'System.DBNull' to type 'System.String'.
[REALLIFE] System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at MySqlConnector.Core.Row.GetString(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 344
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 272
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(String name) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 273
   at ReallifeRP.LoadPlayerModule.LoadPlayer(Player p, String password) in C:\Users\clash\Desktop\ReallifeGanglifeBackend-main\ReallifeRemake\Core\Login\LoadPlayerModule.cs:line 186

**Comment by trejjam** [comment]
Hi,
This is not an issue tracker for MySqlConnector.
You/the program expects that one of the fields is strictly non-nullable. However, the database schema allows null in one of the fields.
Solution: 
1) update the program to work correctly with nullable value.
2) resolve the database schema issue by filling in the null value + updating the schema to be NOT NULL on the spoken column.

**Comment by Criminal93** [comment]
> Hi, This is not an issue tracker for MySqlConnector. You/the program expects that one of the fields is strictly non-nullable. However, the database schema allows null in one of the fields. Solution:
> 
> 1. update the program to work correctly with nullable value.
> 2. resolve the database schema issue by filling in the null value + updating the schema to be NOT NULL on the spoken column.

Yo, how do I fix this? I already asked ChatGPT, and he gave me some weird code that didn't work at all. Even though I wanted to try, can you please help me with that?

**Comment by lauxjpn** [comment]
@Criminal93 Please asks general development questions on a website like [StackOverflow](https://stackoverflow.com).

This our repository here is about an EF Core provider for MySQL/MariaDB databases.

Thanks!
