### ISSUE TITLE
Primitive collections error with 9.0.0-preview.2.efcore.9.0.0

### ISSUE THREAD

**Issue by Germs2004** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1960]
### Steps to reproduce
With .NET8, Microsoft.EntityFrameworkCore 8.0.11, and Pomelo.EntityFrameworkCore.MySql 8.0.2, the code below works fine.  If I upgrade to NET9, Microsoft.EntityFrameworkCore 9.0.0, and Pomelo.EntityFrameworkCore.MySql 9.0.0-preview.2.efcore.9.0.0, it throws an exception.

```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

namespace ConsoleApp1
{
    internal class Program
    {
        public class PizzaDb : DbContext
        {
            public PizzaDb() { }
            public PizzaDb(DbContextOptions options) : base(options) { }
            public DbSet<Pizza> Pizzas { get; set; } = null!;

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                string connectionString = "Server=localhost;Database=PizzaDatabase;User=pizza;Password=p1zz@;";
                optionsBuilder.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString));
            }
        }

        public class Pizza
        {
            public int Id { get; set; }
            public string? Name { get; set; }
            public bool IsYummy { get; set; }
            public string? Description { get; set; }
        }

        static void Main(string[] args)
        {
            using (PizzaDb db = new())
            {
                // create the database
                db.Database.EnsureCreated();
                db.Pizzas.RemoveRange(db.Pizzas);
                db.Pizzas.Add(new() { Id = 1, Name = "Cheese", IsYummy = false, Description = "for the kids" });
                db.Pizzas.Add(new() { Id = 2, Name = "Pepperoni", IsYummy = true, Description = "cheese & pep" });
                db.Pizzas.Add(new() { Id = 3, Name = "Hawaiian", IsYummy = false, Description = "pineapple, canadian bacon" });
                db.Pizzas.Add(new() { Id = 4, Name = "Supreme", IsYummy = true, Description = "cheese, pep, sausage, peppers" });
                db.SaveChanges();

                List<int> yummyPizzaIds = db.Pizzas.Where(p => p.IsYummy).Select(p => p.Id).ToList();

                // this line throws the error:
                List<Pizza> yummyPizzas = db.Pizzas.Where(p => yummyPizzaIds.Contains(p.Id)).ToList();
            }

        }
    }
}
```

The above code gets error:
```
System.InvalidOperationException: 'The LINQ expression '@__yummyPizzaIds_0' could not be translated. Additional information: Primitive collections support has not been enabled. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

   at Pomelo.EntityFrameworkCore.MySql.Query.Internal.MySqlQueryableMethodTranslatingExpressionVisitor.TranslatePrimitiveCollection(SqlExpression sqlExpression, IProperty property, String tableAlias)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateParameterQueryRoot(ParameterQueryRootExpression parameterQueryRootExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.<VisitMethodCall>g__TranslateAsSubquery|33_0(Expression expression, <>c__DisplayClass33_0& )
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitor.CallBaseVisitMethodCall(MethodCallExpression methodCallExpression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateExpression(Expression expression, Boolean applyDefaultTypeMapping)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateLambdaExpression(ShapedQueryExpression shapedQueryExpression, LambdaExpression lambdaExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateWhere(ShapedQueryExpression source, LambdaExpression predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass11_0`1.<ExecuteCore>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\git\ConsoleApp1\ConsoleApp1\Program.cs:line 44
```

Next, I changed the code to enable Primitives:
`optionsBuilder.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString), x => x.EnablePrimitiveCollectionsSupport());`

But then I get a different error:
```
System.InvalidOperationException: 'Expression '@__yummyPizzaIds_0' in the SQL tree does not have a type mapping assigned.'

   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionTranslators.Internal.MySqlJsonTableExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.<VisitChildren>g__VisitList|117_0[T](List`1 list, Boolean inPlace, Boolean& changed, <>c__DisplayClass117_0& )
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.InExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalTypeMappingPostprocessor.Process(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.ProcessTypeMappings(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryTranslationPostprocessor.Process(Expression query)
   at Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlQueryTranslationPostprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass11_0`1.<ExecuteCore>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\git\ConsoleApp1\ConsoleApp1\Program.cs:line 44
```

### The issue
Updating to EF 9 and Pomelo 9 Preview changes something that throws an exception with previously working code.  Is this just a breaking change with EF9, or is it something Pomelo can fix for us?

Thank you.

### Further technical details

MySQL version: MariaDB 11.5.1
Operating system: Windows 11 Pro 24H2
Pomelo.EntityFrameworkCore.MySql version: 9.0.0-preview.2.efcore.9.0.0
Microsoft.AspNetCore.App version: 9.0.0?

**Comment by lauxjpn** [comment]
To make your query work with EF Core 9, you either need to wrap your collection in a `EF.Constant()` expression inside your query, or use the `TranslateParameterizedCollectionsToConstants()` option call:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

#nullable enable

namespace IssueConsoleTemplate;

public class Pizza
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public bool IsYummy { get; set; }
    public string? Description { get; set; }
}

public class Context : DbContext
{
    public DbSet<Pizza> Pizzas { get; set; } = null!;

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;Database=Issue1956";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(
                    connectionString,
                    serverVersion/*,
                    options => options.TranslateParameterizedCollectionsToConstants()*/) // <-- uses EF.Constant() for all collections
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Pizza>(
            entity =>
            {
                entity.HasData(
                    new Pizza { Id = 1, Name = "Cheese", IsYummy = false, Description = "for the kids" },
                    new Pizza { Id = 2, Name = "Pepperoni", IsYummy = true, Description = "cheese & pep" },
                    new Pizza { Id = 3, Name = "Hawaiian", IsYummy = false, Description = "pineapple, canadian bacon" },
                    new Pizza { Id = 4, Name = "Supreme", IsYummy = true, Description = "cheese, pep, sausage, peppers" });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();

        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var yummyPizzaIds = context.Pizzas
            .Where(p => p.IsYummy)
            .Select(p => p.Id)
            .ToList();

        List<Pizza> yummyPizzas;
        
        try
        {
            yummyPizzas = context.Pizzas
                .Where(p => yummyPizzaIds.Contains(p.Id))
                .OrderBy(p => p.Id)
                .ToList();
        }
        catch (InvalidOperationException)
        {
        }

        yummyPizzas = context.Pizzas
            .Where(p => EF.Constant(yummyPizzaIds).Contains(p.Id)) // <-- wraps collection in EF.Constant() call
            .OrderBy(p => p.Id)
            .ToList();

        Trace.Assert(yummyPizzas.Count == 2);
        Trace.Assert(yummyPizzas[0].Id == 2);
        Trace.Assert(yummyPizzas[1].Id == 4);
    }
}
```

</details>

<details>
<summary>Output (SQL)</summary>

```sql
warn: 13.12.2024 18:09:33.999 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.

info: 13.12.2024 18:09:34.402 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      DROP DATABASE `Issue1956`;

info: 13.12.2024 18:09:37.893 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1956`;

info: 13.12.2024 18:09:38.257 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET utf8mb4;

info: 13.12.2024 18:09:38.271 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Pizzas` (
          `Id` int NOT NULL AUTO_INCREMENT,
          `Name` longtext CHARACTER SET utf8mb4 NULL,
          `IsYummy` tinyint(1) NOT NULL,
          `Description` longtext CHARACTER SET utf8mb4 NULL,
          CONSTRAINT `PK_Pizzas` PRIMARY KEY (`Id`)
      ) CHARACTER SET=utf8mb4;

info: 13.12.2024 18:09:38.276 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Pizzas` (`Id`, `Description`, `IsYummy`, `Name`)
      VALUES (1, 'for the kids', FALSE, 'Cheese'),
      (2, 'cheese & pep', TRUE, 'Pepperoni'),
      (3, 'pineapple, canadian bacon', FALSE, 'Hawaiian'),
      (4, 'cheese, pep, sausage, peppers', TRUE, 'Supreme');

info: 13.12.2024 18:09:38.638 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `p`.`Id`
      FROM `Pizzas` AS `p`
      WHERE `p`.`IsYummy`

info: 13.12.2024 18:09:38.823 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `p`.`Id`, `p`.`Description`, `p`.`IsYummy`, `p`.`Name`
      FROM `Pizzas` AS `p`
      WHERE `p`.`Id` IN (2, 4)
      ORDER BY `p`.`Id`
```

</details>

This issue is further discussed in #1955.

**Comment by madloff** [comment]
Thanks for the example! This issue has been a severe breaking change once we went from .NET7 to .NET9.

**Comment by sfmskywalker** [comment]
Many thanks for the explanation and example! This fixes a host of issues with Elsa Workflows' MySQL support.

**Comment by lauxjpn** [comment]
The `TranslateParameterizedCollectionsToConstants()` option will become the default from `9.0.0-preview.3.efcore.9.0.0` onwards (see #1955).
