### ISSUE TITLE
The 'DbSet<>' uses 'join' and  'into', throws the exception

### ISSUE THREAD

**Issue by Lissbrict** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#198]
### Steps to reproduce

my `dbcontext ` included tow entity `TestClass1` , `TestClass2`
 
- TestClass1
  - id(long)
- TestClass2
  - id(long)
  - Class1Id (long)
``` 
DbSet<TestClass1> _class1Set = DbContext.Set<TestClass1>();
DbSet<TestClass2>  _class2Set = DbContext.Set<TestClass2>();



var query = from testClass1 in _class1Set
                   join testClass2 in _class2Set on testClass1.Id equals testClass2.Class1Id  into list
                  select new { testClass1, list};
```
> Call  `query.ToList()` can get the data normally
But call  `query.Count()` throw Exception

Exception:

```
Expression of type 'System.Collections.Generic.IEnumerable`1[System.Collections.Generic.IEnumerable`1[<>f__AnonymousType0`2[FeiniuBus.Linq.Dynamic.Test.Lib.TestClass1,System.Collections.Generic.IEnumerable`1[FeiniuBus.Linq.Dynamic.Test.Lib.TestClass2]]]]' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Int32]'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
```

### Further technical details

MySQL version: 5.6.23 (aws)
Operating system: win10 pro x64
Pomelo.EntityFrameworkCore.MySql version:1.1.1

- what is the problem?  thank you

**Comment by Lissbrict** [comment]
Calling `query.Any()` will have the same problem...

**Comment by mguinness** [comment]
I believe there is a known issue with GroupJoin in EF Core, see https://github.com/aspnet/EntityFramework/issues/7497.
