### ISSUE TITLE
Migrations with ulong autoincrement primary keys generate signed long keys in DB

### ISSUE THREAD

**Issue by james7132** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#201]
### Steps to reproduce
1. Try the following code: https://github.com/james7132/Hourai/blob/master/src/Model/Temp.cs
2. Use any LINQ query to try to query for elements. Like here: https://github.com/james7132/Hourai/blob/master/src/Admin/TempService.cs
Full Code: https://github.com/james7132/Hourai
### The issue
Exception:
```
Exception message: System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.UInt64'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.ConvertWithReflection[T](Int32 ordinal, InvalidCastException e)
   at Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryingEnumerable`1.MySqlEnumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()

```

### Further technical details

MySQL version: mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Operating system: Ubuntu 16.04 LTS
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by james7132** [comment]
Found the issue. Using a ulong autoincrement key generates a signed key via migrations, which results in a invalid cast when reading the data.

**Comment by mguinness** [comment]
@james7132 Just to clarify, you mean migrations created column type as bigint instead of bigint unsigned?

**Comment by james7132** [comment]
Yes, precisely that.

**Comment by caleblloyd** [comment]
I'm able to reproduce, I'll look into a fix
