### ISSUE TITLE
It causes a exception when i select NewValue = a Datetime + a TimeSpan

### ISSUE THREAD

**Issue by HongyanShen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#204]
Thew code as follows:

```
var result = await (from task in _dbContext.Set<BaseChildTask>().AsQueryable()
                                     join trip in _dbContext.Set<BaseTrip>().AsQueryable() on task.TripId equals trip.Id
                                     select new
                                     {
                                         task.BusId,
                                         StartTime = task.UseDate + trip.StartTime,
                                         EndTime = task.UseDate + trip.EndTime,
                                     }).ToListAsync();

```

**task.UseDate's type is DateTime,trip.StartTime's type is TimeSpan**

The version of Pomelo.EntityFrameworkCore.MySql:**1.1.0**

Exception Message:**Unable to cast object of type 'System.Decimal' to type 'System.DateTime'.**

The call stack: **at MySql.Data.MySqlClient.MySqlDataReader.GetDateTime(Int32 ordinal)
   at Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.GetDateTime(Int32 ordinal) in C:\Users\HongyanShen\Desktop\Pomelo.EntityFrameworkCore.MySql-1.1.0-rtm\src\Pomelo.EntityFrameworkCore.MySql\Storage\SynchronizedMySqlDataReader.cs:line 41
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.MySqlAsyncQueryingEnumerable`1.MySqlAsyncEnumerator.<MoveNext>d__5.MoveNext() in C:\Users\HongyanShen\Desktop\Pomelo.EntityFrameworkCore.MySql-1.1.0-rtm\src\Pomelo.EntityFrameworkCore.MySql\Query\Internal\MySqlAsyncQueryingEnumerable.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestPomelo.Program.<Foo>d__1.MoveNext() in C:\Users\HongyanShen\Desktop\Pomelo.EntityFrameworkCore.MySql-1.1.0-rtm\test\TestPomelo\Program.cs:line 213**

**Comment by caleblloyd** [comment]
Can you `SHOW CREATE TABLE` for all of the tables involved in your query.

Then turn logging for `Microsoft` to `Information` ([example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/appsettings.json#L7)) and post the generated queries here also.

**Comment by mguinness** [comment]
@HongyanShen An alternative to doing this calculation at the client, you can alternatively do this server side by using the DateAdd translator added in PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/164.

If the timespan is being stored as a numeric value, say number of seconds since midnight, then instead of:

`task.UseDate + trip.StartTime`

Use DateAdd translator that resolves to DATE_ADD(task.UseDate, INTERVAL trip.StartTime SECOND) in SQL:

`task.UseDate.AddSeconds(trip.StartTime)`

**Comment by HongyanShen** [comment]
@caleblloyd Thanks to @mguinness ,i resolved this probem by using Datetime's **Add** method instead of operator + between Datetime and TimeSpan.Here is the details of my problem.
Linq expression:
```
var tasks = await dbCxt.Set<Task>().Join(dbCxt.Set<Trip>(),
                t => t.TripId,
                t => t.Id,
                (task, trip) => new
                {
                    task.BusId,
                    task.Id,
                    StartTime = task.UseDate + trip.UseTime,
                    EndTime = task.UseDate + trip.EndTime,
                }
                ).ToListAsync();
```

Create table sql:
```
CREATE TABLE `task` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `BusId` bigint(20) NOT NULL,
  `TripId` bigint(20) NOT NULL,
  `UseDate` datetime(6) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `trip` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `EndTime` time(6) NOT NULL,
  `UseTime` time(6) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

```

Sql query generated by the linq expression:
```
SELECT `t`.`BusId`, `t`.`Id`, `t`.`UseDate` + `trip`.`UseTime`, `t`.`UseDate` + `trip`.`EndTime`
FROM `Task` AS `t`
INNER JOIN `Trip` AS `trip` ON `t`.`TripId` = `trip`.`Id`
```
