### ISSUE TITLE
Revisit Datetime Type Mapping for older MySQL versions

### ISSUE THREAD

**Issue by Nick-Lucas** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#210]
Please consider offering legacy support for MySQL 5.5, particularly in relation to `DateTime` and `DateTime(6)` as discussed in #145.

Many supported and widely used Linux distros (Ubuntu 14.04, Debian 8) still come with MySQL 5.5 in their repositories, which means that using Pomelo requires jumping through hoops to get up to a newer version.

This considered, the insistence on using `DateTime(6)` without an option for legacy support (prior to 5.6) seems to be a little premature, with how widely available MySQL 5.5 still is.

**Comment by caleblloyd** [comment]
I thought this was fixed when we introduced [MySqlScopedTypeMapper.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlScopedTypeMapper.cs)

Are you still hitting this with the latest `1.1.1-prerelease`?

**Comment by Nick-Lucas** [comment]
Oooh thanks, I didn't realise this was in the works!

So I've updated to the pre-release and now `.Database.EnsureDeleted` and `.Database.EnsureCreated` are both broken: 

Both return this error:
```
Message: MySql.Data.MySqlClient.
MySqlException : Unknown database 'name_of_my_database'

Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlConnectionSettings.<>c__DisplayClass3_0.<GetSettings>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlScopedTypeMapper.get_ConnectionSettings()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlScopedTypeMapper.MaybeConvertMapping(RelationalTypeMapping mapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapperExtensions.IsTypeMapped(IRelationalTypeMapper typeMapper, Type clrType)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_13(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at Tests.Integration.Pipelines.DbContexts.SalesDbContextFactory.Create(String dbmsName, DbContextFactoryOptions factoryOptions) in C:\Users\nicho\Local\Repositories\Pipelines\test\Tests.Integration.Pipelines\DbContexts\SalesDbContextFactory.cs:line 24
   at Tests.Integration.Pipelines.Providers.Sources.MySqlSourceTests..ctor() in C:\Users\nicho\Local\Repositories\Pipelines\test\Tests.Integration.Pipelines\Providers\Sources\MySqlSourceTests.cs:line 17
```

My use case here is for some integration tests, and I don't use migrations for this, so run each command in turn (Delete then Create) to refresh the database for each test class.

I just went through updating to MySQL 5.6 and the current stable release works great for this use case. I can create a separate issue for this if it's not already a known problem.

**Comment by Nick-Lucas** [comment]
More detail: If I create the database and JUST run `EnsureCreated` the test works fine, but then if I run `EnsureDeleted` I get the same error, even though I can see does exists

**Comment by caleblloyd** [comment]
I've written a test for `EnsureCreate` and `EnsureDelete` and I am unable to reproduce.  Make sure your MySQL user has appropriate permissions to create and drop databases:

![image](https://cloud.githubusercontent.com/assets/2414837/23835518/17a8b272-073f-11e7-83ca-d2bb308c2160.png)

I'm going to add a formal `EnsureCreate`, `EnsureDelete`, and `Migrate` test to the test suite.

**Comment by Nick-Lucas** [comment]
Interesting. So the MySql user is a super with full permissions, and the last stable release does work perfectly when I upgrade the server to 5.6. So it could either be the MySql 5.5 configuration, or an edge case regression with the ScopedTypeMapper and MySql 5.5.

I will have more of a dig into this on my side and report back this week

**Comment by caleblloyd** [comment]
Test for `dbContext.Database.Migrate`, `dbContext.Database.EnsureCreate` and `dbContext.Database.EnsureDelete` is here: [TestMigrateCommand.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Commands/TestMigrateCommand.cs)

I ran it against MySql 5.5 and 5.7 and everything passed.  Please open a new issue if you hit this again.
