### ISSUE TITLE
"Cannot access a disposed object. Object name: 'MySqlConnection'." when trying to persist 35 MB to MariaDb.

### ISSUE THREAD

**Issue by jp7677** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#242]
### Steps to reproduce
Please take a look at https://github.com/jp7677/hellocoreclr/tree/mariadb. When running the app I can reproduce the error by enter some text and press the "Say Hello" button.
Entity and dataservice are pretty straight forward (relevant parts):

```
 public class Greeting
 {
   public int GreetingId { get; set; }
   public byte[] SomeHugeFile { get; set; }
}

var somehugeFile = new byte[35* 1000 * 1000];
using(var db = dbContextFactory.CreateHelloWorldDbContext())
{
  db.Greetings.Add(new Greeting
  {
    Name = greeting,
    TimestampUtc = DateTime.Now.ToUniversalTime(),
    SomeHugeFile = somehugeFile
   });
  await db.SaveChangesAsync();
}

```
### The issue
I'm trying to save 35MB to the database in an ASP.Net Core request, unfortunately it ends with a ObjectDisposedException.

```
An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlConnection'.
   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed()
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlTransaction.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.EntityFrameworkCore.DbContext.Dispose()
   at HelloCoreClrApp.Data.DataService.<SaveGreetingAsync>d__5.MoveNext() in /home/jpeters/Develop/hellocoreclr/src/HelloCoreClrApp/Data/DataService.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HelloCoreClrApp.WebApi.Actions.SayHelloWorldAction.<SaveGreetingAsync>d__4.MoveNext() in /home/jpeters/Develop/hellocoreclr/src/HelloCoreClrApp/WebApi/Actions/SayHelloWorldAction.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HelloCoreClrApp.WebApi.Actions.SayHelloWorldAction.<ExecuteAsync>d__3.MoveNext() in /home/jpeters/Develop/hellocoreclr/src/HelloCoreClrApp/WebApi/Actions/SayHelloWorldAction.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HelloCoreClrApp.WebApi.HelloWorldController.<SayHelloWorldAsync>d__3.MoveNext() in /home/jpeters/Develop/hellocoreclr/src/HelloCoreClrApp/WebApi/HelloWorldController.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-03-31 11:17:22 +02:00|Debug|10|0HL3O2QSK80BB|Microsoft.AspNetCore.Server.Kestrel
```

### Further technical details

MySQL version: MariaDb 10.1.22-MariaDB-1~jessie - mariadb.org binary distribution
Operating system: Fedora 25/Docker
Pomelo.EntityFrameworkCore.MySql version:
PackageReference Include="MySqlConnector" Version="0.15.1"
PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.1-prerelease-10026"

**Comment by jp7677** [comment]
I'm seeing this exeception (sometimes) before the ObjectDisposedException:

```
Microsoft.EntityFrameworkCore.DbContext
    An exception occurred in the database while saving changes.

System.InvalidOperationException: MySqlSession is not connected.
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.TryAsync[TArg](Func`3 func, TArg arg, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.Serialization.MySqlSession.SendAsync(PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlTransaction.Dispose(Boolean disposing)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__35.MoveNext()
```

**Comment by jp7677** [comment]
ok, trying 15MB give me a much more useful exception:

```
Microsoft.EntityFrameworkCore.DbContext
    An exception occurred in the database while saving changes.

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: The
size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.<ExecuteAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__35.MoveNext()
```
I wonder if this should be the same exception when trying 35 MB.

**Comment by caleblloyd** [comment]
Whoa, 35MB is a lot to be putting into an RDBMS.

Regardless we should be returning the proper exceptions.  I wonder if MariaDB is just hanging up the connection after a certain amount of data to "save" itself, and that's why we're getting odd exceptions.

**Comment by bgrainger** [comment]
I'm guessing that [`max_allowed_packet`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet) on your server is set to 32MB (so a 35MB packet can't be sent at all, but a 15MB packet can be sent, but causes a different error in MySQL Server/MariaDB).

The workaround is to increase both the `max_allowed_packet` and [`innodb_log_file_size`](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_log_file_size) server variables.

**Comment by jp7677** [comment]
Hi @bgrainger, @caleblloyd,
Thanks for the info. Yeah, the 35MB is the reproduction scenario in my playground ;). I had hit the same ObjectDisposedException (without the "MySqlSession is not connected." up front) in a real project with just 7MB and was completely clueless.
Your explanation and solution sounds completely sane.
Thanks a lot for willing to raise a more descriptive Exception in that case.

**Comment by bgrainger** [comment]
[MySqlConnector 0.16.1](https://www.nuget.org/packages/MySqlConnector/0.16.1) will throw a more helpful exception message in this scenario. However, this is still a limit enforced by the server and there's no way inserting 35MB of data will succeed without increasing the server variables I mentioned earlier.

**Comment by jp7677** [comment]
Thanks a lot, unfortunately the exception is still the same on my machine after updating to:
<PackageReference Include="MySqlConnector" Version="0.16.1" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.1-prerelease-10027" /> 

15MB gives me:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.

Everything above 16MB (the default of max_allowed_packet in MariaDB according to the MariaDB docs)  gives me:  
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlConnection'.
   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed()
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()

With one of these exceptions directly before the ObjectDisposedException:
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
System.Net.Sockets.SocketException: Connection reset by peer
System.InvalidOperationException: MySqlSession is not connected.

Eventually a difference between MySql and MariaDB?

**Comment by Kagamine** [comment]
shipped in 10027

**Comment by jp7677** [comment]
@Kagamine, Sorry, I'm on 10027 (the xml tags didn't show up in my github response, I have remove the `<>`. now its there)

**Comment by bgrainger** [comment]
I think you might be running into the known issue I mentioned in the last paragraph at mysql-net/MySqlConnector#216.

Currently, once you exceed the `max_allowed_packet`, the server resets the connection and it's no longer usable. Oracle's connector works around this (for the most part, I believe) by not sending the packet if it thinks it will fail, which preserves the connection. 

I'm guessing that you might not have the ability to close the connection and open a new one. Unfortunately, I don't know yet what we can do to recover here, because we no longer have a connection to the DB server; it was forcibly closed.

I haven't tested the new code against MariaDB; it's possible it might behave differently (but that seems unlikely based on the exception messages you've posted above).

**Comment by bgrainger** [comment]
@caleblloyd if MySqlConnector was able to change `MySqlConnection.State` to `Closed` would Pomelo EF Core have better error handling?

**Comment by caleblloyd** [comment]
I'm not sure, I can try a patched build and see. Might take me a day or two before I have time.

**Comment by caleblloyd** [comment]
The `ObjectDisposedException` is happening because we are in a transaction.  When the connection is disposed in the Using block, it tries to execute a `ROLLBACK` on the uncommitted transaction, but since the connection has been reset it hits the `ObjectDisposedException`

I'm able to recreate by adding a transaction in the MySqlConnector tests, should be a pretty easy fix.

**Comment by jp7677** [comment]
I couldn't resist to test with MySqlConnector 16.2. The ObjectDisposedException is indeed gone, but now I'm getting a SocketException. This is far closer to the truth, but would be cool to get the MySqlException with "Error submitting {0}MB packet; ensure 'max_allowed_packet' is greater than {0}MB" message.

**Comment by caleblloyd** [comment]
I've opened #247, my local copy of your test with that commit now produces:

```
Failed   Pomelo.EntityFrameworkCore.MySql.PerfTests.Tests.Models.ExpressionTest.LargeObject
Error Message:
 System.AggregateException : One or more errors occurred. (An error occurred while updating the entries. See the inner exception for details.) (MySqlSession is not connected.)
---- Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
-------- MySql.Data.MySqlClient.MySqlException : Error submitting 14MB packet; ensure 'max_allowed_packet' is greater than 14MB.
------------ System.Net.Sockets.SocketException : Broken pipe
---- System.InvalidOperationException : MySqlSession is not connected.
```

**Comment by jp7677** [comment]
Yeah, cool! Thanks a lot.
Its a pleasure to use this project (and the underlying MySqlConnector of course ) and to work with you!
