### ISSUE TITLE
Wrong MySQL syntax is generated for the Migration's down method when setting up UNIQUE constraint with HasAlternateKey

### ISSUE THREAD

**Issue by Bogatinovski** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#252]
### Steps to reproduce

1. Create basic User entity:
`public class User
{
      public int ID { get; set; }
      public string Email { get; set; }
}`

2. In the DbContext class inside OnModelCreating method configure the Email property to be unique:
`modelBuilder.Entity<User>().HasAlternateKey(c => c.Email).HasName("AlternateKey_Email");`

3. Create the migration file: 
`dotnet ef migrations add "UserEmailUniqueConstraint"`
In the generated migration's Down method this is the relevant code that generates the sql that will drop the constriant: `migrationBuilder.DropUniqueConstraint(name: "AlternateKey_Email", table: "Users");`

4. Update the database. It should run smoothly:
`dotnet ef database update`
 
5. Rollback the database. It should fail with MySQL server throwing error for bad syntax:
`dotnet ef database update 0`

6. Output the generated sql code to file to see the generated sql syntax for rolling back the db:
dotnet ef migrations script '20170407093714_UserEmailUniqueConstraint' '0' -o 'db-log.sql' -v

7. From the output file we can find the relevant code that drops the unique constraint:
`ALTER TABLE `Users` DROP CONSTRAINT `AlternateKey_Email`;`

8. Run the generated command directly from some MySql server manager (ex: phpmyadmin) to verify that the command fails. This sql command is invalid for MySQL server and that is why we get the error. 

9. The correct sql command should be `ALTER TABLE `Users` DROP INDEX `AlternateKey_Email`;`
Run this correct command from the MySql server manager to verify that the command works.

### The issue
When I run `dotnet ef database update 0` MySQL server throws the following exception: 

`Exception Message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near AlternateKey_Email`' at line 1.

Stack Trace
MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server v
ersion for the right syntax to use near 'CONSTRAINT `AlternateKey_Email`' at line 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeM
ethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDic
tionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRe
lationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`

### Further technical details

MySQL version: 5.7.14 - MySQL Community Server (GPL)
Operating system: Windows 10 Pro x 64
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10021

### Workaround
To avoid getting this sql syntax error I used a different method of defining unique constraint for my property:
`modelBuilder.Entity<User>().HasIndex(p => p.Email).IsUnique(true);`

**Comment by Kagamine** [comment]
MySql does not support AK. Please use .HasIndes().IsUnique()

**Comment by jp7677** [comment]
Would it be possible to raise a NotSupportedException in this case somewhere?
