### ISSUE TITLE
Table already exists

### ISSUE THREAD

**Issue by GuerrillaCoder** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#256]
### Steps to reproduce
I upgraded from 1.1.0 to 1.1.1.  I added a migration that added a new entity.  After I ran update-database it gives me an error that my enquiries table already exists (not for new entity, for an entity that has already been created fine before update).  The migration does not change this table.  I am not sure why it is failing because this table exists.  Something must be out of sync due to upgrade maybe?

### The issue
I cannot update database because of the already existing table.

```
PM> update-database
MySql.Data.MySqlClient.MySqlException: Table 'enquiries' already exists
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Table 'enquiries' already exists
```

### Further technical details

MySQL version:  10.1.21-MariaDB
Operating system:  win10
Pomelo.EntityFrameworkCore.MySql version: 1.1.1

**Comment by mguinness** [comment]
Is it possible that the __EFMigrationsHistory table is missing/empty?  Maybe try `dotnet ef migrations script` to see what DDL is being generated.

**Comment by Kagamine** [comment]
Therr were many breaking changes after 1.1.0. Maybe you have to fix this manually.

**Comment by caleblloyd** [comment]
This would be difficult for us to track down and could be a one-off problem with a migration.  It could even be related to upstream EF.

My recommendation is also to manually inspect the migration that has been created and adapt it so that it applies the proper configuration.  It's always a good idea to review migrations before applying anyways to make sure that EF has detected your intent.

**Comment by blackbird91** [comment]
I have the same problem and I think that the issue is related to the fact that the migration is automatically commited to database after running the "add-migration" command without updating the "EFMigrationHistory" table. When you try to run the "update-database" command you will have the error that you've mentioned above because the table actually really exists in the database

**Comment by huxaiphaer** [comment]
@caleblloyd , what if I deleted all my previous migrations ?
