### ISSUE TITLE
"There is already an open DataReader associated with this Connection..." on .Include()

### ISSUE THREAD

**Issue by ChristianHaase** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#264]
### The issue
I'm trying to load multiple pieces of data, and my second piece of data is dependent on the first piece of data. Basically I don't know whether I need to load the second piece of data, before I retrieved the first piece of data.

Here's an example:

```
// First piece of data
var frontPageSettings = _context.Settings.FirstOrDefault(x => x.Key == Constants.SettingsKeys.FrontPageSettings.ToString());
if (frontPageSettings != null && frontPageSettings.ShowFeaturedThreads)
{
    var threads = _context.Threads.Include(x => x.UserProfile).Where(x => x.IsFeatured).OrderByDescending(x => x.FeatureDate).Take(3).ToList();
}
```
If I remove the `.Include(x=> x.UserProfile)` I'm not getting any exceptions, so I believe that's the source of the problem.

This creates the following exception:
```
Exception message: There is already an open DataReader associated with this Connection which must be closed first.
Stack trace:
   at MySql.Data.MySqlClient.MySqlCommand.VerifyValid()
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlTransaction.Dispose(Boolean disposing)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalTransaction.Dispose()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.System.IDisposable.Dispose()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OurGhostsOfWar.Controllers.HomeController.Index()
```

### Further technical details
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10017

Other details about my project setup:
I'm using MAriaDB instead of MySQL, but that's just a simple fork of MySQL. Shouldn't cause any problems problems, and haven't the during the last year I've been working with MariaDB and the Pomelo.EntityFrameworkCore.MySql package provider

**Comment by caleblloyd** [comment]
Can you upgrade to the latest `1.1.2-*` release and try again? Many changes have been made.

**Comment by ChristianHaase** [comment]
Yes, I'll try and then post my progress here.

**Comment by ChristianHaase** [comment]
I can't seem to find the 1.1.2-* version on nuget? How do I add this again?

**Comment by caleblloyd** [comment]
https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.2-preview-10038

**Comment by ChristianHaase** [comment]
Alright got it working, but it doesn't seem to change anything. I'm still getting the same error.

**Comment by caleblloyd** [comment]
You are likely running two queries over the same context before the first one has completed. I'd recommend enabling logging and investigating if that is the cause:

Change `Microsoft` log level to `Information` ([example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/appsettings.json#L7))

If you don't already have this somewhere, here's some examples:

- [Read a JSON object into a configuration object](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppConfig.cs#L17-L31).
- [Add logging to MVC app in Startup.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Startup.cs#L59)
- [Add logging to DBContext if using simple console app with no Startup.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L63)

This will print all SQL statements that are getting executed.

If you still have issues after that could you please post a full recreate. The model and controller in a gist would be great.

**Comment by ChristianHaase** [comment]
**Found my issue.**

I'm not sure why it's giving me the exception: `There is already an open DataReader associated with this Connection which must be closed first.`, when the actual problem is an `InvalidCastException`.

I had a datatype of `BLOB` in my DB, but in my class i defined the property as a string. It tried to cast a byte[] into a string, hence the invalid cast exception.

Thank you for you help anyways, at least I got my package updated 👍 
I hope I didn't take to much of your time ;)

**Comment by caleblloyd** [comment]
I'll look into the incorrect exception.  It comes because the reader hasn't been used due to the first exception, then the transaction getting closed throws the DataReader exception. We need to make sure the first exception gets through though.
