### ISSUE TITLE
DateTimeOffset using Sql Server Specific Fluent Api Configuration

### ISSUE THREAD

**Issue by AndyC5** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#274]
**Issue**
The issue appears to be because of the Fluent API mapping for the property. I am working on a system which will end up supporting both Microsoft Sql Server and MySql. The mapping for the property looks like this:

```
builder.Entity<Blog>()
           .Property(t => t.CreatedOn)
           .IsRequired()
           .ForSqlServerHasDefaultValue(DateTimeOffset.MinValue);
```

Right now I am using Database.EnsureCreated(); to create the database for development. When targeting the MySql provider, the database is generated with the default value for the CreatedOn field with CURRENT_TIMESTAMP(6). If I remove .ForSqlServerHasDefaultValue(DateTimeOffset.MinValue); from the mapping, then it will leave the default value blank. My understanding of how this works, is that the MySql provider would ignore that part of the configuration for the property since it is specifically for Sql Server.

When looking into this issue, I discovered that trying to use .HasDefaultValue(DateTimeOffset.MinValue) threw the following error:

**StackTrace:**
{MySql.Data.MySqlClient.MySqlException: Incorrect datetime value: '0001-01-01 00:00:00.0000000+00:00' for column 'CreatedOn' at row 1
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at EFCore.Data.ApplicationDbContext..ctor(DbContextOptions`1 options)

MySQL version: 5.7
Operating system: Windows 10 64-bit
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by bgrainger** [comment]
From [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/datetime.html):

> The `DATE` type is used for values with a date part but no time part. MySQL retrieves and displays `DATE` values in `'YYYY-MM-DD'` format. The supported range is `'1000-01-01'` to `'9999-12-31'`.
> 
> The `DATETIME` type is used for values that contain both date and time parts. MySQL retrieves and displays `DATETIME` values in `'YYYY-MM-DD HH:MM:SS'` format. The supported range is `'1000-01-01 00:00:00'` to `'9999-12-31 23:59:59'`.

`DateTimeOffset.MinValue` is out-of-range of MySQL's limits.

I don't know if the right answer here is to fix MySqlConnector's mapping of out-of-range `DateTimeOffset` values (map them to what?) or for the database client to use valid (for MySQL) data, e.g., `.HasDefaultValue(new DateTimeOffset(new DateTime(1000, 1, 1), TimeSpan.Zero)`.

(Note also that MySQL can't really support the `DateTimeOffset` data type, because it cannot represent the time zone. All `DateTimeOffset` values stored in the database will be converted to UTC and the TZ will be lost. I think you'd have to manually map it on to separate "datetime" and "offset" columns if you needed to roundtrip the original value. I'm not sure if there's a more "natural" way to do that in EF Core.)

**Comment by bgrainger** [comment]
Well, despite what the documentation says, MySQL 5.7.18 appears to accept `0001-01-01 00:00:00` as a valid date time value, and inserting `DateTimeOffset.MinValue` works with the latest MySqlConnector library.

There must be something else going on because MySqlConnector does not serialize `DateTimeOffset` with the time zone ([code](https://github.com/mysql-net/MySqlConnector/blob/d6639af0b940a0ab915b4b4d8926387e086e0bec/src/MySqlConnector/MySqlClient/MySqlParameter.cs#L144-L148)), but that's happening here according to the exception message:

> MySqlException: Incorrect datetime value: '0001-01-01 00:00:00.0000000+00:00' for column 'CreatedOn'
