### ISSUE TITLE
Cast error

### ISSUE THREAD

**Issue by hugosmarques** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#277]
When i run:

dotnet ef dbcontext scaffold "Host=xxx.xxx.xxx.xxx;Port=3307;Database=xxxxxxxx;Username=xxxxx;Password=xxxxxxxxx" ^ Pomelo.EntityFrameworkCore.MySql ^ --force ^ --context "FooContext" ^ --output-dir "Entities" ^ --verbose

Get this error

System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDesignTimeServices' to type 'Microsoft.EntityFrameworkCore.Infrastructure.IDesignTimeServices'.
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to cast object of type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDesignTimeServices' to type 'Microsoft.EntityFrameworkCore.Infrastructure.IDesignTimeServices'.

Can anyone help on this

**Comment by SilverioMiranda** [comment]
You are using version 2.0. * - pre that is incompatible with version 1.1.*

**Comment by hugosmarques** [comment]
and when will be available the version for .net core 2?

**Comment by caleblloyd** [comment]
You can use the `1.1.2` line with .net core 2.

We are working on a package that tracks EF Core 2 in #282
