### ISSUE TITLE
mariadb  DATETIME does not support values generated

### ISSUE THREAD

**Issue by zuosc** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#280]
### Steps to reproduce
dotnet run testMigrate

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
`EnsureCreate creates database...Error in GeneratedTime.CreatedDateTime: DATETIME does not support values generated on Add or Update in MySql <= 5.5, try explicitly setting the column type to TIMESTAMP
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerationHelper.ColumnDefinition(String schema, String table, String name, Type clrType, String type, Nullable`1 unicode, Nullable`1 maxLength, Boolean rowVersion, Boolean nullable, Object defaultValue, String defaultValueSql, String computedColumnSql, IAnnotatable annotatable, IModel model, MigrationCommandListBuilder builder) in E:\GitHubCode\Pomelo.EntityFrameworkCore.MySql\src\Pomelo.EntityFrameworkCore.MySql\Migrations\MySqlMigrationsSqlGenerator.cs:line 424
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.ColumnDefinition(AddColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerationHelper.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder) in E:\GitHubCode\Pomelo.EntityFrameworkCore.MySql\src\Pomelo.EntityFrameworkCore.MySql\Migrations\MySqlMigrationsSqlGenerator.cs:line 59
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Pomelo.EntityFrameworkCore.MySql.PerfTests.Commands.TestMigrateCommand.Run() in E:\GitHubCode\Pomelo.EntityFrameworkCore.MySql\test\Pomelo.EntityFrameworkCore.MySql.PerfTests\Commands\TestMigrateCommand.cs:line 15
   at Pomelo.EntityFrameworkCore.MySql.PerfTests.Commands.CommandRunner.Run(String[] args) in E:\GitHubCode\Pomelo.EntityFrameworkCore.MySql\test\Pomelo.EntityFrameworkCore.MySql.PerfTests\Commands\CommandRunner.cs:line 29``

### Further technical details

MySQL version:  10.1.23-MariaDB-1~jessie
Operating system: win10
Pomelo.EntityFrameworkCore.MySql version:1.1.0

Other details about my project setup:

**Comment by caleblloyd** [comment]
#281 fixes the datetime issue.  I still couldn't run that command because the tests have JSON types and MariaDB does not support JSON columns.  But the fix clears the datetime issue.

If you comment out all of the JSON fields in the tests, then it works.

**Comment by Kagamine** [comment]
Thank you @caleblloyd.

**Comment by zuosc** [comment]
Thank you @caleblloyd.
