### ISSUE TITLE
dotnet ef migrations add <name> fails in docker container

### ISSUE THREAD

**Issue by denDAY04** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#291]
### Steps to reproduce
Create .NET Core 1.1 web application with EFCore integration to MySql database. The app is contained in one docker service, and the MySql databse in another. 

docker-compose.yml content: 
```
version: '2'

services:
  coreapp:
    image: coreapp
    ports:
      - 80:80
    build:
      context: ./CoreApp
      dockerfile: Dockerfile
    links:
      - mysql:CoreAppDB 
  mysql:
    image: mysql
    container_name: CoreAppDB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "fooCoreApp"
    volumes:
      - C:/mysql-data:/var/lib/mysql
```

Dockerfile content:

```
FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "CoreApp.dll"]
```

docker-compose.ci.build.yml content: 
```
version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./CoreApp.sln && dotnet publish ./CoreApp.sln -c Release -o ./obj/Docker/publish"

```

I have tried both having Startup#ConfigureServices(IServiceCollection) include
```
services.AddEntityFrameworkMySql().AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(Configuration["ConnectionStrings:DefaultConnection"]));
```
where appsettings.json looks like 
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "server=CoreAppDB;port=3306;database=CoreAppDB;user=root;password=fooCoreApp"
  } 
}
```

and also overriding the DbContext#OnConfigure():
```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseMySql(@"server=CoreAppDB;port=3306;database=CoreAppDB;user=root;password=fooCoreApp");
```

### The issue
When executing the dotnet CLI command 
```
dotnet ef migrations add <name>
```
in the VS 2017 project directory the following stacktrace is dropped.

```
MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts.
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlConnectionSettings.<>c__DisplayClass2_0.<GetSettings>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlScopedTypeMapper.get_ConnectionSettings()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlScopedTypeMapper.MaybeConvertMapping(RelationalTypeMapping mapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapperExtensions.IsTypeMapped(IRelationalTypeMapper typeMapper, Type clrType)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to connect to any of the specified MySQL hosts.
```

This is with an existing database and scheme. 

### Further technical details

MySQL version: Uknown
Operating system: Windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: 1.1.2
Microsoft.EntityFrameworkCore.Tools.DotNet version: 1.0.0

**Comment by caleblloyd** [comment]
Add `host=mysql` to your connection string.

**Comment by caleblloyd** [comment]
Check it out:

Compose file: https://github.com/caleblloyd/dotnet-core-boilerplate/blob/develop/docker-compose.yml

Connection string from Docker Container: https://github.com/caleblloyd/dotnet-core-boilerplate/blob/develop/dotnet/src/App/Common/Config/config.dev.json

Connection string from host: https://github.com/caleblloyd/dotnet-core-boilerplate/blob/develop/dotnet/src/App/Common/Config/config.local.json except replace `dockerhost` with `localhost`

You can't access the docker service from the host by using the `link`. `link` is only between docker containers.

If you want a full dockerized development solution feel free to use my boilerplate

**Comment by denDAY04** [comment]
Thank you for the reference repo. I've tried looking around in it a mirror a few things, but I'm still unsure how I'm supposed to solve the problem; or more specifically, how/where I can run the dotnet ef command to generate a migration class based on the mysql db wrapped in one of the docker containers. Changing the host in the connectionstring to localhost results in a similar exception at run-time when simply debugging the application (which makes sense, since docker now tries to look for the db in the wrong container).

**Comment by caleblloyd** [comment]
Are you running the `dotnet ef` commands from your host, or from the `coreapp` container?

**Comment by denDAY04** [comment]
From the host (cmd in windows directory). I'm not sure how I would run it in the container.

**Comment by caleblloyd** [comment]
The host network cannot access the docker network.  The docker network is for container-to-container communication only.  You need 2 different connection strings: one for `host <-> container` and one for `container <-> container`

Here's an example:

```
version: '2'

services:
  coreapp:
    image: coreapp
    ports:
      - 80:80
    environment:
      - CONTAINER=true
    build:
      context: ./CoreApp
      dockerfile: Dockerfile
    links:
      - mysql
  mysql:
    image: mysql
    container_name: CoreAppDB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "fooCoreApp"
    volumes:
      - C:/mysql-data:/var/lib/mysql
```

Then for your connection strings:

```
string connectionString;
if (Environment.GetEnvironmentVariable("CONTAINER") == "true")
    connectionString="server=mysql;port=3306;database=CoreAppDB;user=root;password=fooCoreApp";
else
    connectionString="server=localhost;port=3306;database=CoreAppDB;user=root;password=fooCoreApp";
```

**Comment by denDAY04** [comment]
Thank you, that ended up fixing it. 

Sorry that it took a bit of explaining on your part, but now I get how the problem is addressed. 👍

**Comment by rhaynes123** [comment]
I had this same problem article saved me
