### ISSUE TITLE
Failed to find or load the registered .Net Framework Data Provider.

### ISSUE THREAD

**Issue by knocte** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#294]
### Steps to reproduce
Change already working EF program to start using Pomelo library.

### The issue
In the Readme it's not explained how to add a provider in the config file, so I didn't add anything (hoping that it would somehow be able to find it at runtime). However, this is not the case.

```
Exception message: Error in InitializeExRateManager.
System.Configuration.ConfigurationErrorsException: Failed to find or load the registered .Net Framework Data Provider.
Stack trace:
2017-06-20 19:22:18,905 [5] ERROR ExchangeRateLogger - 
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.Entity.Infrastructure.DependencyResolution.DefaultProviderFactoryResolver.GetService(Type type, Object key, Func`3 handleFailedLookup)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Data.Entity.Infrastructure.DependencyResolution.CachingDependencyResolver.GetService(Type type, Object key)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService[T](IDbDependencyResolver resolver, Object key)
   at System.Data.Entity.Core.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Entity.Internal.LazyInternalConnection.InitializeFromConnectionStringSetting(ConnectionStringSettings appConfigConnection)
   at System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config)
   at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   at System.Data.Entity.Internal.LazyInternalConnection.CreateObjectContextFromConnectionModel()
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
```

### Further technical details

MySQL version: 5.7.1
Operating system: Windows2012
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

Other details about my project setup:
This project worked fine with Mysql.Data 6.9.3 and 6.9.9

How to switch it to start using Pomelo? I'm sure I'm missing something obvious.

**Comment by knocte** [comment]
The previous configuration had:

```
 <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v11.0"/>
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"/>
      <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.9.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d">
      </provider>
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.3.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d"/>
    </DbProviderFactories>
  </system.data>   
```

**Comment by caleblloyd** [comment]
EF Core is different. You must do the Configuration in your code. Add this method to your DbContext:

```
 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder .UseMySql(@"Server=localhost;database=ef;uid=root;pwd=123456;");
```

**Comment by caleblloyd** [comment]
Here's the official docs. Configure pomelo with `UseMySql` instead of `UseSqlServer`

https://docs.microsoft.com/en-us/ef/core/

**Comment by knocte** [comment]
I'm not using .NET Core. I've read this is compatible with .NET 4.5.x

**Comment by caleblloyd** [comment]
It is compatible with `net451` and up. Still this is EFCore, not the same thing as EF6 that you are coming from. It's not a drop in replacement.

https://docs.microsoft.com/en-us/ef/efcore-and-ef6/

**Comment by knocte** [comment]
Oh, wait, what? EF Core is 4.5.x compatible? what a naming fuckup... :facepalm: thanks

**Comment by caleblloyd** [comment]
Yup it targets `netstandard1.3` and `net451`

EFCore v2 will target `netstandard2.0` and will work with `net461` and up as well as .net core 2.

Yes there are only so many combinations of "net" "core" "framework" and "asp" and Microsoft has used almost all of them :smile:

**Comment by mguinness** [comment]
@knocte Instead of overriding OnConfiguring, you can also use [AddDbContext](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#using-dbcontext-with-dependency-injection) shown below and inject it into your DbContext class using DI.

`services.AddDbContext<ApplicationDbContext>(options => options.UseMySql(Configuration.GetConnectionString("DefaultConnection")));`

`public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }`
