### ISSUE TITLE
Unable to cast object of type 'System.String' to type 'System.DateTime' 

### ISSUE THREAD

**Issue by Garyxiao** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#313]
pls help me.

`FATAL 2017-07-08 22:45:03,628 [1    ] soft.AspNetCore.Hosting.Internal.WebHost - Application startup exception
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
   at MySql.Data.MySqlClient.MySqlDataReader.GetDateTime(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryingEnumerable`1.MySqlEnumerator.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)`

Microsoft.EntityFrameworkCore : 1.1.1
.Netcore1.1
MySQL version: 10.2.6-MariaDB
Operating system: Windows 10 Pro x64
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
Your db type is varchar or text and your C# type is DateTime or DateTimeOffset

Migrate your db type to DateTime

**Comment by Garyxiao** [comment]
@caleblloyd Thanks a lot ,The problem is solved.
