### ISSUE TITLE
Unable to use uint as primary key

### ISSUE THREAD

**Issue by NicatorBa** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#328]
### Steps to reproduce
Create an entity model with auto increment Id of type uint.
```CSharp
public class EnergyType
{
  public uint Id { get; set; }
  public string Name { get; set; }
}
```

Create new objects and add them into DB context.
```CSharp
dbContext.EnergyTypes.Add(new EnergyType{ Name = "electricity" });
dbContext.EnergyTypes.Add(new EnergyType{ Name = "gas" });
dbContext.SaveChanges();
```

### The issue
Get an InvalidCastException exception on SaveChanges(), also get an exception for duplicated key after i've added
```CSharp
if (typeof(T) == typeof(uint))
{
  return (T)Convert.ChangeType(Convert.ToUInt32(ordinal), typeof(T));
}
```
in T GetFieldValue<T>(int ordinal) in WrappedMySqlDataReader.cs from Pomelo.EntityFrameworkCore.MySql.

```
Exception message:
Unable to cast object of type 'System.UInt64' to type 'System.UInt32'.

Stack trace:
{Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.InvalidCastException: Unable to cast object of type 'System.UInt64' to type 'System.UInt32'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.ConvertWithReflection[T](Int32 ordinal, InvalidCastException e)
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, DbDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.AspNetCore.Builder.ZipCodesBuilderExtensions.InitializeDatabase(IApplicationBuilder app, String[] zipCodes) in C:\Projects\eva-wuepp-gateway-service\webserver\Gateway.Eva.Wüpp\src\Gateway.Eva.Wüpp.ZipCodes\ZipCodesBuilderExtensions.cs:line 76
   at Gateway.Eva.Wüpp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Projects\eva-wuepp-gateway-service\webserver\Gateway.Eva.Wüpp\src\Gateway.Eva.Wüpp\Startup.cs:line 61}	Microsoft.EntityFrameworkCore.DbUpdateException
```

### Further technical details

MySQL version: 5.7
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
Your DB schema probably has the `ID` field defined as `bigint unsigned`. Change it to `int unsigned` in MySQL and it should work.

**Comment by NicatorBa** [comment]
I've created the DB schema with Pomelo.EntityFrameworkCore.MySql.Design 1.1.2. If i generate sql script from the migration:
```
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);

CREATE TABLE `EnergyTypes` (
    `Id` int unsigned NOT NULL AUTO_INCREMENT,
    `Name` varchar(16) NOT NULL,
    CONSTRAINT `PK_WueppEnergyTypes` PRIMARY KEY (`Id`)
);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170630074424_InitialCreate', '1.1.2');
```

It seems correct for me, so it should not be a problem with the DB schema.

**Comment by crowly0** [comment]
I also have this problem when the PK is ushort or byte. 
DB schema is ok, byte = tinyint(3) unsigned and ushort = smallint(5) unsigned. 
Possible an issue when PK is not bigint (unsigned)?

**Comment by caleblloyd** [comment]
@NicatorBa @crowly0 I cannot recreate

My best guess is that your Migrations are out of sync with your Database.

If you are using `uint` in your code, you should apply a migration that makes your PK use `int unsigned`.  If you have not done so, you will get `InvalidCastException`

I changed all of the keys in the [CRM Test Model](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Models/Crm.cs) to `uint`, then to `ushort` and they worked

I do see an issue when migrating PKs that have FKs associated - MySQL won't let you.  In this case it's better to adjust the migration by hand to drop the FKs, make the change, then add the FKs back.

I am on `2.0.0-preview` but I believe `1.1.2` works the same way.

If you can repro the issue with the CRM Test Model and open a pull request, then it'll be far easier for me to debug.  Until then I am going to close the issue though.

**Comment by NicatorBa** [comment]
#336
