### ISSUE TITLE
error generating migration with 2.0.0-preview3

### ISSUE THREAD

**Issue by joeaudette** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#341]
I am trying to use asp.net core 2.0 preview2 and using Pomelo 2.0.0-preview3-10051

I am using fluent api and adding some indexes like this:

    entity.HasIndex(p => p.UserId);

Not using any full text indexes and none of the fields I'm indexing are larger than 255 chars

When I try to generate a migration I'm getting this error:

System.InvalidOperationException: The annotation 'MySql:FullTextIndex' was not found. Ensure that the annotation has been added.
   at Microsoft.EntityFrameworkCore.Infrastructure.AnnotatableExtensions.GetAnnotation(IAnnotatable annotatable, String annotationName)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MySqlMigrationsAnnotationProvider.<For>d__3.MoveNext()
   at Microsoft.EntityFrameworkCore.MutableAnnotatableExtensions.AddAnnotations(IMutableAnnotatable annotatable, IEnumerable`1 annotations)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__43.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.<Add>d__26.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The annotation 'MySql:FullTextIndex' was not found. Ensure that the annotation has been added.

Any idea how to get past the error?

**Comment by Kagamine** [comment]
Could you try to use 2.0.0-preview3-10052

**Comment by joeaudette** [comment]
@Kagamine thanks for the speedy fix! Yes it works now and this issue can be closed.

Seems to require a valid connection to the database to be able to run migrations, but I think I saw that as a known/existing issue.

I also ran into a problem when executing migrations generated previously under 1.x so I may open a new issue on that, but works well with newly generated migrations now
