### ISSUE TITLE
error generating a new migration with 2.0.0-preview3-10053

### ISSUE THREAD

**Issue by joeaudette** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#342]
I am upgrading an app from asp.net 1.x to 2.0 preview3 using pomelo 2.0.0-preview3-10053

Things worked fine until I added new model changes and tried to generate a new migration.
Previous migrations were generated using 1.x and I had to make a couple of small edits to the existing migrations to remove some bad default values but then it worked fine.

I added 4 new bool properties with a default of true like this:

```
    entity.Property(p => p.PwdRequireNonAlpha)
            .IsRequired()
            .HasDefaultValue(true)
            ;
      entity.Property(p => p.PwdRequireLowercase)
            .IsRequired()
            .HasDefaultValue(true)
            ;
        entity.Property(p => p.PwdRequireUppercase)
            .IsRequired()
            .HasDefaultValue(true)
            ;
        entity.Property(p => p.PwdRequireDigit)
           .IsRequired()
            .HasDefaultValue(true)
             ;
```

then when I tried to generate the migration I got this error:

```
PS C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Core.Storage.EFCore.MySql> dotnet ef migrations ad
d changes20170730 -c CoreDbContext
System.ArgumentException: An item with the same key has already been added. Key: Microsoft.EntityFrameworkCore.Infrastructure.Internal.MySqlOptionsExtension
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.EntityFrameworkCore.DbContextOptions`1.WithExtension[TExtension](TExtension extension)
   at Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsBuilderInfrastructure.AddOrUpdateExtension[TExtension](TExtension extension)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.ConfigureWarnings(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql[TContext](DbContextOptionsBuilder`1 optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at cloudscribe.Core.Storage.EFCore.MySql.CoreDcContextDesignTimeFactory.CreateDbContext(String[] args) in C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Core.Storage.EFCore.MySql\Startup.cs:line 26
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_0.<FindContextTypes>b__3()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
An item with the same key has already been added. Key: Microsoft.EntityFrameworkCore.Infrastructure.Internal.MySqlOptionsExtension
PS C:\_joe\__projects\__cloudscribe\_code\cloudscribe\src\cloudscribe.Core.Storage.EFCore.MySql>
```

**Comment by caleblloyd** [comment]
Could you create a detailed reproduce with the following 4 files:

1. Original model
2. First migration
3. Changed model with new properties
4. Second migration

That way we can reproduce.

**Comment by joeaudette** [comment]
It is kind of a large solution but it is open source so it would be great if you could look into it.

Steps to repro:
1 clone or fork cloudcsribe repository https://github.com/joeaudette/cloudscribe and change to netcore20 branch
2. dotnet restore --no-cache
3 dotnet build
4. in sourceDev.WebApp edit appsettings.json or override it with a gitignored file appsettings.dev.json, change this:

    "DevOptions": {
    "DbPlatform": "ef",
    "EFProvider": "MSSQL"
      }

like this to switch to mysql

    "DevOptions": {
    "DbPlatform": "ef",
    "EFProvider": "MySql"
    }

5. provide a valid connection string for MySqlEntityFrameworkConnectionString
6. in the project cloudscribe.Core.Storage.EFCore.MySql you will need to temporarily edit in Startup.cs file to put in a valid connection string to generate the migration, you will see an extra class in Startup.cs like this:

        public class CoreDcContextDesignTimeFactory : IDesignTimeDbContextFactory<CoreDbContext>
        {
            public CoreDbContext CreateDbContext(string[] args)
            {
                var builder = new DbContextOptionsBuilder<CoreDbContext>();
                builder.UseMySql("Server=yourserver;Database=yourdb;Uid=youruser;Pwd=yourpassword;Charset=utf8;");
                return new CoreDbContext(builder.Options);
            }
        }

that is where you need a valid connection string

7. dotnet ef migrations add changes20170730 -c CoreDbContext

should produce the error

**Comment by joeaudette** [comment]
note that the model changes already exist and are the ones I posted previously. All existing migration for mysql were generated before with 1.x

My other implementations for MSSQL and pgsql are currently working and was able to generate the migration for those. So the mysql one is just waiting to generate migration for model changes already in place

**Comment by caleblloyd** [comment]
Thanks for the info, I should be able to check it out early next week.

**Comment by joeaudette** [comment]
Great! Thank you!

**Comment by joeaudette** [comment]
@caleblloyd noticed you are in Raleigh, just fyi I am [presenting on my cloudscribe projects at TRINUG Aug 9](https://www.meetup.com/TRINUG/events/241880485/)

**Comment by caleblloyd** [comment]
@joeaudette I followed all of your steps and got no errors:

```
caleb@rog:~/Projects/caleb/cloudscribe/src/cloudscribe.Core.Storage.EFCore.MySql$ dotnet ef migrations add changes20170730 -c CoreDbContext
The 'bool' property 'PwdRequireDigit' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireLowercase' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireNonAlpha' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireUppercase' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
Done. To undo this action, use 'ef migrations remove'
caleb@rog:~/Projects/caleb/cloudscribe/src/cloudscribe.Core.Storage.EFCore.MySql$ dotnet ef database update
The 'bool' property 'PwdRequireDigit' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireLowercase' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireNonAlpha' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
The 'bool' property 'PwdRequireUppercase' on entity type 'SiteSettings' is configured with a database-generated default. This default will always be used when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used when the property value is 'null'.
Applying migration '20161111133959_Initial'.
Applying migration '20170401123950_changes20170401'.
Applying migration '20170525201242_changes20170525'.
Applying migration '20170526173128_changes20170526'.
Applying migration '20170527164922_changes20170527'.
Applying migration '20170629182344_changes20170627'.
Applying migration '20170731195039_changes20170730'.
Done.
```

I'm using the latest `mysql:5.7` Docker image.  What version are you using when you hit this?

**Comment by joeaudette** [comment]
@caleblloyd now it works for me too, sorry to have used your time. Only thing I notice is I now have pomelo 2.0.0-preview3-10054 which is newer than when I reported the error. I'm using MySql5.7 on windows10

Thanks for your help! Feel free to close this issue.

**Comment by caleblloyd** [comment]
Glad to hear. There was a fix for some type mappings in that release so maybe that's what did it.

**Comment by Kagamine** [comment]
See PR #333
