### ISSUE TITLE
An item with the same key has already been added. Key: p2068

### ISSUE THREAD

**Issue by falps** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#356]
你好，使用Pomelo.EntityFrameworkCore.MySql（2.0.0-rtm-10056），在执行context.SaveChanges();时报错，错误内容：An item with the same key has already been added. Key: p2068，
StackTrace如下
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
同样的代码，使用版本：Pomelo.EntityFrameworkCore.MySql（1.1.2）没有问题，请帮忙看看，谢谢

**Comment by Kagamine** [comment]
Please provide a repro for your issue, and use English to describe your issue.

**Comment by munir-jb** [comment]
hi guys, I found these same bug because of the inability of .UseMySQL method to automatically checking wether optionsBuilder.Isconfigured in an EF class, so I had to do this :

`      try {
        if (!optionsBuilder.IsConfigured) {
          optionsBuilder.UseMySql("connection string");
          CustomizeConfiguration(ref optionsBuilder);
          base.OnConfiguring(optionsBuilder);
        }
      }
      catch (Exception e) {
        Console.WriteLine(e.Message);
      }`

the most important block is this :
`if (!optionsBuilder.IsConfigured) {
...
}`

In SQL Server/SQLite we can call optionsBuilder safely, but with Pomelo EF MySQL we had to check is configuration already exists to prevent those error from occuring.

ref : https://stackoverflow.com/questions/29054794/configure-more-than-one-dbcontext-in-ef-7
see the last answer, that's what I'm using now.

**Comment by alexzaytsev-newsroomly** [comment]
I am getting the same issue, unfortunately.

**Comment by mguinness** [comment]
@munir-jb @alexzaytsev-newsroomly We have limited resources so please feel free to create a PR to make the necessary modification to [MySqlDbContextOptionsExtensions.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs) if you'd like to contribute.

**Comment by munir-jb** [comment]
I'll try to contribute after finishing my current project. Because our team will be using MySQL/MariaDB onward after our initial project is deployed...

**Comment by sgarnovsky** [comment]
The error is still reproduced with official 2.0.0 version.

The update process includes 10-12 tables to insert ~50-200 records for each table.
Error is always reproduced for the the same record.

An exception occurred in the database while saving changes for context type 'Some.Namespace.SomeDbContext'.
System.ArgumentException: An item with the same key has already been added. Key: p2078
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

the part of the last sql is ran:
INSERT INTO `object_region` (`obr_id`, `obj_id`, `rgn_id`, `rgp_id`, `type`)
VALUES (@p2058, @p2060, @p2062, @p2064, @p2066);
SELECT ROW_COUNT();

INSERT INTO `object_region` (`obr_id`, `obj_id`, `rgn_id`, `rgp_id`, `type`)
VALUES (@p2068, @p2070, @p2072, @p2074, @p2076);
SELECT ROW_COUNT();


I feel like the updates are generated inside one sql command so it exceeds the number of parameters are sent to the command.

Now I continue with simple walkalround to fix this issue: 
- apply updates after each table is changed, 
- all updates applied in one transaction. 
Error doesn't appear in this case. 

But bug is still in place and it is possible to catch it again when one table will have many records to insert or update.

**Comment by mguinness** [comment]
@sgarnovsky Please see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/365.  Have you tried with 2.0.1-preview-10066?

**Comment by sgarnovsky** [comment]
>  Please see #365. Have you tried with 2.0.1-preview-10066?
yes, thank you the both options work.

**Comment by Prince269090** [comment]
I have multi tenant application and i have to change the connection run time based on the tenant database. 

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
	var connectionString = FetchAsPerTenant();

	// I am getting the same error about key already exists. 
	return contextOptionsBuilder.UseMySql(connectionString);
}

@falps , @yukozh , @jatmika-com , @alexzaytsev-newsroomly , @mguinness 
Please let me know for any solution of this. I am having .Net core 3.1 project.

**Comment by lauxjpn** [comment]
@Prince269090 No need to spam here. You did just asked the same question in #376.
