### ISSUE TITLE
`dotnet ef database update` fails while creating schemata

### ISSUE THREAD

**Issue by Dormanil** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#366]
### Steps to reproduce
- Grab the latest code from [my GitHub repository for my project](https://github.com/Dormanil/Shinoa)
- `dotnet restore` just to be sure that the dotnet ef tools are installed
- Navigate to `Shinoa/src/Shinoa`
- Edit `example_config.yaml` and save as `config.yaml`
  - Set Provider to MySQL
  - Set connection string appropriately
- Execute `initdatabase.sh`
- Notice that creating the migration works, but that applying the migration fails.

### The issue
The generated SQL, where it fails, for applying the database, is as follows:
```mysql
DROP PROCEDURE IF EXISTS mysql_ef_ensure_schema;
CREATE PROCEDURE mysql_ef_ensure_schema()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE `SCHEMA_NAME` = 'animefeed')
    THEN
        CREATE SCHEMA `animefeed`;
    END IF;
END;

CREATE TABLE `animefeed`.`AnimeFeedBindings` (
    `ChannelIdString` varchar(127) NOT NULL,
    CONSTRAINT `PK_AnimeFeedBindings` PRIMARY KEY (`ChannelIdString`)
);
```
Looking at the database after aborting after the first exception tells me that the procedure was created, but I assume it's never called, since calling the procedure manually works. 
Subsequently the SQL transaction fails when it tries to create a table in a schema that doesn't exist.

```
Exception message: 
Unknown database 'animefeed'

Stack trace: 
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database 'animefeed'
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 5.7.19
Operating system: Ubuntu Linux 16.04.03 LTS, on kernel Linux 4.4.0-042stab123.9
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-rtm

**Comment by caleblloyd** [comment]
This has been fixed and will be included in out 2.0.0 release next week
