### ISSUE TITLE
Double.NaN values cause MySqlException

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#369]
### Steps to reproduce
```
namespace PomeloRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyContext("Server=localhost;database=text;uid=text;pwd=pass;"))
            {
                db.Database.EnsureCreated();

                double? x = 0;
                var mymodel = new MyModel
                {
                    Id = Guid.NewGuid(),
                    MyDouble = x / x
                };
                db.MyModels.Add(mymodel);

                db.SaveChanges();
            }
        }
    }

    public class MyContext : DbContext
    {
        private readonly string _connectionString;

        public MyContext(string connectionString)
        {
            _connectionString = connectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseMySql(_connectionString);

        public DbSet<MyModel> MyModels { get; set; }
    }

    [Table("mymodels")]
    public class MyModel
    {
        [Key]
        public Guid Id { get; set; }

        public double? MyDouble { get; set; }
    }
}

```
### The issue
Running this code causes MySqlException: Unknown column 'NaN' in 'field list'

```
Exception message:
Stack trace:
{Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'NaN' in 'field list'
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at PomeloRepro.Program.Main(String[] args) in C:\code\PomeloRepro\PomeloRepro\Program.cs:line 24}
```

### Further technical details

MySQL version: 5.5.55-0ubuntu0.14.04.1
Operating system: Windows 10 15063 (MySql is running on Linux, Ubuntu 14.04)
Pomelo.EntityFrameworkCore.MySql version: 2.0

Other details about my project setup: .Net Core 2.0

Note: The same issue happens with MySql connector (NuGet package ```MySql.Data.EntityFrameworkCore```)

**Comment by caleblloyd** [comment]
Could you please turn `Microsoft` logging to `Information` and post the SQL Statement that is failing?

**Comment by caleblloyd** [comment]
I think that this is a bit of an edge case.  We are happy to accept a fix as a Pull Request.  There may be additional support needed in the ADO.NET layer at https://github.com/mysql-net/MySqlConnector

I'm going to close for now, if you'd like to make a pull request just reference the issue in the PR and we'll reopen it at that time.  Thanks
