### ISSUE TITLE
Exception when scaffolding with a copy of a database in the same server

### ISSUE THREAD

**Issue by MicBoucinha** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#382]
### Steps to reproduce
1. Have a simple database with tables that have FK constraints
(example)
```sql
CREATE TABLE bar (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(ID)
);

CREATE TABLE bar2 (
  ID int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(ID)
);

CREATE TABLE foo (
   ID int(11) NOT NULL AUTO_INCREMENT,
   bar_ID int(11) NOT NULL,
   bar2_ID int(11) NOT NULL,
   PRIMARY KEY (ID, bar_ID),
   CONSTRAINT fk_bar FOREIGN KEY (bar_id) REFERENCES bar (ID),
   CONSTRAINT fk_bar2 FOREIGN KEY (bar2_id) REFERENCES bar2 (ID)
);
```

2. Create a copy of the database in the same server
3. Try to scaffold either the original or the copy.

### The issue
Hi, I am having a problem with scaffolding. 
I was trying to scaffold a database schema that I have in my database, and I got the exception showed below. 

```
Exception message: Subquery returns more than 1 row
Stack trace:
MySql.Data.MySqlClient.MySqlException (0x80004005): Subquery returns more than 1 row
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<>c__DisplayClass8_0.<<ScanRowAsync>g__ScanRowAsyncAwaited0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.Read()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String r
ootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IE
numerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IE
numerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I went to the code for the GetConstraints method and tried to execute the query used there directly in the database. After some tests, a friend noticed that the problem might reside in the fact that the query wasn't considering database copies in the server. A small change was made to the query and now it seems to work properly (added **AND `REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA`=`{0}`**).

```sql
SELECT
  `CONSTRAINT_NAME`, 
  `TABLE_NAME`, 
  `REFERENCED_TABLE_NAME`, 
  GROUP_CONCAT(CONCAT_WS('|', `COLUMN_NAME`, `REFERENCED_COLUMN_NAME`) ORDER BY `ORDINAL_POSITION` SEPARATOR ',') AS PAIRED_COLUMNS, 
  (SELECT `DELETE_RULE` FROM `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` WHERE `REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_NAME` = `KEY_COLUMN_USAGE`.`CONSTRAINT_NAME` AND `REFERENTIAL_CONSTRAINTS`.`CONSTRAINT_SCHEMA`=`{0}`) AS `DELETE_RULE`
 FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` 
 WHERE `TABLE_SCHEMA` = '{0}' 
   AND `TABLE_NAME` = '{1}' 
   AND `CONSTRAINT_NAME` <> 'PRIMARY'
        AND `REFERENCED_TABLE_NAME` IS NOT NULL
        GROUP BY `CONSTRAINT_NAME`, 
        `TABLE_NAME`, 
        `REFERENCED_TABLE_NAME';
```

### Further technical details

MySQL version: 5.7.11 (version 5.7.19 on Linux)
Operating system: Windows 10 Pro (also tried on Ubuntu 14.04LTS)
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-rtm-10062

Can someone please confirm if that the change suggestion doesn't break anything else or if it is the most correct approach to the problem?

Thank you.

**Comment by Kagamine** [comment]
Fixed in #414
