### ISSUE TITLE
"Could not find column definition for table ..." after renaming column.

### ISSUE THREAD

**Issue by tuanbs** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#391]
### Steps to reproduce
* Rename 1 column from old name "abc" into new name "aBc".
* Run EF tool to add new migration: 
```
dotnet ef migrations add Renamed_Column
```
-> success with no issue.
* Run EF tool to update Db:
```
dotnet ef database update
```
-> success with no issue.
* Run EF tool to generate script:
```
dotnet ef migrations script -o dbScript.sql
```
-> Failed with issue: Could not find column definition for table: '`Test`' column: abc

### The issue
Failed with issue: Could not find column definition for table: '`Test`' column: abc

```
System.InvalidOperationException: Could not find column definition for table: ... at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model,MigrationCommandListBuilder builder)
at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__63_20(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, Boolean idempotent)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration,Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 5.6.31 
Operating system: macOS Sierra
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-rtm-*

Other details about my project setup:

**Comment by cjalpha** [comment]
I have the same error. Not after renaming a column, but after introducing inheritance in my models. Has anyone found a workaround for this?

**Comment by Kagamine** [comment]
This is a user error, You have input the -From <Your DB current migration version>, If missing the from arg, it means starts with the first migration.

**Comment by cjalpha** [comment]
I do want to point out that I was able to fix my issue by doing the following by:

1 - Dropping the database 
2 - Deleting all migration files 
3 - Adding a new migration and running _dotnet ef database udpate_

I made no changes whatsoever to the migration files themselves or to my models, so calling this a _user error_ might be a bit incomplete. 

To add a bit of context in my situation, I had a model with 3 tables in the form of Animal, Bear, Grizzly Bear. In my original model, I had no inheritance and each class were related to the others via foreign keys. 

Later, I decided to use inheritance instead, and I changed my model so that Bear was a subclass of Animal, and Grizzly Bear was a subclass of Bear. Then when I tried to add a new migration to account for the changes, I received the error mentioned here (along with some others).

**Comment by Kagamine** [comment]
You must specify the argument `From`, because mysql does NOT have a command to rename column only, so Pomelo will read your database information schema to load the current field type.
The rename column SQL query should be:
```mysql
ALTER TABLE `XXX` CHANGE `OLD_COLUMN` `NEW_COLUMN` <TYPE>;
```
If you don't supply the -From arg, EF will consider the first migration script by default. But your database not match the first migration script, so throw the exception.
