### ISSUE TITLE
Scaffolding not working

### ISSUE THREAD

**Issue by erwinwolff** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#392]
When I start the scaffolding with - I think - the correct parameters, the whole thing fails on a TypeLoadException later on

### Steps to reproduce
Start a scaffolding with an existing database: 

Scaffold-DbContext "host=localhost;user=**;password=***;database=***" "Pomelo.EntityFrameworkCore.MySql" -Verbose

Using project 'Desktop.Tech.Database'.
Using startup project 'Desktop.Tech.Database'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database\bin\Debug\netcoreapp2.0\Desktop.Tech.Database.deps.json --additionalprobingpath C:\Users\ErwinWolff\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --fx-version 2.0.0 "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.0.0\tools\netcoreapp2.0\ef.dll" dbcontext scaffold host=localhost;user=root;password=10qoal;database=desktoptechiowp Pomelo.EntityFrameworkCore.MySql --json --output-dir DbModels --verbose --no-color --prefix-output --assembly D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database\bin\Debug\netcoreapp2.0\Desktop.Tech.Database.dll --startup-assembly D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database\bin\Debug\netcoreapp2.0\Desktop.Tech.Database.dll --project-dir D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database --root-namespace Desktop.Tech
Using assembly 'Desktop.Tech.Database'.
Using startup assembly 'Desktop.Tech.Database'.
Using application base 'D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database\bin\Debug\netcoreapp2.0'.
Using working directory 'D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database'.
Using root namespace 'Desktop.Tech'.
Using project directory 'D:\csharp\DesktopOrganizer2Website\Desktop.Tech.Database'.
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.DesignTimeProviderServicesAttribute' from assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.DesignTimeProviderServicesAttribute' from assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by mguinness** [comment]
Before we take a look please edit your question to include the following.

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:

**Comment by nicolasguzca** [comment]
Hi, I was having this same error. I had Pomelo.EntityFrameworkCore 1.0.1 installed with EntityFrameworkCore 2.0.3. If you upgrade to Pomelo.EntityFrameworkCore 2.1.0 the issue will go away :)
