### ISSUE TITLE
The instance of entity type 'Review' cannot be tracked 

### ISSUE THREAD

**Issue by JonPSmith** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#397]
### Steps to reproduce
I am writing a book [Entity Framework in Action](http://bit.ly/2m8KRAZ) for Manning and I am trying to use MySql, but I get an error on a standard setup that has worked with SQL Server and SQLite. 

I am using Pomelo.EntityFrameworkCore.MySql version 2.0.1-preview-10068 with EF Core 2.0.0

### The issue
I want to use another database than SQL Server, and I chose MySQL because my hosting service supports that.

I started with some basic unit tests to check everything was OK. I then ran a method to seed the database,  `SeedDatabaseFourBooks`, that I have used a lot (60+ references in my unit tests) and it failed with the exception.

To try an pinpoint the problem I have copied the `SeedDatabaseFourBooks` method core into the unit test you see below. I have removed one book and it still fails - if I comment out any of the three books it works. But with the statements as shown it errors with the exception shown after the code:

```c#
[Fact]
public void TestMySqlCreateBooks()
{
    //SETUP
    var connection = AppSettings.GetConfiguration()["MySql-Test"];
    var optionsBuilder =
        new DbContextOptionsBuilder<EfCoreContext>();
    optionsBuilder.UseMySql(connection);
    optionsBuilder.EnableSensitiveDataLogging();

    using (var context = new EfCoreContext(optionsBuilder.Options))
    {
        context.Database.EnsureCreated();
        var logIt = new LogDbContext(context);
        var existingBooks = context.Books.Count();

        //ATTEMPT
        var martinFowler = new Author
        {
            Name = "Martin Fowler"
        };

        var books = new List<Book>();

        var book2 = new Book
        {
            Title = "Patterns of Enterprise Application Architecture",
            Description = "Written in direct response to the stiff challenges",
            PublishedOn = new DateTime(2002, 11, 15),
            Price = 53
        };
        book2.AuthorsLink = new List<BookAuthor> { new BookAuthor { Author = martinFowler, Book = book2 } };
        books.Add(book2);

        var book3 = new Book
        {
            Title = "Domain-Driven Design",
            Description = "Linking business needs to software design",
            PublishedOn = new DateTime(2003, 8, 30),
            Price = 56
        };
        book3.AuthorsLink = new List<BookAuthor> { new BookAuthor { Author = new Author { Name = "Eric Evans" }, Book = book3 } };
        books.Add(book3);

        var book4 = new Book
        {
            Title = "Quantum Networking",
            Description = "Entangled quantum networking provides faster-than-light data communications",
            PublishedOn = new DateTime(2057, 1, 1),
            Price = 220
        };
        book4.AuthorsLink = new List<BookAuthor> { new BookAuthor { Author = new Author { Name = "Future Person" }, Book = book4 } };
        book4.Reviews = new List<Review>
            {
                new Review { VoterName = "Jon P Smith", NumStars = 5, Comment = "I look forward to reading this book, if I am still alive!"},
                new Review { VoterName = "Albert Einstein", NumStars = 5, Comment = "I write this book if I was still alive!"}
            };
        book4.Promotion = new PriceOffer { NewPrice = 219, PromotionalText = "Save $1 if you order 40 years ahead!" };
        books.Add(book4);
        context.AddRange(books);
        context.SaveChanges();

        //VERIFY
        context.Books.Count().ShouldEqual(existingBooks + 3);
    }
}
``` 

I could include all my setup but you can find it the Git repo [EfCoreInAction.DataLayer](https://github.com/JonPSmith/EfCoreInAction/tree/Chapter12/DataLayer/EfCode).

```
Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
---- System.InvalidOperationException : The instance of entity type 'Review' cannot be tracked because another instance with the key value 'ReviewId:1' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at DataLayer.EfCode.EfCoreContext.SaveChanges() in C:\Users\Jon\Documents\Visual Studio 2017\Projects\EfCoreInAction\DataLayer\EfCode\EfCoreContext.cs:line 39
   at test.UnitTests.DataLayer.Ch14_MySql.TestMySqlCreateBooks() in C:\Users\Jon\Documents\Visual Studio 2017\Projects\EfCoreInAction\Test\UnitTests\DataLayer\Ch14_MySql.cs:line 254
----- Inner Stack Trace -----
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.UpdateIdentityMap(InternalEntityEntry entry, IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)


```

### Further technical details

MySQL version: 5.7.17 - MySQL Community Server (GPL) 
Operating system: Windows 10, but accessing a a remote web server - details are
     Microsoft-IIS/8.5
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.0.20
Pomelo.EntityFrameworkCore.MySql version: 2.0.1-preview-10068

Other details about my project setup:

**Comment by mguinness** [comment]
Take a look at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/379 and see if setting MaxBatchSize helps.

**Comment by JonPSmith** [comment]
Hi @mguinness,

Yep, that fixed it! Thanks. I'll close this issue.
