### ISSUE TITLE
FSharp dotnetcore2.0 app got an error: Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'

### ISSUE THREAD

**Issue by zaaack** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#408]
### Steps to reproduce
Create a simple code-first app got an error when database is already exists. But if database doesn't exists, it can create the database and tables.
### The issue

```
Exception message:
Stack trace:
$ dotnet run --project ./src/Server/Server.fsproj
/Users/z/Projects/Strawberry/strawberry-backend/src/Server/Server.fsproj : warning NU1701: Package 'MySql.Data 6.9.9' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/Users/z/Projects/Strawberry/strawberry-backend/src/Server/Server.fsproj : warning NU1701: Package 'MySql.Data 6.9.9' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.<HasTables>b__13_0(IMySqlRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at ServerCode.Program.testDb() in /Users/z/Projects/Strawberry/strawberry-backend/src/Server/Program.fs:line 23
   at ServerCode.Program.main(String[] args) in /Users/z/Projects/Strawberry/strawberry-backend/src/Server/Program.fs:line 34

```

### Further technical details

MySQL version: mariadb:10.3.2
Operating system: macos/linux
Pomelo.EntityFrameworkCore.MySql version:2.0
Microsoft.EntityFrameworkCore version: 2.0

Other details about my project setup:
Scaffold : https://github.com/SAFE-Stack/SAFE-BookStore
My model:
```F#
module ServerCode.Models.User

open System
open System.Collections.Generic
open System.Linq
open System.ComponentModel
open System.ComponentModel.DataAnnotations
open System.ComponentModel.DataAnnotations.Schema
open Microsoft.EntityFrameworkCore
[<Table("User")>]
type User() = 
    [<Key>]
    member val id: int64 = 0L with get, set
    [<Column(TypeName="varchar(255)")>]
    member val username = "" with get, set
    [<Column(TypeName="varchar(255)")>]
    member val password = "" with get, set
```

My DBContext:

```F#
module ServerCode.Models.MyContext

open System
open System.Collections.Generic
open System.Linq
open System.ComponentModel.DataAnnotations
open System.ComponentModel.DataAnnotations.Schema
open Microsoft.EntityFrameworkCore
open ServerCode.Models.User

type MyContext() =
    inherit DbContext()
    member val Users: DbSet<User> = null with get, set

    override this.OnConfiguring (optionsBuilder: DbContextOptionsBuilder): unit =
            optionsBuilder
                .UseMySql(@"Server=localhost;database=ef;uid=root;pwd=123456;charset=utf8mb4") |> ignore
```

my Test code:

```F#
open ServerCode.Models.MyContext
open ServerCode.Models.User


let testDb() =
    use context = new MyContext()
    context.Database.EnsureCreated() |> printfn "%A" // remove this line also can working with database-first mode.
    let user = User()
    user.username <- "哈哈"
    user.password <- "bb"
    context.Add(user) |> printfn "%A"
    context.SaveChanges() |> printfn "%A"
    ()
```

**Comment by mguinness** [comment]
Can you share your database schema for User table?

**Comment by zaaack** [comment]
@mguinness I'm trying code-first mode, there is no database created before. Here is a working-pre-created database schema:

```sql
/*
 Navicat Premium Data Transfer

 Source Server         : mariadb
 Source Server Type    : MySQL
 Source Server Version : 50505
 Source Host           : localhost
 Source Database       : ef

 Target Server Type    : MySQL
 Target Server Version : 50505
 File Encoding         : utf-8

 Date: 10/18/2017 11:00:51 AM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `User`
-- ----------------------------
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(255) CHARACTER SET utf8mb4 DEFAULT 'NULL',
  `username` varchar(255) CHARACTER SET utf8mb4 DEFAULT 'NULL',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;

```

**Comment by mguinness** [comment]
@zaaack Currently there is a datatype mismatch.  Either your id field in db should be bigint, or your member in model should be Int32.

**Comment by zaaack** [comment]
@mguinness I think about this before, but the database is created by EFCore, and id's datatype is int, the id in user model is also int. 

The code above can work normally if I remove this line:

```F#
context.Database.EnsureCreated() |> printfn "%A"
```

this method should update database schema based on model schema, but throw an error.

**Comment by caleblloyd** [comment]
Please try upgrading to 2.1.1 and open a new issue if the problem persists
