### ISSUE TITLE
ObjectDisposedException when reading RecordsAffected

### ISSUE THREAD

**Issue by ajcvickers** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#418]
See issue filed here on EF: https://github.com/aspnet/EntityFrameworkCore/issues/10147

We're putting code in the patch to workaround these issues (https://github.com/aspnet/EntityFrameworkCore/pull/10151), but it seems like they should really be fixed in the MySQL provider.

Full text of original issue:

The following simple case, which worked in 2.0.0, throws a NullReferenceException in the new preview:

```
var context = services.GetRequiredService<VolunteerDbContext>();
context.Database.Migrate();
```

Note that it happen with any of my DbContexts, not just the one shown above.
The exception is as follows:

```
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at TestAspNetCore.Program.Main(String[] args)
```

Additionally, when executing a CountAsync and a ToListAsync the following exceptions are thrown, respectively:

```
Microsoft.EntityFrameworkCore.Query: Error: An exception occurred in the database while iterating the results of a query for context type 'TestAspNetCore.Model.VolunteerDbContext'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.Dispose()
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<GetResult>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()

Microsoft.EntityFrameworkCore.Query: Error: An exception occurred in the database while iterating the results of a query for context type 'TestAspNetCore.Model.VolunteerDbContext'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WrappedMySqlDataReader'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.GetReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.get_RecordsAffected()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.Dispose()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.Dispose()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()

```

### Further technical details
EF Core version: 2.0.1-rtm-203
Database Provider: Pomelo.EntityFrameworkCore.MySql (version 2.0.0 as well as 2.0.1-preview-10072)
Operating system: Windows 7 x64
IDE: Visual Studio 2017 15.4.1

**Comment by divega** [comment]
@ajcvickers any clues on whether the issue could be in the EF Core provider layer or in the ADO.NET provider?

**Comment by smitpatel** [comment]
Issue is here:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/a4325caedc24bcd4cf59cb3ae6b8a1940a53f2c9/src/EFCore.MySql/Storage/Internal/MySqlRelationalCommand.cs#L54

In ExecuteAsync method DbCommand is being used inside "using" block which disposes the command right away. In our pipeline we dispose command in `ExecuteAsync` if no reader. If there reader then dispose happens inside `RelationalDataReader`.
Our newly added code to clear parameters started throwing because command was already disposed.

**Comment by caleblloyd** [comment]
Pomelo.EntityFrameworkCore.MySql buffers everything upon calling ExecuteReader.  Since MySQL does not support Multiple Active Result Sets, this is how we get around it.

If we delay disposing `dbCommand` until Entity Framework's reader has used it, the underlying connection will be sitting around unable to be re-used even though it has already buffered everything and can be closed.

**Comment by smitpatel** [comment]
@caleblloyd - I am bit confused.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/a4325caedc24bcd4cf59cb3ae6b8a1940a53f2c9/src/EFCore.MySql/Storage/Internal/MySqlRelationalConnection.cs#L37

Above code says that MySQL supports MARS. If it does not then you should just set that flag as false. EFCore has mechanism to buffer queries automatically when MARS is not supported so that there are not multiple readers.

**Comment by bgrainger** [comment]
@caleblloyd I'd much rather have EF do the buffering than MySqlConnector. (Don't know if we should go so far as removing `BufferResultSets` and deleting all the related code, but it would definitely make things simpler in the connector...)

**Comment by caleblloyd** [comment]
@bgrainger I agree that it is nicer to have EF do it in this situation.  I'm about to make the change to use EF's buffering and set `BufferResultSets` back to the default.

I'm [not seeing BufferResultSets](https://github.com/search?q=BufferResultSets%3Dtrue&type=Code&utf8=%E2%9C%93) used anywhere except here on GitHub.  I think it would probably be safe to remove if there's no other good reason to keep it around.

**Comment by caleblloyd** [comment]
@smitpatel thanks for the heads up about EF supporting buffering now.  We added buffering to MySqlConnector to workaround this back in the EF 1.x days.

I've opened #419 to remove buffering in the driver, set `IsMultipleActiveResultSetsEnabled => false`, and fix this issue with double dispose.

**Comment by smitpatel** [comment]
Thanks @caleblloyd @Kagamine for updating this in provider. I tested latest dev with 2.0.1 patch of EF (which was failing) and everything is working now.
