### ISSUE TITLE
Array is not long enough

### ISSUE THREAD

**Issue by SharpNoiZy** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#42]
I received a Exception which I can not describe.
I don't know what the reason is, I just know with EF 6 and the official MySQL provider the access works on the same db with the same EF configurations.

Maybe you find something by the stacktrace.

System.ArgumentException: Array is not long enough. Check array index and length.
Parameter name: value
   at System.BitConverter.ToInt64(Byte[] value, Int32 startIndex)
   at Pomelo.Data.MySql.NativeDriver.GetResult(Int64& affectedRow, Int64& insertedId)
   at Pomelo.Data.MySql.Driver.NextResult(Int32 statementId, Boolean force)
   at Pomelo.Data.MySql.MySqlDataReader.NextResult()
   at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)

### Further technical details

MySQL version: 5.6.22 
Operating system: Windows Server 2012 R2
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

Kind regards

**Comment by Kagamine** [comment]
Can you paste your code here?

**Comment by Kagamine** [comment]
We've released 1.0.1-prerelease-10001, please try to use the latest version. If the issue still occur, please reopen this.

https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.0.1-prerelease-10001
