### ISSUE TITLE
Error in migration going from 1.1.2 to 2.0.0.1 provider for Id column involved in FK relation

### ISSUE THREAD

**Issue by dls314** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#423]
### Steps to reproduce
1. Create migrations for IdentityServer4.EntityFramework version 1.0.1 using Pomelo.EntityFrameworkCore.MySql version 1.1.2
2. Upgrade both IdentityServer4.EntityFramework (to version 2.0.0) and Pomelo.EntityFrameworkCore.MySql (to version 2.0.0.1)
3. Add migrations for the ConfigurationDbContext changes between IdentityServer4.EntityFramework-1.0.1 and IdentityServer4.EntityFramework-2.0.0
4. Try to create/update database with the resulting migrations

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot change column 'Id': used in a foreign key constraint 'FK_IdentityClaims_IdentityResources_IdentityResourceId' of table ...

Stack trace: 
Applying migration '00000000000000_ModifyConfigurationSchema'.
Applying migration '20171030203140_IdentityServer4-2.0.2'.
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `IdentityResources` MODIFY COLUMN `Id` int NOT NULL;
ALTER TABLE `IdentityResources` ALTER COLUMN `Id` DROP DEFAULT;
MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot change column 'Id': used in a foreign key constraint 'FK_IdentityClaims_IdentityResources_IdentityResourceId' of table 'identity_service.IdentityClaims' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot change column 'Id': used in a foreign key constraint 'FK_IdentityClaims_IdentityResources_IdentityResourceId' of table 'identity_service.IdentityClaims'
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot change column 'Id': used in a foreign key constraint 'FK_IdentityClaims_IdentityResources_IdentityResourceId' of table 'identity_service.IdentityClaims'
```

### Further technical details

MySQL version: mysqld 10.2.9-MariaDB-10.2.9+maria~jessie
Operating system: dockerized mariadb:10.2 from https://hub.docker.com/_/mariadb/
Pomelo.EntityFrameworkCore.MySql version: 2.0.0.1 (also same behavior in 2.0.0)

Other details about my project setup:
Upgrade scenario as per the steps to reproduce.

**Comment by dls314** [comment]
Maybe related to
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/362
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/364
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/370

**Comment by caleblloyd** [comment]
Looks like MySQL doesn't support dropping a default value if a field is used in a foreign key constraint.

You need to manually add code in your migration to disable foreign key checks or drop the foreign keys, run the migration, then add them back.
