### ISSUE TITLE
To support generate idempotent migration script

### ISSUE THREAD

**Issue by thisroot** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#424]
This is my error, or this version does not support publish migration
Error  Message: Generating idempotent scripts for migration is not currently supported by MySql
Trace:
```bigdog -> C:\Users\User\documents\visual studio 2017\Projects\bigdog\bigdog\obj\Release\netcoreapp2.0\PubTmp\Out\
Generating Entity framework SQL Scripts...
Executing command: dotnet ef migrations script --idempotent --output "C:\Users\User\documents\visual studio 2017\Projects\bigdog\bigdog\obj\Release\netcoreapp2.0\PubTmp\EFSQLScripts\bigdog.Data.ApplicationDbContext.sql" --context bigdog.Data.ApplicationDbContext 
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\User\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'ApplicationDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
System.NotSupportedException: Generating idempotent scripts for migration is not currently supported by MySql
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MySqlHistoryRepository.GetBeginIfNotExistsScript(String migrationId)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, Boolean idempotent)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, Boolean idempotent, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Generating idempotent scripts for migration is not currently supported by MySql

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(93,5): Ошибка : Entity framework SQL Script generation failed```

**Comment by Kagamine** [comment]
As the error said ` Generating idempotent scripts for migration is not currently supported by MySql`

**Comment by mguinness** [comment]
FWIW, the Npgsql provider added support for idempotence with commit [0ed798c](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/commit/0ed798c834b008ed53b270d3946b4d283b45fc1e) which may help someone who wishes to look into this further.

**Comment by sirajmansour** [comment]
👍 to adding support for this.

**Comment by mguinness** [comment]
@sirajmansour There are no plans to add support for this at this time, but since this is marked up for grabs a PR can be submitted.
