### ISSUE TITLE
Retry Code throws NRE; does not match upstream

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#443]
The Retry Related code that was added in #425 and #431 throws a NRE if no database is reachable.

There are also some files that have fallen out of sync with upstream EF Core and are making it hard to track changes.

Here is the NRE:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCore.MySql.Internal.MySqlRetryNoDependendiciesExecutionStrategy.Execute(Action action) in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Internal/MySqlRetryNoDependendiciesExecutionStrategy.cs:line 100
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlConnectionSettings.<>c__DisplayClass2_0.<GetSettings>b__0(String key) in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs:line 40
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlConnectionSettings.GetSettings(String connectionString, MySqlRetryNoDependendiciesExecutionStrategy mySqlRetryNoDependendiciesExecutionStrategy) in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs:line 34
   at Microsoft.EntityFrameworkCore.Internal.MySqlOptions.<.ctor>b__3_0() in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Internal/MySqlOptions.cs:line 32
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.MySqlOptions.get_ConnectionSettings() in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Internal/MySqlOptions.cs:line 57
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlSmartTypeMapper.MaybeConvertMapping(RelationalTypeMapping mapping) in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Storage/Internal/MySqlSmartTypeMapper.cs:line 55
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlSmartTypeMapper.FindMapping(Type clrType) in /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Storage/Internal/MySqlSmartTypeMapper.cs:line 43
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapper.IsTypeMapped(Type clrType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.IsCandidatePrimitiveProperty(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextInfo(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetContextInfoImpl(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.GetContextInfo.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

**Comment by xcellsoft** [comment]
I see 2 changes.

1) MySqlTransientExceptionDetector.cs - you removed a broad range of errors and put in a specific set, that is fine.

2) MySqlConnectionSettings.cs - you removed the hack with MySqlRetryNoDependendiciesExecutionStrategy, this is okay if you resolved having the connection.Open() wrapped in an executionstrategy. Previously this connection.Open() was outside of the entity framework core built in executionstrategy, which is why i created the manual execution strategy. To test just make set your connection string to an invalid endpoint, set a break-point on this open and see if it retries..

**Comment by caleblloyd** [comment]
Re 1: I limited it to actual transient errors, mainly deadlock and transaction related code.  This isn't going to help with flaky connections, which I believe may have been your original goal.  I think that you can extend `MySqlRetryingExecutionStrategy` to achieve retrying for other error codes, see this [SQL Server Test Case](https://github.com/aspnet/EntityFrameworkCore/blob/1c8c8aa08b3ced138e5bd34dfe17b6bcca419a35/test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs) for examples

Re 2: Code in `MySqlConnectionSettings.cs` runs once per connection string and is cached.  The introduction of an additional class for such a small codepath is a lot of maintenance overhead and I don't think it is needed.

**Comment by xcellsoft** [comment]
That small code path is the one that is called on the first database request for the context which would be for every http request (if using scoped), using .net core as webapi there will be a large volume of those and i would think this would be one of the most critical areas. It would defeat the retry strategy purpose if it is not handled. It would be nice if that connection.open wasn't even in there so that everything would fall in the standard execution strategy mechanism. I don't know enough of the history as to it was there to refactor any of it.

**Comment by caleblloyd** [comment]
`MySqlConnectionSettings` solves a bit of a chicken and egg problem in this library.  We need to know what MySql server version we are talking to in order to use the proper types in the [MySqlSmartTypeMapper](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/f4d48219ebaef321561e5a53dfc7458209b1b7b0/src/EFCore.MySql/Storage/Internal/MySqlSmartTypeMapper.cs).  Since any calls that go through the full library already require the Type Mapper, we have to use normal ADO.NET calls in `MySqlConnectionSettings`.

The [Settings cache object is static](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/1b1fbdcdf7f243d778b4fe32cc57998793f16e2e/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs#L15-L16)

The call to `GetSettings` does a [GetOrAdd](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/1b1fbdcdf7f243d778b4fe32cc57998793f16e2e/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs#L33) on the Dictionary with a key of the Connection String.

This call will only happen once per Connection String over the lifetime of a process.  Consider the following program that prints "Get Settings" when the actual code is invoked:

250 HTTP Requests are processed:

```
$ ./scripts/stress.sh 
Rate = 50 RPS
Duration = 5s
Targets = targets-async.txt
Requests      [total, rate]            250, 50.20
Duration      [total, attack, wait]    4.991907521s, 4.979999941s, 11.90758ms
Latencies     [mean, 50, 95, 99, max]  12.747282ms, 12.083865ms, 23.067064ms, 30.041132ms, 34.845092ms
Bytes In      [total, mean]            5430376, 21721.50
Bytes Out     [total, mean]            182206, 728.82
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:250  
```

"Get Settings" is only printed once:

```
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
Get Settings
```
