### ISSUE TITLE
Migrating and Deleting Two Databases Throws Exception

### ISSUE THREAD

**Issue by whatjakecodes** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#457]
### Steps to reproduce
I am running unit tests in .NET Core 2.0.3 using XUnit, EF Core 2.0, and Pomelo 2.0.1. In my tests, I setup a new database for every test so that the test can run in an isolated environment. After the test run, the database is deleted. Here is my BaseTest class that all other test classes inherit from:

```
public class BaseTest : IDisposable
{
    protected string connectionString;

    public BaseTest()
    {
        var guid = Guid.NewGuid();
        this.connectionString = $"Server=localhost;database=my_test_{guid};uid=root;Pooling=false";
        using (var context = CreateTestDbContext())
        {
            context.Database.Migrate();
        }
    }

    public void Dispose()
    {
        using (var context = CreateTestDbContext())
        {
            context.Database.EnsureDeleted();
        }
    }

    protected MyDbContext CreateTestDbContext()
    {
        var optionsBuilder = new DbContextOptionsBuilder<MyDbContext>();
        optionsBuilder.UseMySql(this.connectionString);
        var testContext = new MyDbContext(optionsBuilder.Options);
        return testContext;
    }
}
```

### The issue
When I run two tests (either `dotnet test` or `dotnet xunit`), the second test ALWAYS fails. The first test successfully creates and disposes of the first database. When the second test hits the `context.Database.Migrate();` line, however, I get the below exception. For some reason, the migration is trying to update the FIRST database a second time, but it does not exist because the first test called `.EnsureDeleted()` on it.

I expect the second test to only migrate the database with the second GUID. I noticed using `.EnsureCreated()` instead of `.Migrate()` does NOT have this issue. My use case prefers Migrate() however.

```

MySql.Data.MySqlClient.MySqlException : Unknown database 'my_test_5e8d367c-59ba-4f90-a9e4-8f34b0154e67'
      Stack Trace:
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
        C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs(251,0): at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs(365,0): at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs(160,0): at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs(137,0): at MySql.Data.MySqlClient.MySqlConnection.Open()
           at Microsoft.EntityFrameworkCore.Internal.MySqlOptions.GetCreateTable(String connectionString, ISqlGenerationHelper sqlGenerationHelper, String table, String schema)
           at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
           at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__63_20(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
           at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
           at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
           at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
           at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
           at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
           at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
        /Users/meUser/workspace/my/test/MyWebUnitTest/BaseTest.cs(44,0): at MyWebUnitTest.BaseContextUnitTest.MigrateDatabase()
        /Users/meUser/workspace/my/test/MyWebUnitTest/Managers/InterviewManagerTests.cs(21,0): at MyWebUnitTest.Managers.InterviewManagerTests..ctor()
           at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

### Further technical details

MySQL version: 5.7.20
Operating system:  macOS 10.12.3
Pomelo.EntityFrameworkCore.MySql version: 2.0.3

Other details about my project setup: .NET Core 2.0, EF Core 2.0

**Comment by whatjakecodes** [comment]
To add to this, even when using CreateDatabase in my TestClass constructor to setup the database, there is a flakey error where occasionally I get a `System.ObjectDisposedException : Cannot access a disposed object.` error. Stack trace below:

```
[MyTest.Api.MyApiTests.DownloadFile_IfMissingCookie_RedirectsToLogin] MySql.Data.MySqlClient.MySqlException : Connect Timeout expired.
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at MySqlConnector.Core.ServerSession.<OpenTcpSocketAsync>d__69.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 620
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 137
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.Delete()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at MyTest.BaseFunctionalTest.System.IDisposable.Dispose() in /Users/userMe/Documents/buildAgent/work/c0dac30dfdf9b5f0/test/MyTest/BaseFunctionalTest.cs:line 205
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
   at MySqlConnector.Core.ServerSession.<OpenTcpSocketAsync>d__69.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 607
```

**Comment by yukozh** [comment]
I don't think we have published 2.0.3. Please correct the version.

**Comment by nonoandy** [comment]
> To add to this, even when using `.EnsureCreated()` in my TestClass constructor to setup the database, there is a flakey error where occasionally I get a `System.ObjectDisposedException : Cannot access a disposed object.` error. Stack trace below:
> 
> ```
> [MyTest.Api.MyApiTests.DownloadFile_IfMissingCookie_RedirectsToLogin] MySql.Data.MySqlClient.MySqlException : Connect Timeout expired.
> ---- System.ObjectDisposedException : Cannot access a disposed object.
> Object name: 'System.Net.Sockets.Socket'.
>    at MySqlConnector.Core.ServerSession.<OpenTcpSocketAsync>d__69.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 620
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 205
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 365
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 137
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.Delete()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
>    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
>    at MyTest.BaseFunctionalTest.System.IDisposable.Dispose() in /Users/userMe/Documents/buildAgent/work/c0dac30dfdf9b5f0/test/MyTest/BaseFunctionalTest.cs:line 205
>    at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
> ----- Inner Stack Trace -----
>    at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
>    at MySqlConnector.Core.ServerSession.<OpenTcpSocketAsync>d__69.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 607
> ```

did you fix this issues?

**Comment by lauxjpn** [comment]
@nonoandy There are no known issues with `EnsureCreated()`. I use it in all my code samples here on our repo. Do you have any concrete issues?
