### ISSUE TITLE
Down() migration throws NullReferenceException when switching PrimaryKey

### ISSUE THREAD

**Issue by JulianKlauser** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#465]
### Steps to reproduce
New .Net Core 2 Cli Project with the following class:
```
public class Test
{
        public int Id1 { get; set; }
	public int Id2 { get; set; }
}
```
and with a DbContext with OnModelCreating:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Test>().HasKey(test => test.Id1);
}
```

-  After adding an initial migration with `dotnet ef migrations add Initial` change the PK to Id2 with `modelBuilder.Entity<Test>().HasKey(test => test.Id2);` in the DbContext.
- Add another migration with `dotnet ef migrations add PkChange`.
- Apply both migrations to the database with `dotnet ef database update`.
- Revert to Initial migration with `dotnet ef database update Initial`

### The issue
When reverting the migration that changes the primary key before the first SQL is executed a NullReferenceException is thrown.

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(AddPrimaryKeyOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__63_2(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_1.<GetMigrationCommandLists>b__1()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

The remarkable thing is, when runing  `dotnet ef database update 0` (meaning **both** migrations call the Down() function) it gets executed correctly.
I also tried creating a new migration and copying the code from `Down()` into its `Up()` and it also gets executed correctly.

### Further technical details

MySQL version: MariaDB 10.1.22
Operating system: Windows 10 (Build 16299.125)
Pomelo.EntityFrameworkCore.MySql version: v2.0.1

Other details about my project setup:
Microsoft.EntityFrameworkCore version: v2.0.1

**Comment by caleblloyd** [comment]
Let's work this issue as part of #504
