### ISSUE TITLE
unknown field int field list

### ISSUE THREAD

**Issue by linusaurus** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#469]
### Steps to reproduce
Unit test basic efcore read write to single table Mysql

### The issue
Describe what is not working as expected.

I have checked the POCO classes thoroughly, and can find no difference in the classes or the Mysql table.

   [TestMethod]
        public void TestGetInventory()
        {
            var ctx = new BadgerData.DataAccess.BadgerDataContext();
            var parts = ctx.Inventory.ToList();
            Assert.IsTrue(parts.Count > 0);
        }

    public class PurchaseLineItem
    {
        public int LineID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int? JobID { get; set; }
        public int? PartID { get; set; }
        public decimal? UnitCost { get; set; }
        public string Description { get; set; }
        public decimal? Qnty { get; set; }
        public decimal? Extended { get; set; }
        public bool? Recieved { get; set; }
        public int? UnitOfMeasureID { get; set; }
        public int? RequisitionID { get; set; }
        public decimal? Width { get; set; }
        public decimal? Length { get; set; }
        public decimal? Thick { get; set; }
        public decimal? Weight { get; set; }
        public string SupplierPartName { get; set; }
        public string BCode { get; set; }
        public string Note { get; set; }

        public PurchaseOrder PurchaseOrder { get; set; }
    }

CREATE TABLE `PurchaseLineItem` (
  `LineID` int(11) NOT NULL AUTO_INCREMENT,
  `PurchaseOrderID` int(11) DEFAULT NULL,
  `JobID` int(11) DEFAULT NULL,
  `PartID` int(11) DEFAULT NULL,
  `UnitCost` decimal(18,4) DEFAULT '0.0000',
  `Description` varchar(512) DEFAULT ' ',
  `Qnty` decimal(18,4) DEFAULT '1.0000',
  `Extended` decimal(18,4) DEFAULT '0.0000',
  `Recieved` tinyint(1) DEFAULT '0',
  `UnitOfMeasureID` int(11) DEFAULT NULL,
  `RequisitionID` int(11) DEFAULT NULL,
  `Width` decimal(18,4) DEFAULT '0.0000',
  `Length` decimal(18,4) DEFAULT '0.0000',
  `Thick` decimal(18,4) DEFAULT '0.0000',
  `Weight` decimal(18,4) DEFAULT '0.0000',
  `SupplierPartName` char(120) CHARACTER SET utf8mb4 DEFAULT '',
  `BCode` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Note` varchar(254) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`LineID`),
  KEY `FK_PurchaseLineItem_PurchaseOrder` (`PurchaseOrderID`),
  CONSTRAINT `FK_PurchaseLineItem_PurchaseOrder` FOREIGN KEY (`PurchaseOrderID`) REFERENCES `PurchaseOrder` (`PurchaseOrderID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=36482 DEFAULT CHARSET=latin1;

Exception message:
Test Name:	TestGetPurchaseLineItems
Test FullName:	BadgerDataTest.BasicDataAccess.TestGetPurchaseLineItems
Test Source:	C:\Users\rich.DESIGNSYNTHESIS\Source\Repos\BadgerData\BadgerDataTest\UnitTest1.cs : line 53
Test Outcome:	Failed
Test Duration:	0:00:00.6056945

Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 43
--- End of inner exception stack trace ---
    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 92
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__65.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 297
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__64.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 172
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BadgerDataTest.BasicDataAccess.TestGetPurchaseLineItems() in C:\Users\rich.DESIGNSYNTHESIS\Source\Repos\BadgerData\BadgerDataTest\UnitTest1.cs:line 58
Result Message:	
Test method BadgerDataTest.BasicDataAccess.TestGetPurchaseLineItems threw exception: 
MySql.Data.MySqlClient.MySqlException: Unknown column 'p.PurchaseOrderID1' in 'field list' ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'p.PurchaseOrderID1' in 'field list'
Stack trace:
```

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:

Other details about my project setup:

**Comment by mguinness** [comment]
`MySql.Data.MySqlClient.MySqlException: Unknown column 'p.PurchaseOrderID1' in 'field list'`

**Comment by AngelVlc** [comment]
I've the same problem when the table has a foreign key.

**Comment by ChristianHaase** [comment]
I'm getting same exception using asp.net identity. Trying to receive a user:

> Unknown column 'x.UserProfile.Roles.UserId1' in 'field list'

`UserProfile` inherits from `IdentityUser` and roles is just the default `IdentityRole`

**Comment by mguinness** [comment]
If someone can share a repo with the recreate that can be cloned and run we can investigate.

**Comment by caleblloyd** [comment]
Closing due to issue age; please open more detailed issue with recreate if problem persists
