### ISSUE TITLE
Scaffolding not working

### ISSUE THREAD

**Issue by GardSteinsvik** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#490]
### Steps to reproduce
Starting out with a clean ASP.NET Core Web Application with MVC in Visual Studio 2017.

From Visual Studio's Package Manager Console:
```
Scaffold-DbContext "Server=servername;User Id=root;Password=password;Database=dbname" Pomelo.EntityFrameworkCore.MySql -OutputDir Models
```

MySQL schema:
```
-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 15:05:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbname
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbname` DEFAULT CHARACTER SET utf8 ;
USE `dbname` ;

-- -----------------------------------------------------
-- Table `dbname`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbname`.`person` ;

CREATE TABLE IF NOT EXISTS `dbname`.`person` (
  `personID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`personID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dbname`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbname`.`car` ;

CREATE TABLE IF NOT EXISTS `dbname`.`car` (
  `carID` INT NOT NULL AUTO_INCREMENT,
  `licenseNumber` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `person_personID` INT NOT NULL,
  PRIMARY KEY (`carID`),
  INDEX `fk_car_person_idx` (`person_personID` ASC),
  CONSTRAINT `fk_car_person`
    FOREIGN KEY (`person_personID`)
    REFERENCES `dbname`.`person` (`personID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
```

### The issue
Scaffolding not working properly. No models are produced with the simple 2 table database. If I remove the car table, it works fine with no errors.

```
Exception message:
Stack trace:
Using project 'TestApp'.
Using startup project 'TestApp'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\users\m6800\source\repos\TestApp\TestApp\bin\Debug\netcoreapp2.0\TestApp.deps.json --additionalprobingpath C:\Users\M6800\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft SDKs\NuGetPackagesFallback" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\users\m6800\source\repos\TestApp\TestApp\bin\Debug\netcoreapp2.0\TestApp.runtimeconfig.json "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.0.1\tools\netcoreapp2.0\ef.dll" dbcontext scaffold "Server=servername;User Id=root;Password=password;Database=dbname" Pomelo.EntityFrameworkCore.MySql --json --output-dir Models --verbose --no-color --prefix-output --assembly C:\users\m6800\source\repos\TestApp\TestApp\bin\Debug\netcoreapp2.0\TestApp.dll --startup-assembly C:\users\m6800\source\repos\TestApp\TestApp\bin\Debug\netcoreapp2.0\TestApp.dll --project-dir c:\users\m6800\source\repos\TestApp\TestApp\ --root-namespace TestApp
Using assembly 'TestApp'.
Using startup assembly 'TestApp'.
Using application base 'C:\users\m6800\source\repos\TestApp\TestApp\bin\Debug\netcoreapp2.0'.
Using working directory 'c:\users\m6800\source\repos\TestApp\TestApp'.
Using root namespace 'TestApp'.
Using project directory 'c:\users\m6800\source\repos\TestApp\TestApp\'.
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
Using design-time services from provider 'Pomelo.EntityFrameworkCore.MySql'.
Finding IDesignTimeServices implementations in assembly 'TestApp'...
No design-time services were found.
Error assigning index for `car`.
fail: EntityFramework.Commands[0]
      Error assigning index for `car`.
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at MySqlConnector.Core.Row.GetBoolean(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 79
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetIndexes()
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no matching element
```

### Further technical details

MySQL version: 8.0.3-rc
Operating system: Microsoft Windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by mguinness** [comment]
Unable to repro.  Maybe due to MySQL 8.0 - try again using MySQL 5.7.

**Comment by mguinness** [comment]
Confirmed issue with MySQL 8.0, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/494.

**Comment by mguinness** [comment]
Change was merged, but not published.

**Comment by wchiquito** [comment]
Using `2.0.2-preview-10088` works as expected.
