### ISSUE TITLE
Exception after updating to 2.1-*preview

### ISSUE THREAD

**Issue by p3root** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#502]
I have created a migration script and wanted to update the database.

Exception message:
Stack trace:
`PM> Update-Database
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WrappedMySqlDataReader'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.GetReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.get_RecordsAffected()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot access a disposed object.
Object name: 'WrappedMySqlDataReader'.`

The same exception occures at runtime when I want to access my database. If you need some repro code, I can provide some tomorrow.

p3

**Comment by boxofnotgoodery** [comment]
Same here.
I switched back to the MSSql provider and migrations work as expected

**Comment by allanxp4** [comment]
Happening here with any query, not only migrations. Same exceptions.

**Comment by caleblloyd** [comment]
Pomelo `2.0` is not compatible with EF Core `2.1`. We will publish a Pomelo `2.1` release. Continue to use Pomelo `2.0` with EF `2.0`

Typically patch releases of EF work fine, but major and minor updates will require some changes in the provider and we will publish a new Pomelo version to match.

**Comment by Giantaxe** [comment]
so, I followed the instructions on the readme.
My data library looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0-preview1-final" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.0-preview1-10085" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
</Project>
```

Now, I made a new .NET Core console app with this
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRM.Data\CRM.Data.csproj" />
  </ItemGroup>

</Project>
```
and in the startup.cs
```csharp
static void Main(string[] args)
{
	try
	{
		using (var db = new CRMContext("User Id=root;Password=root;Host=127.0.0.1;Database=my_db;CharSet=utf8mb4"))
		{
			int res = db.Relations.Count();
			Console.ForegroundColor = ConsoleColor.Green;
			Console.Write(res);
		}
	}
	catch (Exception ex)
	{
		Console.ForegroundColor = ConsoleColor.Red;
		Console.Write(ex);
	}
	Console.ReadKey();
}
```
results in:
```log
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WrappedMySqlDataReader'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.GetReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.WrappedMySqlDataReader.get_RecordsAffected()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.Dispose()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at EFTest.Program.Main(String[] args) in D:\Sourcecode\NetCore 2.1 Tests\EFTest\Program.cs:line 16
```
the Pomelo 2.1.0 preview does not actually work with EFCore 2.1 preview it seems.

**Comment by caleblloyd** [comment]
@Giantaxe I updated the README.md, you need to use `2.0.1` right now.  The README.md should not have had a preview reference, that was a mistake.

2.1.0-preview-* is not stable yet.  We're working on it, track the `2.1.0` milestone for progress

**Comment by caleblloyd** [comment]
Closing this, please track progress in the overarching 2.1.0 issue #514

**Comment by TechnikEmpire** [comment]
@caleblloyd How can we drop back to `2.0.1` when it's broken with .NET Core 2.1 preview? I'm assuming that you mean we can't use any version of this lib with .NET core 2.1 preview.

**Comment by mguinness** [comment]
2.1.0-preview-* is not stable yet and is currently blocked by https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/512#issuecomment-373572421.  We welcome any help with this effort if you can contribute.

**Comment by TechnikEmpire** [comment]
@mguinness I started looking at it to see if I could submit a PR but the work left to be done looks substantial, plus MS is just figuring out that they need to fix stuff on their end. I have way too much catching up to do in order to be effective any time soon unfortunately.
