### ISSUE TITLE
1.0.1 throw an exception which didn't happen in 1.0.0

### ISSUE THREAD

**Issue by ElderJames** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#52]
It throw an  exception when I upgrade the release to the 1.0.1-prerelease-10002:

> Unable to cast object of type 'System.Decimal' to type 'System.Int32'.

**Comment by Kagamine** [comment]
@bgrainger Is decimal supported in MySqlConnector?

**Comment by ElderJames** [comment]
@Kagamine  Here is the stack trace:
```
   at MySql.Data.MySqlClient.MySqlDataReader.GetInt32(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YunGo.Indiana.MobiApi.Controllers.ChargeController.<GetLevel>d__2.MoveNext() in D:\YunGo\YunGo.Indiana\src\YunGo.Indiana.MobiApi\Controllers\ChargeController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
```

**Comment by bgrainger** [comment]
Yes, `MySqlConnector` supports `DECIMAL` columns; the issue here appears to be that it's being mapped to an `int`, so `GetInt32` is being called for the decimal column (which seems like a possible incorrect or lossy mapping)? MySqlConnector's numeric conversions are currently rather conservative; I've opened bgrainger/MySqlConnector#54 to investigate this.

**Comment by bgrainger** [comment]
@ElderJames what is the schema of the table you're querying, and what is the C# code that repros the bug? If you select this column into a variable of type `decimal`, does that resolve the issue?

**Comment by ElderJames** [comment]
In my code,the relationship between the C# type and the Mysql type is here:
| C# type | MySQL type|
| :-------: | :------------: |
| int         | int.               |
| string.   | char/varchar|
| enum.   | tinyint.         |         
| DateTime | datetime. |

I call the EF Core method "Where().FirstOrDefaultAsync()",and then throw that exception.

**Comment by bgrainger** [comment]
From the exception, it really seems like MySQL is reporting the column type as `DECIMAL`. Can you run the `mysql` console app and execute `describe [database].[table]`? Or run MySQL Workbench (GUI), right-click the table name, choose Copy To Clipboard > Create Statement. The paste the output from either one here.

**Comment by ElderJames** [comment]
It's my pleasure 😊,but the database is run on my company's server and I having a two-day holiday,so It seems to need the Kagamine's help😂

**Comment by Kagamine** [comment]
I will try to reproduce this issue tomorrow.

**Comment by ElderJames** [comment]
@bgrainger  Hi,here is the Create Statement, but can't found the column type as DECIMAL:
```
CREATE TABLE `one_redbag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `num` int(11) NOT NULL DEFAULT '0',
  `float_range` int(11) NOT NULL,
  `goods_range` varchar(255) DEFAULT NULL,
  `goods_describe` varchar(255) DEFAULT NULL,
  `premise_golds` int(11) NOT NULL DEFAULT '0',
  `charge_golds` int(11) DEFAULT '0',
  `limit_golds` int(11) NOT NULL,
  `give_num` int(11) NOT NULL,
  `used_num` int(11) NOT NULL,
  `give_golds` int(11) NOT NULL,
  `used_golds` int(11) NOT NULL,
  `type` tinyint(4) NOT NULL,
  `unit` tinyint(4) NOT NULL DEFAULT '0',
  `is_static` bit(1) NOT NULL,
  `can_get_num` int(11) NOT NULL DEFAULT '1',
  `get_interval` int(11) NOT NULL DEFAULT '0',
  `can_overlay` bit(1) NOT NULL,
  `is_one_time` bit(1) NOT NULL,
  `begin_time` datetime DEFAULT NULL,
  `validity_time` int(11) NOT NULL DEFAULT '0',
  `open_time` datetime NOT NULL,
  `close_time` datetime NOT NULL,
  `create_time` datetime NOT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;
```

**Comment by Kagamine** [comment]
@ElderJames Your code isnot generated by ef core. we need the code which generated by ef core.
