### ISSUE TITLE
Table 'Client' already exists

### ISSUE THREAD

**Issue by pantonis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#528]
### The issue
In my project I have added InitialCreate migration. Everything was working fine. Database was successfully created. Note in this migration Client was created
After a week I added a new table (Invoice) and I have run the command:

```
Add-Migration AddInvoice -Context MySqlContext -OutputDir Migrations\MySqlMigrations
```

Migration files were created. 
When I start my console app though I am getting an exception that Client already exists

My context is 
```

    public sealed class MySqlContext  : DbContext
    {
        public MySqlContext (DbContextOptions<MySqlContext > options)
            : base(options)
        {
            Database.Migrate();
        }

        public DbSet<Client> Client { get; set; }

        public DbSet<Invoice> Invoice { get; set; }        
    }

```
### If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:  Table 'Client' already exists
Stack trace:  MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Client' already exists
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
FATAL 2018-04-11 12:15:52,502 [1] roServices.Console.Program - FirstChance Exception  -- Table 'Client' already exists
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Client' already exists ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'Client' already exists
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
```

### Further technical details

MySQL version: 5.7
Operating system:  Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:

**Comment by mguinness** [comment]
Can you provide SQL generated using ```Script-Migration``` command?

**Comment by mguinness** [comment]
Closing due to no activity.

**Comment by Ukmandal** [comment]
Line 16:             DContext db = new DContext(); Line 17:  Line 18:             if (db.schoolroles.ToList().Count < 1) Line 19:             {  Line 20:                 SchoolRole role = new SchoolRole();
--
