### ISSUE TITLE
No value provided for required parameter '?ids'.

### ISSUE THREAD

**Issue by male110** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#531]
dbcontext.Database.ExecuteSqlCommand("delete from table where Id in ?ids", new MySqlParameter("?ids", proxyIds));

System.InvalidOperationException: No value provided for required parameter '?ids'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/467 for details regarding parameters.
