### ISSUE TITLE
Scaffold problem (System.InvalidOperationException: Sequence contains no matching element)

### ISSUE THREAD

**Issue by jllodra** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#546]
### Steps to reproduce
`Scaffold-DbContext "server=localhost;port=3306;user=root;password=root;database=rs_ui_db" Pomelo.EntityFrameworkCore.MySql -OutputDir Rs_ui_db -Tables apptypes,app`

### The issue
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Sequence contains no matching element
```

### Further technical details

MySQL version: 8.0.11
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:
DDL for the tables that are causing this issue:

![image](https://user-images.githubusercontent.com/273590/40323132-cd3da0e2-5d34-11e8-98b6-3628755fe3f0.png)

![image](https://user-images.githubusercontent.com/273590/40323174-e257410e-5d34-11e8-87a3-99877c15f85f.png)

Thank you.

PS: It works if I specify different tables, but "apps" and "apptypes" seem to be a problem.

**Comment by jllodra** [comment]
What can I say... 

I installed 2.1.0-preview1-10085 and now it's working.

Now I just have some warnings. I will leave them here, maybe they help you identifying bugs (or not).

![image](https://user-images.githubusercontent.com/273590/40326632-4452f014-5d40-11e8-9cd8-3d4242da5817.png)

Do you think I can manually add those skipped columns? They seem to be 'float unsigned', 'date' and 'enum'.

Thanks.

**Comment by VictorHaine** [comment]
If I'm not wrong, enum is not supported yet. See issue #36

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/490 regarding the exception.

**Comment by rasel-void** [comment]
@jllodra, Thanks man. I was finding solution of the same issue and settled by upgrading to 2.1.0. Quite a disturbing issue.
