### ISSUE TITLE
TINYINT(1) Boolean and SByte type mismatch

### ISSUE THREAD

**Issue by fmauNeko** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#577]
### Steps to reproduce
- Have a table which contains a TINYINT(1) column
- Have a model which binds this column to a property (declared as SByte or Boolean, both are broken)
- Query the database using this model

### The issue
The runtime throws on a type mismatch, because MySqlConnector returns a Boolean value for TINYINT(1) column (except if TreatTinyAsBoolean=false is appended to the connection string, but the default value of TreatTinyAsBoolean is true), and Pomelo.EntityFrameworkCore.MySql expects a SByte for all TINYINT columns.

To solve this, Pomelo.EntityFrameworkCore.MySql should either map TINYINT(1) columns to Boolean while keeping other TINYINT definitions as SByte if the connection string doesn't contains "TreatTinyAsBoolean=false", or enforce "TreatTinyAsBoolean=false".

```
Exception message: An exception occurred while reading a database value for property 'AgenceWeb.ColorText'. The expected type was 'System.SByte' but the actual value was of type 'System.Boolean'.
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at EFCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Eos.Api.Models.EosQuery.<>c__DisplayClass0_0.<.ctor>b__0(ResolveFieldContext`1 context) in E:\Code\eos\Eos.Api\Models\EosQuery.cs:line 65
   at GraphQL.Resolvers.FuncFieldResolver`2.GraphQL.Resolvers.IFieldResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Resolvers.FuncFieldResolver`1.GraphQL.Resolvers.IFieldResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Execution.ExecutionStrategy.<ExecuteNodeAsync>d__7.MoveNext()
```

### Further technical details

MySQL version: 8.0.11
Operating system: Up-to-date Arch Linux and Windows 10 1803
Pomelo.EntityFrameworkCore.MySql version: d93f46a

**Comment by mguinness** [comment]
Covered in the underlying library at https://github.com/mysql-net/MySqlConnector/issues/141 so closing this issue.

**Comment by fmauNeko** [comment]
Yes, I know about this and I had to add the parameter to my connection strings.
I was about the Pomelo.EntityFrameworkCore.MySql defaults being incompatible with the MySqlConnector defaults and whether Pomelo.EntityFrameworkCore.MySql should forcibly set TreatTinyAsBoolean=false, or even better, find a way to handle TINYINT(1) as Boolean if TreatTinyAsBoolean=true or isn't present in the connection string.
Or maybe at least document the caveat and if possible raise a less cryptic exception.

**Comment by mguinness** [comment]
> find a way to handle TINYINT(1) as Boolean if TreatTinyAsBoolean=true

This is how it should currently work, or are you not seeing that?

If you'd like to add a note in the README.md please create a PR and we'll look at inclusion.

**Comment by fmauNeko** [comment]
> This is how it should currently work, or are you not seeing that?
Well as I'm getting exceptions when not setting TreatTinyAsBoolean and I have to specify TreatTinyAsBoolean=false, and I spent half a day before finding this information, from my point of view there's an issue.

I'll take an in-depth look at this and open a PR.

Thanks for your time

**Comment by caleblloyd** [comment]
We map `sbyte` to `tinyint` by default, not `tinyint(1)`

We do set some default connection string types already here though:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7083319d9a8750104f010461a660e60ee9034117/src/EFCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs#L29-L56

If `TreatTinyAsBoolean=false` does not break anything by default, then I'm open to enabling it

**Comment by mguinness** [comment]
In Connector/Net [Connection-String Options Reference](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html) the setting `TreatTinyAsBoolean` defaults to true.

**Comment by mguinness** [comment]
Interestingly EF Core 2.1 is providing several built-in `ValueConverter` classes including [BoolToZeroOneConverter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.booltozerooneconverter-1).  I haven't tried it yet, but another option going forward.

**Comment by wenbinke** [comment]
any update for this ticket?

**Comment by AccessViolator** [comment]
@fmauNeko try tinyint(4) for sbyte. For bool behavior there's some info [here](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/654)

**Comment by ischipor** [comment]
I used TINYINT(2) or BIT(1) and worked. TINYINT(2) defaults to sbyte and BIT(1) defaults to bool

**Comment by clarity99** [comment]
So, is there any way to map a BOOL (tinying(1)) column in mysql to bool type in .net?

**Comment by lauxjpn** [comment]
@clarity99 That is the default from 3.0.0 onward. If you do not specify anything different in your connection string with `TreatTinyAsBoolean=SomeValue` or with a call to `MySqlDbContextOptionsBuilder.DefaultDataTypeMappings(m => ClrBoolean = SomeValue)`, then `tinyint(1)` will be mapped to `System.Boolean`.

See #909 and #875. For a discussion about the faulty implementation before 3.0.0, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/866#issuecomment-541349206.

Beware that the actual MySQL type `bool` is just there for compatibility with other 3rd party database systems, and maps (as you point out) to `tinyint(1)`. Pomelo only implements mapping of native MySQL data types, so MySQL's `tinyint(1)` is supported, while MySQL's `bool` is not.
