### ISSUE TITLE
Error to create model by context CodeFirst with Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by edisonmap** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#594]
### Steps to reproduce
1. PM> Add-Migration InitialCreateMySql
Process OK
2. Update-Database
Error.

### The issue
With:
PM> Update-Database
**I have this error:**
: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.0-rtm-30799 initialized 'BayteqContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlCommandBuilder..ctor(IDiagnosticsLogger`1 logger, IRelationalTypeMapper typeMapper)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlCommandBuilderFactory.CreateCore(IDiagnosticsLogger`1 logger, IRelationalTypeMapper relationalTypeMapper)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommandListBuilder..ctor(IRelationalCommandBuilderFactory commandBuilderFactory)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.

```
Exception message:
Stack trace: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
```

### Further technical details

MySQL version: 5.0.11
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1
Microsoft.EntityFrameworkCore: 2.1.0

Other details about my project setup:

**Comment by TriJetScud** [comment]
It's a known problem. This database provider was using internal code which the upstream EF Core ORM made changes to.

For now you'll have to install the 2.1.0-rc* branch of this database provider for it to work with EF Core 2.1. Since you don't have any existing migrations from the looks of it, you can safely use the RC for most workloads.

See Issue #591 and #590 for details with migrations created with the 2.0.x branch of this database provider.
