### ISSUE TITLE
Add Generated Column to Table

### ISSUE THREAD

**Issue by andy-clymer** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#599]
### Steps to reproduce
1. Create a new property on an existing entity model that has already had a migration generated for the creation of the corresponding db table for the entity model.

2. Configure the new property using FluentAPI to have a generated column in MySQL.

```
builder.Entity<User>()
    .Property(t => t.DisplayName)
    .HasColumnName("display_name")
    .HasComputedColumnSql("(CONCAT(last_name, ', ', first_name))");
```

3. Create a new migration to apply the changes to the db.

4. Run the migration.

### The issue
When applying the new migration, an error is thrown saying there is a SQL syntax error. To try and find the syntax error, I generated a script for the migration. The issue resides in the line below:

```
Syntax Error: NULL is in the wrong spot.
ALTER TABLE `users` ADD `display_name` longtext NULL AS (CONCAT(last_name, ', ', first_name));
```

If I edit the generated script file and change the line to what is below, everything works correctly.

```
No Syntax Error: Move null to the end of the line, and everything works.
ALTER TABLE `asp_net_users` ADD `display_name` longtext AS (CONCAT(last_name, ', ', first_name)) NULL;
```
```
Exception message:

An unhandled exception occurred while processing the request.
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS (CONCAT(last_name, ', ', first_name))' at line 1

Stack trace:

MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS (CONCAT(last_name, ', ', first_name))' at line 1 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS (CONCAT(last_name, ', ', first_name))' at line 1
   at MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1119
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 43
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 92
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 324
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 309
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 73
   at MySqlConnector.Core.TextCommandExecutor.ExecuteNonQueryAsync(String commandText, MySqlParameterCollection parameterCollection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 26
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQueryAsync(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at TestApp.Controllers.MigrateController.GetAsync() in Controllers\MigrateController.cs:line 33
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details

MySQL version: 8.0.11
Operating system: Windows 10 Pro Version 1803
Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc2-20180603202706

**Comment by caleblloyd** [comment]
Fixed in [2.1.0-rc2-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final)

**Comment by rcollette** [comment]
Does this mean that existing code like:

```c#
        //Row versioning see https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency
        [Timestamp]
        [Column("row_version", TypeName = "TIMESTAMP")]
        public DateTime RowVersion { get; set; }
```
Will have to be updated?  If so, that sounds like a breaking change to me that would warrant a major version bump.

**Comment by erik1980** [comment]
I'm testing the example in  https://docs.microsoft.com/en-us/ef/core/modeling/relational/computed-columns  using version 2.1.0-rc2-final of Pomelo.EntityFrameworkCore.MySql, with the modification below: 

modelBuilder.Entity<Person>()
.Property(p => p.DisplayName)
.HasComputedColumnSql("CONCAT(LastName,FirstName)");

When I update the database this error is shown:

Applying migration '20180807161400_Initial'.
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `People` (
    `PersonId` int NOT NULL AUTO_INCREMENT,
    `FirstName` varchar(50) NULL,
    `LastName` varchar(50) NULL,
    `DisplayName` longtext AS (CONCAT(LastName,FirstName)) NULL,
    CONSTRAINT `PK_People` PRIMARY KEY (`PersonId`)
);
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
    CONSTRAINT `PK_People` PRIMARY KEY (`PersonId`)
)' at line 5 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error inyour SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
    CONSTRAINT `PK_People` PRIMARY KEY (`PersonId`)
)' at line 5
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 44
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 298
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 283
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 73
   at MySqlConnector.Core.TextCommandExecutor.ExecuteNonQueryAsync(String commandText, MySqlParameterCollection parameterCollection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 26
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 60
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL,
    CONSTRAINT `PK_People` PRIMARY KEY (`PersonId`)
)' at line 5

**Comment by mguinness** [comment]
Column definitions vary between MySQL and MariaDB for generated columns:

[MySQL ref](https://dev.mysql.com/doc/en/create-table.html)
```
column_definition:
    data_type [GENERATED ALWAYS] AS (expression)
      [VIRTUAL | STORED] [NOT NULL | NULL]
      [UNIQUE [KEY]] [[PRIMARY] KEY]
      [COMMENT 'string']
```

[MariaDB ref](https://mariadb.com/kb/en/library/create-table/)
```
column_definition:
    data_type [GENERATED ALWAYS] AS { { ROW {START|END} } | { (expression) [VIRTUAL | PERSISTENT] } }
      [UNIQUE [KEY]] [COMMENT 'string']
```

As you can see, MariaDB does not permit NULL/NOT NULL in the definition.

**Comment by erik1980** [comment]
You are right but how can I do the migration for mariadb 10.x? [Here](https://docs.microsoft.com/en-us/ef/core/providers/) it says that Pomelo.EntityFrameworkCore.MySql that can be used for both databases (mysql and mariadb)

**Comment by mguinness** [comment]
Looking at [MySqlMigrationsSqlGenerator](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L966-L969) you can try adding `IsRequired()` to the field as a short term fix.  The long term solution would be to skip that code for MariaDB.

**Comment by erik1980** [comment]
yes, it's true, mariadb does not support NULL and NOT NULL in generated columns. it worked correctly adding IsRequired(). Thanks!!!
