### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by xjnxdwl** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#600]
## What happen ?
```
System.InvalidCastException:` Unable to cast object of type 'System.Int32' to type 'System.Int64'.
  at at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<HasTables>b__13_0(IMySqlRelationalConnection connection)
  at at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
  at at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
  at at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
  at at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
  at at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.HasTables()
  at at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
  at at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
  at Nico.Blog.SeedData.Initializer.IniTask() in C:\Users\Administrator\Desktop\54\Nico.Blog\SeedData\Initializer.cs:24
  at Nico.Blog.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime appLifetime) in C:\Users\Administrator\Desktop\54\Nico.Blog\Startup.cs:120
  at at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
  at at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
  at at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
  at at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
  at Nico.Blog.Startup.Main(String[] args) in C:\Users\Administrator\Desktop\54\Nico.Blog\Startup.cs:38

```

**Comment by mguinness** [comment]
Without more information we cannot help.  You have a datatype mismatch. Either your field in db should be bigint, or your member in model should be Int32.

**Comment by bison92** [comment]
Hello there, 

This is happening at the very beggining of the application startup, it seems like EntityFramework is trying to check if the database is already created or if it has to create it and issues the following query (according to logs):

`SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
                          FROM information_schema.tables
                          WHERE table_type = 'BASE TABLE' AND table_schema = '{DATABASENAME}'`

But then, when reading the response the InvalidCastException exception is thrown:
`Application startup exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.<HasTables>b__13_0(IMySqlRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Mediapro.MediacoachPlatform.WebApi.Startup.InitializeDatabase(IApplicationBuilder app)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Mediapro.Msf.HealthChecks.HealthCheckStartupFilter.<>c__DisplayClass8_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception`

**Comment by caleblloyd** [comment]
It's fixed in the latest nightly build https://www.myget.org/Package/Details/pomelo?packageType=nuget&packageId=Pomelo.EntityFrameworkCore.MySql

Will go out in the next release when EF Upstream does a release
