### ISSUE TITLE
Four (or five?) exceptions raised when server is offline

### ISSUE THREAD

**Issue by Bidthedog** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#604]
### Steps to reproduce
* Create a dotnet core project (v2.1)
* Write some code to connect to the DB
* Optional: Configure nlog to log exceptions as per their dot net core page (https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2)
* Shut down the database
* Run the app and try to connect - you should get an exception. Obviously only one bubbles up, but it seems that four or five are raised internally. If you're running VS in debug mode, you'll see the following:

Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll

I'm using a docker container for the database so I'm just stopping the container to replicate this.

### The issue
Four exceptions are raised, all with similar error messages. I first noticed when nlog was sending me 4 emails - thought it was an nlog configuration issue, but doing some tracing shows that the Pomelo driver IS actually raising 4 or 5 exceptions - not entirely sure where. Here's my nlog output after a single call using the following LINQ query:

```
        public async Task<UserDAO> ReadByEmailAsync(string email) {
            return await _ctx.Users
                .Include(x => x.UserSiteDAOs)
                .ThenInclude(x => x.UserSiteSecurityGroup)
                .FirstOrDefaultAsync(u => u.Email == email);
        }
```

```
THREAD 00004 | ERROR | 2018-06-12 10:13:47.8340 | Security.AuthenticateAsyncSecurity | Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log | An error occurred using the connection to database 'ProjectDConfiguration' on server 'localhost'. | MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
AsyncStateMachineBox`1.MoveNext => ExecutionContext.RunInternal => <OpenDbConnectionAsync>d__48.MoveNext => RelationalLoggerExtensions.ConnectionError => EventDefinition`2.Log
---------------------------------------------
THREAD 00004 | ERROR | 2018-06-12 10:13:47.9349 | Security.AuthenticateAsyncSecurity | Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`3.Log | An exception occurred in the database while iterating the results of a query for context type 'Client.ProjectServer.Data.Configuration.Model.ProjectDConfigurationContext'.
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken) | MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
AsyncStateMachineBox`1.MoveNext => ExecutionContext.RunInternal => <MoveNext>d__5.MoveNext => CoreLoggerExtensions.QueryIterationFailed => EventDefinition`3.Log
---------------------------------------------
THREAD 00004 | ERROR | 2018-06-12 10:13:47.9586 | Security.AuthenticateAsyncSecurity | Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`3.Log | An exception occurred in the database while iterating the results of a query for context type 'Client.ProjectServer.Data.Configuration.Model.ProjectDConfigurationContext'.
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType) | MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
AsyncStateMachineBox`1.MoveNext => ExecutionContext.RunInternal => <ExecuteSingletonAsyncQuery>d__21`1.MoveNext => CoreLoggerExtensions.QueryIterationFailed => EventDefinition`3.Log
---------------------------------------------
THREAD 00004 | ERROR | 2018-06-12 10:13:48.4313 | Security.AuthenticateAsyncSecurity | Microsoft.AspNetCore.Diagnostics.Internal.DiagnosticsLoggerExtensions.UnhandledException | An unhandled exception has occurred while executing the request. | MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 293
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 399
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Client.ProjectServer.Data.Configuration.Repositories.UsersRepository.ReadByEmailAsync(String email) in F:\Git\Client\ProjectServer\src\Client.ProjectServer.Data.Configuration\Repositories\UsersRepository.cs:line 26
   at Client.ProjectServer.Services.Authentication.SecurityService.LookupUserAsync(String username) in F:\Git\Client\ProjectServer\src\Client.ProjectServer.Services\Authentication\SecurityService.cs:line 246
   at Client.ProjectServer.Services.Authentication.SecurityService.AuthenticateDAOAsync(String username, String password) in F:\Git\Client\ProjectServer\src\Client.ProjectServer.Services\Authentication\SecurityService.cs:line 196
   at Client.ProjectServer.Services.Authentication.SecurityService.IssueAccessTokenAsync(String username, String password, String audience) in F:\Git\Client\ProjectServer\src\Client.ProjectServer.Services\Authentication\SecurityService.cs:line 73
   at Client.ProjectServer.API.Controllers.SecurityController.AuthenticateAsync(AuthenticateRequest req) in F:\Git\Client\ProjectServer\src\Client.ProjectServer.API\Controllers\SecurityController.cs:line 64
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
<>c.<OutputWaitEtwEvents>b__12_0 => AsyncStateMachineBox`1.MoveNext => ExecutionContext.RunInternal => <Invoke>d__7.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
---------------------------------------------
```

Each exception is separated by a hyphenated line. 4 are logged, all very similar.

### Further technical details
MySQL version: 5.7.22 in Linux docker container (don't think this is relevant)
Operating system: Microsoft Windows 10 Enterprise 10.0.17134 Build 17134

Pomelo.EntityFrameworkCore.MySql version:
2.1.0-rc2-20180603202706 (not 100% why I'm using the RC - there was an issue either with the latest release or I needed it because I'm using dotnet core 2.1). I set it up a while ago.

Other details about my project setup:

I am capturing logs using nlog - but even if I disable nlog entirely, and also disable the dotnet core exception handler I've written, I still get 4/5 debug lines output when the error occurs. When I disable "Just My Code" in VS, I get the following debug output:

```
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in MySqlConnector.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Interactive.Async.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in Microsoft.EntityFrameworkCore.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in Microsoft.EntityFrameworkCore.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in System.Private.CoreLib.dll
```

But I'm not able to catch the exception whilst debugging due to it being inside an async task.

**Comment by Bidthedog** [comment]
The bug is that there are multiple exceptions thrown that are *almost* identical, which means any error handler is going to catch multiple exceptions and react the same way four times.

Look at the errors I've pasted - all happen during a single call with the code I've posted.

Definitely not trying to connect multiple times - I've set it up exactly like your example pages, and I connect via a single call to the repository:

```
var mySQLConfig = config.GetSection("Connections").GetSection("Data.Configuration");
var mySQLConnectionString = mySQLConfig.GetValue<string>("ConnectionString");
services.AddDbContext<MyDatabaseContext>(options => options.UseMySql(mySQLConnectionString));

```
Connection string is:

`server=localhost;port=3306;user=myuser;password=mypw;database=MyDatabase`

Could it be to do with the includes? Does each include initiate a new connection to the DB?

**Comment by Bidthedog** [comment]
I'm not sure how dot net core's DI works internally - would a DB connection be instantiated for each time you inject the context into a class, or does the DB only open when you query it? I have many repositories and services in the app - many more than 4 - but only one of them is in the call stack during this method call, so I would only expect a single Context to get injected?

FYI all my exceptions are bubbled up the stack and caught by my global exception handler.

**Comment by caleblloyd** [comment]
The DB connection is handled by EF and only opened when it is queried. Each include will create a new query, but when the first exception happens the execution should stop.

**Comment by Bidthedog** [comment]
Well, I'll have a proper dig around but I'm 100% certain I've done it the way your wiki pages recommend and there's no other way to connect.

I'll try and put a small project together to replicate it - NDAs and all that :\

**Comment by caleblloyd** [comment]
I can recreate it, but I don't think there's anything we can do about it.  EF Core Upstream has the connection management logic.  It probably tries to open the connection, then when it fails it tries to clean up the connection with a few different `Dispose()` commands and encounters more errors since it can't acces the database.
