### ISSUE TITLE
Support for System.Transactions

### ISSUE THREAD

**Issue by acmajia** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#612]
### Steps to reproduce
```C#
using (var scope = new TransactionScope(
        TransactionScopeOption.Required,
        new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted }, TransactionScopeAsyncFlowOption.Enabled))
{
    try
    {
        DbSet.Set<MyEntity>().Add(entity);
        await DbSet.SaveChangesAsync();
        scope.Complete();
    }
    catch (Exception e)
    {

    }
}

```

### Target Framework
netcoreapp2.1

### The issue
Expected:
Successfully complete the scope.

Actually:
Throws a exception as below.

```
Exception message:
Error generated for warning 'Microsoft.EntityFrameworkCore.Database.Transaction.AmbientTransactionWarning: An ambient transaction has been detected. The current provider does not support ambient transactions. See http://go.microsoft.com/fwlink/?LinkId=800142'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.AmbientTransactionWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

Stack trace:
at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.AmbientTransactionWarning(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DateTimeOffset startDate)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.HandleAmbientTransactions()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ACC.EntityFramework.EntityFrameworkStorage`4.AddAsync(IEnumerable`1 entities, Processor processor) in F:\Codes\eaiyun\ACC\ACC.EntityFramework\Storages\EntityFrameworkStorage.cs:line 113
   at ACC.EntityFramework.EntityFrameworkStorage`4.AddAsync(TObject entity, Processor processor) in F:\Codes\eaiyun\ACC\ACC.EntityFramework\Storages\EntityFrameworkStorage.cs:line 76
   at ACC.Diagnoses.ChinesePatentMedicinePrescriptionService.AddAsync(ChinesePatentMedicinePrescriptionCreationContext context, Processor processor) in F:\Codes\eaiyun\ACC\ACC.Core\Services\Diagnoses\ChinesePatentMedicinePrescriptionService.cs:line 188
```

### Further technical details

MySQL version: 5.7.22
Operating system: ubuntu .16.04
Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc1-final

Other details about my project setup:
see: https://docs.microsoft.com/en-us/ef/core/saving/transactions#using-systemtransactions

**Comment by mguinness** [comment]
Transaction scope mode isn't supported by this provider yet I believe.  For a workaround, take a look at [How to implement ambient transaction in Entity Framework Core?
](https://stackoverflow.com/a/45921353/310601)

**Comment by acmajia** [comment]
@mguinness , thanks for the reply. 
As you mentioned, `IDbContextTransaction`(provided by EntityFrameworkCore) can solve my problem, but I think by using ambient transactions, I can decouple `DbContext`(and the `IDbContextTransaction`) from my bussiness code.

Do you have any plan to support it?

**Comment by mguinness** [comment]
Currently the focus is on EF Core 2.1 and there are limited developers available.  There is a [Call for Contributors](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/522) and we always welcome PR's for new features.

**Comment by dandrejvv** [comment]
@mguinness , based on the date this was closed I reckon that this issue will not be addressed since it doesn't fall in the current development roadmap?

**Comment by dandrejvv** [comment]
Hey @mguinness thank you for your reply. Just wanted to make sure that it wasn't completely off radar since the "official" provider doesn't even currently support Enums in the entity model, not even sure if it supports ambient transactions. So hoping the community would be able to assist.

**Comment by qgxcry** [comment]
I just ran into this too. An ambient transaction has been detected. The current provider does not support ambient transactions.

**Comment by xshiiiidev** [comment]
Hope this will be supported soon.

**Comment by lauxjpn** [comment]
Ambient transactions will be supported by us with the 3.0 release.
