### ISSUE TITLE
System.InvalidOperationException: Read past end of buffer, in Linux Docker

### ISSUE THREAD

**Issue by artziem** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#616]
### Steps to reproduce
Run app in **Linux docker** that select all records from table (about ~1000 rows, table size ~210Kb).
On Windows it works.
```
DataContext.Set<Category>().ToList();
```
Schema
```
CREATE TABLE `category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `uid` char(36) NOT NULL,
  `fid` int(11) NOT NULL,
  `type` int(11) NOT NULL,
  `priority` int(11) NOT NULL,
  `name` varchar(128) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `original_name` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IX_parent_id` (`parent_id`) USING HASH,
  KEY `IX_uid` (`uid`) USING HASH,
  CONSTRAINT `FK_category_category_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `category` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### The issue
I'm getting an error **System.InvalidOperationException: Read past end of buffer.**
Probably after upgrade to .NET Core 2.1, but not sure because of cache.

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Read past end of buffer.
   at MySqlConnector.Protocol.Serialization.ByteArrayReader.ReadUInt16() in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Serialization\ByteArrayReader.cs:line 48
   at MySqlConnector.Protocol.Payloads.OkPayload.Create(PayloadData payload, Boolean deprecateEof) in C:\projects\mysqlconnector\src\MySqlConnector\Protocol\Payloads\OkPayload.cs:line 37
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncRemainder|9_1(PayloadData payload, Row row_) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 235
   at MySqlConnector.Core.ResultSet.ScanRowAsync(IOBehavior ioBehavior, Row row, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 201
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 175
   at MySqlConnector.Core.ResultSet.ReadEntireAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 161
   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 55
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 426
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 290
   at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+System.IDisposable.Dispose()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Domain.Services.CategoryService.GetCategories() in C:\Sources\SomeProject\Domain\Services\CategoryService.cs:line 78
   at Cache.Restore.CacheRestoreAll`2.RestoreAllEntitiesAndGetMany(IEnumerable`1 keys) in C:\Sources\SomeProject\Cache\Restore\CacheRestoreAll.cs:line 22
   at Domain.Cache.ProductCacheProvider.FillCategories(IEnumerable`1 products) in C:\Sources\SomeProject\Domain.Cache\ProductCacheProvider.cs:line 97
   at Domain.Cache.ProductCacheProvider.SetProductsRelations(IEnumerable`1 products) in C:\Sources\SomeProject\Domain.Cache\ProductCacheProvider.cs:line 68
   at Domain.Cache.ProductCacheProvider.GetMany(IEnumerable`1 ids) in C:\Sources\SomeProject\Domain.Cache\ProductCacheProvider.cs:line 60
   at WebApi.Controllers.ProductController.Search(String name, Nullable`1 page, Nullable`1 pageSize) in C:\Sources\SomeProject\WebApi\Controllers\ProductController.cs:line 34
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```
Logged DB query:
```
SELECT `c`.`id`, `c`.`created_at`, `c`.`fid`, `c`.`name`, `c`.`original_name`, `c`.`parent_id`, `c`.`priority`, `c`.`type`, `c`.`uid` FROM `category` AS `c`
```
Execute above SQL query via MySqlConnector (0.42.1) from project return valid results.

### Further technical details

MariaDB version: 10.2.7-MariaDB
Operating system: Linux Docker (Windows 10 Home or Debian 8), Docker version: 18.03.1-ce
Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc2-20180613003118
Framework: .NET Core 2.1

**Comment by caleblloyd** [comment]
This appears to be a bug with MySqlConnector, could you open this issue here: https://github.com/mysql-net/MySqlConnector/

**Comment by caleblloyd** [comment]
It appears your type mapping is trying to read a `UInt16`, but I don't see any `small int unsigned` in your table. What is the model?

Regardless, I wouldn't expect MySqlConnector to throw this exception

**Comment by caleblloyd** [comment]
Do you have `OldGuids=true` in your connection string by chance.

See `GuidFormat` at https://mysql-net.github.io/MySqlConnector/connection-options/

If you do that would cause it to try to read your `char(36)` column as a `ushort`. Try removing that if so.

**Comment by renemadsen** [comment]
If anybody gets this error as I did, when upgrading .net 7 to .net 8 and therefore the Pomelo version to 8.0.x

This can be caused by the query cache returning a package, which the underlying client does not understand, hence the error.
Just login to the mysql/mariadb servers and run "RESET QUERY CACHE" this will clean out all query caches and solve the problem.
