### ISSUE TITLE
rename can't roll back

### ISSUE THREAD

**Issue by rcl4444** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#621]
### Steps to reproduce
Up
`migrationBuilder.RenameColumn(
                name: "PTId",
                table: "SplitRule_ProductClass",
                newName: "StintMark");`
Down
`migrationBuilder.RenameColumn(
                name: "StintMark",
                table: "SplitRule_ProductClass",
                newName: "PTId");`
### The issue
when I roll back change.
`Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation`
Exception message:
Stack trace:
`System.InvalidOperationException: Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`

### Further technical details

MySQL version: 5.7.21
Operating system: win10 17134.112
Pomelo.EntityFrameworkCore.MySql version:2.1.0-rc2-20180621144030

**Comment by rcl4444** [comment]
#615 
@mguinness 
can you tell me how to use `new { columnType = "int" })`

**Comment by mguinness** [comment]
Ah it looks like `anonymousArguments` is only for [RenameColumn](https://msdn.microsoft.com/en-us/library/system.data.entity.migrations.dbmigration.renamecolumn) in EF6, not EF Core.

**Comment by rcl4444** [comment]
:(,it's can be repair in v2.1?I use EF Core

**Comment by caleblloyd** [comment]
Fixed in [2.1.0-rc2-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final)

**Comment by rcl4444** [comment]
@caleblloyd 
I use the  

> 2.1.0-rc2-final 

Still so.

> update-Database init
Reverting migration '20180626063032_task2'.
System.InvalidOperationException: Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation

**Comment by mguinness** [comment]
Can you try adding [The Column Attribute](https://www.learnentityframeworkcore.com/configuration/data-annotation-attributes/column-attribute) to the field in your model?

For example try either `[Column(TypeName = "int")]` or the following:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7083319d9a8750104f010461a660e60ee9034117/upstream/EFCore.Upstream.FunctionalTests/Query/MappingQueryMySqlTest.cs#L81-L83

**Comment by rcl4444** [comment]
@mguinness it does't work
>             modelBuilder.Entity<SplitRuleItem>().Property(c => c.StintMark).HasColumnType("varchar(50)");
the abnormal again
> update-Database init
Reverting migration '20180626063032_task2'.
System.InvalidOperationException: Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateDownSql(Migration migration, Migration previousMigration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not find the property corresponding to the column: `SplitRule_ProductClass`.`PTId`. Specify the column type explicitly on 'RenameColumn' using the "Relational:ColumnType" annotation

**Comment by caleblloyd** [comment]
I think what this error is saying is that EF can no longer map the Migration to the Column that is in the code.  This can happen if the column name name has changed again, or if the table name has changed.

I tested a bunch of roll forward and roll back renames in MySQL 5.7 and could only find the issue that was fixed in #628.  If you can post a full recreate we can investigate further.

As a workaround I would recommend doing a roll-forward migration to get your DB into the state you need it in.

**Comment by PhilipNunn** [comment]
I was finally able to get around this by adding `.Annotation("Relational:ColumnType", "LONGTEXT;");` to my RenameColumn statement.
