### ISSUE TITLE
Create index with filter in migrations throws exception in 2.1.0-rc2-final

### ISSUE THREAD

**Issue by WillooWisp** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#631]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

Add a create index migration with filter, e.g.:

migrationBuilder.CreateIndex(
name: "IX_Hardwares_SerialNumber",
table: "Hardwares",
column: "SerialNumber",
unique: true,
filter: "[SerialNumber] IS NOT NULL");

which looks like this in designer file:

b.HasIndex("SerialNumber")
.IsUnique()
.HasFilter("[SerialNumber] IS NOT NULL");

### The issue
Describe what is not working as expected.

Automatically generated create index with filter migrations, that works fine on SQL Server, and that used to work fine on MySQL with Pomelo for .NET Core 2.0, now throws exception. Since filters on indexes are not supported in MySQL 5.7, I guess they have been ignored earlier and still should be.

If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE [SerialNumber] IS NOT NULL' at line 1 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE [SerialNumber] IS NOT NULL' at line 1

Stack trace:
MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 44
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 298
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 283
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 73
   at MySqlConnector.Core.TextCommandExecutor.ExecuteNonQueryAsync(String commandText, MySqlParameterCollection parameterCollection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 26
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 60
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Exception thrown: 'MySql.Data.MySqlClient.MySqlException' in Microsoft.EntityFrameworkCore.Relational.dll
An exception of type 'MySql.Data.MySqlClient.MySqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE [SerialNumber] IS NOT NULL' at line 1

### Further technical details

MySQL version: 5.7.22
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc2-final

Other details about my project setup:

**Comment by mguinness** [comment]
Take a look at [Model configuration: Make filtered indexes play nice with other providers](https://github.com/aspnet/EntityFrameworkCore/issues/7087).
