### ISSUE TITLE
DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by michalejoye** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#640]
### Steps to reproduce
I have a test project ISLambdaCSharp.TestConsole in the [Test Project Repo](https://github.com/michalejoye/testmysql) that setup the what I am trying to do. 
I am trying to do Code First with MySql DB

### The issue
Describe what is not working as expected.
When models are add or updated, the SaveChanges throws an error

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException
  HResult=0x80131500
  Message=Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ISLambdaCSharp.TestConsole.Program.InsertData() in C:\code\darknightsstudio\IS Severside CSharp\test\ISLambdaCSharp.TestConsole\Program.cs:line 54
   at ISLambdaCSharp.TestConsole.Program.Main(String[] args) in C:\code\darknightsstudio\IS Severside CSharp\test\ISLambdaCSharp.TestConsole\Program.cs:line 12

```

### Further technical details

MySQL version: 5.6.36-82.2
Operating system:  window 10
Pomelo.EntityFrameworkCore.MySql version:2.0.1

**Comment by mguinness** [comment]
Probably the best way to troubleshoot this is to use the [The General Query Log](https://dev.mysql.com/doc/refman/5.5/en/query-log.html) to look at the SQL is being executed.

**Comment by michalejoye** [comment]
When i look into the query log i get this 
```
180706 12:15:03	  139 Connect	innersanctum@localhost as anonymous on 
		  139 Quit	
		  140 Connect	innersanctum@localhost as anonymous on 
		  140 Query	USE `innersanctum`
		  140 Quit	
180706 12:15:04	  141 Connect	innersanctum@localhost as anonymous on innersanctum
		  141 Query	SELECT CASE WHEN COUNT(*) = 0 THEN FALSE ELSE TRUE END
                    FROM information_schema.tables
                    WHERE table_type = 'BASE TABLE' AND table_schema = 'innersanctum'
		  141 Change user	innersanctum@localhost on innersanctum
		  141 Query	set transaction isolation level repeatable read; start transaction
		  141 Query	INSERT INTO `Publisher` (`Name`)
VALUES ('Mariner Books');
SELECT `ID`
FROM `Publisher`
WHERE ROW_COUNT() = 1 AND `ID` = LAST_INSERT_ID();

INSERT INTO `Severs` (`SeverID`, `CurrentCapaticy`)
VALUES ('dfda649a-eab5-4525-84db-9edbf6ef830e', 10);
SELECT `MaxCapaticy`
FROM `Severs`
WHERE ROW_COUNT() = 1 AND `SeverID` = 'dfda649a-eab5-4525-84db-9edbf6ef830e'
		  141 Query	rollback
```

**Comment by michalejoye** [comment]
So it seem to have a problem with my Server Model

Sever.cs
```
public class Sever
	{
		[Column(TypeName = "BINARY(16)")]
		public Guid SeverID { get; set; }
		public int CurrentCapaticy { get; set; }

		public int MaxCapaticy { get; set; }

	}
```
Modelbuilder options for the that model
```
modelBuilder.Entity<Sever>(entity =>
			{
				entity.HasKey(e => e.SeverID);
				entity.Property(e => e.MaxCapaticy).HasDefaultValue(100);
			});
```

**Comment by mguinness** [comment]
Your GUID will get truncated in `BINARY(16)`.  Remove `[Column(TypeName = "BINARY(16)")]` annotation and create a new migration, then try again.

**Comment by michalejoye** [comment]
I thought that myself. I removed the ```[Column(TypeName = "BINARY(16)")]``` annotation, and i still get the same error. The only way that I can get rid of the error is to set MaxCapaticy to something, seem like that DefaultValue is not work.

**Comment by mguinness** [comment]
What does the schema for the table show?  Did you rerun migration?
