### ISSUE TITLE
.Average() Query is Breaking #385 (Still Occuring)

### ISSUE THREAD

**Issue by jatmika-com** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#644]
### Steps to reproduce
I've created solution to show the failure here : https://github.com/munir-jb/db_access_sample

### The issue
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/385 still affecting my project above. Average query is failing.

```
An exception occurred while reading a database value. The expected type was 'System.Double' but the actual value was of type 'System.Decimal'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Average[TSource](IQueryable`1 source, Expression`1 selector)
   at DbInitializer.GetAverageData() in D:\GIT\draft\db_access_sample\db_access_sample\DbInitializer.cs:line 56
   at db_access_sample.Startup.<>c.<<Configure>b__2_0>d.MoveNext() in D:\GIT\draft\db_access_sample\db_access_sample\Startup.cs:line 41
Unable to cast object of type 'System.Decimal' to type 'System.Double'.
   at MySqlConnector.Core.Row.GetDouble(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 315
   at lambda_method(Closure , DbDataReader )
```

### Further technical details

MySQL version: mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for Win64 (AMD64)
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

cc: @caleblloyd @mguinness

**Comment by marbletravis** [comment]
Is there a workaround for this?

**Comment by munir-jb** [comment]
> 
> 
> Is there a workaround for this?

If only for temporary workaround, you could use Sum() function and divide the result with Count() result (you must create 2 query and operating the result in c# code).

**Comment by marbletravis** [comment]
Now I feel a little silly I didn't think of that. I had only thought of bringing all the records back then averaging client side (which I didn't want to do). I don't know why I didn't think of count/sum... 

Thanks!

**Comment by munir-jb** [comment]
> 
> 
> Now I feel a little silly I didn't think of that. I had only thought of bringing all the records back then averaging client side (which I didn't want to do). I don't know why I didn't think of count/sum...
> 
> Thanks!

you're welcome, I do the exact same thing in my project while waiting for other further solution. 😄 👍

**Comment by yukozh** [comment]
Seems that we should override the Average visitor and cast the decimal to float with SQL commands

**Comment by lauxjpn** [comment]
This issue is fixed since the `2.2.0` release. The following code works as expected in `2.2.0`, `2.2.6` and `3.0.0`:

```c#
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double PriceAsDouble { get; set; }
        public decimal PriceAsDecimal { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3308;user=root;password=;database=Issue644")
                .UseLoggerFactory(LoggerFactory.Create(b => b.AddConsole()))
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>()
                .HasData(
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>()
                .HasData(
    new IceCream { Id = 1, Name = "Vanilla", PriceAsDouble = 1.00d, PriceAsDecimal = 1.00m },
    new IceCream { Id = 2, Name = "Strawberry", PriceAsDouble = 1.40d, PriceAsDecimal = 1.40m },
    new IceCream { Id = 3, Name = "Chocolate", PriceAsDouble = 1.20d, PriceAsDecimal = 1.20m }
                );
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var averageIceCreamPriceAsDouble = context.IceCreams.Average(i => i.PriceAsDouble);
            var averageIceCreamPriceAsDecimal = context.IceCreams.Average(i => i.PriceAsDecimal);

            Debug.Assert(averageIceCreamPriceAsDouble == 1.20d);
            Debug.Assert(averageIceCreamPriceAsDecimal == 1.20m);
        }
    }
}
```

It successfully executes the following SQL statements:

```sql
SELECT AVG(`i`.`PriceAsDouble`)
FROM `IceCreams` AS `i`

SELECT AVG(`i`.`PriceAsDecimal`)
FROM `IceCreams` AS `i`
```

**Comment by jatmika-com** [comment]
Unfortunately, me and my team still working with 2.1 version of .netcore
because of its LTS status. We'll try again if there are newer LTS version
of .netcore release.

regards,

Kurniawan Jatmika
http://kurniawan.jatmika.com/

**Comment by lauxjpn** [comment]
@jatmika-com The next LTS release will be 3.1, which is going to be released next month.

**Comment by jatmika-com** [comment]
Thx for the information, can't wait to try that :D

regards,

Kurniawan Jatmika
http://kurniawan.jatmika.com/
