### ISSUE TITLE
Can't read TINYINT(1) as bool

### ISSUE THREAD

**Issue by AccessViolator** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#654]
### Steps to reproduce
```
using System.Threading.Tasks;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;
using NUnit.Framework;

namespace Tests
{
    [TestFixture, Explicit]
    class MySqlCustomModelTests
    {
        static readonly LoggerFactory _loggerFactory
            = new LoggerFactory(new[] { new ConsoleLoggerProvider((category, logLevel) => true, false) });
        DbContextOptions<Context> _options;

        Context GetContext()
        {
            return new Context(_options);
        }

        class Context : DbContext
        {
            public Context(DbContextOptions<Context> options) : base(options) { }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);

                modelBuilder.Entity<Bool>(entity =>
                {
                    entity.ToTable("bools");
                    entity.Property(e => e.BoolValue).HasColumnType("tinyint(1)");
                });
            }

            public DbSet<Bool> Bools { get; set; }
        }

        class Bool
        {
            public int Id { get; set; }
            public bool BoolValue { get; set; }
        }

        [SetUp]
        protected void BeforeEach()
        {
            _options = new DbContextOptionsBuilder<Context>()
                .UseLoggerFactory(_loggerFactory)
                .UseMySql("Server=localhost;database=createtest;uid=user;pwd=password")
                .ConfigureWarnings(warnings => warnings.Throw(CoreEventId.IncludeIgnoredWarning))
                .Options;

            using (var db = GetContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
            }
        }

        [Test]
        public async Task CanReadBools()
        {
            using (var db = GetContext())
            {
                db.Bools.Add(new Bool { BoolValue = false });
                db.Bools.Add(new Bool { BoolValue = true });
                await db.SaveChangesAsync();
            }

            using (var db = GetContext())
            {
                var list = await db.Bools.ToListAsync();
                list[0].BoolValue.Should().BeFalse();
                list[1].BoolValue.Should().BeTrue();
            }
        }
    }
}
```
### The issue

Can't read TINYINT(1) mapped to bool
It's not MySqlConnector issue, it reads fine with reader.GetBoolean(1)

```
Exception: 
System.InvalidOperationException : An exception occurred while reading a database value for property 'Bool.BoolValue'. The expected type was 'System.Boolean' but the actual value was of type 'System.Boolean'.
  ----> System.InvalidCastException : Unable to cast object of type 'System.Boolean' to type 'System.SByte'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at Tests.MySqlCustomModelTests.CanReadBools() in C:\Dev\Tests\MySqlCustomModelTests.cs:line 75
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 113
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 96
--InvalidCastException
   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue[T](Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 286
   at lambda_method(Closure , DbDataReader )
```

### Further technical details

MySQL version: 8.0.11
Operating system: Win 7
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

**Comment by csboling** [comment]
Counterintuitively I have actually had to set `TreatTinyAsBoolean=false` when using a mapping like this. If I don't configure `.HasColumnType("tinyint(1)")` then a `bool` model property gets set just fine when querying a column of type `tinyint(1)`, but when `HasColumnType("tinyint(1)")` is configured I would consistently get the exception above unless I set `TreatTinyAsBoolean=false`. I also tried the [BoolToZeroOneConverter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.booltozerooneconverter-1?view=efcore-2.1) but it had the same issue.

**Comment by AccessViolator** [comment]
Hm, it did help, thanks, but I find it very strange because according to [this](https://github.com/mysql-net/MySqlConnector/issues/141) ([and this](https://github.com/caleblloyd/MySqlConnector/blob/4a4b86038eba438d668b12100dff35a5ce0f2e7d/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnectionStringBuilder.cs#L526)) it's on by default.
Closing.

**Comment by AccessViolator** [comment]
@csboling thanks for details, very counter intuitive indeed.
I think I'll be omitting the `HasColumnType("tinyint(1)")` and use default setting.

**Comment by AccessViolator** [comment]
Turns out omitting `HasColumnType("tinyint(1)")` and using default setting generates `bit(1)` column with model first. I actually use db first, so I think I'll need to research further. If I'm not mistaken I remember reading that `bit(1)` takes at least 7 bits of row storage anyway...

**Comment by twsI** [comment]
Has anyone solved this issue so far?

**Comment by mguinness** [comment]
@twsl Is the field nullable in database?  If so try bool? instead.

**Comment by twsI** [comment]
Thanks for the tip, somehow I must have missed that combination of nullable bool, no additional connection string and without converters. But aparently that is not, what the scaffold command suggests.

**Comment by lol768** [comment]
> Counterintuitively I have actually had to set `TreatTinyAsBoolean=false` when using a mapping like this. If I don't configure `.HasColumnType("tinyint(1)")` then a `bool` model property gets set just fine when querying a column of type `tinyint(1)`, but when `HasColumnType("tinyint(1)")` is configured I would consistently get the exception above unless I set `TreatTinyAsBoolean=false`. I also tried the [BoolToZeroOneConverter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.booltozerooneconverter-1?view=efcore-2.1) but it had the same issue.

I had exactly the same experience - wtf? Why does it need to be _false_?

**Comment by neven10** [comment]
Any resolution on this?  Same problem here. I have tinyint(1) in database which needs to be interpreted as bool.  And pomelo returns it as sbyte no matter what option i use.

**Comment by neven10** [comment]
Nevermind, i'm dumb. Set TreatTinyAsBoolean=false in connection string. Scaffolded property must be sbyte.

**Comment by coultonluke** [comment]
> > Counterintuitively I have actually had to set `TreatTinyAsBoolean=false` when using a mapping like this. If I don't configure `.HasColumnType("tinyint(1)")` then a `bool` model property gets set just fine when querying a column of type `tinyint(1)`, but when `HasColumnType("tinyint(1)")` is configured I would consistently get the exception above unless I set `TreatTinyAsBoolean=false`. I also tried the [BoolToZeroOneConverter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.booltozerooneconverter-1?view=efcore-2.1) but it had the same issue.
> 
> I had exactly the same experience - wtf? Why does it need to be _false_?
> 
> The docs say:
> 
> > When set to true, TINYINT(1) values are returned as booleans. Setting this to false causes TINYINT(1) to be returned as sbyte/byte.
> 
> So I guess Pomelo _needs_ to get back an sbyte/byte and can't handle a bool?

Exactly the same experience. Setting it to false just doesn't make sense to me but it seems to work. I hope that I don't experience other issues with this later down the line.

I have a bool type property, .HasColumnType("TINYINT(1)") on all of my bool properties and then have `TreatTinyAsBoolean=false` in my connection string.

The above setup seems to work for scaffolding and reading the data out afterwards.

Weird

**Comment by lauxjpn** [comment]
While #875 should fix this issue for good, #866 contains workaround options (especially for anybody stuck on EF Core 2.2.x).

**Comment by lauxjpn** [comment]
Thanks @AccessViolator and everybody else for taking the time to report and discuss this issue.
This has been fixed in #875.

**Comment by lol768** [comment]
Great news, thanks @lauxjpn!
