### ISSUE TITLE
left join result is nullable

### ISSUE THREAD

**Issue by hemiaoio** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#692]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.
![qq 20181009180818](https://user-images.githubusercontent.com/5441896/46662549-585dd700-cbee-11e8-8416-7075a35df2bb.png)

Look at the SQL ,table 'c' is primary table ,but the result use the 't' key ,this time ,'t' has not record.
my linq code is :
```csharp
var query = from p in _productRepository.GetAllIncluding(c => c.ProductCategory)
                join ht in (
                    (from ph in _productHintRepository.GetAll()
                        where
                            ph.CreationTime.Date == DateTime.Today &&
                            ph.HintType == 0
                        group ph by new
                        {
                            ph.CreationTime.Date,
                            ph.ProductId
                        }
                        into g
                        select new ProductHintCount
                        {
                            StatisticDate = g.Key.Date,
                            ProductId = g.Key.ProductId,
                            HintCount = (int?) g.Count()
                        })) on p.Id equals ht.ProductId into ht_join
                from ht in ht_join.DefaultIfEmpty()
                where
                    p.DayMaxHintCount == 0 ||
                    (p.DayMaxHintCount != 0 &&
                     p.DayMaxHintCount > ht.HintCount)
                select p;
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Nullable object must have a value.
Stack trace:
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.GetCount(Boolean onlyIfCheap)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at lambda_method(Closure , QueryContext , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.CompositeShaper.TypedCompositeShaper`5.Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper<TResult>.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.GetCount(Boolean onlyIfCheap)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

### Further technical details

MySQL version: Docker - 8.0
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

Other details about my project setup:

**Comment by mguinness** [comment]
@hemiaoio Please share your models.

**Comment by hemiaoio** [comment]
> @hemiaoio Please share your models.

```csharp
    [Table(RapidLoanConsts.TablePrefix + "Products")]
    public class ProductEntity : AuditedEntity<Guid>
    {
        public const string LogoPictureAssociateType = "ProductLogoPicture";

        public Guid? LogoPictureId { get; set; }

        [StringLength(64)]
        public string Name { get; set; }

        public Guid? ProductCategroyId { get; set; }

        [ForeignKey(nameof(ProductCategroyId))]
        public virtual ProductCategoryEntity ProductCategory { get; set; }

        public int DayMaxHintCount { get; set; } = 0;
        // ......other properties
    }


    [Table(RapidLoanConsts.TablePrefix + "ProductHints")]
    public class ProductHintEntity : CreationAuditedEntity<long>
    {
        public Guid ProductId { get; set; }

        public long? MemberId { get; set; }

        public Guid AdIdentity { get; set; }
    }
```

Are you saying this? I use it in [abp](https://github.com/aspnetboilerplate/aspnetboilerplate)

**Comment by hemiaoio** [comment]
It in base class AuditedEntity ,type is Guid.  the ProductHintEntity same .

Sorry, I am late.

**Comment by hemiaoio** [comment]
My class type with `ProductHintEntity ` has not navigation properties.I want to join them with the key only.  Do you means I should be add the navigation properties and make association for them on the children class? It look's like this:
```csharp
[Table(RapidLoanConsts.TablePrefix + "ProductHints")]
    public class ProductHintEntity : CreationAuditedEntity<long>
    {
        public Guid ProductId { get; set; }

         [ForeignKey(nameof(ProductId))]
        public virtual ProductEntity Product { get; set; }

        public long? MemberId { get; set; }

        public Guid AdIdentity { get; set; }
    }
```
