### ISSUE TITLE
Remove UNIQUE generate wrong sql

### ISSUE THREAD

**Issue by MiyamuraMiyako** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#698]
### Steps to reproduce
1. Simple add one model class.
2. Extend ```DbContext``` class, in ```OnModelCreating``` method, add ```entity.HasAlternateKey(e => e.CompanyId);```.
3. Execute ```dotnet ef migrations add InitialCreate```.
4. Execute ```dotnet ef database update```.
5. Remove ```entity.HasAlternateKey(e => e.CompanyId);```.
6. ef migrations add v2.
7. Reexecute ```dotnet ef database update```.

### The issue
![default](https://user-images.githubusercontent.com/10345361/47481272-a1a45c80-d865-11e8-9112-27037e3f2f22.png)
```log
Log and Stack trace:
Applying migration '20181025064905_v2'.
Opening connection to database 'DCTest' on server 'localhost'.
Opened connection to database 'DCTest' on server 'localhost'.
Beginning transaction with isolation level 'Unspecified'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `Company` DROP CONSTRAINT `AK_Company_CompanyId`;
Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `Company` DROP CONSTRAINT `AK_Company_CompanyId`;
Disposing transaction.
Closing connection to database 'DCTest' on server 'localhost'.
Closed connection to database 'DCTest' on server 'localhost'.
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `AK_Company_CompanyId`' at line 1 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `AK_Company_CompanyId`' at line 1
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 44
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 88
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT `AK_Company_CompanyId`' at line 1
```

### Further technical details

MySQL version: 8.0.13 MySQL Community Server
Operating system: windows10 pro 1809 x64
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

**Comment by mguinness** [comment]
Also see [How to remove constraints from my MySQL table?](https://stackoverflow.com/questions/14122031/how-to-remove-constraints-from-my-mysql-table).  As a workaround you can manually edit the migration by [Executing Custom SQL](https://www.learnentityframeworkcore.com/migrations#executing-custom-sql).

**Comment by MiyamuraMiyako** [comment]
May be change ```Pomelo.EntityFrameworkCore.MySql/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs```, add below code can resolve issue?
```C#
/// <summary>
///     Builds commands for the given <see cref="DropUniqueConstraintOperation" /> by making calls on the given
///     <see cref="MigrationCommandListBuilder" />, and then terminates the final command.
/// </summary>
/// <param name="operation"> The operation. </param>
/// <param name="model"> The target model which may be <c>null</c> if the operations exist without a model. </param>
/// <param name="builder"> The command builder to use to build the commands. </param>
protected override void Generate(
    DropUniqueConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)
    => Generate(operation, model, builder, terminate: true);

/// <summary>
///     Builds commands for the given <see cref="DropUniqueConstraintOperation" /> by making calls on the given
///     <see cref="MigrationCommandListBuilder" />, and then terminates the final command.
/// </summary>
/// <param name="operation"> The operation. </param>
/// <param name="model"> The target model which may be <c>null</c> if the operations exist without a model. </param>
/// <param name="builder"> The command builder to use to build the commands. </param>
/// <param name="terminate"> Indicates whether or not to terminate the command after generating SQL for the operation. </param>
protected virtual void Generate(
    DropUniqueConstraintOperation operation,
    IModel model,
    MigrationCommandListBuilder builder,
    bool terminate)
{
    Check.NotNull(operation, nameof(operation));
    Check.NotNull(builder, nameof(builder));

    builder
        .Append("ALTER TABLE ")
        .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(operation.Table, operation.Schema))
        .Append(" DROP KEY ")
        .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(operation.Name));

    if (terminate)
    {
        builder.AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator);
        EndStatement(builder);
    }
}
```

**Comment by mguinness** [comment]
If you look at the [ALTER TABLE Syntax](https://dev.mysql.com/doc/refman/5.6/en/alter-table.html) it needs to be `DROP FOREIGN KEY fk_symbol`.  Looking back at the MySqlMigrationsSqlGenerator class it appears that SQL is already there, so the question is why it isn't being called.

**Comment by MiyamuraMiyako** [comment]
Uh, but my issue is ```drop unique key```, not foreign key. ```MySqlMigrationsSqlGenerator``` not contain ```protected override void Generate(DropUniqueConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)``` method.

**Comment by mguinness** [comment]
OK, build the code and see if it works for you.

**Comment by MiyamuraMiyako** [comment]
I try fork project and change code. It seems works.

![default](https://user-images.githubusercontent.com/10345361/47601288-e3b5d580-da00-11e8-8913-f0e9be542b2e.png)
![default](https://user-images.githubusercontent.com/10345361/47601293-eb757a00-da00-11e8-9e70-dd0079c7647c.png)

**Comment by mguinness** [comment]
Go ahead and create a PR also look at updating the related test.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/cb5740a13010f5365a673279ef40a34de3908e17/test/EFCore.MySql.FunctionalTests/MigrationSqlGeneratorMySqlTest.cs#L927-L935

**Comment by mguinness** [comment]
Closed in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/700, thanks for your contribution.
