### ISSUE TITLE
scaffold return error 2003

### ISSUE THREAD

**Issue by okian** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#699]
### Steps to reproduce

```bash
dotnet ef dbcontext scaffold "server=[address.com];port=3306;user=[user];password=[password];database=[db]" "Pomelo.EntityFrameworkCore.MySql"
```
### The issue
returns
```
MySql.Data.MySqlClient.MySqlException (0x80004005): Received error: 2003 : Can't connect to MySQL server on 'xxx.xxx.xxx.xxx' (111 "Connection refused")
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncAwaited|8_0(Task`1 payloadTask, Row row_, CancellationToken token) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 212
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 170
   at MySqlConnector.Core.ResultSet.Read() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 162
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetConstraints()
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String namespace, String language, String contextDir, String contextName, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Received error: 2003 : Can't connect to MySQL server on 'xxx.xxx.xxx.xxx' (111 "Connection refused")
```

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 

innodb_version | 5.6.39-83.1
protocol_version | 10
slave_type_conversions |  
version | 10.0.36-MariaDB-0ubuntu0.16.04.1
version_comment | Ubuntu 16.04
version_compile_machine | x86_64
version_compile_os | debian-linux-gnu
version_malloc_library | bundled jemalloc

Operating system: Ubuntu 18.04 and Arch
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

Other details about my project setup:
Connection data/string is correct and i can connect to that database with DataGrip on that PC. I also tried with user root with very simple password (to be sure privlage and escaping is not the issue)

**Comment by mguinness** [comment]
Is it a local or remote database?  Check your firewall and your grants:

https://mariadb.com/kb/en/library/troubleshooting-connection-issues/

If a remote server, try a local database instead.  Also see:

https://serverfault.com/questions/808977/mariadb-refuses-remote-connections
