### ISSUE TITLE
Problem with Json fields.

### ISSUE THREAD

**Issue by RaviDesai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#70]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
I've created a JSON field in a table called "Definition".
I can store JSON objects like `{"test": "abc"}` in this field.
I set up a POCO object as so: 
```
public class ContentItem
{
    ContentItem() {
        this.Dependencies = new HashSet<Dependency>();
    }
    
    [Key]
    public Guid Id { get; set; }

    public string Name { get; set; }
    public string Type { get; set; }
    public string Folder { get; set; }
    public string Hash { get; set; }
    public string Description { get; set; }

    public JsonObject<string> Definition { get; set; }
}
```

I've tried `JsonObject<string[]>`, `JsonObject<string>`, and `JsonObject<List<string>>` all to no avail.  Everytime I fire up my app, it crashes with the an error message indicating that the Definition field should be a complex property (see stack trace below).

I should note here, that if I just set the type of the Definition field to `string`, it all works fine.

Also my ConfigureServices method (in Startup.cs) looks like this:
```
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(
                options => options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme
            );

            services.AddDbContext<ApplicationDbContext>( x => x.UseMySql(Configuration["ConnectionStrings:SampleConnection"]) );
            services.AddPomeloLocalization(x =>
            {
                x.AddCulture(new string[] { "zh", "zh-CN", "zh-Hans", "zh-Hans-CN" }, new JsonLocalizedStringStore(Path.Combine("Localization", "zh-CN.json")));
                x.AddCulture(new string[] { "en", "en-US", "en-GB" }, new JsonLocalizedStringStore(Path.Combine("Localization", "en-US.json")));
            });
            var jsonFormatter = new JsonMediaTypeFormatter();
            var negotiator = new JsonContentNegotiator(jsonFormatter);
            
            // Add framework services.
            services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            services.AddSingleton<IUrlHelperFactory, UrlHelperFactory>();
            services.AddSingleton<ISampleService, ApplicationDbContext>();
            services.AddSingleton<IContentNegotiator, JsonContentNegotiator>((n) => negotiator);
            services.AddOData<ISampleService>(builder => {
                builder.Namespace = "Default";
            });

            services.AddMvc()
                .AddMultiTemplateEngine()
                .AddCookieTemplateProvider();
        }
```

And ApplicationDbContext looks (something) like this:
```
using System.Linq;
using Microsoft.EntityFrameworkCore;
public class ApplicationDbContext: DbContext, ISampleService 
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
    : base(options)
    { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ContentItem>().ToTable("ContentItem");
        modelBuilder.Entity<ContentItem>().Property(p => p.Definition).HasColumnType("json");
    }

    public DbSet<ContentItem> ContentItems { get; set; }

    IQueryable<ContentItem> ISampleService.ContentItems => ContentItems;
}
```
### The issue
Describe what is not working as expected.

Well, the exception is not really expected.  I'm not sure if there is anything I'm just missing as far as configuration is concerned.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The property 'Definition' on type 'ContentItem' must be a Complex property.
Parameter name: propertyInfo

Stack trace:
   at Microsoft.AspNetCore.OData.Builder.StructuralTypeConfiguration.AddComplexProperty(PropertyInfo propertyInfo)
   at Microsoft.AspNetCore.OData.Builder.ODataConventionModelBuilder.MapStructuralProperty(StructuralTypeConfiguration type, PropertyInfo property, PropertyKind propertyKind, Boolean isCollection)
   at Microsoft.AspNetCore.OData.Builder.ODataConventionModelBuilder.AddPropertyInternal(EntityTypeConfiguration entity, PropertyInfo property)
   at Microsoft.AspNetCore.OData.Builder.StructuralTypeConfiguration.RemoveProperty(PropertyInfo propertyInfo)
   at Microsoft.AspNetCore.OData.Builder.EntityTypeConfiguration.RemoveProperty(PropertyInfo propertyInfo)
   at Microsoft.AspNetCore.OData.Builder.ODataConventionModelBuilder.ReconfigureEntityTypesAsComplexType(EntityTypeConfiguration[] misconfiguredEntityTypes)
   at Microsoft.AspNetCore.OData.Builder.ODataConventionModelBuilder.RediscoverComplexTypes()
   at Microsoft.AspNetCore.OData.Builder.ODataConventionModelBuilder.GetEdmModel()
   at Microsoft.AspNetCore.OData.DefaultODataModelProvider.BuildEdmModel(Type apiContextType, AssembliesResolver assembliesResolver, Action`1 after)
   at Microsoft.AspNetCore.OData.Extensions.BuilderExtensions.AddOData[TODataService](IServiceCollection services, Action`1 after)
   at HCS.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at HCS.Program.Main(String[] args)
```
### Further technical details

MySQL version: 5.7.15
Operating system: macOS Sierra
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

Other details about my project setup:
Also running dot net core, aspnet core, and entity foundation core.

**Comment by RaviDesai** [comment]
Sorry - posted this in the wrong spot.  This is not an MySQL issue (as you can clearly see).
