### ISSUE TITLE
System.TypeLoadException: Method 'Apply' in type  'Microsoft.EntityFrameworkCore.Metadata.Conventions.Interna l.RelationalColumnAttributeConvention'

### ISSUE THREAD

**Issue by 491134648** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#72]
Hello:
  When I execute the command 'dotnet ef migrations add mysqlmigrations',Get an exception

```
dotnet : System.TypeLoadException: Method 'Apply' in type 
'Microsoft.EntityFrameworkCore.Metadata.Conventions.Interna
l.RelationalColumnAttributeConvention' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.0.0.0, Cult
ure=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
所在位置 行:1 字符: 1
+ dotnet ef migrations add mysqlmigrations
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.TypeLoad...implementation.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalConventionSetBuilder.AddConventions(Conve
ntionSet conventionSet)

   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder c
onventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()

   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scope
dCallSite, ServiceProvider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProv
ider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provid
er)


   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite
 transientCallSite, ServiceProvider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCall
Site constructorCallSite, ServiceProvider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite
 transientCallSite, ServiceProvider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProv
ider provider)


   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider p
rovider, Type serviceType)


   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvide
r provider)


   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String co
ntextType)


   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, 
String outputDir, String context, String environment, Action`1 reporter)


   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()

   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)


   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)

Method 'Apply' in type 'Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalColumnAttributeConventi
on' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793
829ddae60' does not ha
ve an implementation.
```

This is my DbContext 

``` c#
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            var mappingInterface = typeof(IEntityTypeConfiguration<>);
            // Types that do entity mapping
            var mappingTypes = GetType().GetTypeInfo().Assembly.GetTypes()
                .Where(x => x.GetInterfaces().Any(y => y.GetTypeInfo().IsGenericType && y.GetGenericTypeDefinition() == mappingInterface));

            // Get the generic Entity method of the ModelBuilder type
            var entityMethod = typeof(ModelBuilder).GetMethods()
                .Single(x => x.Name == "Entity" &&
                        x.IsGenericMethod &&
                        x.ReturnType.Name == "EntityTypeBuilder`1");

            foreach (var mappingType in mappingTypes)
            {
                // Get the type of entity to be mapped
                var genericTypeArg = mappingType.GetInterfaces().Single().GenericTypeArguments.Single();

                // Get the method builder.Entity<TEntity>
                var genericEntityMethod = entityMethod.MakeGenericMethod(genericTypeArg);

                // Invoke builder.Entity<TEntity> to get a builder for the entity to be mapped
                var entityBuilder = genericEntityMethod.Invoke(builder, null);

                // Create the mapping type and do the mapping
                var mapper = Activator.CreateInstance(mappingType);
                mapper.GetType().GetMethod("Map").Invoke(mapper, new[] { entityBuilder });
            }
        }
```

RelationInterface :

``` c#
   public interface IEntityTypeConfiguration<TEntity> where TEntity : class
    {
        /// <summary>
        /// 关系映射 Relation Map
        /// </summary>
        /// <param name="builder"></param>
        void Map(EntityTypeBuilder<TEntity> builder);
    }
```

Implementation:

``` c#
 public class BlogConfigutation : IEntityTypeConfiguration<Blog>
    {
        public void Map(EntityTypeBuilder<Blog> builder)
        {
            builder.HasKey(x => x.Id);
        }
    }
```

**Comment by Kagamine** [comment]
Can you format your issue content?

**Comment by 491134648** [comment]
Sorry !
 When I execute the command  
> dotnet ef migrations add mysqlmigrations

Get an exception is as follows:
`dotnet : System.TypeLoadException: Method 'Apply' in type 'Microsoft.EntityFrameworkCore.Metadata.Conventions.Interna
l.RelationalColumnAttributeConvention' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.0.0.0, Cult
ure=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
所在位置 行:1 字符: 1

dotnet ef migrations add mysqlmigrations
CategoryInfo : NotSpecified: (System.TypeLoad...implementation.:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalConventionSetBuilder.AddConventions(Conve
ntionSet conventionSet)

at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder c
onventionSetBuilder, IModelValidator validator)
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()

at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()

at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scope
dCallSite, ServiceProvider provider)

at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.b__0(ServiceProv
ider provider)

at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServiceT

at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite
transientCallSite, ServiceProvider provider)

at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCall
Site constructorCallSite, ServiceProvider provider)

at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite
transientCallSite, ServiceProvider provider)

at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.b__0(ServiceProv
ider provider)

at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider p
rovider, Type serviceType)

at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredServiceT

at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String co
ntextType)

at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, 
String outputDir, String context, String environment, Action`1 reporter)

at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.b__0()

at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)

at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)

Method 'Apply' in type 'Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalColumnAttributeConventi
on' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793
829ddae60' does not ha
ve an implementation.`

This is my DbContext method OnModelCreating as follows:
 

> protected override void OnModelCreating(ModelBuilder builder)
>    {
>        base.OnModelCreating(builder);
>        var mappingInterface = typeof(IEntityTypeConfiguration<>);
>        var mappingTypes = GetType().GetTypeInfo().Assembly
>            .GetTypes().Where(x => x.GetInterfaces().Any(y => y.GetTypeInfo()
>            .IsGenericType && y.GetGenericTypeDefinition() == mappingInterface));
>         var entityMethod = typeof(ModelBuilder).GetMethods()
>             .Single(x => x.Name == "Entity" && x.IsGenericMethod &&x.ReturnType.Name ==                     "EntityTypeBuilder`1");
>       foreach (var mappingType in mappingTypes)
>         {
>             var genericTypeArg = mappingType.GetInterfaces().Single().GenericTypeArguments.Single();
>             var genericEntityMethod = entityMethod.MakeGenericMethod(genericTypeArg);
>             var entityBuilder = genericEntityMethod.Invoke(builder, null);
>             var mapper = Activator.CreateInstance(mappingType);
>             mapper.GetType().GetMethod("Map").Invoke(mapper, new[] { entityBuilder });
>         }
>     }


RelationInterface as follows:

> public interface IEntityTypeConfiguration<TEntity> 
>            where TEntity : class { 
>  void Map(EntityTypeBuilder<TEntity> builder); }

Implementation RelationInterface as follows:

>  public class BlogConfigutation : IEntityTypeConfiguration<Blog>
>  { 
>           public void Map(EntityTypeBuilder<Blog> builder) 
>               { 
>                builder.HasKey(x => x.Id);
>                } 
> }

**Comment by Kagamine** [comment]
Which version are you using.

**Comment by 491134648** [comment]
>  "Pomelo.EntityFrameworkCore.MySql": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",

**Comment by Kagamine** [comment]
Can you try to use 1.0.1-prerelease-10014?

**Comment by 491134648** [comment]
When I execute the command 'dotnet ef migrations add mysqlmigrations',Get an exception

> dotnet : System.InvalidOperationException: Option 'sslmode' not supported.
所在位置 行:1 字符: 1
+ dotnet ef migrations add mysqlmigration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO... not supported.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at MySql.Data.MySqlClient.MySqlConnectionStringOption.GetOptionForKey(String key)

   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.set_Item(String key, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)

   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mySqlOptionsAction
)

   at Farmer.WebApp.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__0(DbContextOptionsBuilder options) in D:\lixise\Farmer\Farmer\Farmer.WebApp\Startup.cs:line 41


   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.DbContextOptionsFactory[TContext](IServiceProvider applicationServiceProvider, 
Action`2 optionsAction)

**Comment by Kagamine** [comment]
Ah, sslmode has blocked by https://github.com/bgrainger/MySqlConnector/issues/88.

**Comment by Kagamine** [comment]
@491134648 We have supported ssl in 1.0.1-prerelease-10016. Can you try again?

**Comment by 491134648** [comment]
I will try tomorrow,thank!

**Comment by Kagamine** [comment]
Close this as long time did not received reply.

**Comment by jyotendra** [comment]
I was getting this error when I upgraded to Msbuild using VS 2017. Updating nuget for entityframework.tools solved my issue.
