### ISSUE TITLE
Problem with JsonObject, i cant insert data with json column, mysql8

### ISSUE THREAD

**Issue by leobert1226** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#725]
### Steps to reproduce
my menu class:
![default](https://user-images.githubusercontent.com/46367729/50677054-adb15500-1032-11e9-98c5-3c874f4fbed1.png)

Startup.cs:
![default](https://user-images.githubusercontent.com/46367729/50677107-eea96980-1032-11e9-9009-2eb69fae62b7.png)

### The issue
when try to insert a menu like this

![default](https://user-images.githubusercontent.com/46367729/50677200-742d1980-1033-11e9-98d0-d78548fa1adb.png)

it cant work,. then i change property route to JsonObject<string> and JsonObject<Dictionary<string,object>>, i  cant work.
```
Exception message:
System.NullReferenceException:“Object reference not set to an instance of an object.”

Stack trace:
   at System.JsonObject`1.Equals(JsonObject`1 other)
   at lambda_method(Closure , InternalEntityEntry )
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at ZhiYuan.ISMS.Web.Controllers.AccountController.Login(String returnUrl) in D:\Git\Core\ZyISMS\ZhiYuan.ISMS.Web\Controllers\AccountController.cs:line 52
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

```

### Further technical details

MySQL version: 8.0.13
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
.net core version: 2.2.0

**Comment by leobert1226** [comment]
i tried the same codes under .net core 2.1, it worked. 
how cani fix it in .net core 2.2?

**Comment by mguinness** [comment]
The provider library version number is tightly coupled to the upstream EF library, so you will have to wait for version 2.2 to be released which has yet to be announced.

**Comment by gouhan** [comment]
@mguinness ,hi.
How long will the new version package released?
In worry.
