### ISSUE TITLE
Trying to setup build env

### ISSUE THREAD

**Issue by jrocha** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#745]
### Steps to reproduce
Just cloned this repo to a Win10 and tried to setup a build environment.

### The issue
Looks it is not happy run on MariaDB 10.3

```
Exception message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>> "$[0]") VIRTUAL NULL,
    `Email` VARCHAR(63) GENERATED ALWAYS AS (`ContactI' at line 3
Stack trace:
```

### Further technical details
C:\data\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\scripts>rebuild.cmd
Dropping database 'pomelo_test'.
Successfully dropped database 'pomelo_test'.
Done. To undo this action, use 'ef migrations remove'
C:\data\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\Migrations\20190219180244_initial.cs
C:\data\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\Migrations\20190219180244_initial.Designer.cs
C:\data\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\Migrations\AppDbModelSnapshot.cs
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>> "$[0]") VIRTUAL NULL,
    `Email` VARCHAR(63) GENERATED ALWAYS AS (`ContactI' at line 3 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>> "$[0]") VIRTUAL NULL,
    `Email` VARCHAR(63) GENERATED ALWAYS AS (`ContactI' at line 3
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 43
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 81
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 307
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 292
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 276
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 77
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>> "$[0]") VIRTUAL NULL,
    `Email` VARCHAR(63) GENERATED ALWAYS AS (`ContactI' at line 3

C:\data\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\scripts>

MySQL version: 10.3.12-mariadb
Operating system: Microsoft Windows [Version 10.0.17134.590]
Pomelo.EntityFrameworkCore.MySql version: 
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by mguinness** [comment]
It would seem that the JSON unquoting extraction operator added in MySQL 5.7.13 is not supported by MariaDB.  You'll have to skip those functions similar to what was done for AppVeyor.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/c58e00c7b3b6bc8f2eeffebd4d10f2e1ff16b790/test/EFCore.MySql.IntegrationTests/Models/GeneratedTypes.cs#L14-L15

**Comment by BartjeD** [comment]
I've reproduced this and created a pull request,
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/780

@jrocha 
@mguinness

**Comment by caleblloyd** [comment]
#780 merged
