### ISSUE TITLE
EF still looking for column after removing it

### ISSUE THREAD

**Issue by NicQb1** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#755]
### Steps to reproduce
I have the model builder code as follows:
 ```
modelBuilder.Entity("Vrn.Db.Models.Brand", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DATECREATED")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<sbyte>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ACTIVE")
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("VARCHAR(250)");
                    b.Property<uint>("UserId")
                        .HasColumnName("USERID");
                    b.HasKey("Id");
                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IDX_BRAND_NAMEUNIQUE");
                    b.ToTable("brand");
                });

The class looks like:

  public class Brand
    {
        public uint Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public DateTime DateCreated { get; set; }
        public uint UserId { get; set; }
    }
```

I manually dropped the column from MySQL

### The issue
When I hit my endpoint I see that it's still trying to use the column "ProductTypeId" even though it's been removed. I removed it from the migrations scripts as well. I see the following error message when i hit the endpoint

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://host.docker.internal:5000/api/inventory/Brand/AddAsync application/json 45
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "AddAsync", controller = "Brand"}. Executing action Vrn.WebApi.Controllers.Inventory.BrandController.AddAsync (Vrn.WebApi)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Vrn.WebApi.Controllers.Inventory.BrandController.AddAsync (Vrn.WebApi) with arguments (Vrn.Db.Models.Brand) - Validation state: Valid
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.4-rtm-31024 initialized 'VirtueRnDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (48ms) [Parameters=[@p0='?' (DbType = DateTime), @p1='?' (DbType = SByte), @p2='?' (Size = 250) (DbType = AnsiString), @p3='?' (DbType = UInt32), @p4='?' (DbType = UInt32)], CommandType='Text', CommandTimeout='30']
      **INSERT INTO `brand` (`DATECREATED`, `ACTIVE`, `NAME`, `ProductTypeId`, `USERID`)
      VALUES (@p0, @p1, @p2, @p3, @p4);
      SELECT `ID`
      FROM `brand`
      WHERE ROW_COUNT() = 1 AND `ID` = LAST_INSERT_ID();**
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'ProductTypeId' in 'field list' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'ProductTypeId' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Vrn.Db.VirtueRnDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'ProductTypeId' in 'field list' ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'ProductTypeId' in 'field list'
         at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
         --- End of inner exception stack trace ---
         at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
         at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
         at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
         at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'ProductTypeId' in 'field list' ---> MySql.Data.MySqlClient.MySqlException: Unknown column 'ProductTypeId' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 
Operating system:  win 10
Pomelo.EntityFrameworkCore.MySql version: 2.2
Microsoft.AspNetCore.App version:

Other details about my project setup:
I've deleted my bin directories and obj directories and rebuilt everything.....several times.

**Comment by mguinness** [comment]
Can't reproduce with the information provided.  Do you have another brand class in another namespace?

**Comment by NicQb1** [comment]
I have a BrandDTO but its not being used in the endpoint.

**Comment by NicQb1** [comment]
Ill put my code in a repo tonight.
