### ISSUE TITLE
Connection Resiliency doesn't trigger when mysql server is stopped

### ISSUE THREAD

**Issue by Mikaka27** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#766]
### Steps to reproduce
1. Prepare project with connection string that points to host which has no mysql server running (or exists but is stopped)
2. Enable connection resiliency in OnConfiguring method like follows:
`optionsBuilder.UseMySql(ConfigurationManager.ConnectionStrings["MyConnectionString"].ConnectionString, o =>
				{
					o.EnableRetryOnFailure(10, TimeSpan.FromSeconds(30), null);
				});`
3. Execute any query against database

### The issue
Connection resiliency fails to work in this case and I receive MySqlException after 16-17 seconds, which do not match the retry configuration specified above.

I would expect it to fail after retrying 10 times, 30 seconds each, so after 5 minutes.

This is the exception I see:

```
`MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Connect Timeout expired.
  Source=MySqlConnector
  StackTrace:
   at MySqlConnector.Core.ServerSession.<OpenTcpSocketAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 785
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__64.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 274
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 111
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__97.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 515
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__27.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 244
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenDbConnectionAsync>d__48.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__45.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 128
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Gui.Database.Managers.DatabaseManager.<GetAccountsAsync>d__17.MoveNext() in C:\Users\Mikaka\Documents\Visual Studio 2017\Projects\MyProject\Gui\Database\Managers\DatabaseManager.cs:line 107
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Gui.MainWindow.<Window_Loaded>d__186.MoveNext() in C:\Users\Mikaka\Documents\Visual Studio 2017\Projects\MyProject\Gui\MainWindow.xaml.cs:line 129

Inner Exception 1:
ObjectDisposedException: Nie można uzyskać dostępu do usuniętego obiektu.`
```

### Further technical details

MySQL version: 8.0.15
Operating system: Windows 10 x64 1809
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: This is NetFramework 4.7 WPF application

I run MySql server on a remote Ubuntu Server 18.04 host. This MySql server is stopped for this test, so outcome should be the same as if I pointed (in connection string) to host which has no mysql server.

I'm trying to make my project resistant to short network outages, and thought this option would be help, but I cannot trigger it at all.

**Comment by mguinness** [comment]
This feature was added in PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/425 and exception detection code in MySqlTransientExceptionDetector class.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/42c335ceac6d93d1c0487ef45fc992810c07fd9d/src/EFCore.MySql/Storage/Internal/MySqlTransientExceptionDetector.cs#L24-L36

From what I can see a connection timeout is error number 0 which isn't currently handled.  I think ideally the following code in [MySqlConnection](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs) class could be changed in the underlying MySqlConnector library:

`throw new MySqlException("Connect Timeout expired.", ex);`
TO
`throw new MySqlException((int) MySqlErrorCode.UnableToConnectToHost, null, "Connect Timeout expired.", ex);`

Then UnableToConnectToHost error 1042 could be handled in the MySqlTransientExceptionDetector class.

**Comment by mguinness** [comment]
If anyone is interested in contributing to this issue, MySqlConnector release [0.51.0](https://www.nuget.org/packages/MySqlConnector/0.51.0) now supports `MySqlErrorCode.UnableToConnectToHost` error number.

I would also suggest replacing the integer error numbers with [MySqlErrorCode](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySql.Data.MySqlClient/MySqlErrorCode.g.cs) enumeration.

**Comment by BartjeD** [comment]
I have reproduced this and have forked a branch in which I am adding:

// Thrown if timer queue couldn't be cleared while reading sockets
case MySqlErrorCode.CommandTimeoutExpired:
// Unable to open connection
case MySqlErrorCode.UnableToConnectToHost:

As enum per your suggestions @mguinness 
I am going through the MySqlConnector repo to spot whether there are any other error codes we should handle. I was thinking of 'AbortingConnection / 1152'

**Comment by BartjeD** [comment]
I have opened a pull request for this issue,
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/779

**Comment by mguinness** [comment]
@xcellsoft As you introduced this feature, do you have any comments on this PR?

**Comment by xcellsoft** [comment]
I no longer use entity framework in my current projects.

My original resolution was based off of the sql server resiliency and included a wide range of error code including 0 which was the important for connection recovery, also i added the ability to specify additional error codes with the option builder, refer to my pull request for details. There was some debate on my implementation and that's probably why your having some issues. I also had to modify some code that is specific to this driver where it gets server information outside of the normal traps. Good luck.

[https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/425](url)

**Comment by BartjeD** [comment]
Pull request has been completed @Mikaka27.
