### ISSUE TITLE
Option 'trusted_connection' not supported.

### ISSUE THREAD

**Issue by liuzhenyulive** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#774]
### Steps to reproduce
1.download project from   https://aspnetboilerplate.com/Templates .
2. add nuget package and alter db configeration

``` c#
    public static class MiniBlogDbContextConfigurer
    {
        public static void Configure(DbContextOptionsBuilder<MiniBlogDbContext> builder, string connectionString)
        {
            builder.UseMySql(connectionString);
        }

        public static void Configure(DbContextOptionsBuilder<MiniBlogDbContext> builder, DbConnection connection)
        {
            builder.UseMySql(connection);
        }
    }
```
3. add-migration Initial_Migration at package manager console

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
PM> add-migration Initial_Migration
System.ArgumentException: Option 'trusted_connection' not supported.
   at MySql.Data.MySqlClient.MySqlConnectionStringOption.GetOptionForKey(String key) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 396
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.set_Item(String key, Object value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 310
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql[TContext](DbContextOptionsBuilder`1 optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at Abp.MiniBlog.EntityFrameworkCore.MiniBlogDbContextConfigurer.Configure(DbContextOptionsBuilder`1 builder, String connectionString) in C:\Users\liuzh\MyBox\GitHub\Abp.MiniBlog\Abp.MiniBlog\src\Abp.MiniBlog.EntityFrameworkCore\EntityFrameworkCore\MiniBlogDbContextConfigurer.cs:line 10
   at Abp.MiniBlog.EntityFrameworkCore.MiniBlogDbContextFactory.CreateDbContext(String[] args) in C:\Users\liuzh\MyBox\GitHub\Abp.MiniBlog\Abp.MiniBlog\src\Abp.MiniBlog.EntityFrameworkCore\EntityFrameworkCore\MiniBlogDbContextFactory.cs:line 17
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Option 'trusted_connection' not supported.
```

### Further technical details

MySQL version: 8.0
Operating system: win10_64 
Pomelo.EntityFrameworkCore.MySql version: 2.20
Microsoft.AspNetCore.App version: 2.2

Other details about my project setup:

connectstring :
```
"Server=localhost;Database=MiniBlogDb;User ID=root;Password=123456;"
```

**Comment by liuzhenyulive** [comment]
Oh, No, The still have a other  appsetting.json file, I remove trusted_connection, it worked,
