### ISSUE TITLE
NotSupportedException, enum type not mapped to db type correctly. 

### ISSUE THREAD

**Issue by liamwang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#78]
### Steps to reproduce
Add an entity class with a enum type property. Such as:
```csharp
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public EditorType EditorType { get; set; }
        ...
    }

    public enum EditorType : byte
    {
        WYSIWYG = 0,
        Markdown = 1
    }
```

Create and savechages:
```csharp
var post = new Post{ ..., EditorType = EditorType.WYSIWYG  };
context.Set<Post>().Add(post);
context.SaveChanges();
```

### The issue
A NotSupportedException throwed at `context.SaveChanges();`。

```
Exception message:

NotSupportedException: Parameter type EditorType (DbType: Byte) not currently supported. Value: WYSIWYG

Stack trace:

System.NotSupportedException: Parameter type EditorType (DbType: Byte) not currently supported. Value: WYSIWYG
   at MySql.Data.MySqlClient.MySqlParameter.AppendSqlString(BinaryWriter writer, StatementPreparerOptions options)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParameterSqlParser.DoAppendParameter(Int32 parameterIndex, Int32 textIndex, Int32 textLength)
   at MySql.Data.MySqlClient.MySqlParser.Parse(String sql)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParseAndBindParameters()
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.<ExecuteAsync>d__20.MoveNext()
```

### Further technical details

MySQL version: 5.7
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.0.1-prerelease-10014

**Comment by Kagamine** [comment]
Could you remove inherit from byte?

**Comment by liamwang** [comment]
@Kagamine Removing byte declaration is OK.
