### ISSUE TITLE
unable to cast object of type System.Data.SqlClient.SqlParameter to type mysql.Data.MySqlClient.MysqlParameter

### ISSUE THREAD

**Issue by pantonis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#796]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
I am using EF Core 2.2.0 and I have the code below that when executes it throws an exception as described below.
When I change SqlParameter to MySqlParamer the code works. But we are losing the actual purpose of the EF Core which is database agnostic.

```
var dateFromParam = new SqlParameter("@DateFrom", dateFrom.Date.ToString("yyyy-MM-dd"));
            var dateToParam = new SqlParameter("@DateTo", dateTo.Date.ToString("yyyy-MM-dd"));

            List<MyModel> result = await context.Query<MyModel>().AsNoTracking().FromSql(
                                                           "CALL myDB.StoredProcedure1(@DateFrom, @DateTo)",
                                                           dateFromParam, dateToParam).ToListAsync();
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Unable to cast object of type 'System.Data.SqlClient.SqlParameter' to type 'MySql.Data.MySqlClient.MySqlParameter'.
Stack trace:
   at MySql.Data.MySqlClient.MySqlParameterCollection.Add(Object value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlParameterCollection.cs:line 32
   at Microsoft.EntityFrameworkCore.Storage.Internal.DynamicRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.CompositeRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__31`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext() in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Aggregate.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Further technical details

MySQL version: 8
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2.0

Other details about my project setup:

**Comment by bgrainger** [comment]
> But we are losing the actual purpose of the EF Core which is database agnostic.

`SqlParameter` is not a database-agnostic class; it's specific to SQL Server. The DB agnostic type is `DbParameter`.

If you have a `DbProviderFactory` object, you can call [`DbProviderFactory.CreateParameter`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbproviderfactory.createparameter?view=netframework-4.8#System_Data_Common_DbProviderFactory_CreateParameter) to create a parameter, then set its `ParameterName`, `Value` properties, etc.

Or if you have a `DbConnection` object, you can call [`DbConnection.CreateCommand`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.createcommand?view=netframework-4.8) to get a `DbCommand` object, then call `DbCommand.CreateParameter`.

(There might be some APIs in EF.Core to create parameters, too; I'm less familiar with that so can't say for sure.)

**Comment by lauxjpn** [comment]
The solution @bgrainger posted is the route to choose for EF Core 2.2.x, if you want to make your code less database provider dependent.

This is not relevant to EF Core 3.0.0, as it replaced `FromSql()` with `FromSqlInterpolated()` and `FromSqlRaw()`, which take parameters in form of direct values instead of `DbParameter` derived objects.

---

> But we are losing the actual purpose of the EF Core which is database agnostic.

I disagree on this general statement. The main purpose of EF Core is to abstract you code away from SQL and bind your object model to your database tables with as little pain as possible.

The moment you use methods like `FromSql()` in your code, you are leaving the database-agnostic territory anyway.

The official [elevator pitch](https://docs.microsoft.com/en-us/ef/core/) for EF Core is this one:

> EF Core can serve as an object-relational mapper (O/RM), enabling .NET developers to work with a database using .NET objects, and eliminating the need for most of the data-access code they usually need to write.
