### ISSUE TITLE
System.ArgumentException: Unqualified data type varchar

### ISSUE THREAD

**Issue by khteh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#868]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.
I am using ASP.Net Core 3.0 with EF Core 3.0 and the latest Pomelo package. Bump into this exception when the application runs the following code:

The exception is thrown in a `IServiceProvider` scope when a DbContext is accessed.
```
using (var scope = sp.CreateScope())
try
{
// access DbContext;
}
```
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Unhandled exception. System.ArgumentException: Unqualified data type varchar
Stack trace:
Unhandled exception. Unhandled exception. System.ArgumentException: Unqualified data type varchar
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.ValidateMapping(CoreTypeMapping mapping, IProperty property)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo& mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.TypeMappingConvention.ProcessModelFinalized(IConventionModelBuilder modelBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Biz4x.Backend.Repositories.CommonLoaderRepository.LoadAllCountriesCitiesAndIsoCurrencies() in /usr/src/4xlabs/bz-frontend/src/Biz4x.Backend.Repositories/CommonLoaderRepository.cs:line 24
   at Biz4x.Backend.Services.Providers.CommonProvider.<Initialize>b__27_0(ICommonLoaderRepository repository) in /usr/src/4xlabs/bz-frontend/src/Biz4x.Backend.Services/Providers/CommonProvider.cs:line 60
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

### Further technical details

MySQL version: 8.0.17
Operating system: Ubuntu 19.04
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:

**Comment by lauxjpn** [comment]
> Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

Please provide us with your `Domain.Country` model (the actual class), the corresponding model definition (the `ModelBuilder` calls in `OnModelCreating()`) and a SQL dump of the table with some sample data, so we can reproduce this issue on our end.

**Comment by khteh** [comment]
Further investigations show that the exception thrown is NOT specific to that table. The exception is thrown in a `IServiceProvider` scope when a DbContext is accessed.
```
            using (var scope = sp.CreateScope())
            try
            {
```
As I have around 141 tables in the database, I can't identity which table/column that cases the exception. It would be helpful to understand what the exception message `Unqualified data type varchar` means in order to narrow down the debugging scope. Any thought on this?

**Comment by lauxjpn** [comment]
This is the method that throws:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/49cac2e6dd08e60e2cb91c8127f087af8a9f594e/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L244-L252

It checks for disallowed types. A look into the disallowed types, reveals the following:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/49cac2e6dd08e60e2cb91c8127f087af8a9f594e/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L97-L106

With the comment explaining the root cause of the problem:

```c#
// These are disallowed only if specified without any kind of length specified in parenthesis.
```

**Comment by khteh** [comment]
Creating an extension method for `PropertyBuilder` and add `HasColumnType($"varchar({maxLength})")` works. Thanks.
