### ISSUE TITLE
Failed to connect to MariaDB hosted on Linux

### ISSUE THREAD

**Issue by Harardin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#873]
All works fine on windows but when I am running my app on CentOS it breaks because it fails to connect to MarinaDB on local

Program is a simple .NET Core 3.0 Console Application.

My Connection string is: `SERVER=116.203.211.43;DATABASE=amazon_db;USER=mgtuser;PASSWORD=ThePassword;PORT=3306`

And my DB Context code:

```
using Microsoft.EntityFrameworkCore;

namespace AmazonDemonParser.Models
{
    public class DbContextModel : DbContext
    {
        private string ConnectionString;
        public DbContextModel(string _connString)
        {
            ConnectionString = _connString;
        }
        public DbSet<TaskModel> TaskModelSet { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySql(ConnectionString);
        }
    }
}

```

**Comment by lauxjpn** [comment]
> [...] it breaks because it fails to connect to MarinaDB on **local**

First observation is, that you are connecting to a non-local ip address:

> SERVER=**116.203.211.43**;DATABASE=amazon_db;USER=mgtuser;PASSWORD=ThePassword;PORT=3306

Second observation is, that you provided us with your **real and working** access information.
Which I just used to successfully connect to your MariaDB database server.

```
PS C:\Users\Lau> & 'D:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe' -h 116.203.211.43 -P 3306 -u mgtuser -pThePassword amazon_db
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 26
Server version: 5.5.5-10.4.8-MariaDB MariaDB Server

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| amazon_db          |
| information_schema |
| mysql              |
| performance_schema |
| test               |
+--------------------+
5 rows in set (0.03 sec)
```

I therefore edited your post, removed at least your password, and deleted the original version of the post.

**Comment by jespersh** [comment]
@Harardin in case @lauxjpn didn't make it clear. You should now consider the server and the databases content compromised. Even though he deleted the password from your original post, others may have seen it or have the password in their email inbox now due to github sending notification emails out.

Depending on the content and your country then you'll need to notify someone appropriate if the content contains person data.

**Do not use that mysql instance anymore**

**Comment by lauxjpn** [comment]
> Even though he deleted the password from your original post, others may have seen it or have the password in their email inbox now due to github sending notification emails out.

@jespersh Good point!

**Comment by Harardin** [comment]
Damn, this was real miss at my side, thank everyone for noticing my mistake about pointing my password.

**Comment by Harardin** [comment]
Also I forgot to mention this is connection string from Windows, when on CentOS it looks like this `SERVER=127.0.0.1;DATABASE=amazon_db;USER=mgtuser;PASSWORD=ThePasswordThatIFried;PORT=3306;`

**Comment by jespersh** [comment]
My suggestion to abandoning it all together, is someone could have created events (https://dev.mysql.com/doc/refman/8.0/en/create-event.html) unbeknownst to you to do all manner of nasties, or created another user and setup a replicating slave to siphon the data as it is inserted.

Once it is compromised and you don't know how to deal with all these cleanup nuances. Then you'll really draw the short straw against someone who does.

**Comment by lauxjpn** [comment]
Have you checked this:

>@Harardin Can you connect to the MariaDB database using the MySQL command line tools from the same machine you run your app on?

**Comment by Harardin** [comment]
> Have you checked this:
> 
> > @Harardin Can you connect to the MariaDB database using the MySQL command line tools from the same machine you run your app on?

Yes

**Comment by lauxjpn** [comment]
Which CentOS version are you using?

**Comment by bgrainger** [comment]
> when I am running my app on CentOS it breaks because it fails to connect to MariaDB on local

Please provide the full exception message and call stack, including any inner exceptions.

If, for example, the exception message is "SSL Handshake failed with OpenSSL error" then there are issues on the dotnet/corefx repo that discuss some breaking changes in .NET Core 3.0 related to this. You could try applying the workarounds in those cases, or enabling `SslMode=None` (for local connections), or using a Unix domain socket. (OTOH, if the exception message is different, a different solution is most likely needed.)

**Comment by Harardin** [comment]
> Which version of the following components do you use:
> 
> * CentOS
> * .NET Core
> * EF Core
> * Pomelo.EntityFrameworkCore.MySql
> * MySqlConnector
> 
> I will try to reproduce this issue.

Parameters that I use to run my program

CentOS = 7.0
.NET Core = 3.0
EF Core = 3.0.0
Pomelo.EntityFrameworkCore.MySql = 3.0
MySqlConnector = 0.59.2

Full exception message:

```
Unhandled exception. MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 326
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 507
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 232
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GetResult[TResult](IAsyncEnumerable`1 valueBuffers, Boolean throwOnNullResult, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
```

**Comment by lauxjpn** [comment]
> EF Core = 3.0.0
> Pomelo.EntityFrameworkCore.MySql = 2.2.0

EF Core 3.0.0 and Pomelo.EntityFrameworkCore.MySql 2.2.0 are not compatible with each other.

If you want to use EF Core 3.0.0, there is a prelease of [Pomelo.EntityFrameworkCore.MySql (version 3.0.0-rc1.final) on NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.0.0-rc1.final) that should work.

Otherwise, EF Core 2.2.x can be used together with Pomelo.EntityFrameworkCore.MySql 2.2.x and .NET Core 3.0.
