### ISSUE TITLE
MySqlConversionException on 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by drakoumel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#89]
### Steps to reproduce
Create a table that includes a Datetime field.
Create an entry on the table setting the Datetime to 0000-00-00 00:00:00

### The issue
When I try to fetch this row an exception is being thrown: (full stack trace at the bottom of the ticket)
```
Pomelo.Data.Types.MySqlConversionException: Unable to convert MySQL date/time value to System.DateTime
```
I would expect this to be handled, and return maybe even a null value instead of breaking.
### Further technical details

MySQL version: 5.6
Operating system: Ubuntu 12.04
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

Other details about my project setup:

```
fail: Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      Pomelo.Data.Types.MySqlConversionException: Unable to convert MySQL date/time value to System.DateTime
         at Pomelo.Data.Types.MySqlDateTime.GetDateTime()
         at Pomelo.Data.MySql.MySqlDataReader.GetDateTime(Int32 i)
         at lambda_method(Closure , DbDataReader )
         at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
         at lambda_method(Closure , QueryContext )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
Pomelo.Data.Types.MySqlConversionException: Unable to convert MySQL date/time value to System.DateTime
   at Pomelo.Data.Types.MySqlDateTime.GetDateTime()
   at Pomelo.Data.MySql.MySqlDataReader.GetDateTime(Int32 i)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKVO607S35OR": An unhandled exception was thrown by the application.
Pomelo.Data.Types.MySqlConversionException: Unable to convert MySQL date/time value to System.DateTime
   at Pomelo.Data.Types.MySqlDateTime.GetDateTime()
   at Pomelo.Data.MySql.MySqlDataReader.GetDateTime(Int32 i)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at DatacircleAPI.Controllers.DatasourceController.Get(Nullable`1 id) in /Users/christoszioutas/Development/DatacircleAPI/Controllers/DatasourceController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by caleblloyd** [comment]
Try putting `Convert Zero Datetime=true` in your [connection string](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html)

**Comment by drakoumel** [comment]
thnx for the quick reply, I will test it locally and update the ticket accordingly.

**Comment by drakoumel** [comment]
@caleblloyd worked like a charm thnx a lot!
