### ISSUE TITLE
DatabaseFacade.EnsureCreated throws 'MySqlDbException'

### ISSUE THREAD

**Issue by LeaFrock** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#892]
### Steps to reproduce
`using var context = new MyDbContext(DbConfig);`
`context.Database.EnsureCreated();`

As the annotation says, the method should return a 'bool' value instead of throwing an exception. But in fact it throws and the message tells 'Table xxxx already exists'.
So I turn on the 'general_log' of local MySql, check the sql it gets and I find something wrong.  Please see the image below.
![20191024181014](https://user-images.githubusercontent.com/20787265/67475895-9870ea00-f689-11e9-8465-1a9e26bbfe25.png)

### The issue
I wonder what's wrong about the problem above. Why doesn't the sql of table creating contain '**if not exists**'? Is it a bug or just my misunderstanding?

Exception message:
`MysqlDbException: Table MyTableName already exists`
Stack trace:
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__95.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__63.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateTables()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
  ……（skip useless info here）
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
  ……（skip useless info here）
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SpiderX.Launcher.BllCaseLaunchService.<StartAsync>d__5.MoveNext() in D:\ProgramDemos\Github\SpiderX\SpiderX.Launcher\BllCaseLaunchService.cs:line 72
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SpiderX.Launcher.Program.<Main>d__0.MoveNext() in D:\ProgramDemos\Github\  ……（skip useless info here）\Program.cs:line 81

### Further technical details
MySQL version: 8.0
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 3.0-rc1
Microsoft.AspNetCore.App version: 3.0

**Comment by lauxjpn** [comment]
See [DatabaseFacade.EnsureCreated on MSDN](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-3.0) for the EF Core behavior of this method:

> Ensures that the database for the context exists. If it exists, no action is taken. If it does not exist then the database and all its schema are created. If the database exists, then no effort is made to ensure it is compatible with the model for this context.

The exact EF Core behavior is the following:

```c#
public virtual bool EnsureCreated()
{
    using (new TransactionScope(TransactionScopeOption.Suppress,
               TransactionScopeAsyncFlowOption.Enabled))
    {
        if (!Exists())
        {
            Create();
            CreateTables();
            return true;
        }

        if (!HasTables())
        {
            CreateTables();
            return true;
        }
    }

    return false;
}
```
If the database does not exist, the database and all tables are being created.
If the database does exist, the database is checked for the existence of any table. If at least one is found, no tables are being created, otherwise all tables are being created.

What is interesting in your case is, that your database seems to not exist (or is empty) at the beginning of the call to `DatabaseFacade.EnsureCreated()`, but throws later, when creating a table that does already exist.

This would suggest, that the table that is being created at the point in time the exception is thrown, has already been created during the call of the `DatabaseFacade.EnsureCreated()` method. 

Is your model using the same table name twice?

**Comment by LeaFrock** [comment]
@lauxjpn Thank you very much about your reply and I'm touched by the codes you show me. So I decide to find the reason even if I'm staying up late. Luckily, I think I find the direct reason, but may still need you to tell me why.
I change your codes like below.
```C# using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ConsoleAppTest
{
	public class Blog
	{
		public int BlogId { get; set; }
		public string Description { get; set; }
	}

	public class Issue892Context : DbContext
	{
		public DbSet<Blog> Blogs { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder
				.UseMySql("server=127.0.0.1;port=3306;user=root;password=20180423;database=test")//I change the port/psw in my local. Please notice the database.
				.UseLoggerFactory(LoggerFactory.Create(b => b.AddConsole()))
				.EnableDetailedErrors();
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			Debugger.Launch();
			modelBuilder.HasDefaultSchema("Blog");// <========== Here is the key point! I want the table to be created in schema 'blog' instead of 'test'.
			modelBuilder.Entity<Blog>()
				.HasData(new Blog { BlogId = 1, Description = "This is my blog." });
		}
	}

	internal class Program
	{
		private static void Main()
		{
			using var context = new Issue892Context();
			context.Database.EnsureCreated();
			var theBlog = context.Blogs.Single();
			Debug.Assert(string.Equals(theBlog.Description, "This is my blog."));
			Console.ReadKey();
		}
	}
}
```
**Please notice the code annotations I add**. Let's create the 'test' schema firstly, then something interesting will happen.

- If the schema 'blog' does not exist, everything seems to be OK.

![image](https://user-images.githubusercontent.com/20787265/67509667-1357f600-f6c6-11e9-800a-712954c29c43.png)
![image](https://user-images.githubusercontent.com/20787265/67509716-2ff42e00-f6c6-11e9-85d0-b3ef840391ad.png)

**But if you take a look at the 'create table' sql, you may realize the direct reason of my issue.**

- If the schema 'blog' exists but the table does not exist, it's certainly OK.

- **If both the schema 'blog' and table exist, the issue is reproduced.**

![image](https://user-images.githubusercontent.com/20787265/67510364-63838800-f6c7-11e9-8606-4424fde638be.png)

The question is, that I'm not sure if my codes using 'HasDefaultSchema' to create a table in a specified schema are right. If it's my wrong use's fault rather than a bug, forgive me for wasting your time. Thanks again.

**Comment by lauxjpn** [comment]
There is no support for the EF Core concept of schemas in MySQL.

Also see the [MSDN article](https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-schema) on default schema:

>For example, Microsoft SQL Server will use the dbo schema and SQLite will not use a schema (since schemas are not supported in SQLite).

So like SQLite, MySQL does not support schemas as well.

---

What MySQL calls a "schema" is just a "database" in EF Core. So you are using the wrong tool for the job.

If you want to use a different database for specific tables, you will need to use multiple `DbContext` derived classes, each with it's own connection to a database.

---

If you want to read-up on schemas, SQL Server allows for [different schemas](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/ownership-and-user-schema-separation-in-sql-server) in a single database.
