### ISSUE TITLE
Crashing and poor stability in ASP Net Core NullReference/ObjectDisposed/DBUpdateException

### ISSUE THREAD

**Issue by Nick-Lucas** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#91]
@caleblloyd here is a reproduction project for an issue I was not able to to work around, as related to [this discussion](https://github.com/mysql-net/MySqlConnector/issues/104)

Steps to reproduce
Clone, restore and run the following:
https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug
Follow steps in README.md. This is an ASP Core project and the way it's set up requires you to click a button in your web browser.

### The issue
Crashes whenever trying to update data on (but not necessarily limited to) a Post endpoint, inconsistent exceptions.
I am not at all sure how to track down the problem further, as I'm not even getting a stacktrace back.

### Further technical details

MySQL version: 
mysql --version: `mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64)` on Ubuntu in Vagrant
Operating system: Windows 10 (latest)
Pomelo.EntityFrameworkCore.MySql version: "1.0.1-prerelease-10018"

Other details about my project setup:
Reproduction project:
https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug

**Comment by Nick-Lucas** [comment]
When I faced this issue in my personal project, I switched provider and DBMS to NpgSql/Postgres and the issue completed went away, implying it's related to Pomelo/MysqlConnector.

**Comment by caleblloyd** [comment]
@Nick-Lucas thanks for the very detailed report and sharing your code!  I haven't written any tests for a scoped context like this yet, I'll add tests using this style.  Should have it figured out by the end of the weekend.

**Comment by Nick-Lucas** [comment]
No problem! It's worth mentioning explicitly that I did try this as a console application and disposing of the DBContext to try and mimic the web request scoping, and couldn't get a repro case until I introduced ASP, so I suspect it's the dependency injection scoping which triggers the issue.

**Comment by caleblloyd** [comment]
@Nick-Lucas try changing your function signature in [HomeController.cs#L21](https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug/blob/master/src/ASPCore/Controllers/HomeController.cs#L21) to `public async Task SetModel`

Right now it is set to `public async void SetModel`.  What I am seeing when I run your app is `SetModel` returns immediately and doesn't actually await anything (since it has returned void and not an empty Task).  This causes your Scoped `DbContext` to call Dispose, and free it's connection.  Meanwhile, your async code is still executing against a disposed connection, which throws some weird exceptions.

The proper way to declare a void method in the async world is to make the return type an empty `Task`.

As of 1.0.1-prerelease-10019, you should be able to set `UseAffectedRows=false` in your connection string to achieve unchecked update behavior.

Let me know if you're still seeing issues after implementing these changes.

**Comment by caleblloyd** [comment]
I've updated our [Async Performance Test Controllers](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Controllers/AsyncController.cs) to use DI, you may want to look at them as a sample.

I like to use `public async Task<IActionResult>` for all of my async controller methods.  If it's a method that does not require a response body, such as a `DELETE` method, returning `Ok();` will send a HTTP 200 OK response to the browser.

**Comment by Nick-Lucas** [comment]
Okay I've just updated [Pomelo and switched the endpoint to return Task](https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug/commit/7a021a62f2dc8e4cfe042f6adbefd1bafff4fcac) and [switched off UseAffectedRows](https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug/commit/a4abac6ecf9c5f7b4832841008fdbd25fe9a93ac)

The problem is still there, but the step forward with return Task is ASP no longer completely exits without a useful stacktrace. We now get this on the Console:

``` C#
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
MySql.Data.MySqlClient.MySqlException: Connect Timeout expired. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__21_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.<OpenSocketAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at MySql.Data.Serialization.MySqlSession.<OpenSocketAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryingEnumerable`1.MySqlEnumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(IEnumerable`1 entities)
   at ASPCore.Controllers.HomeController.<GetModel>d__4.MoveNext() in C:\Users\nicho\Local\Repositories\EFCorePomeloBugReproduction\src\ASPCore\Controllers\HomeController.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by caleblloyd** [comment]
That looks like an error connecting to your MySQL server.  Do any requests work or is there a problem with your server configuration?

**Comment by Nick-Lucas** [comment]
Do you have any thoughts on what I should check?

The user is configured as a full grant user, since it's for dev purposes, and the migrations and initial query which loads the page work fine. That's not to say it's definitely working properly, as I rarely use this installation, but I've found that migrations and queries using Pomelo seem to work just fine, so it surprises me a simple update might not.

I've just attempted manually creating `MyDBContext` from the endpoint to cut out DI and the same issue is occurring. A console write indicated the connection is closed by default (which may be a simple optimisation, I wouldn't now) and manually opening it causes the same crash.
This branch is available here: https://github.com/Nick-Lucas/ASPCore-EFCore-Pomelo-MySql-NullReferenceBug/tree/test/create-connection-manually 

I can attempt reproduction on my work PC tomorrow which I can guarantee is working fine, alternatively, have you been able to clone and build the test project yourself?

**Comment by caleblloyd** [comment]
Yes, I cloned and tested it when I initially found the `void` to `async` fix.  After making that change, it worked for me.

I'll try it again this evening or tomorrow evening with your updates and see if I find any bugs.  If your migration connection string works, your app connection string should work, so not sure of the issue.  Which version of MySQL server are you running?

**Comment by Nick-Lucas** [comment]
Okay that's interesting, it does seem to point at a configuration issue on my side. 
Yes that's my MySql version.

I will run this on my dev machine at work too, to confirm.

**Comment by Nick-Lucas** [comment]
Okay looks like this is working okay, my Vagrant installation at home must be dying. Apologies for any time wasted!
