### ISSUE TITLE
Cannot cast enum  to int in where clause.

### ISSUE THREAD

**Issue by hrattls** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#957]
### The issue

My code contains the following where clause:

```
query = query.Where(sjabloonveld => sjabloonveld.Portalnotificatietype == (int)request.Portalnotificatietype);
```

This code results in a System.InvalidCastException, when await query.ToArrayAsync() is called.
The code runs fine when I change it to:

```
int v = (int)request.Portalnotificatietype;
query = query.Where(sjabloonveld => sjabloonveld.Portalnotificatietype == v);
```

### Exception message:
```
Unable to cast object of type 'TelaSoft.PraktijkData.Domain.Enums.PortalNotificatieType' to type 'System.Int32'.
```

### Stack trace:

```
   at MySql.Data.MySqlClient.MySqlParameter.AppendSqlString(ByteBufferWriter writer, StatementPreparerOptions options) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlParameter.cs:line 389
   at MySqlConnector.Core.StatementPreparer.ParameterSqlParser.DoAppendParameter(Int32 parameterIndex, Int32 textIndex, Int32 textLength) in C:\projects\mysqlconnector\src\MySqlConnector\Core\StatementPreparer.cs:line 90
   at MySqlConnector.Core.StatementPreparer.ParameterSqlParser.OnNamedParameter(Int32 index, Int32 length) in C:\projects\mysqlconnector\src\MySqlConnector\Core\StatementPreparer.cs:line 77
   at MySqlConnector.Core.SqlParser.Parse(String sql) in C:\projects\mysqlconnector\src\MySqlConnector\Core\SqlParser.cs:line 199
   at MySqlConnector.Core.StatementPreparer.ParseAndBindParameters(ByteBufferWriter writer) in C:\projects\mysqlconnector\src\MySqlConnector\Core\StatementPreparer.cs:line 39
   at MySqlConnector.Core.SingleCommandPayloadCreator.WriteCommand(IMySqlCommand command, ByteBufferWriter writer) in C:\projects\mysqlconnector\src\MySqlConnector\Core\SingleCommandPayloadCreator.cs:line 201
   at MySqlConnector.Core.SingleCommandPayloadCreator.WriteQueryPayload(IMySqlCommand command, IDictionary`2 cachedProcedures, ByteBufferWriter writer) in C:\projects\mysqlconnector\src\MySqlConnector\Core\SingleCommandPayloadCreator.cs:line 60
   at MySqlConnector.Core.SingleCommandPayloadCreator.WriteQueryCommand(CommandListPosition& commandListPosition, IDictionary`2 cachedProcedures, ByteBufferWriter writer) in C:\projects\mysqlconnector\src\MySqlConnector\Core\SingleCommandPayloadCreator.cs:line 35
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 50
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__64`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TelaSoft.PraktijkData.PraktijkPortalAdapter.Queries.Sjabloonvelden.SjabloonveldenQueryHandler.<Handle>d__2.MoveNext() in C:\Git\PraktijkData\BackEnd\PraktijkData\PraktijkPortalAdapter\Queries\Sjabloonvelden\SjabloonveldenQueryHandler.cs:line 34
```

### Further technical details

MySQL version: 8.0.16
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0
Microsoft.AspNetCore.App version: 3

**Comment by hrattls** [comment]
It appeared that database type (int(11)) was not compatible with enum base type(sbyte).
The example below explains why it went wrong.

```
  var v1 = (int)request.Portalnotificatietype; //succeeds
  var v2 = (sbyte)(object)request.Portalnotificatietype; //succeeds
  var v3 = (int)(object)request.Portalnotificatietype; //System.InvalidCastException: 'Unable to cast object of type 'TelaSoft.PraktijkData.Domain.Enums.PortalNotificatieType' to type 'System.Int32'.'
```
